### ISSUE TITLE
Implement Auth backends

### ISSUE THREAD

**Issue by InnayTool** [hedgedoc/hedgedoc#1006]
Core auth backends:
- [x] Internal (#1515)
- [x] LDAP
  - Note: ensure that attributes for profile information (username, display name etc) are configurable #1216
  - Note: ensure Azure AD is configurable too
- [ ] Login via OAuth2/OIDC (#1152)
  - with front-channel logout option see #2066
- [ ] external Auth by trusted header (e.g. authentik auth proxy)

Eventually to be considered:
- [ ] Login via IndieAuth

Just documentation (using OAuth2/OIDC):
 - Login via GitLab (OIDC: https://gitlab.com)
 - Login via GitHub (non OIDC!) (and #1182)
 - Login via Facebook (OIDC: https://www.facebook.com)
 - Login via Dropbox (OIDC: https://www.dropbox.com)
 - Login via Google (OIDC: https://accounts.google.com)

---

Auth backends can be activated and deactivated by configuration. For some of them it is possible to use multiple instances (for example LDAP or OAuth2/OIDC).

Issues with user data are tracked in #451.

**Comment by InnayTool** [comment]
A another suggested Auth mode #491

**Comment by DerMolly** [comment]
I'd suggest implementing each of the initial auth methods and returning an JWT afterwards. All subsequent request to the private api are then made with the help of this JWT.

**Comment by SISheogorath** [comment]
For email please keep in mind that we stated at some point it would make more sense to just use "Username + password" instead of email, since email requires an mail integration, and is always a pain to maintain, and thr existing solution is closer to username + password, as we have no mail backend with verification etc.

**Comment by DerMolly** [comment]
> For email please keep in mind that we stated at some point it would make more sense to just use "Username + password" instead of email, since email requires an mail integration, and is always a pain to maintain, and thr existing solution is closer to username + password, as we have no mail backend with verification etc.

Yeah it's already planed so, it's only named email here because it was email in HedgeDoc1

**Comment by espenfl** [comment]
Would be happy to contribute here. We have the rather common use case of needing to integrate our Azure AD (not LDAP). Have tried the general OAuth2, but we get stuck getting the user profile, ultimately handing this information to HedgeDoc. I suspect there is something related to the use of the Graph `/me` endpoint and that the this is not authorized properly. Maybe it is easiest to just make a dedicated auth section for Azure AD. First, do anyone know if work exists to make this work? And could someone point me in the right direction of what needs to be added/modified. I do not know much about the framework and design principles behind HedgeDoc.

**Comment by espenfl** [comment]
Sorry, I just now realized that this pertains strictly to the 2.0 version. Not saying we can not contribute on that, but we would like to get 1.x up first. I will open a dedicated issue on that.

**Comment by max-tet** [comment]
I'd like to suggest adding a proxy auth option. Implementation should be very simple.

The perfect proxy auth feature for me would work like this:

1. Start the app with additional environment variables:

* containing the name of the initial admin user (e.g. admin=admin_user)
* enabling proxy auth (e.g. proxy_auth=true)
* setting the key of the http header that contains the username (e.g. auth_header=X-Authenticated-User)

2. Configure the reverse proxy to authenticate incoming requests in any way you like.
3. Let the reverse proxy set X-Authenticated-User to the authenticated username on every request.
4. The app treats the requests as if they belong to the appropriate user session.
5. Bonus: if the app does not know the username, it creates a new user with that name.

**Comment by DerMolly** [comment]
Intressting idea.
A few questions:

> containing the name of the initial admin user (e.g. admin=admin_user)

1. Which admin user? I feel like I'm missing something…

> Configure the reverse proxy to authenticate incoming requests in any way you like.

2. We're talking about HTTP Basic Auth, correct? Or are there other options?

3. How would we handle logouts, specifically if the user want's to logout?

**Comment by max-tet** [comment]
1. Isn't there something like an admin user? Some user with special permission? If not, this is not needed. I'm not sure how user creation would be handled then, though. Perhaps automatically.
2. That is totally up to how the reverse proxy is configured. [Look at Traefik](https://doc.traefik.io/traefik/middlewares/http/forwardauth/) for example. There is another auth server that makes the decision and either adds the `X-Authenticated-User` header to the request or not.
3. There would be no concept of logout. Or rather, if there is one, it is also handled by the auth server. But HedgeDoc need not concern itself with it. It can handle each request totally independently.

**Comment by mrdrogdrog** [comment]
This is tricky. HedgeDoc is handling its own sessions right now.

**Comment by aroberts** [comment]
right. The way this works is that any time hedgedoc would serve a request that contained an `x-authenticated-user` header (or whatever it was configured to as a header name) it would perform a passwordless LOGIN action for the username contained as a value for that header (if it exists). Then, it would serve the response.

HedgeDoc still handles its own sessions, it just trusts the header completely (because hedgedoc is only exposed behind the reverse proxy that attaches the header).

**Comment by DerMolly** [comment]
I think this could be possible, but we should probably move this into it's own issue to work on the details. And I'm unsure if this is something we want definitely for 2.0 or if this should come later…

**Comment by ErikMichelson** [comment]
We already have an issue for this: https://github.com/hedgedoc/hedgedoc/issues/491

**Comment by max-tet** [comment]
Oh now I remember. I commented there as well. Sorry for the duplication.
Anyway, it might have made sense to add it to this ticket as well.

Correction on the sessions: @aroberts is totally right as far as I can tell. Proxy auth would just insert itself in the login flow, nothing else. I am not sure how this is setup in HedgeDoc, but with all the apps I've been involved in, the needed change was very small. So if there is work done on auth backends, this might be a quick win, and a very useful one.

**Comment by GGH-WeyboZetO** [comment]
Hello I would like to try to implement google login but I'm kinda new here.
Which is the file where I should implement that login method in v2.0?
I think that following theses instructions is the right thing to do is that correct?
https://developers.google.com/identity/sign-in/web/sign-in

**Comment by h0jeZvgoxFepBQ2C** [comment]
Is there any way to specify a JWT token to login a user while loading a note?
We have our own project management tool and only want to embed (hedgedoc) notes, so the user is authenticated in our rails project management tool and we would only pass a JWT token to the iframe-hedgedoc note?

**Comment by ErikMichelson** [comment]
Such a scenario is currently not considered. However, maybe a future version could introduce an API endpoint for a token-login (JWT and/or similar) with a redirect-back-URL.
Then your embed could look something like: https://md.example.com/auth/token?token=abcdef&redirect=/n/my-note

**Comment by h0jeZvgoxFepBQ2C** [comment]
Ah ok I see, shall I create a new issue? I guess there is no ETA for such a feature or?

**Comment by ErikMichelson** [comment]
The auth backends have been discussed and finally implemented with #4827.

For the following backends we'll keep track of them in separate issues:
- Trusted Header (proxy auth), #491
- IndieAuth, #553
- URL Token, #5795
