### ISSUE TITLE
Import and Export Features in 2.0

### ISSUE THREAD

**Issue by InnayTool** [hedgedoc/hedgedoc#1011]
Which export features do we want in Version 2.0?

By now we have the following imports in 1.X:
- Github *Gist*
- *Clipboard*

And the following exports:
- *Markdown*
- *HTML*
- *Raw HTML*

The 2.0 frontend list the following imports:
- Github *Gist*
- *Gitlab Snippets*
- *Clipboard*
- *Markdown file*

And the following exports:
- Github *Gist*
- *Gitlab Snippets* (Issue #508)
- *Markdown file*
- *HTML*
- *Raw HTML*

It also describes the missing of the PDF export which is handled by Issue #965.

**Other Ideas:**
- Exports to WebDAV a little bit like WebDAV suggested in #60 
- Export to other formats #1004 (#203).
- Export of a note with it's pictures to disk or other locations (#1005).
- Automated saving of revisions in a git repo (#222)
- Export of a note with revisions via a save or export to git button #705.

**Comment by davidmehren** [comment]
Creating GitHub Gists and GitLab Snippets needs code in the backend to handle authentication:
- [Gists](https://docs.github.com/en/rest/reference/gists) needs an OAuth token of the user that will create the gist
- [Snippets](https://docs.gitlab.com/ee/api/snippets.html) need an [OAuth Token or a personal access token](https://docs.gitlab.com/ee/api/README.html#authentication)

We need to think about how these access tokens are handled.

**Comment by boschkundendienst** [comment]
It should be possible to export html with the image embedded base64 encoded. - Why? - Well one can write his documentation perfectly using hedgedoc privately and then export the result as HTML with embeded images like TiddlyWiki does. - Just an idea!

**Comment by davidmehren** [comment]
These features should all be tracked in https://github.com/hedgedoc/react-client/issues/623 and https://github.com/hedgedoc/react-client/issues/622
