### ISSUE TITLE
Spell checking

### ISSUE THREAD

**Issue by VictorVenema** [hedgedoc/hedgedoc#1017]
**Is your feature request related to a problem? Please describe.**

My spell checker does not work in the edit screen (Firefox under Suse Linux). Not sure whether this is a bug, the spell checker is automatically active in any form/text box, or a feature request.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DerMolly** [comment]
Hello @VictorVenema,

yes spell checker do not work with CodeMirror 5. This is known.

We plan to include better spell checkers in 2.0 (see https://github.com/hedgedoc/react-client/issues/479)

**Comment by ErikMichelson** [comment]
Just to add: Basic spellchecking for English can already be enabled from the bottom status bar in the editor:

![image](https://user-images.githubusercontent.com/52606896/110553730-baadbf80-8139-11eb-897a-2a5eed511207.png)

**Comment by VictorVenema** [comment]
Dear @DerMolly,
 
Sorry about that. I searched for spell checkers in the issues, but somehow this one did not come up.

I have 6 dictionaries pre-installed in my browser. I would seem a better solution to get them working again than code completely new spell checkers. 

P.S. Thanks for creating this great tool. Really useful to jointly write simple texts.

**Comment by VictorVenema** [comment]
> Just to add: Basic spellchecking for English can already be enabled from the bottom status bar in the editor:

Thanks. Had missed that. That solves 90% of my problems. 

Am I again too stupid to find that in the help files or is it missing?

**Comment by VictorVenema** [comment]
> Not really our choice. CodeMirror does not work with browser spell checkers.

Could they solve that or Mozilla? I am really bad at spelling, could not have survived this internet age without spell checkers. Happy to file a feature request at the right location.

**Comment by DerMolly** [comment]
I think they are well aware of that, but feel free to have a look at https://github.com/codemirror/CodeMirror.

**Comment by VictorVenema** [comment]
> I think they are well aware of that, but feel free to have a look at https://github.com/codemirror/CodeMirror.

Right. There are many issues going back many years on spell checking.

I stumbled upon a recent addition to Weblate, which uses CodeMirror for a translation tool, that seems to have solved it (it worked for me on the two pages I tested) and enabled the browser spell checker. 
https://github.com/WeblateOrg/weblate/issues/4977#issuecomment-756311471
