### ISSUE TITLE
Incorrect automatic replacements in URLs

### ISSUE THREAD

**Issue by jrselzer** [hedgedoc/hedgedoc#1038]
**Description**
When typing in URLs like "somedomain.in" the text is displayed incorrectly

**To Reproduce**

1. open a pad
2. type www.cryptoparty.in
3. the text is displayed as www.cryptopartyIn
4. type www.somedomain.in
5. the text is displayed as somedomain (the TLD is completely gone)

**Expected behavior**
when I type www.cryptoparty.in, I want to see www.cryptoparty.in
when I type www.somedomain.in, I want to see www.somedomain.in
**Logs**
no logs available
**Config**
no config available
**Your Setup (please complete the following information):**
using a remote installation, no information about setup available
**Additional context**
none

**Comment by davidmehren** [comment]
I just tried that in https://demo.hedgedoc.org/JBZqh20FQNC5eKP6f7NIjg with Firefox 86.0.1, the URLs are displayed correctly:
![grafik](https://user-images.githubusercontent.com/5023650/111443630-dbfa4700-8709-11eb-8d48-121af86e13d9.png)

What browser do you use? Does the behavior persist in incognito mode without any add-ons?

Please find out what your HedgeDoc version is, you can do that by visiting `<YOUR_INSTANCE_DOMAIN>/s/release-notes` and looking at the latest release notes entry.

**Comment by jrselzer** [comment]
Please accept my apologies. It was my fault. I was using a plugin that was messing up the page content. Sorry for the inconvenience.
