### ISSUE TITLE
Add WebDAV media backend

### ISSUE THREAD

**Issue by DerMolly** [hedgedoc/hedgedoc#1041]
As @ErikMichelson suggested in https://github.com/hedgedoc/hedgedoc/issues/529#issuecomment-783736443 we could include WebDAV as a media backend. In this I tried to think this through and will show my findings.

I'd suggest using https://www.npmjs.com/package/webdav. Looking at the auth methods possible with this package, it seems we could support many auth methods for WebDAV. But I'm not too sure, if that is needed or if we could just use username and password as this is the way NextCloud and ownCloud (two of the most used WebDAV servers) do auth.

We would then need the following additional configs:

```
HD_MEDIA_BACKEND_WEBDAV_SERVER
HD_MEDIA_BACKEND_WEBDAV_UPLOAD_DIR
HD_MEDIA_BACKEND_WEBDAV_PUBLIC_URL
```

`SERVER` should include the username and password in the known `schema://user:pass@url` notation.

As is shown beneath, the `PUBLIC_URL` would need to support a placeholder, that the media backend then replaces with the filename, to be usable with NextCloud. 

### NextCloud
<del>
I played around with NextCloud and found that if the folder, that the images are in, is shared, it's possible to build the link to the image the following way:

`https://<SERVER>/apps/files_sharing/publicpreview/<SHARE_ID_FOLER>?file=/<FILE_NAME>&x=3840&y=2160&a=true`

It's necessary to include a screen resolution via the `x` and `y` parameters. The `a` parameter seems to indicate if the image should be kept at its ratio or if it should be trimmed / to the ratio indicated by `x` and `y`.

This should be the relevant docs from NextCloud: <https://docs.nextcloud.com/server/21/admin_manual/configuration_files/previews_configuration.html>

</del>

As @mrdrogdrog and @ErikMichelson suggested it's possible to use the download url of NextCloud instead:

`https://<SERVER>/s/<SHARE_ID_FOLER>/download?path=%2F&files=<FILE_NAME>`

### webdav package

The necessary code from the webdav package should be somthing like this:

#### client creation
```
const client = createClient(
    "https://webdav.example.com/marie123",
    {
        username: "marie",
        password: "myS3curePa$$w0rd"
    }
);
```

#### file upload
```
await client.putFileContents("/my/file.jpg", imageBuffer, { overwrite: false });
```

#### file deletion
```
await client.deleteFile("/tmp.dat");
```

**Comment by ErikMichelson** [comment]
Why do you have separate URL, username and password variables, when everything can be bundled into one URL-variable?

**Comment by DerMolly** [comment]
Because the lib want's to handle that

**Comment by SISheogorath** [comment]
Should we split this using an URL object instead of exposing those variables?

**Comment by ErikMichelson** [comment]
We should definitely support URLs which include username and password as that's quite common.
