### ISSUE TITLE
Private API: Purge note history

### ISSUE THREAD

**Issue by davidmehren** [hedgedoc/hedgedoc#1064]
**Describe the solution you'd like**
The private API should provide a way to purge the note history.

The documentation merged in documentation merged in https://github.com/hedgedoc/hedgedoc/pull/1033 says:
> The owner of a note may delete all revisions. This effectively purges the edit history of a note.

Note: We expect that a Note *always* has at least one revision. Purging the history must therefore preserve the latest revision.

**Comment by Abhilasha06** [comment]
Hey @davidmehren can I work on this?

**Comment by davidmehren** [comment]
Hi @Abhilasha06, great that you want to help. Please join the [dev chat](https://chat.hedgedoc.org/dev) to coordinate your contribution :smiley:

**Comment by davidmehren** [comment]
Fixed by #1595
