### ISSUE TITLE
Split ESLint config for tests and code?

### ISSUE THREAD

**Issue by DerMolly** [hedgedoc/hedgedoc#1098]
If you check `yarn lint` on the `notes/deleteMedia` the following error will be reported:

```
347:14  error  Avoid referencing unbound methods which may cause unintentional scoping of `this`.
If your function does not access `this`, you can annotate it with `this: void`, or consider using an arrow function instead  @typescript-eslint/unbound-method
```

the relevant code can be seen here:

https://github.com/hedgedoc/hedgedoc/blob/f4536460f5631d50fa684533fdc9a442084a2684/src/media/media.service.spec.ts#L340-L348

The documentation suggest disabling `@typescript-eslint/unbound-method` and using `jest/unbound-method` instead, but only for the tests. This would need a bigger change to the eslint config.

While Googling I found that the same error was already fixed in tslint (see [here](https://github.com/palantir/tslint/issues/4500) and [here](https://github.com/palantir/tslint/pull/4472)). As tslint is currently in the process of being incorporated into `@typescript-eslint` we could also try to raise an issue to get this fixed. But according to the [roadmap](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/ROADMAP.md#L91) `@typescript-eslint/unbound-method` incorporates all of `tslint/no-unbound-method`, but it does not contain the whitelist. I guess this is because `jest/unbound-method` exists.

All this raises one question:

1. Do we want to split the eslint config for tests and regular code? It seem we need to do that to get this probably fixed (we could of course also `eslint-disable` this one line of code).
 
See: 
[`@typescript-eslint/unbound-method` docs](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/unbound-method.md)
[`jest/unbound-method` docs](https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/unbound-method.md)

**Comment by InnayTool** [comment]
I think splitting the config for code and tests is pretty reasonable because we do a lot of things in the tests we don't want to do in the production code.
