### ISSUE TITLE
Local domain support

### ISSUE THREAD

**Issue by mdegat01** [hedgedoc/hedgedoc#1100]
**Is your feature request related to a problem? Please describe.**

I have a self-hosted HedgeDoc deployment. I have it set up so there are two ways to get to it:

1) A public URL I can access from anywhere in the world
2) A private local-only URL I can use within my network

The problem is I can only put one of those URLs in `CMD_DOMAIN`. And whichever one I put is the only one that works because when the website loads all assets (fonts, stylesheets, etc.) are set to the domain in `CMD_DOMAIN`. Which means they just don't load on the local URL due to CORS errors. If I don't set a value for this setting then it works but I get a warning in my log like this:

```
2021-04-03T16:44:48.949Z warn: 	Neither 'domain' nor 'CMD_DOMAIN' is configured. This can cause issues with various components.
Hint: Make sure 'protocolUseSSL' and 'urlAddPort' or 'CMD_PROTOCOL_USESSL' and 'CMD_URL_ADDPORT' are configured properly.
```

It's not clear what all components break but I can guess some of them. Nearly all of the alternate login methods and some of the upload storage options use OAuth so I'm guessing those will not work. I'm not familiar enough with the app to know what all else will have problems in this setup.

**Describe the solution you'd like**

A way to set a separate public and private URL to HedgeDoc. The app should treat the public URL as the URL for share links, OAuth requests etc. But users should still be able to successfully access and use HedgeDoc at the private URL without a broken experience due to cross-origin requests for static assets.

**Describe alternatives you've considered**

Not sure there is much alternative besides simply not setting `CMD_DOMAIN`. Which might be fine, I just don't know what all breaks. That warning seems ominous.

**Additional context**

I know typically people solve this using DNS rewrites if they have a router with that capability or something like Pi-Hole/Adguard set up to do DNS locally. Unfortunately that's not an option for me since I have a cloudflare proxy/firewall set up in front of all external access to my network and my reverse proxy is set up to ensure any public access did in fact go through it.

**Comment by davidmehren** [comment]
Sorry, using multiple domains is not supported in 1.x and not planned for 2.x, as it would make secure content rendering much more difficult.

> It's not clear what all components break 

The server URL is used in many places (just grep for `config.serverURL`), like redirects, auth and creating URLs.

**Comment by mdegat01** [comment]
Ok, that's too bad, thanks for letting me know.

**Comment by pirate** [comment]
Oh no 😿 , this totally breaks our whole company's publishing platform built on top of HedgeDoc. We very strongly depend on supporting multiple domains and would be willing to pay + contribute dev time to keep it supported.

We're getting these new CORS errors after upgrading from 1.7.2 to 1.8.2. Is there any temporary workaround or should we downgrade for now?
![image](https://user-images.githubusercontent.com/511499/118768053-87c82c00-b84c-11eb-8b9d-976f5e815ea9.png)

**Comment by davidmehren** [comment]
> Is there a link to any forum/team discussions that went on about removing multi-domain support?

There was never multi-domain support, we always only supported *one* domain in the `domain` setting.
Multiple domains might have worked in the past, but only by pure luck.

**Comment by pirate** [comment]
We only need one domain usable for auth, and one main domain set in the `CMD_DOMAIN` config. However we need *read* / non-authed access from many domains, we have 8+ domains listed in `CMD_ALLOW_ORIGIN` where we're hosting docs from a single server.

**Comment by davidmehren** [comment]
The easiest fix for this issue is probably to just add the required header in your reverse proxy.
As far as I can see, HedgeDoc itself does not support adding CORS-headers.

**Comment by pirate** [comment]
Would you be open to me creating a PR to add CORS header support to HedgeDoc? It's relatively easy to do in node and I just did the same change on another one of my projects a couple weeks ago, so it's fresh in my mind.

**Comment by davidmehren** [comment]
Sorry, we really don't want to add any more features to HedgeDoc 1. :pray: 
Especially as there is a useable workaround.
