### ISSUE TITLE
Imgur: Should be keep the default client ID?

### ISSUE THREAD

**Issue by DerMolly** [hedgedoc/hedgedoc#1161]
In the 1.x code the imgur code had a default client ID, that was used if imgur was chosen as the mediaupload backend, but no other id was configured. If we want to omit this is, 2.0 is the time to do that in my opinion. I tried to find some Pros and Cons for this decision:

#### Pro

- It's easy to use and doesn't need any setup.

#### Con

- It's not a very privacy forward way of configuring HedgeDoc (the same could probably be said about the whole imgur upload in general, so not too sure how much this argument should weight)
- One should not include api keys in their source code in general

#### Additional remarks

If you happen to have any other not mentioned Pros or Cons, feel free to add them to this post (or comment them below, if you can't edit this post)

*Note: If you just want to express your opinion please use :+1: / :-1:*

**Comment by mrdrogdrog** [comment]
Please keep in mind that there is no default imgur client id!  The maintainer of node-imgur registered a client id for their lib. Also the source code says that the id shouldn't be used without the lib!

**Comment by DerMolly** [comment]
> Also registering a client id is not so easy for normal users / not so experienced admins because you have to go through an oauth process using e.g. postman. There Is no web interface for!

Either I forgot already or you're talking about registering an app with imgur. The clientId was obtained by simply filling out https://api.imgur.com/oauth2/addclient iirc.

**Comment by mrdrogdrog** [comment]
Okay then forget this point. The API docs read as if you can obtain the client id only by using postman

**Comment by SuperSandro2000** [comment]
Changes this how the files are attached to an account and can be deleted?

**Comment by mrdrogdrog** [comment]
> Changes this how the files are attached to an account and can be deleted? 

Do you mean in imgur or HedgeDoc?

**Comment by SuperSandro2000** [comment]
> > Changes this how the files are attached to an account and can be deleted?
> 
> Do you mean in imgur or HedgeDoc?

Images uploaded through hedgedoc to imgur. In the past they where anonymously on imgur and you couldn't delete them.

**Comment by mrdrogdrog** [comment]
You can delete images only if you have the delete hash. This hash is ONLY included into the upload response. So it doesn't matter which client id you use. Afaik the owner of the account that created the client id can't delete the images.

**Comment by davidmehren** [comment]
I think this was open long enough.
There is currently one vote for keeping a default ID and 4 votes against it.

So we can conclude: HedgeDoc 2 will require the user to supply their own client ID for Imgur.

**Comment by davidmehren** [comment]
https://github.com/hedgedoc/hedgedoc/blob/develop/src/config/media.config.ts#L71 already requires the user to supply a client ID, if they enable Imgur. So everything's done already.
