### ISSUE TITLE
Copying to the Clipboard possible?

### ISSUE THREAD

**Issue by DocBrown101** [hedgedoc/hedgedoc#1181]
If it is a format block with e.g. shell=sh, that there is a "copy to clipboard" button in the upper right corner?

### Enabling SSH
```shell=sh
sudo apt update
sudo apt install openssh-server
```

**Comment by DerMolly** [comment]
Hello @DocBrown101,

This is currently not supported in 1.7.2 and won't be in 1.8, but the new 2.0 will add this feature. You can try this at https://ui-test.HedgeDoc.org.

**Comment by DocBrown101** [comment]
@DerMolly Oh thanks, then I'm really looking forward to version 2.0. Will the version come this year or will it take longer?

**Comment by DerMolly** [comment]
The plan is to release it this year, if that worked out we'll find out at 31th of December …

**Comment by cmuc24** [comment]
Hi, as this small feature is not implemented, i'm wondering why this FeatureRequest is closed .. 
Maybe some Code from Material-MKDocs could help out? Seems that also the license is 'friendly'.

[squidfunk](https://github.com/squidfunk) / [mkdocs-material](https://github.com/squidfunk/mkdocs-material)
**Codeblock Copy Feature** [Integration](https://github.com/squidfunk/mkdocs-material/blob/92dc0375dc8c0218034b651dbf37c0406e49d6bb/src/assets/javascripts/integrations/clipboard/index.ts)

**Comment by DocBrown101** [comment]
@cmuc24 because hedgedoc version 1 is no longer under active development. 
Version 2 already has this feature and hopefully this version will be released soon.
