### ISSUE TITLE
Spell Checking Language

### ISSUE THREAD

**Issue by cod3licious** [hedgedoc/hedgedoc#1192]
It would be really great if the spell checking either allowed one to manually select the language or (even better) the browser/system spell checking of one's own computer could be used. 

In my case, my computer/browser language is set to English, but periodically I will write texts in other languages. This is not a problem for virtually all other websites, where I think the spell checking functionality is somehow provided by the Chrome browser (or macOS?): here the language is automatically detected and the spell checking works fine. In your editor, however, I only have the choice between your spell checking (which right now assumes that my text is in English, which it is not, and therefore everything is red) or nothing, i.e. this also disables the internal spell checking of the browser that works so great on all other websites.

**Comment by DerMolly** [comment]
Hey @cod3licious,

we are aware of this problem and track it with https://github.com/hedgedoc/react-client/issues/479 for version 2.0, which we plan to release this year.

**Comment by DerMolly** [comment]
I'll close this issue, because we track the progress with the other issue…
