### ISSUE TITLE
How do you create email login user using cli? 

### ISSUE THREAD

**Issue by johannfza** [hedgedoc/hedgedoc#1205]
Hi! I’ve managed to set up everything. However I want to manage the email login. As stated there is a .bin/manage_user script? How do I perform that? 

I’m using a docker image behind an nginx proxy.

thank you

**Comment by DerMolly** [comment]
Hey @johannfza,

first of all I'd urge you to ask such questions in the [community forum](https://community.hedgedoc.org) or our [chat](https://chat.hedgedoc.org), as the issue tracker is meant for feature requests and bugs and not for support questions.

To answer your question:
The script is in the docker container and can be called like you'd do with every other docker container
```
docker exec <CONTAINER_NAME> ./bin/manage_users
```

**Comment by johannfza** [comment]
Hi @DerMolly 

Sorry for raising an issue here.

Thank you for responding nonetheless. I've figured it out thanks to you
