### ISSUE TITLE
Can't change permissions or delete note

### ISSUE THREAD

**Issue by agross** [hedgedoc/hedgedoc#121]
I have a single note that I cannot change permissions for (or delete it). The permissions are displayed in the edit screen, but there is no arrow to open the dropdown. I have tested deletion with other notes successfully.

<img width="88" alt="2019-06-21_23-41-48" src="https://user-images.githubusercontent.com/16245/59952937-525b0e00-947e-11e9-893c-919e9dca09c8.png">

**Comment by ccoenen** [comment]
This should only happen in one of these two scenarios:
- You are not logged in
- The note was originally created by someone else

This setting can only be changed by a note's owner.

**Comment by agross** [comment]
Thanks for the quick response. The note was added by a guest user. That guest session now has expired while I am still logged in. How can I remove the note?

Having that note is not an issue, but consider the implications if an anonymous user posts data on a freely available codimd server that you need to remove for legal reasons.

**Comment by ccoenen** [comment]
We're still missing an admin section. This would be one future possibility to get rid of such data. For now, sadly, the only option is to log into your database and delete the row in question from the `Note` and `Revision` tables.

**Comment by agross** [comment]
Alright, thank you. Should we leave this ticket open then? You may close it as you provided a workaround or keep it open to track the feature.

**Comment by DerMolly** [comment]
I think this can safely be closed, because we already have #561…
