### ISSUE TITLE
Allow changing your displayname as a user

### ISSUE THREAD

**Issue by MTRNord** [hedgedoc/hedgedoc#1216]
**Is your feature request related to a problem? Please describe.**
It is frustrating to not set a displayname. Especially that it is based on email as those maybe should not be public to others.

**Describe the solution you'd like**
An input to change the displayname would be nice on an account level.

**Describe alternatives you've considered**
None

**Additional context**
My email starts with my private name and I prefer using a nickname in the internet. Another person does emails by service. So their displayname is a useless one thats the name of the hedgedoc instead.

This is about the email based login.

**Comment by ErikMichelson** [comment]
We're aware of this and version 2.0 will have the option to change your display name. See [the UI test](https://ui-test.hedgedoc.org/profile) for the current state on this.

As we're currently not using the email address for anything else than being login identifier and libravatar profile picture source, you could use an email address like "mtrnord@example.com" in the meanwhile when creating an account.

**Comment by sonicnkt** [comment]
i just setup 1.8.2 with ldap, really nice and simple :) 

Since 2.0 adds profile settings and displayname configuration it would be great to get this info out of ldap attributes (like givenname + Surname). Our setup is mainly for internal use so having the full name displayed instead of the username would be nice :)

**Comment by ErikMichelson** [comment]
2.0 will have the option to define sync sources, so yes LDAP info could be used.
See this document for the planned details: https://github.com/hedgedoc/hedgedoc/blob/10f92de94e911932d75ba7b918ae7ff811bb25ef/docs/content/dev/authentication.md

**Comment by DerMolly** [comment]
As there is https://github.com/hedgedoc/hedgedoc/blob/develop/backend/src/users/users.service.ts#L66-L75 already, I think this is done.
