### ISSUE TITLE
poor sequence diagram rendering (especially in Firefox)

### ISSUE THREAD

**Issue by ccb23** [hedgedoc/hedgedoc#1217]
**Description**
There is to much distance between description and arrow, so that in some cases one would even "assign" the description to the wrong arrow. 

**To Reproduce**
Try the following Sequence chart and watch its result in Firefox.
```sequence
client0->server: enter_lobby()
server-->client0: Ok
Note right of server: waiting for more\nclients or start()
client1->server: enter_lobby()
server-->client1: Ok
client0->server: start_game()
client1->server: start_game()
client1->server: far_to_high()
```
![Bildschirmfoto von 2021-05-03 14-02-57](https://user-images.githubusercontent.com/135532/116873653-56c6e500-ac18-11eb-8b87-41b7c43e6a73.png)

**Comment by davidmehren** [comment]
HedgeDoc 1 uses the `js-sequence-diagrams` library for these diagrams. Unfortunately, it is not being developed anymore, so we cannot fix this problem in HedgeDoc 1.

HedgeDoc 2 switched to Mermaid for rendering and does not have this bug. You can already play around with the new renderer on https://ui-test.hedgedoc.org/n/features, but please be aware this is just a UI demo and no data is saved.
