### ISSUE TITLE
Checkbox on ordered list does not update text on click in preview

### ISSUE THREAD

**Issue by xoriade** [hedgedoc/hedgedoc#1220]
**Description**
The text `1. [ ]` is not properly replaced with `1. [x]` when clicking the checkbox within preview (while the checkbox is toggled locally).

**To Reproduce**
1. Create an ordered list checkbox

```
1. [ ] Some item
```

2. Click the checkbox within preview

**Expected behavior**
The `[ ]` should be replaced with `[x]`, as working with unordered checkbox lists.

**Your Setup (please complete the following information):**
Used some pad on https://pad.gwdg.de/ for testing purposes, you probably know its setup better than me ;-)

**Comment by ErikMichelson** [comment]
I don't know whether we're going to still fix this in 1.x.
Anyway, for the upcoming 2.0 I created a fix.

**Comment by davidmehren** [comment]
The fill will land in 1.8.1
