### ISSUE TITLE
List button causing duplication of unselected prefix

### ISSUE THREAD

**Issue by AnomalRoil** [hedgedoc/hedgedoc#1231]
**Description**
When selecting a few lines to turn them into a list, if the first line isn't fully selected, it will  add a list sign and a copy of the full line after the unselected words, effectively duplicating words.

![image](https://user-images.githubusercontent.com/10077203/117177686-984ec000-add1-11eb-8d62-121fcff040c5.png)

**To Reproduce**
1. Write in a markdown doc: 
    ``` 
    This is a test
    Wow such test
    ```
2. Select the two lines from 'is' until 'such'
3. Click on the "List" button in the formatting option in the toolbar
4. See the same duplication as in the above picture. 

**Expected behavior**
Turn both lines into list items. Notice the bug isn't affecting the second line even when not selecting it entirely.

**Your Setup (please complete the following information):**
 - Host OS: no idea, not my setup.
 - NodeJS version: no idea, not my setup.
 - HedgeDoc version: no idea, I'm using one which was setup by someone else and it doesn't have a version link in the footer I think.
 But I reproduced this on the online demo on your website :)

**Comment by davidmehren** [comment]
Thanks for bringing that up!
While looking at a fix, I wondered what the most expected behavior would be: 
If you have text selected like at the top of the screenshot and then press the "list" or "quote" button, what would you expect to happen?

![grafik](https://user-images.githubusercontent.com/5023650/117196719-21242680-ade7-11eb-9ad6-991deee26e06.png)

**Comment by AnomalRoil** [comment]
Good question.

Github seems to be doing 1. but it also moves the unselected text to below the list.
I think MS Words is doing 3. so that might be what people would expect most likely.
2. definitively feels wrong to me.

On my side I was expecting 3, and was lazy since I didn't want to select the whole lines.
Also when typing with the keyboard it's much easier to select from any place and then go up or go down with the arrows with the shift key pressed, thus selecting stuff from anywhere on the first line to anywhere on the last line.
In that case 3 makes more sense, IMO. (But since we don't have keybindings for formatting, I guess it's not too much of an issue since people will have to use the mouse in the end)
Notice that this wouldn't be a problem in Vim mode, since we have V to select the whole lines, but Vim mode isn't that practical since Escape is loosing focus from the text area.

**Comment by AnomalRoil** [comment]
Actually on second thought I feel like 2. makes a lot of sense for the quote button but not for the list one.

**Comment by davidmehren** [comment]
We decided that 3 is the most intuitive behavior. The fix will be released with 1.8.1.
