### ISSUE TITLE
Heroku Button installation ends in error

### ISSUE THREAD

**Issue by cybrpimp** [hedgedoc/hedgedoc#1245]
Using the button Installation here ends in an error and does not deploy Dyno on Heroku.

https://docs.hedgedoc.org/setup/heroku/

![image](https://user-images.githubusercontent.com/61793417/117493808-1237a280-afa6-11eb-8304-8c6d5953b4be.png)

**Comment by davidmehren** [comment]
Thanks for bringing this issue to our attention!
A fix is up in #1246.

**Comment by davidmehren** [comment]
The fix has been merged and the Heroku button should work again.
Note that you need to set `CMD_DOMAIN=<your-app-name>.herokuapp.com` and `CMD_PROTOCOL_USESSL=true` to get a working deployment.
