### ISSUE TITLE
1.8.1 source install fails with missing webpack

### ISSUE THREAD

**Issue by inducer** [hedgedoc/hedgedoc#1252]
**Description**

I tried to update my manually-maintained, from-source install to 1.8.1, but I ran into the following issue:
```
$ ./bin/setup
(...succeeds as normal...)
$ yarnpkg run build
yarn run v1.22.10
$ webpack --config webpack.prod.js --progress
/bin/sh: 1: webpack: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
(Debian packages yarn as `yarnpkg`.)

**Comment by inducer** [comment]
Reverting to 1.8.0 helped, FWIW.

**Comment by InnayTool** [comment]
I think you ran into the documentation issue fixed by PR #1249.

**Comment by mrdrogdrog** [comment]
We recommend to use the prebundled tar file on the release page.

**Comment by inducer** [comment]
Ah, thanks. Yes, agreed. Sorry for the noise.
