### ISSUE TITLE
Update document title with user defined title to improve tab navigation

### ISSUE THREAD

**Issue by lightnin** [hedgedoc/hedgedoc#1262]
Currently I have 3 hedgedoc tabs open, which in my browser (FF) looks like this:

![Screenshot 2021-05-10 at 09 28 57](https://user-images.githubusercontent.com/1538027/117621727-2b8d4a00-b172-11eb-9b4c-2a0529d3b792.png)

The tabs correspond to 3 different documents. But there is no way for me to id which document is which from the text in the tab. In order to find the correct one, I am forced to give each one focus until I find the one I need. 

It would be better if the document title could be set to the title of the document I have set. This way I can see which tab I wish to return to, and click it.

I recognize there must be some challenges here due to the choice of allowing the user to edit the document title in the markdown directly (without any modal document name change dialog from which to trigger an event that could change the document title.) So perhaps this isn't practical. If there is an internal debate about this, I would say that forcing the user to change the document title through a modal would be a worthwhile trade off for enabling them to more quickly find the tab they need. But perhaps that breaks the markdown spec in some way?

Thanks to all the contributors for making such excellent software - it really is a beaut. 👍

**Comment by mrdrogdrog** [comment]
There is already two ways. You can use frontmatter. Prepend your document with
```
---
title: I'm the frontmatter title
---

```

Or

Use headlines. If no frontmatter title is defined then the first headline will be used.

**Comment by lightnin** [comment]
Thanks very much for that suggestion, mrdrogdrog - setting the front matter title that way does indeed work. When you say "headlines" did you mean "headings?" (As in: # HeadingName) ? I do have headings set, and this does set the title of the document on the hedgedoc history feed. But that doesn't set it in the browser tab title the way the frontmatter approach you shared does.

I wonder what you think about the idea of making setting the tab's title test a little more of a "default" behavior - for example, setting it to whatever the user has defined as the first # heading?

**Comment by mrdrogdrog** [comment]
Don't worry. Those things happen. 🙂
Thanks for your issue anyway. Maybe it will help other people.
