### ISSUE TITLE
Get rid of database backend

### ISSUE THREAD

**Issue by braderhart** [hedgedoc/hedgedoc#1274]
**Is your feature request related to a problem? Please describe.**

I'm not sure how others will feel about this, but I prefer keeping my markdown notes on my filesystem using a hierarchical file system. I generally prefer Hugo because of its speed and being a single binary it is very easy. A lot of high-level projects have switched to Hugo for docs generation because of speed and what I would consider good design principles. My biggest complaint about HedgeDoc is that it saves everything into a database, which isn't ideal for backups among other things like being able to transparently view and edit files regardless of the editor.

Requiring a database server to access and view markdown files defeats the initial purpose IMO. Don't get me wrong, I appreciate the work of the developers and think they have done some amazing things by implementing extended Markdown syntax, diagrams, presentation mode, etc. There are not many projects I've came across that has done this so well. But, with the great features I also see a lot left to be desired to create a fast collaborative editor that uses the file system rather than a database. This would help enable features like Git integration, IPFS support, and more. Heck, I'd use it daily as a note taking app, word processor and more.

**Describe the solution you'd like**

Separating frontend development and backend development into different projects. Backend development could be written in a more optimal language like Go or Rust to serve the app, manage permissions, interface with static site generators, handle configs, etc. Temporary revision history could be saved into a swap file, using common Markdown representations for edits... and then publishing or saving could be saved as a Git commit if the directory is initialized. That way you wouldn't have countless revisions, but meaningful ones.

It'd be really neat to be able to serve up a directory of Markdown files as well from the CLI or create new files in a specific directory, by running something like `hedgedocs serve ~/mydocs` and then be able to generate a token and possibly password using a relay that other people can connect to by sharing that token. That way you don't even really need logins.

**Describe alternatives you've considered**

Can't find anything else like this.

**Comment by davidmehren** [comment]
HedgeDoc does more than just "view markdown files", like real-time collaborative editing, providing access control, versioning, authorship information etc. which requires a database. It seems you are looking for a local, non-collaborative markdown editor, in which case there are other projects that might fit your needs better. Personally, I'm happily using https://joplinapp.org/ as a local editor.

As a side-note, it should be reasonably easy to use the API of the upcoming HedgeDoc 2.0 to regularly dump the state of all documents of a user to disk.
You may also be interested at the [other issues](https://github.com/hedgedoc/hedgedoc/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+export+label%3Afeature%3Aexport) discussing export-features.

**Comment by braderhart** [comment]
@davidmehren None of the things you mentioned do you need a database for.

**Comment by davidmehren** [comment]
You are of course free to build a new backend without a database yourself, but this project will continue to use a database and Node.js.

**Comment by braderhart** [comment]
Okay, well merely a feature request that maybe someone else will be interested in. If I were to invest in building something it would be a replacement, not a backend.

**Comment by SISheogorath** [comment]
Just to point out some flaws of the stretched out solution:

Git itself is not made for real-time editing. It'll require time-based commits (similar to how our revision system currently works). The bigger problem is the question where to draw the multi-tendency line with a git repository in collaborative work. Currently each note is a individual document represented at the top level. What should the repository store? All notes from the same person? All notes of the server? All notes from the same user with the same permissions?

At least in the current setup, you won't get any meaningful multi-tenancy capabilities, which limits the usefulness of you git repository drastically. Unless you introduces folders and directories and let users decide themselves where a repository should originate and where the files should go.

But then you just come to the next set of questions, how to you make it as easy as possible? What if someone wants to move a document from one repository to another? What happens to your revisions of the document?

And finally, as who built a revision-based backup system on git for a text database, I can tell you, it's eating up your diskspace quickly, and becomes slower with every commit. After 5 years a single commit took roughly 30 seconds. And that was just the result of commit a single file, every 5 minutes in case something changed in that file.

So all in all, no, as much as it sounds attractive to just have a directory with markdown around, it's not worth the drawbacks required to provide a similar feature set.

PS: Yes, you can do low level plumping to built a yearly separated out of tree branch and fiddle your new branch onto it, so the history remains smooth, and strich everything together, but this is completely unneccessary work, when you just use a database which also provides transaction safety.

**Comment by braderhart** [comment]
> Git itself is not made for real-time editing.

Correct, that is why saving temporary revisions in a swap file makes more sense until it is published, at which point you'd create a Git commit under whatever user is configured in the Git directory. If having a history of collaborative edits is important then the best solution IMO would be to use a markup format that implements additions, subtractions, etc for each user in the Markdown file similar to the extended tags that are already in place; however I'm not convinced that is entirely useful as anytime I've used a collaborative edit the goal isn't to track real-time revisions but to work on a document that you're publishing together. This could be more easily handled by just listing the authors of the document or certain sections. Non-collaborative edits would make most sense for when you have a group of people working on a document independently where you'd want to track changes by authors, which in that case you could use a PR/MR.

This model would help take out the centralization aspect, so that anyone could serve up a directory using HedgeDoc and collaboratively edit it using WebRTC or something similar. Currently HedgeDoc is based around centralization where fewer users would run a central server, but with the decentralized approach any user could easily start working collaboratively on Markdown files without the need for a centralized server.

> What should the repository store?

The repository in this instance would just be a local directory on that users file system, it could store as many directories as they want to work on multiple documents or even be a single file. If they want revision history outside of a temporary swap file, then they'd need to save (publish) the document which would then commit it with Git.

> All notes of the server.

There wouldn't be a traditional server in this instance. You could run HedgeDoc on your laptop to act as a temporary server, until you've committed your changes.

> Unless you introduces folders and directories and let users decide themselves where a repository should originate and where the files should go.

I supposed this could easily be accomplished by implementing a config file that lets users select multiple directories to work on if desired.

> how to you make it as easy as possible? What if someone wants to move a document from one repository to another? What happens to your revisions of the document?

I think this actually simplifies things a lot. If someone wants to move a document, then the file system functionality would allow them to do so. This could either be tracked in a cache or swap file until they're ready to submit their changes. Temporary revisions would be saved in a swap file until they publish (or save) them at which point it would make the final changes to commit to a Git repo, even a local Git repo if they desire.

> And finally, as who built a revision-based backup system on git for a text database, I can tell you, it's eating up your diskspace quickly, and becomes slower with every commit. After 5 years a single commit took roughly 30 seconds. And that was just the result of commit a single file, every 5 minutes in case something changed in that file.

I definitely wouldn't recommend committing every minor change. The swap files could get added to .gitignore until you have a change that is actually meaningful enough to commit that you'd want in your revision history. I think having a large revision history isn't very useful as well. Saving a file is quick, so you could easily have a backup save method in a swap file but then your commits would be meaningful changes thus only giving you a revision history of your meaningful changes and greatly reducing the amount of commits.

**Comment by SISheogorath** [comment]
I'll keep the answer short:

> This model would help take out the centralization aspect, so that anyone could serve up a directory using HedgeDoc and collaboratively edit it using WebRTC or something similar. Currently HedgeDoc is based around centralization where fewer users would run a central server, but with the decentralized approach any user could easily start working collaboratively on Markdown files without the need for a centralized server.

At this point, you talk about an entirely different application. All you described point into the same direction, that the change would be so fundamental to the existing application, that it would no longer align with the requirements and expectations with the existing user-base.

Decentralised solutions are cool, but as with everything, they aren't the perfect solution for everything. I encourage you too look into the [real-time editing tutorial by the IPFS guys](https://blog.ipfs.io/30-js-ipfs-crdts/), and maybe fork the react-frontend for 2.0 once it's done/functional. You should be able to integrate the frontend with IPFS and get a perfectly working decentralised markdown editing application.

But as things are right now, for the existing HedgeDoc community, this is not the solution they are looking for and therefore we, as the HedgeDoc community, will not actively engage in that direction. I hope you can understand this and I wish you a lot of success to integrate the editor with IPFS :)

**Comment by braderhart** [comment]
@SISheogorath Fair, and makes sense. I can see how this would be too fundamental from the typical direction the app has headed and where it forked from.
