### ISSUE TITLE
Manual Install Fails: Could not find the include file "../build/cover-pack-header"

### ISSUE THREAD

**Issue by jlpoolen** [hedgedoc/hedgedoc#1275]
Manual install based on instructions at https://docs.hedgedoc.org/setup/manual-setup/#manual-installation
results in: Internal Server Error

See attached install log.
[hedgedoc_install1.txt](https://github.com/hedgedoc/hedgedoc/files/6471504/hedgedoc_install1.txt)

**Comment by mrdrogdrog** [comment]
It seems like you haven't run "yarn install" and "yarn build" like stated in Step 6.

**Comment by SISheogorath** [comment]
Can we please just automate this when a `.git` directly exists? Let's not document the problem away.

**Comment by mrdrogdrog** [comment]
This message is also necessary if you downloaded the source tarball.

**Comment by jlpoolen** [comment]
Thank you.

For posterity, the instruction is:

 If you use the release tarball for 1.7.0 or newer, this step can be skipped.
Build the frontend bundle by running yarn install and then yarn build. The extra yarn install is necessary as bin/setup does not install the build dependencies.

I misread it, thinking I did not download the tarball, so no need to read on.

I executed "yarn install" and then "yarn build" and ran the server.  An HTML page appeared, albeit with missing links.  I clicked "New User" nothing happened.  Should I log a separate issue for that experience?  Attached is an enhanced log install which not includes "yard install" and "yarn build" and the results --- warnings, possibly errors, too.
[hedgedoc_install2.txt](https://github.com/hedgedoc/hedgedoc/files/6472619/hedgedoc_install2.txt)

**Comment by mrdrogdrog** [comment]
You haven't downloaded the tar ball. You used git. This is why you need to install the build dependencies and bundle the frontend. The release tarball already includes the bundled frontend. This is why you can skip this step then.

The log file doesn't say anything about the server execution. It includes only the installation and the bundling which seems fine. 

Please check if you have configured hedgedoc correctly. Especially if you have set the correct domain in the settings.

But this is not the right place for it. This issue tracker is only for bugs and feature requests. If you need assistance with setting up hedgedoc then  join the hedgedoc matrix room (chat.hedgedoc.org) or open a topic in the support section of our discourse (community.hedgedoc.org)

**Comment by jlpoolen** [comment]
Sorry, I thought I had captured the console after the run starts.  Here's the run portion:

ares /usr/local/src/hedgedoc # NODE_ENV=production yarn start
yarn run v1.22.10
$ node app.js
2021-05-13T13:02:46.405Z warn: 	Session secret not set. Using random generated one. Please set `sessionSecret` in your config.json file. All users will be logged out.
2021-05-13T13:02:46.797Z info: 	All migrations performed successfully
2021-05-13T13:02:46.803Z info: 	HTTP Server listening at 0.0.0.0:3000
2021-05-13T13:03:01.179Z info: 	192.168.1.28 - - [13/May/2021:13:03:01 +0000] "GET / HTTP/1.1" 200 - "-" "Mozilla/5.0 (X11; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0"

2021-05-13T13:03:44.772Z info: 	192.168.1.28 - - [13/May/2021:13:03:44 +0000] "GET /favicon.ico HTTP/1.1" 404 - "http://ares:3000/" "Mozilla/5.0 (X11; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0"

^C2021-05-13T13:09:26.326Z info: 	HedgeDoc has been killed by signal, try to exit gracefully...

ares /usr/local/src/hedgedoc # 

I well understand the difference between a tar ball and using git.  My error was to skip the instruction I quoted above.  But, now I have run both yarn commands.  I also assumed that I could use the example in the documentation to get something up and running.  The documentation might state that using their sample configuration is **not** sufficient and that further reading of the configuration documentation is necessary.

I had hoped I could simply follow your install instructions and without reference to other documentation and I would have a working server.
