### ISSUE TITLE
Vimeo embedding has stopped working (see https://demo.hedgedoc.org/#Externals)

### ISSUE THREAD

**Issue by zeigerpuppy** [hedgedoc/hedgedoc#1281]
**Description**
Embedding of VImeo videos using the `{%vimeo ID %}` syntax has stopped working (shows empty `<div class="vimeo...`)

**To Reproduce**
1. embed video in markdown format: e.g. `{%vimeo 126060304 %}`
2. look for rendered video div
3. compare with youtube method (which works)

**Your Setup (please complete the following information):**
- problem appears general to all v1.7.2 hedgedoc installs (including the hedgedoc demo site)

**Additional context**
I do not see any errors in the console directly related to this.
It seems likely that a change to the Vimeo API may be the cause, here is their [changelog](https://developer.vimeo.com/api/changelog)

While I appreciate that work is going into v2 at the moment, it would be great to fix this issue for all the existing 1.7.2 installs (at least while v2 is not at feature parity).

**Comment by mrdrogdrog** [comment]
Fixed with https://github.com/hedgedoc/hedgedoc/pull/1282. This fix will be included in the next release.
