### ISSUE TITLE
[Vim key-bindings] The substitute command doesn't honour the /n flag

### ISSUE THREAD

**Issue by AnomalRoil** [hedgedoc/hedgedoc#1311]
**Description**
When using Vim key-bindings, it seems that the substitute command is not honouring all flags, at least not the `/n` one.
To read about flag, see maybe here: https://nikodoko.com/posts/vim-substitute-tricks/

Notice the other combinations of flag such as `/gn` should also not substitute anything but does.

**To Reproduce**

Type this text:
```
That is a test
that is there to try and count 
occurrences of that in that text.
```
use vim key-bindings and try to count occurrences with the /gn flag:
input 
`:%s/that//n`

I would expect to see in the cmd line in the status bar in the bottom: 
`2 matches on 2 lines`
(notice how the upper case `That` shouldn't be counted and only the first occurrence is counted since I didn't use /gn in which case I'd expect: `3 matches on 2 lines`.)

Instead I see all instances of `that` being replaced with nothing.
Including the instance where `That` is written with a cap, basically like if the flag `i` had been specified and the flag `I` also doesn't work to say it should respect the case for the pattern...

If I wanted to ignore the case I'd be using `:%s/that//gni` and would expect `4 matches on 3 lines`

**Expected behaviour**
Display the number of matches in the status bar and do not perform substitution when the flag `/n` is used.
Also honour the `I` flag and do not default to the `i` flag behaviour of ignoring the case.

**Your Setup (please complete the following information):**
 - I could reproduce this on the official demo instance.

**Comment by mrdrogdrog** [comment]
The vim key bindings for the editor component (https://github.com/codemirror/CodeMirror) aren't made by us. They are build-in and we have no influence on them. Therefore we can't fix it.
You could open an issue in the codemirror tracker but afaik the vim key bindings are unmaintained.

**Comment by davidmehren** [comment]
@mrdrogdrog is correct, CodeMirror's vim keybindings are unmaintained, see https://codemirror.net/demo/vim.html.

As there is really nothing for us to do here, I'm going to close this issue. If the bug is fixed upstream, you're welcome to poke us again.
