### ISSUE TITLE
Kompilierte Anzeige springt nicht an richtige Stelle bei eingeklappten Paragraphen

### ISSUE THREAD

**Issue by BartMitTyp** [hedgedoc/hedgedoc#1314]
Wenn ich mehrere Überschriften habe (beispielsweise 3 Absätze mit ## und viel Text darunter) und die ersten beiden einklappe, springt die Ansicht rechts nicht an die Stelle, die ich gerade bearbeite
![grafik](https://user-images.githubusercontent.com/34683956/118777830-c92afc80-b889-11eb-9062-e80472f8b50e.png)

**Comment by mrdrogdrog** [comment]
Please write the issue in english and use the templates ☺️
