### ISSUE TITLE
Emoji selector pops and prevents me from entering a newline or moving the cursor

### ISSUE THREAD

**Issue by hydrargyrum** [hedgedoc/hedgedoc#1318]
## Which part of the project should be enhanced?
Document text editor

## Is your enhancement request related to a problem? Please describe.

Suppose I want to type this text:

```
foo:
- bar
- baz
```

But in French, the punctuation rules are different, it would be:

```
foo :
- bar
- baz
```
(note the space before the colon character)

So I'm starting to type:

```
foo :
```
and I press enter to start a new line. The problem is the emoji selector popped right when I typed `:`. Pressing enter adds the emoji to the text instead of adding a newline.
This forces me to remove the emoji, and the selector pops again, so I have to press escape then press enter. Every time I want to add a list preceded by a `:`. This is a big pain to use when adding lists in non-English text.

## Describe the solution you'd like

In the emoji selector, allow only `tab` for validating emoji input, not `enter`.

## Describe alternatives you've considered

- Don't pop the emoji selector immediately when `:` is pressed, add a 0.5 second delay so I can press enter quickly without being nagged by the selector
- Require a keyboard shortcut/toolbar button to pop the selector

**Comment by hydrargyrum** [comment]
In fact, there's worse:

When I have finally typed this:

```
something

foo :
- bar
- baz
```

my cursor is at the end of `baz` line.
Suppose I want to go on the `something line`. So I press the `up arrow` key. My cursor is at the end of `bar` line. I press `up arrow` key again. The cursor ends after the `:` of the `foo` line, boom, the emoji selector pops again! If I press `up arrow` again, the cursor does NOT go on the line above, it just moves the selected emoji... I have to press `escape` to be able to move cursor again.

This is again a lot of pain with this popup getting in the way every time. And disabling `enter` for validating the emoji isn't enough to solve this.

Don't pop the emoji selector immediately when `:` is pressed? Add a 0.5 second delay so I can press enter quickly without being nagged by the selector?

**Comment by hydrargyrum** [comment]
any news on this? the chosen milestone means it should have been fixed in the version after the bugreport?

**Comment by mrdrogdrog** [comment]
Hello,

The milestone means that this bugs affects the HedgeDoc 1 code base and may be fixed in the next 1.x release.

First the bad news: As you can look up in the README, we focus on the development of HedgeDoc 2. The code base of HedgeDoc 1 is pretty messy, untested and behaves quite unpredictable to these kind of changes. So because this isn't a critical bug and affects only a few people we won't do anything. At least not in HedgeDoc 1.

The good news: HedgeDoc 2 will have a highly improved auto completion. ✨

**Comment by hydrargyrum** [comment]
> The good news: HedgeDoc 2 will have a highly improved auto completion.

Ok, so it will be fixed in HedgeDoc 2?

**Comment by mrdrogdrog** [comment]
Yes

**Comment by ErikMichelson** [comment]
As this will be concerned for the autocompletion in HedgeDoc 2, but not for HedgeDoc 1 anymore, we'll close this issue.
