### ISSUE TITLE
Edit Rights menu does not open when clicked

### ISSUE THREAD

**Issue by stragu** [hedgedoc/hedgedoc#1378]
**Description**

Clicking on the edit rights menu to change that setting (in a note owned by the user) does not bring up the different options.

**To Reproduce**

1. Go to a note you own on the demo instance
2. Click on the edit rights blue link to change that setting
3. The menu does not open

**Expected behavior**

The menu with the different choices of edit rights should open, like it used to.

**Your Setup:**
 - OS: Ubuntu 18.04
 - HedgeDoc version: assumed to be 1.8.2 as it is the Demo instance
 - Firefox 89.0 and Chromium 91.0.4472.77

**Comment by mrdrogdrog** [comment]
I can't reproduce the problem with my demo instance account. Are you sure that you're logged in with the correct account?

**Comment by stragu** [comment]
@mrdrogdrog : I believe I am using the right account...
But I created a new note and I could then edit the rights as expected. Very odd.
![image](https://user-images.githubusercontent.com/1747497/121274812-a632bc00-c90e-11eb-867b-2716a613aab1.png)

Are all the notes listed on the main page (https://demo.hedgedoc.org/ > History) definitely the ones you own? Or are they all the notes you have visited in the past?
I find it hard to figure out for sure which ones I own... (which is probably something that should be improved in the HedgeDoc interface)

**Comment by mrdrogdrog** [comment]
The history page shows the notes you have visited. 
We will improve this page with HedgeDoc 2.
If the issue if obsolete then please close it. 😊

**Comment by stragu** [comment]
It looks like I cannot change the setting for my older notes, but can with newly created notes.
I am confident that I am connected with the account I created the notes with.
Is there any way to check which account own a note? I've always used my Launchpad OpenID with CodiMD/HedgeDoc, and if someone can look at note ownership in demo instance database, we could know for sure?

* Note I have create a while ago, but in which I can't change the edit rights: https://demo.hedgedoc.org/vTwOIQIWTMmMkOfd0zmyKQ
* Note I created after I noticed the issue, in which I can change the edit rights: https://demo.hedgedoc.org/wYFh8rmoSAKeRpC76p0q_w

Do they have the same owner?

**Comment by mrdrogdrog** [comment]
@SISheogorath

**Comment by SISheogorath** [comment]
@stragu I just checked the demo instance, and these are owned by two different accounts. OpenID is a bit special in the perspective that in theory you can have 2 different users, based on using HTTP or HTTPS openid URLs. Therefore you once sign-up with HTTPS and once with HTTP. Resulting in two independent users :) So everything works as designed, just openid is a bit silly in that perspective.

**Comment by stragu** [comment]
Wowy good spotting, @SISheogorath ! Thank you for looking into it. I can confirm that using `http` instead of `https` in my OpenID I can access the menu in the previous notes.

Moving forward, would one of these options make sense?

* Mention that using `http` versus `https` in an OpenID will result in different account on HedgeDoc (maybe some text that only appears when the user clicks in the OpenID field)
* Make the two logins lead to the same account, silently. (Is that dangerous? Bad practice?)
* Show a message only if the user has previously logged in with one option and is now logging in with the other option. Along the lines of "You have previously logged in using `http` instead of `https` in your OpenID. Doing so will result in a second, separate account. Do you want to cancel and use `http` instead"?

Just a thought, to avoid that kind of confusion in the future :slightly_smiling_face:

**Comment by SISheogorath** [comment]
I'm undecided whether I really want to break the standard to make it useful:

https://openid.net/specs/openid-authentication-2_0.html#http_s_identifiers

Or if it's better to keep the way it is and live with the confusion for the sake of being standard conform :/

**Comment by stragu** [comment]
But the "warning" options (1 and 3) wouldn't break the standard, would they? Just informing the user how it all works.
