### ISSUE TITLE
[2.0] Length of public IDs

### ISSUE THREAD

**Issue by mrdrogdrog** [hedgedoc/hedgedoc#1386]
**Which part of the project should be enhanced?**
Public ids of notes

**Is your enhancement request related to a problem? Please describe.**
In the current implementation of the HedgeDoc-Dev branch the public id is 205 characters long. Yes, I know the id should be unique. BUT 205 CHARACTERS?!
With this "safe" public ids we will encounter problems with the URL length.

**Describe the solution you'd like**
Cut the length of public ids to ~32 characters. That should be unique enough.

**Describe alternatives you've considered**
never try to spell a public id.

**Additional context**
![image](https://user-images.githubusercontent.com/6124140/121823293-9fa49b80-cca4-11eb-8055-1e39e3d78a45.png)

**Comment by SISheogorath** [comment]
Well, the implementation is wrong:

https://github.com/hedgedoc/hedgedoc/blob/ed9df9fadbfaa248c52400675e26088d1f42e3b3/src/notes/utils.ts#L15

One needs to drastically reduce the number of random**Bytes** here.
