### ISSUE TITLE
docs.hedgedoc.org should explain YAML metadata

### ISSUE THREAD

**Issue by davidmehren** [hedgedoc/hedgedoc#1427]
**Which part of the project should be enhanced?**
Documentation

**Is your enhancement request related to a problem? Please describe.**
It is confusing that the YAML metadata is explained in a note at `/yaml-metadata`, but not in our docs.

**Describe the solution you'd like**
Port over the docs from `/yaml-metadata` into our docs.

**Describe alternatives you've considered**
Rewriting the YAML metadata docs completely

**Comment by Payaspx** [comment]
> **Which part of the project should be enhanced?**
> Documentation
> 
> **Is your enhancement request related to a problem? Please describe.**
> It is confusing that the YAML metadata is explained in a note at `/yaml-metadata`, but not in our docs.
> 
> **Describe the solution you'd like**
> Port over the docs from `/yaml-metadata` into our docs.
> 
> **Describe alternatives you've considered**
> Rewriting the YAML metadata docs completely

**Comment by Cologalaxy** [comment]
Hello! I am a new programmer and would like to contribute. This would be my first open source project, is there any guidance you can offer me on how to get started working on this? Thanks!

**Comment by ErikMichelson** [comment]
Hi @Cologalaxy,

thanks for your interest in contributing to HedgeDoc.
To get started, be sure to read the [contribution information/guidelines](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md).

Regarding this issue, the goal is to port over the information about the frontmatter metadata that can be used in HedgeDoc into our docs. The description of the frontmatter fields can be found [currently here](https://github.com/hedgedoc/hedgedoc/blob/master/public/docs/yaml-metadata.md). The docs reside in the [docs/content](https://github.com/hedgedoc/hedgedoc/tree/master/docs/content) directory.

Please be sure to work with the master branch on this (not develop) as this issue concerns HedgeDoc 1.x and the develop branch is for 2.x only.

If you've got more questions, we're happy to answer them in our [community chat](https://chat.hedgedoc.org) or the [dev-chat](https://chat.hedgedoc.org/dev) too.

**Comment by osresearch** [comment]
For the opengraph data, it might be useful to include the `description` field and it with an alternate string mode like:

```
---
opengraph:
  title: "A short single line title"
  description: |
    A longer multiline description of the page with "quotemarks" included.
---
```

**Comment by osresearch** [comment]
I just noticed that the YAML front matter also supports `description` and if it is supplied then the opengraph description is not necessary.  So then only the `image` field is necessary for the opengraph data to look good:

```
---
title: "A short single line title"
description: |
  A longer multiline description of the page with "quotemarks" included.
opengraph:
  image: https://hedgedoc.org/icons/apple-touch-icon.png
---
```

**Comment by Cologalaxy** [comment]
@osresearch, The [current](https://github.com/hedgedoc/hedgedoc/blob/master/public/docs/yaml-metadata.md) file has an opengraph image at line 175. I do not understand what changes you are suggesting.

**Comment by JunedKhan101** [comment]
Hi, From what I understand `https://hackmd.io/@docs/yaml-metadata` needs to be ported to HedgeDoc docs.

Questions:

Do I need to copy the yellow/blue info boxes that are there in `https://hackmd.io/@docs/yaml-metadata`?

If yes, do I need to display the light bulb icon present in some of the yellow info boxes as well?

**Comment by mrdrogdrog** [comment]
Don't refer to hackmd. It's another project.
We're talking about the markdown file in `public/docs` of the master branch

**Comment by JunedKhan101** [comment]
Okay got it. Please assign this task to me.

**Comment by JunedKhan101** [comment]
@mrdrogdrog Will the changes need to made in the master branch itself or develop branch?

**Comment by DerMolly** [comment]
The milestone for this issue suggest it is intended for the master branch, but I guess we would also port it into the docs for HedgeDoc 2. For now creating a PR against the master branch is the way to go.
