### ISSUE TITLE
Session cookie creation on /status

### ISSUE THREAD

**Issue by g00pix** [hedgedoc/hedgedoc#1446]
**Which part of the project should be enhanced?**
The ``/status`` endpoint should not create a session cookie.

**Is your enhancement request related to a problem? Please describe.**
I host Hedgedoc in Kubernetes and I use the ``/status`` as a readynessProbe and livenessProbe. Each time this endpoint is requested, a new session is created and added to the database. The problem is that these probes are making a request every second, which fills up the database with useless session entries.

**Describe the solution you'd like**
I think the ``/status`` endpoint should not create a session cookie.

**Describe alternatives you've considered**
remove the probes, which is not convenient

**Additional context**
I have not checked if the ``/status`` endpoint has any use case where a session cookie is needed. I am sorry if it is the case.

**Comment by davidmehren** [comment]
Yep, that seems like a bug, thanks for reporting!
It shouldn't be a huge issue, as these session entries will get cleaned up eventually, but the database size does get inflated unnecessarily.

**Comment by davidmehren** [comment]
This was fixed in #1468
