### ISSUE TITLE
Enhancement proposal: Implement a collaboration API

### ISSUE THREAD

**Issue by gerion0** [hedgedoc/hedgedoc#1504]
I'm often in the situation (the COVID related homeoffice has amplified this) that I want to work on some text (often source code) together with others at the same time. Hedgedoc solves this nearly perfectly. I'm just creating a new note/document, send the link to the other party and we can start editing/coding. However, this is all done within the browser with a powerful but regardless limited editor. Especially for code writing a full featured editor with LSP/Git/... support is better.

My proposal therefore is to add the ability to connect Hedgedoc with an external (full featured) editor.

Currently, Hedgedoc has an [API](https://docs.hedgedoc.org/dev/api/) for a limited amount of actions. Notably, the actual editing process is missing here.

[Several](https://code.visualstudio.com/learn/collaboration/live-share) [editors](https://www.emacswiki.org/emacs/CollaborativeEditing) [have](https://teletype.atom.io/) [several](https://github.com/googlearchive/collab-vim) [solutions](https://github.com/FredKSchott/CoVim) [for](https://github.com/jbyuki/instant.nvim) [collaborative](https://github.com/gobby/gobby) [editing](https://floobits.com/). Might it be possible to extend the Hedgedoc API with editing capbilities? If that happens, I'm pretty sure that editor plugins would be created very soon and collaborative editing between full featured editors and the native web editor would be possible _in a simple way_.

**Comment by davidmehren** [comment]
We have no plans to expand the feature set of HedgeDoc to more than "document editing".
Building and maintaining that well is enough work. :smile:
For a similar reason, our real-time APIs are not meant for use outside this project.

As you mentioned, there already are many editor-plugins for collaborative editing. The fact that there is no common API yet does not make me hopeful that introducing a "HedgeDoc collaborative editing spec" would make any difference.
