### ISSUE TITLE
how to start this project

### ISSUE THREAD

**Issue by jiutianxuannan** [hedgedoc/hedgedoc#1510]
**Description**

**To Reproduce**

**Expected behavior**

**Logs**

**Config**

**Your Setup (please complete the following information):**
 - Host OS: [e.g. Ubuntu 20.04]
 - NodeJS version [run `node --version`]
 - HedgeDoc version (Click "Version info" in the footer)
     - server [e.g. 2.0]
     - client [e.g. 2.0]

**Additional context**

**Comment by davidmehren** [comment]
Please have a look at [our docs](https://docs.hedgedoc.org/).

Also note that this is an issue tracker. Use the [chat](https://chat.hedgedoc.org/) for questions.
