### ISSUE TITLE
Login with Username & Password

### ISSUE THREAD

**Issue by davidmehren** [hedgedoc/hedgedoc#1515]
https://github.com/hedgedoc/hedgedoc/issues/987 mentions these routes for login with username and password:

- [ ] POST `/auth/internal/login` for logins
- [ ] POST `/auth/internal` for registering
- [ ] PUT `/auth/internal` for updating the password

I'm fine with calling the login method "internal", even though it sounds a bit awkward.

**Comment by davidmehren** [comment]
Is the `internalPassword` route intended for password resets?

**Comment by davidmehren** [comment]
What about shuffling the routes around a bit?
- [ ] POST `/auth/internal`
- [ ] POST `/auth/internal/register`
- [ ] POST `/auth/internal/reset_password`

**Comment by DerMolly** [comment]
> Is the internalPassword route intended for password resets?

Password changes.

**Comment by DerMolly** [comment]
> What about shuffling the routes around a bit?
> 
>     * [ ]  POST `/auth/internal`
> 
>     * [ ]  POST `/auth/internal/register`
> 
>     * [ ]  POST `/auth/internal/reset_password`

This could be done but the last would be

*[ ] POST `/auth/internal/change_password`

it could also be a PUT route

**Comment by davidmehren** [comment]
Do we even support password resets in the API? I imagine that would need some way of verifying the user.

**Comment by davidmehren** [comment]
We could also do
- POST `/auth/internal/login` for logins
- POST `/auth/internal` for registering
- PUT `/auth/internal` for updating the password

which may be more REST-y?

**Comment by DerMolly** [comment]
> We could also do
> 
>     * POST `/auth/internal/login` for logins
> 
>     * POST `/auth/internal` for registering
> 
>     * PUT `/auth/internal` for updating the password
> 
> 
> which may be more REST-y?

Sounds fine to me.

**Comment by DerMolly** [comment]
While implementing this we found `internal` a confusing term (in fact we did so far earlier, but didn't have any good replacement) and choose to replace it with `local`
