### ISSUE TITLE
Session Handling in the Private API & WebSocket

### ISSUE THREAD

**Issue by davidmehren** [hedgedoc/hedgedoc#1516]
To start implementing auth backends (https://github.com/hedgedoc/hedgedoc/issues/1006), we need to think about how to re-identify a user after they are logged in.

The method we select needs to work for the REST-API and the WebSocket used for real-time communication.

**Current candidates:**
- JSON Web Token (JWT)
  - Would be sent as a bearer token in an `Authentication` header
  - Can be sent as part of a handshake in the socket connection
  - Invalidation of sessions (logging out) is complicated
- Cookies
  - Browsers automatically send cookies

**Open questions:**
- ~~What session-handling does the socket library we are going to use support? Does that narrow down our choices?~~

**Comment by davidmehren** [comment]
If we use socket.io (which is very likely, I guess):

It looks like the [`socket.request` object](https://socket.io/docs/v4/server-api/#socket-request) carries cookies, so it seems to be possible to use them to authenticate the request.

Also, arbitrary objects can be [sent on handshake](https://socket.io/docs/v4/middlewares/#Sending-credentials) for authorization, so using a JWT is similarly possible.

**Comment by ErikMichelson** [comment]
I wouldn't say it's very likely that we use socket.io.
But when using plain cookies, they will be sent with the Upgrade-request as well. We have access to that raw HTTP request and could extract the auth cookie value.

**Comment by DerMolly** [comment]
@ErikMichelson and myself tried to discuss cookies vs jwts:

## Cookies

Cookies are a common way for storing session identifiers on the client. After a successful login request, a session-id is associated with the logged-in user in the backend and this id is sent to the client as a cookie. The user's browser keeps track of resending the cookie with each subsequent request.

### Pro
- Cookies are a common and well established technique for holding a user's session.
- The frontend doesn't need to implement any handling of this.

### Contra

- We would need to maintain a list of session id's, their corresponding users and possibly a validUntil datetime.
- Implementing cookie auth in nestjs and handing the user into each request, seems like a bit more implementation work than just using passport/jwt.

## JWTs

Any of the auth routes would give the frontend (after a successful authorization) a Dto containig this JWT. The frontend then would add this to any other requests to the private API in the form of `Authorization` header with bearer schema.

To keep track of active JWTs, each of them should include a unique random id which is added to a whitelist in the backend.

### Pro
- JWTs contain all required information in themselves. So we don't have to keep track of which token is associated with which user.
- As we only store a random id in the whitelist (opposed to a user object and expiry time with cookies), this could easily be extracted into a redis store (or similar), allowing vertical scalability.

### Contra

- The frontend needs to implement a bit more logic, but this seems negable in the grand scheme of things.
- If a user logs out and their JWT was previously obtained by a third party, this third party can indefinetly continue to impersonate the user. To mitigate this we could implement a whitelist. There and session id encoded in the jwt would be saved. If the user logs out the frontend requests this with the backend and the coressponding entry in the whitelist is deleted.

## Final thoughts

A JWT + the afformentioned whitelist seems like the best option to keep the implementation work to a minimal and make it easy to build the application. It's also a bit more "rest-y" than cookies.

**Comment by mrdrogdrog** [comment]
Your first propsal should be "server side session with session ids" because even with JWT I would propose to use http cookies to transmit JWT. This eliminates a lot of attack surface because attackers can't read these cookies with JavaScript.

**Comment by davidmehren** [comment]
NestJS and express give us cookie/session-handling basically for free, see https://docs.nestjs.com/techniques/session. We actually [already have](https://github.com/hedgedoc/hedgedoc/blob/develop/src/users/session.entity.ts) a `Session` entity defined that can be plugged in [connect-typeorm](https://github.com/nykula/connect-typeorm) to persist the sessions and handle expiry.  
Therefore, using cookies seems much simpler to me.

**Comment by ErikMichelson** [comment]
While `connect-typeorm` sounds like an idea to go with, I've still got two questions:
- How is the performance impact compared between storing and reading session data from the database vs. verifying a JWT?
- When scaling the database, would it be possible to allow vertical scaling of HedgeDoc backends or does `express-session` store certain things only in the processes memory?

**Comment by davidmehren** [comment]
For real facts about performance, we would need to do some benchmarking.
But I imagine that one additional DB query is not that relevant, as we probably do multiple queries anyway to serve the request.  
Doing the cryptographic operations to verify a JWT *might* actually be more expensive?  
Also: Depending on the data that we want to store in the JWT, it would add considerable size to every request.

Afaict there is no caching in `express-session`. If scalability becomes a problem with the normal DB, we can always [switch to Redis](https://www.npmjs.com/package/connect-redis).

**Comment by DerMolly** [comment]
I think this can be closed now. The first implementation with connect-TypeORM is on the way…
