### ISSUE TITLE
Can’t upload image

### ISSUE THREAD

**Issue by riadabdel** [hedgedoc/hedgedoc#1530]
Hello,

My version of HedgeDoc is: 1.8.2
Using Docker with nginx reverse proxy

**What I expected to happen:**

Upload images.

**What actually happened:**

Can’t Upload images: Uploading file…_fyk5d7ljx

```
2021-07-08T08:24:59.563Z info: 	deserializeUser: 3bb5fb0...
(node:35) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_URL]: Invalid URL: /uploads/
    at onParseError (internal/url.js:258:9)
    at new URL (internal/url.js:334:5)
    at new URL (internal/url.js:331:22)
    at Object.exports.uploadImage (/hedgedoc/lib/web/imageRouter/filesystem.js:28:19)
    at /hedgedoc/lib/web/imageRouter/index.js:96:22
(node:35) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:35) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
**I already tried:**

Followed this https://docs.hedgedoc.org/guides/reverse-proxy/#reverse-proxy-config 1, but when i put this variable: CMD_DOMAIN, i got errors:
![Capture d’écran de 2021-07-08 14-42-38](https://user-images.githubusercontent.com/52451122/129150932-05cd1546-0912-41d0-88eb-3cffc10f72f4.png)
 When i add CMD_PATH=/var/run/hedgedoc.sock, i got this error: listen EACCES: permission denied /var/run/hedgedoc.sock

**Comment by davidmehren** [comment]
Please don't use the issue tracker for support requests.
If you don't get an answer in time in the community forum (which seems to have happened here, sorry), it's best to ping us either in the forum thread or in the [community chat](https://chat.hedgedoc.org/).
