### ISSUE TITLE
Delete guest notes

### ISSUE THREAD

**Issue by mrdrogdrog** [hedgedoc/hedgedoc#1547]
**Is your feature request related to a problem? Please describe.**
In HedgeDoc 1 you can't delete a note if you created it while not logged in. Even if you haven't left the page yet.

**Describe the solution you'd like**
As a guest user I want to delete a note I created. That would require that we identify guest sessions or provide a deletion / "I'm the owner" link.

**Describe alternatives you've considered**
- See your note exist for all eternity.
- Tell the user "Create an account or you won't be able to delete the note!"

**Comment by davidmehren** [comment]
https://github.com/hedgedoc/hedgedoc/pull/1266 spelled out that anonymous notes will not have an owner, so deletion is not possible.
We use the session cookie only to track edits by the same user.

**Comment by mrdrogdrog** [comment]
We could create a "delete this note" link like imgur does and present it to the user. We can offer to store this in the browser storage or the user can copy it.

**Comment by ErikMichelson** [comment]
Would it be possible to add a deletion token to the database schema of notes?
We don't need to show this token to logged-in users but can use it for guest users in form of the mentioned delete link.

**Comment by cyriax0** [comment]
> Tell the user "Create an account or you won't be able to delete the note!"

That seems not like a solution, as I don't own the guest note I just created.
It should be "Be logged in or you won't be able to delete the note!" (which has happened to me :/ ).

#### Possible Alternative
Could something like "take ownership of guest note" be a compromise?

The intended effect is guests still can't delete notes but members have a way once they are registered/logged in.
On the other side guests not being protected from vandalism by logged in users might be unwanted.

This wouldn't need additional entries in the database but I'm not sure what API calls would need to be implemented.

**Comment by ErikMichelson** [comment]
> Could something like "take ownership of guest note" be a compromise?

This won't work without any checks as everyone could claim other people's notes this way.
However, when using some guest note token (or URL) for deletion, we could discuss whether such a token can be used to claim ownership of the note.

**Comment by InnayTool** [comment]
We thought about a solution and came up with:
If a guest creates a note, the private API-Route returns a delete token which is saved in the browsers local storage. Then the note can be deleted by the browser which created the note by adding the token to the delete request.

**Comment by DerMolly** [comment]
This discussion seems to be finished. An implementation issue will be created…
