### ISSUE TITLE
Improve config validation / feedback

### ISSUE THREAD

**Issue by SISheogorath** [hedgedoc/hedgedoc#155]
We see a lot of issues caused by wrong configuration. This is an indicator that our docs are not sufficient and even more that our software takes garbage to produce garbage.

We should improve our configs in the perspective that we get proper validation for all options. Most common problems are caused by the `domain` option. This along with `https` prefixing and port numbers (where we already have some feedback), should prevent half of all problems.

We can also work on linking error messages to docs, to improve the ability of figuring out problems.

Feel free to comment where you think work is needed the most.

**Comment by ccoenen** [comment]
I recently came across this, and I believe this checks all the boxes:

https://github.com/mozilla/node-convict

As far as I can tell, it checks all the boxes: config file + env vars, validation, documentation.

**Comment by ccoenen** [comment]
At the same time we would gain support for a different config format (JSON is a bad fit because it does not support comments).

**Comment by A-312** [comment]
> At the same time we would gain support for a different config format (JSON is a bad fit because it does not support comments).

JSON5 support comments. See : https://github.com/mozilla/node-convict/tree/master/packages/convict#allow-comments-in-json-files

**Comment by davidmehren** [comment]
This was implemented in #549. We still need to improve the error messages, but I will open a separate issue for that.
