### ISSUE TITLE
I cannot upload a local image

### ISSUE THREAD

**Issue by clemhacks** [hedgedoc/hedgedoc#1578]
**Description**

**To Reproduce**

**Expected behavior**

**Logs**

**Config**

**Your Setup (please complete the following information):**
 - Host OS: [e.g. Ubuntu 20.04]
 - NodeJS version [run `node --version`]
 - HedgeDoc version (Click "Version info" in the footer)
     - server [e.g. 2.0]
     - client [e.g. 2.0]

**Additional context**

**Comment by mrdrogdrog** [comment]
This issue tracker is not for support requests. Please ask in the [Community Forum](https://community.hedgedoc.org) or in the [chat](https://chat.hedgedoc.org).
