### ISSUE TITLE
Media APIs: Implement a decorator to convert header to Note instance

### ISSUE THREAD

**Issue by davidmehren** [hedgedoc/hedgedoc#1594]
**Which part of the project should be enhanced?**
The `MediaController` in both the public and private APIs

**Describe the solution you'd like**
When uploading media, the ID of the note the upload belongs to is transferred in a header.
Currently, the business logic uses `await this.noteService.getNoteByIdOrAlias(noteId);` to create a Note instance from that. We should implement a custom parameter decorator that uses the `GetNotePipe` to get the Note instance.

**Additional context**
https://stackoverflow.com/a/55561022

**Comment by atkac** [comment]
Hello @davidmehren , I'd like to work on this issue.

**Comment by davidmehren** [comment]
This was implemented by @lautaroalvarez 🎉
