### ISSUE TITLE
Extensive Tagging-System with Realms

### ISSUE THREAD

**Issue by w4tsn** [hedgedoc/hedgedoc#163]
Hey there! This is a feature request.

Summery
---

**Feature:** non-hierarchical categories; intersecting knowledge-realms;
**Proposed technical solution:** n:n tagging

The use-case(s)
---

My use-cases involve: writing books, journalism, basically managing projects of a similar category with reoccurring data or handling personal documents. Managing all my notes in a single tool.

When writing books or especially short-stories within a shared universe there will be notes about characters, the world, magic system, history, story-line, chapter outlines etc. while this makes very good categories and the relationship between those is expressed by further tags, there are two problems. 

1. The categories and tags won't make any sense in the context of my personal bank documents or scanned letters.
2. If I write a second story with a different world, the general system might be the same, but I'm already using it for story one - in this case I have to re-use categories and tags in a different space of data.

So in both cases I'd either have to tinker around with other names for the same concepts or in the worst case create two different accounts. It's partially a multi-tenancy problem for ideas / projects so to speak.

While tags and categories can do a lot of these things already, this is only true for the search. On top of the workings underhood I'm thinking more about a UI way to better explore and work with the data in general.

I propose a new tagging/category/realm/namespace system to tackle this problem, which no editor properly implements today - so this might be relatively new ground.

The technical part
---

In general n:n tags are a generalization of both tags and categories how they are used most often today. Categories are just a special case of n:n tags.

I'm proposing a category system based on a tag-network - opposed to the so well-known tag-trees everyone is implementing today - where tags are assigned to articles and tags themselves alike. Having the ability to use tags more as links between articles (or pices of knowledge), rather than folders (which is how categories work), let's one implement much cooler and more complex knowledge use-cases - especially when working on more than one project/topic.

Think of tags as links that tie several things together. A realm is itself a tag which is linking together tags instead of articles so tags are unique, but may be part of different realms. Depending on the selected realm, I'll now only see tags and hence articles that are within those realms. Opposed to namespaces tags should be unique across realms though, since tags (with proper naming) should implement a concept that may span across realms and one may be interested in some use-cases to cross-explore realms. 

Under the hood it's all n:n-tags, but for different purposes differently used.

**Main problem** with this is probably the implementation of algorithms save against circular paths in the tag-network. Especially at the intersection of realms. Maybe a configurable exploration/work depth is required.

Concepts
---

**Realm**s are a specific view on the whole bunch of knowledge. It serves two purposes: it may provide the same tags (and categories) while holding different data, or it might hold the same data, but with other tags and categories - a filtered set - or in other words a specific view on the data. This might in an extended case also imply UI changes.

**Inter-realm links/relationships** some concepts or pieces of knowledge / data is unique to a single realm, others are shared between realms. Being able to build links that connect realms together and their data is key to multi-realm concepts or projects.

**links/tags** are the lines that tie together pieces of information.

**Under the hood it's alls n:n tags!**

How do others do it (or don't)
---

**Evernote** features two concepts to group information / data together. Categories and Tags. Categories are, as one might expect, just nestable folders. Their relationship to data is 1:1. One article may reside in one category. Their relationship to themselves is 1:1 as well. They're basically folders. *Tags* on the other hand are less restrictive. They serve a n:n relationship to articles / data.  Data is explicitly linked together. Selecting a tag may serve you everything from this tag, also from other tags. That way articles are tied together into implicit realms. Tags to themselves have a 1:1 relationship and with that we narrow down the problem with evernote. Because tags can only be handled like folders, not like knowledge / data (what they are, since they are implicit concepts) it is not possible to have one tag appear in multiple other tags. They can't network which highly limits their possiblities.

*I just chose Evernote to depict the overall problem with most notebook tools today. If you have other examples please put them into the comments - I'll put them here for integrity*

**So let me know what you think about this!**

**Comment by ccoenen** [comment]
I love how conceptually deep this is. It is quite a bit to think about. It comes at the best of times, though: the tagging is one of the areas where we're already in full agreement that it needs a major overhaul.

I will answer a more in-depth reply, and I'd also encourage other people to join this discussion.

**Comment by ccoenen** [comment]
(as always: correct me if I'm wrong!)
From your proposal I take it, that a tag should be unique across realms (as opposed to namespaced tags). I'm trying to construct a case where this might not be desireable, just so we have a good trade-off for discussion.

So we might have __🌐 *realm*__  <--- m : n ---> __🏷 *tag*__ <--- m : n ---> __📝 *note*__, right?

Let's suppose we have __🌐 journalism__ realm on one side and __🌐 storytelling__ realm on the other. Let's say both have a tag __🏷 robot__. In one instance this might refer to automatic vacuum cleaners and in the other it might refer to full-on artificial life forms.

So If I were to look for __🏷 robot__, I would see _all_ of the notes, right? If I look at __🌐 journalism__, I'd mostly see the vacuum cleaners, for example __📝 manufacturer unveils new generation of vacuum cleaners__ but not __📝 Roomba's adventures in Technicolor__.

This somehow reminds me of delicious' tag bundles, if you were a user of delicious before they shut down. A tag could be grouped in a tag bundle (think: __🏷 Bread__ can be in both __🌐 food__ and __🌐 health__ and it could have notes like __📝 recipe for sour dough__ and __📝 white flour found to be ... in a study__ )

Delicious got around the circularity, in that bundles were a different entity (you could not add a realm to a realm). But they were not namespaces or categories either. (a tag could be in multiple bundles _and_ a tag was not defined by it's bundle in any way, so not tree-like).

Note: I'm not trying to change the wording, I'm just still in the phase of understanding the proposal and comparing it to implementations that I know!

What would help me, if you're willing to share this, would be a few more examples to wrap my head around. This is _also_ something that everyone should join in. Mostly: what are other people's uses for tags that would be easier this way, or maybe even that would be hindrer that way. I'd love to know!

**Comment by ccoenen** [comment]
One area that is not yet very defined, is, how tags apply in a collaborative environment. This is very different from both delicious and Evernote (at least what I know from evernote from a few years ago).

Personally, I need to be able to use the same tags as coworkers of mine. If I have a note tagged __🏷 project-A__ then this must be the same tag as another coworker's __🏷 project-A__. We need to be able to find those notes when navigating to something like (spitballing here!) http://example.com/tag/project-A and see all of our combined notes. I'm not sure if we would need to share realms, I haven't given this enough thought, yet.

Also, from my examples abover I don't quite understand how  __📝 manufacturer unveils new generation of vacuum__ knows about its __🌐 journalism__ realm? Do I specify both tag and realm explicitly? If so, how would that really differ from just giving it two tags?

**Comment by ccoenen** [comment]
Relaying a message from the community chat:

> I have a tag for each "namespace" in the data I imported and use a dot for multiple levels. For example, pages in what was formerly the /cooking/cookies/ namespace end with ###### tags: `cooking.cookies`
> -- <cite>bitinerant</cite>

**Comment by w4tsn** [comment]
(As I read through it again, the following is not layed out in the clearest way - I'll be able to respond at the end of the week more clearly, but want to drive the discussion nevertheless)

I'm happy this raises some interest and thanks for the constructive and challenging answers. Although I've worked a lot especially with Evernote and over the years developed this idea to some degree, it's still quite vague and need's refinement. Especially the collaboration part is an interesting and tricky topic.

For collaboration I think it would be interesting to be able to create a namespaced realm where one as a collaborator is able to create notes and tags and potentially link (grant access) to tags and notes of other (own) realms? The namespaced component becomes vital if I'm not only in my world of structure and semantics but when interacting with others like in a compound project. This is why I think of realms as part of the m:n relation as well (opposed to Delicious) since this could mean I could introduce a super-realm which is for example all my realms under my account with my namespace etc. But still, when collaborating with other journalists it is my interest to also link to their knowledge (and use their tags?) as well as having a compound pool). So maybe we could think of it as realms of notes that have users as collaborators?

> Also, from my examples abover I don't quite understand how memo manufacturer unveils new generation of vacuum knows about its globe_with_meridians journalism realm? Do I specify both tag and realm explicitly? If so, how would that really differ from just giving it two tags?

Yes, a realm would be assigned explicitly and could be a tag internally. Technically there must not be a difference but I see a realm also differently from a UI perspective. In my expectation I'd like to "set my UI to a realm", so my perspective on my notes changes. Take story writing example one day I'd like to set it to story one, so all I'll see is story one and maybe research material from one of the journalism realms? But not the contents from story two, because this would distract me and interfere with the creative separation of the two stories. I also don't want to find a story about a character Bill, when going through my bank data. 

**On realms and namespaces**: While a realm is a network of tags (metadata) and therefore notes (that are attached with tags) on a structural level, a namespace is a differentiation on a semantic level. So taking the story writing and personal bank documents example my story might have a character named bill, my bank data a category bill. Both may be expressed by a tag, but are semantically different (this could be solved by storyXY.characters.bill tag). Then two stories might have a tag characters, maybe also a character named bill. The structure is the same, but the contents and what I want to see of it are different. I'm not quite sure if namespaces are also tags but used for a special purpose in the UI or if it's a different entity.

Also on your part on realms being their own entities instead of tags with a different purpose... It makes sense to me. I just realised that conceptionally all those category mechanisms are at their core just "tags" and what really metters is actually structure and semantics behind them. Having everything being the same entity under the hood with an m:n relation might enable interesting **custom structure**, **sharing** and **authorization**. It might also just screw everything up :D So maybe at least there should be realms and namespaces as different entities. This has to be discussed further.

And to take on the relayed message from bitinerant, I also did that but came to the conclusion that especially when dealing with many structural and semantically different realms of data it get's messy pretty fast. I mean, the data is organized, but working in a focused creative manner with all that clutter around is rather annoying to me. At the end, the organization features should on the one hand enable complex relations but at the same time stripping down complexity from a use-case/UI view so I can focus without getting overhelmed.

**On authorization** How would users grant each other access to realms/tags/notes? Basically if realms have collaborators and define an interface to the underlaying notes and a note is at least part of one realm the realms could then be used to authorize collaborators. Maybe every user has a default (super)-realm and if I want to share a note or a set of notes of a specific topic I'll put it into a realm and give the respective user access to it (read, write, whatever-fancy-policy).

**Comment by ccoenen** [comment]
I haven't worked through these, but AO3 has an elaborate way of tagging:
https://archiveofourown.org/faq/tags?language_id=en
https://archiveofourown.org/wrangling_guidelines

Maybe there's things in there that can be adapted as well.

**Comment by SISheogorath** [comment]
After some conversation today, that I had with @w4tsn, let me summarize our findings about the concept:

## What…

At the end of the day the entire structure comes down to 5 Models that are required to implement a system that hopefully fits all needs:

- Notes
- Users
- Teams
- Realms
- Tags

So let me explain the Models a bit:

### Notes

Notes are, as they are right now, document which contain content that we want to share and collaborate with.

### Users

Users are, as they are right now, logged in people who own Notes and Realms.

### Teams

Teams are a concept that provides a hierarchical organization of Users and Notes. This is done similarly on GitLab where Teams exist as organizations but can also have sub-organisations.

A team can, as well as a user, own notes and Realms.

### Realms

Realms are namespaces for tags and allow scoped views of Notes. The realm itself can also be a tag.

### Tags

Tags are strings which are organized in a `Realm name/tag name` way, which allows `Realm name` also to be a tag, without conflicting. Tags are attached to notes.

## Why…

While talking we noticed the problem that tags are useful tools to categorize notes across namespaces. Which means I can simply attach my tags to notes that are interesting for me, but might be owned by someone else, as well as the other way around. Therefore making notes owned by realms makes very little sense.

At the same time, we definitely have people who have a clear interest in the existence of such hierarchical and scoped ownership of notes, which makes Teams a thing.

And now things get a bit messy: First of all I can imagine that a user wants to have multiple realms to organize their notes. From the examples above lets say a journalist keeps notes around and a realm "article A" with the tag "possible source". Now the same tag "possible source" might be attached to the same document but for the realm "article B".

Realms therefore become views with their own structure onto the same set of data.

Teams on the other hand, are a tool to manage access and ownership of notes realms. Since it might be useful when 2 journalists work together, they can create a team. And in this team they share the realms for the tags which can be assigned to the documents.

This provides us the best flexibility and allows both: Networked realms and hierarchical organization structures.

## Consequences

First of all: A lot of work.

The technical implementation looks like this:

Users/Teams <-1:n-> Realms <-1:m-> Tags <-k:l-> Notes

It might be even an idea to create public and private realms which are either or not accessible from outside.

This also allows us easy URL building: `https://codimd.example.com/[user/<username/team name>[/realm/<realm name>[/tag/<tag name>]]]`

Important: Of course users can only see notes which are tagged, that they also have access to. Means when I tag my private note with a tag from a realm owned by a team, only team member who also have access to the note can see this note being tagged like that.

(And yes, this also means we have to rework permissions \o/)

All in all: Quite a big thing to do. Anyone who wants to go for it? :D

**Comment by ccoenen** [comment]
I would have preferred to lay out *things to be achieved* with this in more detail first. Looking at this feature set from a user's perspective for a while. Thinking about real world scenarios that we want to solve and facilitate. We probably need to decide for and against a few things along the way. Also, this tagging system is going to be more complicated than most (which we probably all agree we like about it), but how do we explain this to users?

I would tackle this starting with the user-facing documentation as if everthing was finished. A lengthy how-to with a ton of examples. Including mock-up screenshots (poorly drawn is fine). This is then basically a spec that we need to meet.

In all our proposals, there are unanswered questions. I'd hate to answer them by "what was easiest at the time". An example:

If we work on one note together, and I tag it **🏷 food**, does that mean that you don't even see this tag? What if you also tag it **🏷 food**? In the proposed structure, that is a different tag. Nothing wrong with that, but this has implications for retrieval and user interface that we haven't explored, yet.

If, at some point, we'd like to display all tags that were given to a document, then we now have **🏷 food**, **🏷 food** in that list? or is that now   **👤 ccoenen / 🏷 food**, **👤 SISheogorath  / 🏷 food**?

Can I look at all public documents tagged **🏷 food** regardless of realm and/or user and/or team? Of course, from a database perspective this is easy. What I want to know is, what kind of access and retrievability we want users to have.

Another question:
In the proposal, both 👥 Teams and 👤 Users can create tags and realms. From a database perspective that is trivial. From a user interface perspective this is going to be horrible. How am I going to distinguish this for every single tag I apply? Let's say I'm part of four teams, and you are part of another set of teams (perhaps with some overlap). Now I want to add a tag to this note we're working on. This tag could be part of **👤 ccoenen** or **👥 team A** or even **👥 team B**. I'm not even mixing in the realms, yet (it's basically the same question, just on another level).

A third question:
When we would need to give this amount of info to a tag, it feels like we couldn't just make one up on the spot. This would be a grave mistake. If we need a three-step wizard for every tag in the system, then this is basically unusable right from the start.

**Comment by SISheogorath** [comment]
We just got #178 an idea of how to reorganize notes in CodiMD. Looking forward to working on some input from both sides

**Comment by pierreozoux** [comment]
I think that CodiMD should just take care of notes, and integrate with a proper document management system like Nextcloud, you'd get users, teams (or groups) and tags for free, but I already said it elsewhere ;)

But for the sake of the argumentation, I don't like this realm thingy. I think that tags would be enough for your use case.

If you are writing a book, and the title is say, `MyFantasyBook1`, then you put this as a tag. If it is a `character`, then you also put it as a tag, and you want to search for characters of this book, well you put both tags in the search field ;) I think it is enough, and it shouldn't be more complexe than that.

If you want to embrace all the complexity of the world, then I'd recommend you to let users use arbitrary key values. This is a "new" trend in server administration since some years now, and it is really powerful.

I think most of the time, tags are enough, but if you want to describe real complexe things, then use key: values.

**Comment by w4tsn** [comment]
I thought about your suggestion with just using pair of tags for what I want to achieve.

The problem is this: when I'm having to stories with characters of the same name I can only start to duplicate stuff in each of my tags like this `storyname:charactername,storyname`. I really don't like this idea.

Also when having all the tags in one namespace / realm (which my account basically is at this moment) my tags get pretty tedious. I tried this out once working as I'd like to work and building a 'workaround' with the current tag system. I end up pretty fast with having e.g. 150 tags in roughly a year of usage.

The key problem here is, that I want to organize my knowledge in distinguishable realms since I'm setting up my mind or mood into different modes of operation depending on if I'm about to write story, documentation, blog posts or songs. Those are all very different and I'd like to have a distraction free environment as much as possible.

I hope without going into further detail here and writing a whole user story I could transport what I'm after ;) I think a user-story would definitely help - as soon as I find the time to write one :S

I think the strength of the proposed system (somehow like this, there is room for improvement) is different then using nextcloud groups, teams etc. or arbitrary key:values. It's also about a UX concept and furthermore about the idea of knowledge graphs / networks instead of hierarchies. I'm not quite sure if (or how) this would be possible in nextcloud. If you have an idea about that - I'm always open for thought!

Also it comes to my mind that there are knowledge graph databases out there and maybe this would be to much of a change for codimd. It might be subject for a new project all together or integration in another software better suited for the job - not sure about that, thoughts are welcome!

**Comment by pierreozoux** [comment]
Hum, a mix between neo4j and codi, interesting:)

**Comment by GeneralMine** [comment]
Any update on the folder or tagging topic?

For me and I guess at least some others is this feature is crucial!
As @w4tsn described its getting pretty messy after a year of usage. I also ended up multiple times with over 150 tags. Within a team even over 250 tags..

I agree that there should be another solution than changing or integrating into other platforms, especially when you would have to setup a entire nextcloud only for the note management of codi. 

Codi is too beautiful to move...

**Comment by InnayTool** [comment]
This discussion is continued in #1002.
