### ISSUE TITLE
Run frontend and backend together

### ISSUE THREAD

**Issue by davidmehren** [hedgedoc/hedgedoc#1669]
### Which part of the project should be enhanced?

ehh, development tooling?

### Is your enhancement request related to a problem? Please describe.

We need to start testing the frontend and the backend together.
Currently, the frontend uses mock-data to simulate a backend. Soon, the backend should have implemented enough features to be useable by the frontend.

Therefore, I'd like a way to run frontend and backend together. This is just for developing, so both components can still use their dev-servers.

### Describe the solution you'd like

I have two main ideas:
1. Ship a `Caddyfile` that proxies the required paths to the dev-servers and makes HedgeDoc available at `https://hedgedoc.localhost`
2. Add the required proxy-functionality to the backend, so that it forwards requests to the React dev-server.

I'm not sure what I like more. The first idea requires Caddy, but is completely independent of our software. The second option is built-in, but feels a bit bloat-y

### Describe alternatives you've considered

Another idea included using Docker, but that seems to make e.g. debugging unnecessarily hard.
We can investigate Docker for production deployments at a later time.

**Comment by ErikMichelson** [comment]
Currently both servers can be tested altogether like this:

- Run the backend dev server on http://localhost:3000
- Start the frontend dev server with `yarn start:for-real-backend`.

With this the frontend runs at http://localhost:3001 and communicates with the backend at port 3000. You only need to access HedgeDoc via the frontend URL.

**Comment by SISheogorath** [comment]
as far as I know one of the target pictures we described many moons ago, was to keep the concept of having just one application to start, in order to get a functional Hedgedoc instance.

What I'm concened about with the caddy solution is that it would maybe require a separate config. If we solve this, by e.g. generating it using a template, I'm fine with either way. But we should stick with one config file that rules all aspects of the app for produktion but also development.

**Comment by davidmehren** [comment]
> keep the concept of having just one application to start

That is still the goal. The caddy-solution would be a dev-only stop-gap, until we have the final integration figured out.

I'm going to experiment with option 2 a bit, as the resulting code may be reusable to serve the compiled frontend from static files (which we need anyway, at a later time).

**Comment by mrdrogdrog** [comment]
I don't see why the backend has to reverse proxy the frontend in dev mode 🤔

Backend runs on port 3000.
Frontend runs on port 3001.
Browser opens the frontend. The frontend is (like @ErikMichelson said) capable of sending the API requests to any url you want because we introduced a environment var for that.

**Comment by almereyda** [comment]
A discussion has been commenced in a new issue, which brings more context and opens up three suggested scenarios about how things should work.

- #1965

Indeed it appears that in development environments addressing each process individually will ease debugging, with no local proxy present in any way (integrated or external), and that it may appear suitable to use an external, proper proxy when running in production.

What remains an open question, if it is advisable to consider the individual parts of the HedgeDoc (2) *application* being an integrated part and run as one, or if it actually consists of two individual processes, which are treated as such. For isolation and modularity purposes, the latter seems to be the case.

I will add more reasoning about this to the referenced issue.

**Comment by mrdrogdrog** [comment]
The current dev setup consists of a backend process, a frontend process and a caddy (or other reverse proxy) that fuses both together under one URL-Origin.

[The caddyfile exists in the frontend-repository](https://github.com/hedgedoc/react-client/tree/main/docker)
