### ISSUE TITLE
Link in document refered to the HedgeDoc Instance, not the HTML itself

### ISSUE THREAD

**Issue by dsmrs** [hedgedoc/hedgedoc#1692]
### Description

When create anchor to an ID (like a a section title), the exported HTML refered to the HedgeDoc instance not the HTML itself

### Steps to reproduce

1. create a inner link in Mardown in a HedgeDoc note
```Mardown
# Title1
some text

## Subtitle
As seen in [section 1](#Title1)
```
2. export in HTML (the full one)
3. see the anchor generate from the markdown as 
```HTML
<a htef="https://myhedgedocinstance.com/XXXX#Title1">section 1</a>
```
instead of
```HTML
<a htef="#Title1">section 1</a>
```

### Expected behaviour

The "inner links" in the exported HTML shoudl refer to itself

### Your Setup

- Host OS: YunoHost 4.2.8.3 
- HedgeDoc version: 1.9.0

### Additional context

I used to run on the 1.7.2 version before, and it was exporting like it should (keeping the innerlink ID without adding the instance url).

**Comment by mrdrogdrog** [comment]
It seems like that's because of https://github.com/hedgedoc/hedgedoc/pull/1479 which should fix https://github.com/hedgedoc/hedgedoc/issues/1476.

tbh I have no idea how to fix this without breaking the slide links again.

**Comment by dsmrs** [comment]
The comment was premonitory 😄 

I actually use a note as a website for www.mydomain.tld. But since I updated to the 1.9.0, the HTML generate is much bigger (all bootstrap and images inside it), so it makes it even harder to edit all the "hashtag links" afterwards.

Could it be done when exporting the HTML ? (I don't know how it is done inside HedgeDoc).

**Comment by mrdrogdrog** [comment]
The HedgeDoc 1.x code is big and messy. That's why we're rewriting it. It's also completely untested, (Another thing we're going to change in the new version) so we never know what will break if we touch something. 😅

Hm . I'm not sure if we can fix it without breaking the slides again, but I'll take a look.

**Comment by mrdrogdrog** [comment]
If you want to use markdown for your website, have you thought about using [https://gohugo.io](Hugo)? Making websites out of markdown is it's main purpose while Hedgedoc is for creating document.

**Comment by dsmrs** [comment]
I used to use Jekyll a lot. It's just I love the basic template of HedgeDoc/Codimd, really simple to edit the content for the no-nerd people in the team with a "beautiful live result" (not possible in Jekyll without a proper IDE). And also all the other features: embbed videos, LateX, Alerts, Diagrams, .... . Including all of them in Hugo or Jekyll will be too much work. 

But yes, we're starting to have too much content to keep a simple page website anyway, so we may switch to Jekyll. It's just that, inner links in HTML used to work well. May be it'll be back for the v2 ?? 😀

**Comment by mrdrogdrog** [comment]
Well. Just like I though. The html export just grabs the currently rendered content from the browser. (see https://github.com/hedgedoc/hedgedoc/blob/master/public/js/extra.js#L698). . (Another thing I'm glad we changed in 2.0 :grin: )
I'm not sure if we want to fix this in 1.x as we fix only critical bugs

@davidmehren @ErikMichelson @DerMolly  what do you think?

**Comment by DerMolly** [comment]
I think you're right and fixing this will be complicated and should probably be only tackled if there is some vulnerability. I'd rather not break something else in an upcoming release…

**Comment by davidmehren** [comment]
I, too, think that this is out of scope for 1.x at this point. @mrdrogdrog are we sure that this will be fixed in 2.0 or should we create an issue?

**Comment by mrdrogdrog** [comment]
Well, the html export isn't built in yet, but the way we plan to implement it, this issue shouldn't happen.

(Instead of just grabbing the output, we 
 render the markdown again for the export.)

**Comment by davidmehren** [comment]
Alright, let's close this for now and wait for the new export :pray:

**Comment by PyHahiro** [comment]
I know the issue is closed, but I still got it recommended when I stumbled upon it when trying to export to pdf. the issue is working on hedgedoc 1.9.9 and 1.10.0

My workaround as someone **lazy** while waiting for a fix is to : 
1. Menu => Export to HTML / Download HTML
2. Manually change all links (can easily be done with Notepad++ by doing :
    1. `ctrl+f ` then `ctrl+h` 
    2. replace `http://{hostname}/{documentId}#` by `#`
link example : `http://localhost:3000/NEav5t4nRS60O9mFZfFWOg#`
3. Then, open the freshly edited .html file in your browser
4. execute `ctrl + p` to open the print menu => `save as pdf` => `save`

**Comment by BarnabeCarre** [comment]
I have the same issue.
Thank you for your manual solution.
Do you know if the hedgedoc developers will correct this problem in future updates?
