### ISSUE TITLE
Download HTML file links to Cloudflare and Google-font

### ISSUE THREAD

**Issue by popindavibe** [hedgedoc/hedgedoc#175]
Hello,

When I download a CodiMD note as an HTML page, it uses Cloudflare CDN and import Google-font from the generated html file.

I was (wrongly?) expecting the html file to keep the CSS properties of the page itself (which does not source anything from outside). 
Testing by replacing Cloudflare link ref with my domain `https://<domain>/build/...` seems to display fine. Same goes for Google font import, replaced by `https://<domain>/build/font-pack.css`.

**Comment by SISheogorath** [comment]
Good point, let's work on solving it :)

If you want to start, here you go:

https://github.com/codimd/server/blob/master/public/views/html.hbs

This is the template that is used by the client side function to render the page that is downloaded.

https://github.com/codimd/server/blob/c6e4f3757e16e39f8f1f75c898eb20eb2eb9db4a/public/js/extra.js#L650-L681

**Comment by jadjay** [comment]
Same on **pretty** and **slide**

**Comment by SISheogorath** [comment]
Pretty and Slide respect the `useCDN` setting:

https://github.com/codimd/server/blob/c6e4f3757e16e39f8f1f75c898eb20eb2eb9db4a/public/views/pretty.ejs#L20-L30

https://github.com/codimd/server/blob/c6e4f3757e16e39f8f1f75c898eb20eb2eb9db4a/public/views/slide.ejs#L18-L29

**Comment by popindavibe** [comment]
Thanks @SISheogorath, I'll see what I can do, looks easy enough.

**Comment by popindavibe** [comment]
ok I take that back, it's out of my league :-/
But I agree to get rid of the CDN altogether \o/

Along the same line of idea, the Googleapi import of SourceSansPro font seems redundant, as it is already part of the repo. I'm talking about `public/css/google-font.css`, which ends up in the `{{{css}}}` of the html template (first call in `public/build/html.min.css`). Removing it seems harmless.

**Comment by ccoenen** [comment]
Thank you for trying, and more importantly: thank you for reporting back! This is often forgotten and then issues are left hanging for weeks before this is discovered - so: you did everything right!

**Comment by popindavibe** [comment]
Thanks @ccoenen 

On my last tests, I realised that the fonts are failing to load because of missing CORS. I know codimd handles CSP (works great) but I don't know if it can do CORS as well.

Well it just fails over to system fonts, which isn't dramatic, but ask the question on whether the download should package everything (css, js, images, fonts, etc in a folder to make our downloaded pad fully featured in a non-connected scenario) or only the html bits?

**Comment by InnayTool** [comment]
Hedgedoc 2.0 will drop CDNs and we won't change the behavior of 1.X so I close this issue.
