### ISSUE TITLE
memorable links

### ISSUE THREAD

**Issue by pedro-nonfree** [hedgedoc/hedgedoc#1762]
### Is your feature request related to a problem? Please describe.

hedgedoc provides good secure links by default, but sometimes you want to share the link and remember it. this is already possible with etherpad, you can type anything and it recognizes it as a new pad https://pad.example.com/p/mynewnote . Hedgedoc instead returns `404 Not Found oops.`

### Describe the solution you'd like

the hability to open a new memorable link such as https://demo.hedgedoc.org/2021-10-21_notes ; maybe with a new endpoint, if that interferes with something else https://demo.hedgedoc.org/m/2021-10-21_notes

### Describe alternatives you've considered

nothing else

**Comment by mrdrogdrog** [comment]
Hello,

This is already possible. If you host your own instance then you can activate the free url mode in the configuration.
https://docs.hedgedoc.org/configuration/#users-and-privileges

This is deactivated on the demo instance.
