### ISSUE TITLE
Deleting Note does not remove it from the histories of other users, causing confusion

### ISSUE THREAD

**Issue by someone-somenet-org** [hedgedoc/hedgedoc#1767]
### Description

Deleting Note does not remove it from the histories of other users, causing confusion

### Steps to reproduce

1. create a note and write some text (do some serious work, be finished and send it as finished email or do something else)
2. delete note.
3. other users still have note in their history. when they click it a new and empty note without any history is created.
4. people panick.

### Expected behaviour

+ When deleting the note, it should be removed from the histories of all other users.
+ dont automatically create notes, just tell them 404 or something like that.

### Your Setup

- docker-compose on debian 11.
- HedgeDoc version: 1.9.0

**Comment by davidmehren** [comment]
We are tracking the implementation in 2.0 in https://github.com/hedgedoc/react-client/issues/1586.
As this won't be fixed in 1.x, I'm going to close this issue.
