### ISSUE TITLE
Enhance the permission management features

### ISSUE THREAD

**Issue by WillGoGithub** [hedgedoc/hedgedoc#177]
Hi everyone! Thanks for your amazing work. 😉

If CodiMD could support advanced permission features will be more powerful. 

The concept for example:

**+ System role - Admin** 

* Can maintain all of the note created by any owner (No matter what access permission is) 
* Admin is able to read/write the content or assign/remove owners 
* When first account login, let it auto become the admin (Email/AD) 
* Admin can set multiple users as admin or remove them (Not includes self) 

Or just use the config file to announce the admin account (Separate by comma). That may let implementaion simpler.      

---

**+ Note role**

Even the access permission is private, the note role is beyond it.

| Note role | Ability |
|:--------------:| --- 
|Owner  | Is able to read/write the content or assign/remove owners to a note. 
|Writer | Assigned by admin or note owner through the account. Can read/write the content only.
|Viewer | Assigned by admin or note owner through the account. Only can read the content. 

The permissions of note role: 

Role   | Create | Read | Write | Delete | Assign | *Remark |
-------|:------:|:----:|:------:|:------:|:------:| ------ |
Admin  | ✔ | ✔ | ✔ | ✔ | ✔ | All of notes
Owner  | ✔ | ✔ | ✔ | ✔ | ✔ | Own by self
Writer | -  | ✔ | ✔ | ✖ | ✖ |
Viewer | -  | ✔ | ✖ | ✖ | ✖ |

You guys are awesome! 👍 

---

The following issues might be related:

> #55 
> [hackmdio/codimd#12](https://github.com/hackmdio/codimd/issues/12)
> [hackmdio/codimd#35](https://github.com/hackmdio/codimd/issues/35)
> [hackmdio/codimd#272](https://github.com/hackmdio/codimd/issues/272)
> [hackmdio/codimd#507](https://github.com/hackmdio/codimd/issues/507)
> [hackmdio/codimd#1174](https://github.com/hackmdio/codimd/issues/1174)
> [hackmdio/codimd#1203](https://github.com/hackmdio/codimd/issues/1203)

**Comment by InnayTool** [comment]
The discussion on the admin topic will be continued in issue #995.
