### ISSUE TITLE
Discuss group concept of organize notes

### ISSUE THREAD

**Issue by WillGoGithub** [hedgedoc/hedgedoc#178]
When you have tons of notes and run many teams/projects 😵 , the **folder feature** can be very helpful. 💪

To avoid the implementation effects all of the notes CRUD behaviors. I'm wondering if there is an easier way to do it. 🤔 

**For example**, use the markdown like `###### tags: ` but replace to `dir`:

`###### dir: {folderName}` or
`###### dir: {folderParent} > {folderChild}` or
`###### dir: {folder_1} > {folder_2} > {folder_3}`

Next, let the front-end to do magic tricks! Maybe we don't need the **real entity** to seperate folders. Just use UI to virtualize it. Also, that will be able to split the permission concept which does not need implement on the folder right away. 

**Screenshot** (modified from ShowDoc UI): 

![image](https://user-images.githubusercontent.com/45837931/64587307-7f5df380-d3d1-11e9-83e2-aaf76c295c4b.png)

CodiMD rocks ! 💯

**Comment by SISheogorath** [comment]
Related #163

Both issues try to solve similar problems with two different approaches. Look forward to input from both sides.

**Comment by WillGoGithub** [comment]
Another idea is nested tags:

![image](https://github.com/notable/notable/raw/master/resources/demo/tags.png)

> Refs from: https://github.com/notable/notable

**Comment by pierreozoux** [comment]
I think I'd prefer CodiMD to become agnostic to the data backend.

For instance, [collabora online](https://www.collaboraoffice.com/code/) can be used with Nextcloud, ownCloud or standalone, and I'd love CodiMD to take the same path. But yeah, easier said than done ;)

I love Nextcloud to manage documents, but I love CodiMD to edit Markdown in a collaborative manner ;)  i know, this relates to https://github.com/codimd/server/issues/60 ;)

**Comment by sunjam** [comment]
@pierreozoux Checkout the [Ownpad application](https://apps.nextcloud.com/apps/ownpad) for Nextcloud/Owncloud using Etherpad and EtherCalc, plus [this request for CodiMD support](https://github.com/otetard/ownpad/issues/87)

**Comment by InnayTool** [comment]
This discussion in continued in #1002.
