### ISSUE TITLE
Allow change tracking mode

### ISSUE THREAD

**Issue by nsheff** [hedgedoc/hedgedoc#1815]
### Is your feature request related to a problem? Please describe.

When multiple people are collaborating on a document, sometimes one wants to propose a change for review by someone else.

### Describe the solution you'd like

The 'track changes' feature of MS Word is useful in that it allows a reviewer to propose changes, which can be accepted or rejected by a primary author

### Describe alternatives you've considered

Looking at the revision history could at least let the author know what the editor changed, but this is tedious and doesn't allow for easy rejecting of changes.

**Comment by davidmehren** [comment]
Thanks for the suggestion!
For the record, a similar feature has already been proposed: https://github.com/hedgedoc/react-client/issues/529

It seems that you want the proposed changes to not live in the markdown itself, but be saved only as separate comments.

We currently use only the markdown note content as the source of truth for all features, like tags or other metadata. Changing that would complicate several things, so I'm inclined to say that such a request is out of scope for this project. What do you think @InnayTool @hedgedoc/frontend ?

**Comment by mrdrogdrog** [comment]
I agree. The current plan is to implement critic markup and to see if that's enough.

**Comment by DerMolly** [comment]
Should this then be closed @davidmehren @mrdrogdrog
