### ISSUE TITLE
remove link to writeable note from published read-only note

### ISSUE THREAD

**Issue by uscw** [hedgedoc/hedgedoc#183]
In the Features document (https://demo.codimd.org/s/features) it is stated:

**Share Notes**
If you want to share an editable note, just copy the URL.
If you want to share a read-only note, simply press the publish button and copy the URL.

But it is still possible to change from the read-only note to the URL of the editable version, which means that the URL of the read-only note is actually not read-only. It only would be read-only, if one does not get the hash of the editable notes URL there. This would be particularly interesting for the notes with less protected permissions.

**Comment by ccoenen** [comment]
I totally agree, and this has bothered me before as well. We should keep this in mind when we overhaul the permissions ( #177 ). In my opinion, publishing is only useful if it does not lead back to the editable document. (if I wanted it to link back to the document, I could just share the pad itself).

**Comment by ritesh-pandey** [comment]
Can I take this up?

**Comment by SISheogorath** [comment]
Sure, go ahead :)

If there is anything you need, @ritesh-pandey feel free to reach out to me her or in the [CodiMD community channel](https://riot.im/app/#/room/#codimd:matrix.org) :)

**Comment by ritesh-pandey** [comment]
If I understand correctly, we need to remove link from `public/views/pretty.ejs` file, right?

Is `public/views/pretty.ejs` used for rendering read-only published notes only? If not, we might have to put some condition.

**Comment by SISheogorath** [comment]
I think we need a condition there. It should depend on the note permission.

**Comment by ErikMichelson** [comment]
(See my comment on the PR)

**Comment by davidmehren** [comment]
We won't be able to fix this in 1.x, but intend to not have this problem in 2.0.

**Comment by davidmehren** [comment]
This will be solved by sharing a read-only link, which is tracked in https://github.com/hedgedoc/hedgedoc/issues/471
