### ISSUE TITLE
Configurable password policies for internal auth

### ISSUE THREAD

**Issue by ErikMichelson** [hedgedoc/hedgedoc#1846]
### Is your feature request related to a problem? Please describe.

Short or weak passwords can be a security risk to the instance's data.

### Describe the solution you'd like

Two ideas:
 - Instance owners can define a minimum password length for internal login.
 - Instance owners can define a regex that needs to be fulfilled for passwords of internal login.

### Describe alternatives you've considered

Find sane default values and don't let the instance owner define them. However, currently even empty passwords containing only of spaces would be accepted and that doesn't seem right.

**Comment by SISheogorath** [comment]
Uhm, please be careful with regexes. [ReDoS](https://owasp.org/www-community/attacks/Regular_expression_Denial_of_Service_-_ReDoS) is a thing and can appear easily when people don't know how to avoid them. Rather allow them to define character classes or throw out minimum length[^1] and the regex all together and just implement a complexity score and allow to define a minimum score: https://dropbox.tech/security/zxcvbn-realistic-password-strength-estimation

Some general best practices on the topic can be found here: https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html#implement-proper-password-strength-controls

And integration with "have i been pwned" would be generally recommended to make sure compromised passwords are neither able to authenticate, nor able to sign up in first place.

[^1]: personal opinion here

**Comment by mrdrogdrog** [comment]
Customs length and categories: okay.
Custom regex: please don't.
