### ISSUE TITLE
Docker installation on a vServer leads to unexpected results

### ISSUE THREAD

**Issue by okanIz** [hedgedoc/hedgedoc#1854]
### Description

Functionallitys cannot be loaded

### Steps to reproduce

1. I went to the HedgeDoc Docker Image documentation (https://docs.hedgedoc.org/setup/docker/)
2. pulled the docker image
3. created a docker-compose.yml file on my Ubuntu 20.04 vServer 
4. the result was pretty confusing..

![Bildschirmfoto 2021-12-02 um 05 35 48](https://user-images.githubusercontent.com/25394468/144358444-a52df0dd-4c73-4ba6-aa46-73c30d3f6768.png)
 

### Expected behaviour

I expected, that i would be able to use HedgeDoc on this way with full functionality. 

### Your Setup

- Host OS: [e.g. Ubuntu 20.04]
- NodeJS version: [run `node --version`]
- HedgeDoc version: (Click "Releases" in the footer)

**Comment by mrdrogdrog** [comment]
Hello,

Are you using a reverse proxy?
Have you checked the log?
Have you read the faq entry [why does my interface look weird](https://docs.hedgedoc.org/faq/#why-does-my-interface-look-weird)?

**Comment by ErikMichelson** [comment]
@okanIz Could you fix the problem in the meantime?

**Comment by davidmehren** [comment]
Hi @okanIz, if you still experience problems, please reopen this issue and provide more details.
