### ISSUE TITLE
Adjust one-click-login provider frontend-config API

### ISSUE THREAD

**Issue by ErikMichelson** [hedgedoc/hedgedoc#1884]
### Which part of the project should be enhanced?

API: Frontend-Config

### Is your enhancement request related to a problem? Please describe.

Currently, the backend includes an array of enabled auth providers in the frontend config ([see here](https://github.com/hedgedoc/hedgedoc/blob/develop/src/frontend-config/frontend-config.dto.ts#L19)).
As the frontend-config additionally contains a list of custom auth providers ([see here](https://github.com/hedgedoc/hedgedoc/blob/develop/src/frontend-config/frontend-config.dto.ts#L115)), rendering the relevant one-click-login buttons is harder for the frontend as the data needs to be aggregated on client side.
This situation also does not allow multiple GitHub one-click-logins (when using github.com in addition to self-hosted enterprise deployments).

### Describe the solution you'd like

The API should return an array of enabled and configured one-click-login providers. This could look like this:
```json
[
  {
     "identifier": "fsorg-git",
     "label": "GitLab fachschaften.org",
     "type": "gitlab"
  },
  {
     "identifier": "github",
     "label": "GitHub",
     "type": "github"
  }
]
```

The identifier should be unique and the same as the user configured in the backend config. It is used to build the link target where the one-click-login button points to. Example: `hedgedoc.test/auth/fsorg-git`.

The type should represent which appearance the frontend will choose for the button and logo.

### Describe alternatives you've considered

Keep it like it is. :/

**Comment by mrdrogdrog** [comment]
I support this. This would make the frontend config api less redundant
