### ISSUE TITLE
[1.9] Ignore health check endpoint logging

### ISSUE THREAD

**Issue by licy183** [hedgedoc/hedgedoc#1933]
### Which part of the project should be enhanced?

logger

### Is your enhancement request related to a problem? Please describe.

Hello, I upgraded hedgedoc to the latest version (v1.9.2), deployed it using Docker, and found that the health checking request was logging all the time. A lot of space will be used to save these useless logs.

```
2021-12-27T19:19:23.134Z info:    127.0.0.1 - - [27/Dec/2021:19:19:23 +0000] "GET /status HTTP/1.1" 200 268 "-" "hedgedoc-container-healthcheck/1.0"
2021-12-27T19:19:28.320Z info:    127.0.0.1 - - [27/Dec/2021:19:19:28 +0000] "GET /status HTTP/1.1" 200 268 "-" "hedgedoc-container-healthcheck/1.0"
```

### Describe the solution you'd like

Do not log the health check request.

### Describe alternatives you've considered

The [`skip`](https://github.com/expressjs/morgan#skip) option of library `morgan` may be helpful. 

We can detect this kind of request using `User-Agent`, or create a new route for health check.

Related issue: expressjs/morgan#119

**Comment by DerMolly** [comment]
As an fixing PR was already merged, I think this issue can be closed…
