### ISSUE TITLE
Implement fine-grained routes for changing permissions

### ISSUE THREAD

**Issue by ErikMichelson** [hedgedoc/hedgedoc#1950]
### Is your feature request related to a problem? Please describe.

Currently, there is a permission service implemented, that is capable of checking the permissions of a note (`mayRead`, `mayWrite`) but not of changing permissions.

### Describe the solution you'd like

Following API endpoints:
- `GET /notes/:noteId/permissions` -> optional, equal to the permissions metadata field that is already returned when fetching the complete note
- `PUT /notes/:noteId/permissions/users/:username` -> set permission for this user. Body contains a boolean whether the user should have write access.
- `DELETE /notes/:noteId/permissions/users/:username` -> remove permissions for the given user and note
- `PUT /notes/:noteId/permissions/groups/:groupName` -> set permissions for the given group. Similar to the user method above.
- `DELETE /notes/:noteId/permissions/groups/:groupName` -> remove permissions for the given group and user
- `PUT /notes/:noteId/permissions/owner` -> body contains a username field of the new owner. Can only be issues by previous note owner.

### Describe alternatives you've considered

Simply one endpoint:
- `PUT /notes/:noteId/permissions` 

This would however be more work that needs to be done client-side.

**Comment by InnayTool** [comment]
We have decided that permission changes in the front end should be transmitted by the real time API on web sockets.
Independently for the public API the described routes should be implemented to make it easier to update note permission with an external tool.
