### ISSUE TITLE
Delivery of frontend and backend

### ISSUE THREAD

**Issue by ErikMichelson** [hedgedoc/hedgedoc#1965]
HedgeDoc 2 consists of two server processes:
1. The backend NestJS server
2. The frontend Next.js server

There are multiple ways how the frontend and backend could be deployed and how requests are made. This issue lists the possibilities and serves to discuss these.

## Option 1: Next.js "middleware" for NestJS
With this option, the frontend would not run as a single process but rather be integrated into the NestJS backend using a custom middleware. This requires some implementation effort as Next.js provides an API for integration with e.g. express but not a directly usable middleware. While this solves the problem that it only uses one process and only exposed one port, it creates a bunch of new issues:
1. By using the custom server instead of the integrated Next.js server, the caching and server-side optimizations won't be performed.
2. The custom server uses the source files instead of prebuilt ones and therefore also needs the dev-dependencies and types.
3. Every HTTP request uses the same single-threaded node process.

## Option 2: Proxy
With this option either the backend would proxy all requests not going for `/api/*` to the frontend server or vice-versa. This means that both server processes need to run in parallel while only one of them requires the port to be publicly exposed. This solves the problems that the integrated Next.js server features still can be benefitted from and that dev-dependencies are not needed at runtime.
However, still this creates some extra load by running every request over in node process in addition to also proxying some of them. 

## Option 3: Separate deployments
With this option, both NestJS server and Next.js server would run as separate processes each one with an own exposed port.
A load balancer or reverse-proxy needs to run in front of the deployments. While this solves the problems mentioned above, it requires more configuration for users that install HedgeDoc the manual way (instead of using a docker-compose file).

## Proposal by the dev-team
We thought to combine option 2 and 3. For development purposes and local testing, using an integrated proxy seems useful. As way more requests go to the frontend than to the backend, it makes sense to proxy the API requests to the backend through the frontend server. For production deployments we would recommend the usage of a load balancer/reverse proxy like nginx in front of both HedgeDoc processes that routes everything under `/api/*` to the backend process and the rest to the frontend. By for example adding an already preconfigured nginx container to the docker-compose file, this does not require more effort to deploy. And Kubernetes deployments could simply use the cluster ingress controller to route the requests to the backend or frontend deployments/services.

The different modes of operation of our proposal can be visualized like this:

![Hedgedoc-deployments](https://user-images.githubusercontent.com/52606896/148704095-82f850e9-7785-477f-9219-4d7548fd5dbd.png)

**Comment by mrdrogdrog** [comment]
After months of testing we're stuck with Option 3 right now. Option 1 disabled a lot of useful next.js features that we need. Option 2 has always messed up something like websocket connections.
The only option that turned out to be reliable so far is Option 3. It is the [current way to go to use backend and frontend together in a dev environment](https://github.com/hedgedoc/hedgedoc/issues/1669#issuecomment-1257205697) and also the way we combine frontend and backend on the alpha deployment.

**Comment by almereyda** [comment]
Thank you for the update! Caddy is a welcome choice for a local environment, and its manifest will make a good model to port to other proxies (Traefik, Nginx, HAProxy, ...) in other environments, like a foreseeable production.

**Comment by DerMolly** [comment]
This seems to be finished.
