### ISSUE TITLE
Can't scroll code block when followed by a heading in Firefox

### ISSUE THREAD

**Issue by thomaswucher** [hedgedoc/hedgedoc#1968]
### Description

A markdown code block with horizontal scrolling due to a very long line can't be scrolled if followed by a heading

### Steps to reproduce

In Firefox, create a document with the following content:

> # A Heading 
> ```
> a veeeeeeeeeeeeeeeeeeeeeeeeeeeeeery veeeeeeeeeeeeeeeeeeeeeeeeeeeeeery veeeeeeeeeeeeeeeeeeeeeeeeeeeeeery veeeeeeeeeeeeeeeeeeeeeeeeeeeeeery veeeeeeeeeeeeeeeeeeeeeeeeeeeeeery veeeeeeeeeeeeeeeeeeeeeeeeeeeeeery veeeeeeeeeeeeeeeeeeeeeeeeeeeeeery long line in a code block with a horizontal scrollbar
> ```
> 
> # Another Heading
> 
> More content...

The code block can't be scrolled. When trying to do so the Heading is selected instead.

### Expected behaviour

The scrollbar shown for the code block should be usable, as is the case in Chrome Browsers.

### Your Setup

Hedgedoc is deployed via the Linuxserver Hedgedoc docker image: https://docs.linuxserver.io/images/docker-hedgedoc

### Additional context

The reason this problem occurs is the CSS rule for not hiding the title below the navbar when jumping to an anchor:

```
/* Prevent linked heading from being hidden underneath navbar.
 * Example: http://localhost:3000/features#Editor-Modes would open and
 * hide the headline "Editor Modes" underneath the navbar without this CSS rule.
 */
.markdown-body h1[id]:before,
.markdown-body h2[id]:before,
.markdown-body h3[id]:before,
.markdown-body h4[id]:before,
.markdown-body h5[id]:before,
.markdown-body h6[id]:before {
  display: block;
  content: " ";
  margin-top: -55px;
  height: 55px;
  visibility: hidden;
}
```

Disabling these rules through developer tools makes the scrollbars usable, but of course has the downside mentioned in the code comment.

**Comment by ErikMichelson** [comment]
Thanks for the issue report and the link to the relevant CSS snippet.

I can confirm this behaviour on my machine as well using your test note content: https://demo.hedgedoc.org/Pzkf89NoT8KNyRJTuPownQ

We'll have a look at this for the next 1.x bugfix release.

**Comment by ErikMichelson** [comment]
We currently don't see any possibility to fix this issue without doing a major rework of the layout CSS or breaking the anchor scroll positions. As this issue seems to be very dependent on the browser version, OS and maybe the display server, we decided to not fix it in HedgeDoc 1.
HedgeDoc 2 won't have this problem anymore.
