### ISSUE TITLE
Share document with other member but with password

### ISSUE THREAD

**Issue by HDInfautre** [hedgedoc/hedgedoc#1991]
### Is your feature request related to a problem? Please describe.

Hello
Currently I have opened a pad but it is accessible from a person who knows the url!

### Describe the solution you'd like

Is it possible to put a password to access the url?

### Describe alternatives you've considered

Share access to another person's email!

**Comment by davidmehren** [comment]
It is not possible to password-protect notes. The URL is randomly generated by default, so not guessable by random people.
If you need further access-protection, you can always restrict access to logged-in users.
