### ISSUE TITLE
Improving the process of "Science Report writing"

### ISSUE THREAD

**Issue by kolibril13** [hedgedoc/hedgedoc#203]
Hi,
I love to use CodiMD to make fist writing and formatting of reports because it is so fast.
The real-time compiling and the image adding via drag'n'drop is just amazing.

But the final editing of reports I still do in Latex, cause of bibtex, references, and more adjustment options (to make a report look more pretty.)
It would be nice to have smoother pipeline to get from the CodiMD document to a latex document.
Some ideas to do so:
* one could add on option to download a .tex document (e.g. with pandocs)
* Or if that is not possible : add an option to download .md + pictures, so that you have the pictures in the right order as they occur in the document. Then its easier to use pandocs locally.
* Maybe even an direct pipeline to overleaf. [Overleaf](https://www.overleaf.com) is an nice latex tool, and has already apis to github for latex and Dropbox, so making one to CodiMD to include some text parts should not be impossible. So maybe the overleaf people also like this idea.
I am curious about what you think!

**Comment by ErikMichelson** [comment]
LaTeX export sounds like a good feature request. For references there is already a great idea (#115). Maybe we should add support for exporting a note with all its resources as a ZIP-package? That would maybe solve the problems of CORS which are stated in #175.

**Comment by davidmehren** [comment]
I extracted the first two ideas into #1004 and #1005.
As for a direct integration with Overleaf: This might be possible using our API in combination with #1004, but I don't see such an integration as a HedgeDoc-feature, but as an external tool that glues together the APIs of both Overleaf and HedgeDoc.
