### ISSUE TITLE
The lower --- of YAML metadata in the editor is incorrectly colour highlighted (trivial)

### ISSUE THREAD

**Issue by ethereal-engineer** [hedgedoc/hedgedoc#2041]
### Description

Adding a YAML header section to a document shows the top --- in blue, and the bottom in orange

### Steps to reproduce

1. Create a document with at least a main heading
2. Add ---\ntags: sometag\n--- above it

### Expected behaviour

Expected lower --- to be the same as the top ---

### Your Setup

- Host OS:  Ubuntu 20.04
- HedgeDoc version: 1.9.2 docker image

**Comment by mrdrogdrog** [comment]
Hello,

We already know about this bug. Unfortunately there is nothing we can do about it because this is an upstream bug from the markdown code highlighting in Code Mirror 5 that doesn't support frontmatter.

(HedgeDoc 2 won't have this error anymore because it will use CodeMirror 6)

**Comment by ethereal-engineer** [comment]
Ah. Awesome. Always better to receive the report than not. Once a coder, always a coder.
