### ISSUE TITLE
PlantUML/Kroki.io Support

### ISSUE THREAD

**Issue by ethereal-engineer** [hedgedoc/hedgedoc#2042]
### Which part of the project should be enhanced?

Graphical rendering options

### Is your enhancement request related to a problem? Please describe.

No.

### Describe the solution you'd like

Check the features supported for WikiJS. They are extremely similar, but HedgeDoc is MUCH faster and more suited to quick, focused notes. Which, by the way, is FREAKING AWESOME - this is the best markdown renderer I've EVER used - and I have used A LOT over the last two decades or so. I am in LOVE!!!!

Ok. I'll stop raving for a minute.

I would love to see PlantUML/Kroki.io support, but also an option to specify the server to use for rendering. I already self-host a Kroki.io server, which renders ALLLLLL the things. I usually use NIolesk as an interface to kroki.io, but having HedgeDoc integration would make things even smoother.

### Describe alternatives you've considered

- Working in Niolesk and then using an embedded image area. 
- Learning the mermaid syntax better (plantuml suits my brain better)

**Comment by mrdrogdrog** [comment]
Hello again :upside_down_face: 

This feature won't be added to HedgeDoc 1 because we focus on the rewrite. HedgeDoc 1 is in maintainence only mode (see README).

PlantUML support (with custom server URLs) is already added to HedgeDoc 2 (https://github.com/hedgedoc/react-client/pull/327)

**Comment by ethereal-engineer** [comment]
Hello!!! Will this include kroki.io also? Because that is the meta-bomb! 💣

**Comment by mrdrogdrog** [comment]
Kroki hasn't been added or requested yet. If you want it then please create an issue in the [frontend repository](https://github.com/hedgedoc/react-client). We can't promise that it will make it into 2.0 but we'll add it to the backlog.
