### ISSUE TITLE
Scroll down sometimes jumps up

### ISSUE THREAD

**Issue by xeruf** [hedgedoc/hedgedoc#2045]
### Description

When I scroll in a document with a big diagram rendered from a code block, the preview reaches the bottom before the editor does, and if I scroll further down in the editor, the preview sometimes jumps up.

### Steps to reproduce

1. Include some text and a large diagram.
2. Scroll down in the editor pane in dual-pane mode.

### Expected behaviour

Scrolling synced or at least no jarring jumps

### Your Setup

- Host OS: Arch
- NodeJS version: 14.18.3
- HedgeDoc version: Release notes page not working in Docker container, but I am assuming 1.9.2 as I set it up only recently

**Comment by mrdrogdrog** [comment]
Hello @xeruf,

Bad news first: This is nothing we can fix easily. The HedgeDoc 1 code base is a mess and we don't touch it anymore unless for critical fixes. Therefore we won't fix the sync scrolling in HedgeDoc 1. (See [README](https://github.com/hedgedoc/hedgedoc#state-of-the-project))

Good news:
The sync scrolling was completly reworked in HedgeDoc 2. Even if HD2 isn't useable in production yet you can test the new editor on https://hedgedoc.dev/n/features.

**Comment by xeruf** [comment]
Yeah, I saw that too. Hacked myself PlantUML support into v1 but stuff is all over the place.
What does "not usable in production" mean? From looking at it it seems good enough for me to replace v1 on my instance which is, due to my modifications, a little wonky anyways.

**Comment by mrdrogdrog** [comment]
> What does "not usable in production" mean?

E.g. There is no data persistence yet.

**Comment by xeruf** [comment]
So when I leave an editing session all the content is gone? Or is that just about logins?

**Comment by ErikMichelson** [comment]
Yes, when reloading the page, all content is gone. Nothing is persisted. This demo is just to test out the user interface.

**Comment by xeruf** [comment]
Ah that's unfortunate, I am eager to switch to v2 :)

**Comment by DerMolly** [comment]
If I'm not mistaken this issue is not actionable and as such should be closed…
If you belive this is wrong feel free to reopen @xeruf
