### ISSUE TITLE
Possible Mermaid sequence diagram rendering/styling problem in Firefox

### ISSUE THREAD

**Issue by thanethomson** [hedgedoc/hedgedoc#2046]
### Description

It appears as though something's wrong with the styling of labels in Mermaid sequence diagrams rendered in Firefox.

### Steps to reproduce

See [this gist](https://gist.github.com/thanethomson/9884b90814408fad0bb9d9685297aa85) for a minimal reproduction of the issue, with screenshots in comments.

### Expected behaviour

For sequence diagrams to be rendered consistently across different browsers.

### Your Setup

- Host OS: Ubuntu 20.04
- NodeJS version: v16.13.2
- HedgeDoc version: 1.9.2

### Additional context

The fact that this renders correctly in Firefox in Mermaid's live editor, but incorrectly when embedded in a HedgeDoc page, suggests to me that something HedgeDoc-related is going wrong with the styling in Firefox.

**Comment by davidmehren** [comment]
This might be a duplicate of https://github.com/hedgedoc/hedgedoc/issues/1217

**Comment by thanethomson** [comment]
Ah you're right. I missed that while searching for sequence diagram-related issues. Thanks!
