### ISSUE TITLE
Docker-Setup broken because of issues with the Content Security Policy

### ISSUE THREAD

**Issue by boldt** [hedgedoc/hedgedoc#2098]
### Description

The MWE from the [docker](https://docs.hedgedoc.org/setup/docker/) installation does not work out of the box

### Steps to reproduce

1. Copy the `docker-compose.yml` from the [docker page](https://docs.hedgedoc.org/setup/docker/)
2. Run `docker-compose up -d`
3. Open http://127.0.0.1:3000/

You should see a broken UI and plenty of CPS errors in the console:

![Bildschirmfoto von 2022-02-12 14-48-53](https://user-images.githubusercontent.com/750793/153713984-3cce6990-1685-4754-a634-b73a3712aee3.png)

 

### Expected behaviour

A non-broken UI an no CSP errors

### Your Setup

- Host OS: Ubuntu 18.04.6 LTS
- Docker image: quay.io/hedgedoc/hedgedoc:1.9.2

**Comment by mrdrogdrog** [comment]
`127.0.0.1` isn't the same origin as `localhost`. You MUST use the set domain.

**Comment by DerMolly** [comment]
Thanks to @boldt for making us aware of this bug in the documentation

**Comment by boldt** [comment]
I don't get it.

I am confused, because the docker-compose contains `CMD_DOMAIN=localhost`, while you write in the following paragraph:

> HedgeDoc should be available at http://127.0.0.1:3000/.

Because of `CMD_DOMAIN=localhost`, I expect it to be available via localhost.

**Comment by boldt** [comment]
Okay, that was my mistake (I know CSP):

I was sure, I tried http://localhost:3000 as well, but it seems that I only tried 127.0.0.1.
Thus, I can confirm, that it works with http://127.0.0.1:3000

**Comment by ErikMichelson** [comment]
This documentation issue was fixed with #2103 and is already live on the docs page.
