### ISSUE TITLE
Ensure S3 media backend is compatible with OpenStack

### ISSUE THREAD

**Issue by Salokyn** [hedgedoc/hedgedoc#2104]
### Which part of the project should be enhanced?

Cloud storage

### Describe the solution you'd like

The same way HedgeDoc can store uploads on Azure or S3 cloud services, it'd be nice to support swiftv3.

### Describe alternatives you've considered

Using S3 API compatibility layer. But it doesn't work well for me.

I tried with:
```
docker run -d \
  --name=hedgedoc \
  -e CMD_DB_URL=mysql://hedgedoc:dbpassword@XXXXXX-001.eu.clouddb.ovh.net:12345/hedgedoc \
  -e CMD_DOMAIN=vpsXXXXXX.ovh.net \
  -e CMD_URL_ADDPORT=true \
  -e CMD_IMAGE_UPLOAD_TYPE=s3 \
  -e CMD_S3_ACCESS_KEY_ID=<key_id> \
  -e CMD_S3_SECRET_ACCESS_KEY=<access_key> \
  -e CMD_S3_BUCKET=hedgedoc \
  -e CMD_S3_ENDPOINT=s3.gra.cloud.ovh.net \
  -e CMD_S3_REGION=GRA \
  -p 3000:3000 \
  quay.io/hedgedoc/hedgedoc:alpine
```

Files are well uploaded in the bucket, but the URL do not permit to access the file (ex: https://s3.gra.cloud.ovh.net/hedgedoc/uploads/9b10b4760251ba25fe2af9401.jpg shoud be https://s3.gra.cloud.ovh.net/v1/AUTH_d3302accdd6541e99a2d87be50d64ad4/hedgedoc/uploads/9b10b4760251ba25fe2af9401.jpg)

**Comment by davidmehren** [comment]
Thank you for your suggestion!

We do not consider feature requests for HedgeDoc 1 anymore, as we are focusing on getting 2.0 ready.

In https://github.com/hedgedoc/hedgedoc/issues/529 we discussed which upload providers to support for 2.0, and only considered S3.
Of course, we should ensure that the new implementation of our S3 backend is compatible with the S3-compat-layer of OpenStack. Can you point us to relevant docs about how the resulting URL is constructed?
