### ISSUE TITLE
Modes no more visible to screenreaders

### ISSUE THREAD

**Issue by fcnjd** [hedgedoc/hedgedoc#2125]
### Description

I as a blind user would like to change the current HedgeDoc view, if it is edit, read, or both. This worked very fine in the past, but things don't seem to be labeled anymore.

### Steps to reproduce

1. Launch a screenreader and open a webbrowser
2. Go to a HedgeDoc note of your choice
3. You'll find the radio buttons unlabeled

### Expected behaviour

As this was the case previously, I'd expect those three radio buttons to have a descriptive label what their corresponding mode is, things were very fine when it still worked.

### Your Setup

Client: Windows 10, tested with both Chromium browser and Firefox

**Comment by davidmehren** [comment]
Thanks for your report!

Do you have any idea, on what version of HedgeDoc the labels were working correctly? I don't think we changed anything regarding these buttons in the last releases.

I had a look at the buttons on demo.hedgedoc.org, the HTML looks like this:
```
<div class="btn-group" data-toggle="buttons">
  <label class="btn btn-default ui-view active" title="View (Ctrl+Alt+V)">
    <input type="radio" name="mode" autocomplete="off"><i class="fa fa-eye"></i>
  </label>
  <label class="btn btn-default ui-both" title="Both (Ctrl+Alt+B)">
    <input type="radio" name="mode" autocomplete="off"><i class="fa fa-columns"></i>
  </label>
  <label class="btn btn-default ui-edit" title="Edit (Ctrl+Alt+E)">
    <input type="radio" name="mode" autocomplete="off"><i class="fa fa-pencil"></i>
  </label>
</div>
```
All buttons have a `title` property, but I'm not sure if that is enough for screen readers. Maybe @mrdrogdrog has more insight?

**Comment by mrdrogdrog** [comment]
The labels should be enough. Iirc we haven't changed anything in this part.

**Comment by ErikMichelson** [comment]
This should have been improved with #2243.

If this didn't help, please re-open this issue.

**Comment by fcnjd** [comment]
Sorry that I didn't reply more quickly, but had a lot of exams recently.
Thank you for bringing this fix. I've also tested a bit further: I have to excuse, I blamed you for having changed something, but insted I changed things because I switched from Chromium to Firefox. Yes I wrote in the comments that I tested with both, because Chromium sometimes also is problematic. But when using the mentioned HTML code things get clear: Using Chromium the labels are announced clearly, using Firefox this is not the case. So it was probably a bad idea of mine switching browsers.
Is your change already testable on demo.hedgedoc.org? I tried it out just now, and still it doesn't work. So should I reopen the issue, or wait till an update to the demo instance is pushed?

**Comment by mrdrogdrog** [comment]
@fcnjd No, the current state isn't deployed to the demo instance. 
You can checkout the current master branch state on your local machine and run it in dev mode or install it using [the manual install instructions for production environments](https://docs.hedgedoc.org/setup/manual-setup/).
