### ISSUE TITLE
Document type and recommended length of sessionSecret config variable

### ISSUE THREAD

**Issue by nidico** [hedgedoc/hedgedoc#2205]
### Which part of the project should be enhanced?

Documentation

### Is your enhancement request related to a problem? Please describe.

The docs currently only state that `sessionSecret` (respective `CMD_SESSION_SECRET`) shall be changed in order to not have users logged out. It is not clear what type and how long the secret string shall be.

Concerning type: It looks like an arbitrary string can be used as `secret` is used as an example (though with a special meaning). However looking at `lib/config/index.js`, the automatically generated `sessionSecret` config variable seems to be a hex string.

Concerning length: I guess it should be long in order to be secure. The automatically generated `sessionSecret` is of length `sessionSecretLen`, which defaults to 128 (hex characters). What's recommended? What's the maximum length?

### Describe the solution you'd like

Mention something like the following in the description of the respective config setting:

Set this field to a long (e.g. 100 characters) string.

### Describe alternatives you've considered

None.

### Additional context

Looking at the [library documentation](https://github.com/expressjs/cookie-parser#cookieparsersignedcookiestr-secret) which makes use of the session secret doesn't reveal much information:

> The secret argument can be an array or string. If a string is provided, this is used as the secret. If an array is provided, an attempt will be made to unsign the cookie with each secret in order.

**Comment by ErikMichelson** [comment]
Fixed in #2240
