### ISSUE TITLE
Gitlab snippet export doesn't work

### ISSUE THREAD

**Issue by ghost** [hedgedoc/hedgedoc#2208]
### Description

Gitlab snippet export doesn't work with the current API ->  "files, content are missing, exactly one parameter must be provided"

### Steps to reproduce

1. Install Gitlab Version 14.9.1 CE
2. Connect the hedgedoc application
3. Test Gitlab snippet export

### Expected behaviour

The snippet is transferred.

### Logs

```shell
400
Bad Request
{"error":"files, content are missing, exactly one parameter must be provided"}
```

### Your Setup

- Gitlab Version 14.9.1 CE
- linuxserver/hedgedoc Version 1.9.2

### Additional context

I think in the current API you have to specify **files** in the req-body, **file_name** is not sufficient.
https://docs.gitlab.com/ee/api/snippets.html
An alternative or additional feature would be to push the file directly into a repository 
(however, a branch and commit message is required here). https://docs.gitlab.com/ee/api/repository_files.html

**Comment by ErikMichelson** [comment]
This has been fixed in #2244 and was released with HedgeDoc 1.9.3.
