### ISSUE TITLE
I can't edit a pad because I can't get "Online"

### ISSUE THREAD

**Issue by oupala** [hedgedoc/hedgedoc#2221]
### Description

can't get connected (identified) to a pad

### Steps to reproduce

1. go to a pad
2. eventually "copy-paste" a large portion of text (not sure if this has an impact)
3. leave the pad and go back to it
4. see that the status on the upright corner of the page stays to `Connected` and never go to `Online`
5. see that you can't edit the pad as you are not really `Online`

### Expected behaviour

Being `Online` and able to edit the content.

### Logs

```shell
On the server side, I get a constant list of the following lines:

> 2022-03-25T16:28:34.887Z info: 	deserializeUser: 014c2d20-2932-4341-ac40-b36f662e56f0

And on the browser side, I get a constant list of the following errors on the browser console:

> Uncaught Error: Unknown linkifyHeaderStyle value "lowercase"
```

### Config

```shell
- OAuth2 authentication
```

### Your Setup

- Standard Docker image deployment on kubernetes (OpenShift).
- version 1.9.2

### Additional context

The problem happens on some pads only. Some other pads don't have the problem, on the same server.

**Comment by DerMolly** [comment]
Hello @oupala,

which docker image are you using?

**Comment by oupala** [comment]
The *official* one from [quay.io](https://quay.io/repository/hedgedoc/hedgedoc).

**Comment by oupala** [comment]
The problem was due to an invalid value in the configuration file:

```json
"linkifyHeaderStyle": "lowercase",
```

that should be fixed as:

```json
"linkifyHeaderStyle": "lower-case",
```

And then everything is ok.
