### ISSUE TITLE
How about add a image viewer ?

### ISSUE THREAD

**Issue by yurenchen000** [hedgedoc/hedgedoc#2230]
### Is your feature request related to a problem? Please describe.

not really a problem,
just view large / many image have a better experience.

### Describe the solution you'd like

embed some third-part image viewer .js
to enchance image view:
　zoom, slideshow, rotate..

### Describe alternatives you've considered

I make a demo, which use this component 
https://fengyuanchen.github.io/viewerjs/
　// screenshot at end of the post

pc & mobile seems works，
　but mobile button small.

I handled published & edit preview page，
　but live preview not imlement very well.

### Additional context

If you wish,
 I'd like to post my demo code or site here.

<br>

pc screenshot:
![codimd_img_viewer_pc.png](https://user-images.githubusercontent.com/8458213/161207855-94b5d5ad-554c-479d-85cd-71d0c1a65b04.png)

<br>

mobile screenshot:
![codimd_img_viewer_mobile.png](https://user-images.githubusercontent.com/8458213/161205244-cda29c59-f0dc-4413-be6d-777ade81035b.jpg)

<br>

hedgedoc is awesome !

**Comment by mrdrogdrog** [comment]
Hello @yurenchen000 ,

An image viewer is already planned (and included) in HedgeDoc 2. You can test it out on https://hedgedoc.dev/n/features .
We won't add it to the HedgeDoc 1 code base because it is [in maintenance only mode](https://github.com/hedgedoc/hedgedoc#state-of-the-project)

**Comment by ErikMichelson** [comment]
As this is already included in the current development state of HedgeDoc 2, I'm going to close this issue.
If you want to request more image viewer features (like those from viewer.js), please [open an issue in the frontend issue tracker](https://github.com/hedgedoc/react-client/issues/new/choose).

**Comment by yurenchen000** [comment]
If anyone needs it, here is the patch:

https://github.com/yurenchen000/hedgedoc/issues/1
