### ISSUE TITLE
is it possible to show editor/user in revision history ？

### ISSUE THREAD

**Issue by yurenchen000** [hedgedoc/hedgedoc#2231]
### Which part of the project should be enhanced?

revision history

### Is your enhancement request related to a problem? Please describe.

..

### Describe the solution you'd like

show who made the differ in revision history

### Describe alternatives you've considered

..

**Comment by mrdrogdrog** [comment]
Hello,

No, in HedgeDoc 1 this is not possible. But're reworking the revisions dialog in HedgeDoc 2 and can keep that in mind, if you open a feature request issue in https://github.com/hedgedoc/react-client/issues
