### ISSUE TITLE
Do not store object backend url in notes.

### ISSUE THREAD

**Issue by pierreozoux** [hedgedoc/hedgedoc#2245]
### Which part of the project should be enhanced?

Object Store / S3

### Is your enhancement request related to a problem? Please describe.

I just switched from ceph to minio, and the url is changing.
Then I had to update the database with the following query:

```
# List notes to see one in live
select shortid,REGEXP_MATCHES(content, 'https://old_s3_url/', 'g') from "Notes";


UPDATE "Notes" SET content = regexp_replace(content, ']\(https://old_s3_url/', '](new_s3_url/', 'g');
```

### Describe the solution you'd like

It would be nice if the media would be served by an api endpoint.
(So then, I can change s3 url, and I take care myself that the bucket is with the good content, and the media is served, without going to the db to make updates.)
(Maybe it is already implemented in v2? I'm still running v1.)

### Describe alternatives you've considered

Or, the url is rendered at "serve" time?

**Comment by davidmehren** [comment]
Thanks for your suggestion!
I have created https://github.com/hedgedoc/hedgedoc/issues/2310 to track a concrete proposal to implement this.
