### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by Levinch** [hedgedoc/hedgedoc#2247]
### Which part of the project should be enhanced?

Translation

### Is your enhancement request related to a problem? Please describe.

Some strings are not present in translation file and are hard writed in source code. 

in menu

<img width="452" alt="Capture d’écran 2022-04-08 à 10 33 28" src="https://user-images.githubusercontent.com/3962745/162401704-2e11a2e2-3eed-400f-bf5d-1ba8ac0e36db.png">

in TOC

<img width="109" alt="Capture d’écran 2022-04-08 à 10 33 33" src="https://user-images.githubusercontent.com/3962745/162401745-ababbb47-41e1-4d6a-b11c-67debdeb82b0.png">

and maybe elsewhere.

### Describe the solution you'd like

For example change this string

<img width="906" alt="Capture d’écran 2022-04-08 à 10 52 05" src="https://user-images.githubusercontent.com/3962745/162401796-4b5645bc-ea0b-478c-b2ac-f53d329b7bd9.png">

by

`<%= __('Delete this note') %>` 

### Describe alternatives you've considered

Don't know.

**Comment by DerMolly** [comment]
Hey @Levinch,

we are aware of such things and fixed them already for the 2.0 release, but I think we won't we work these parts of the 1.x Codebase.
