### ISSUE TITLE
Vim bindings: `G` doesn't scroll enough

### ISSUE THREAD

**Issue by tobast** [hedgedoc/hedgedoc#2265]
### Description

In Vim edition mode, when going to the bottom of the text (`G` key), the text is not scolled enough and the last line is not properly displayed

### Steps to reproduce

1. In a document, write more than a screen's height so that there is a substantial scrollbar.
2. Switch to Vim key bindings
3. Scroll up in the document
4. In normal mode, press `G`, which brings you to the last line of text
5. Notice that the last line is just above, or even sometimes half hidden by the toolbox buttons, and that the scrollbar is not fully scrolled — the padding at the bottom of the text is not scrolled.

### Expected behaviour

Upon pressing the `G` key, the edition viewport is scrolled to the maximum, with the padding below the text shown.

### Your Setup

- Host OS: Debian Bullseye
- NodeJS version: 12.22.5
- HedgeDoc version: 1.9.2

**Comment by davidmehren** [comment]
Unfortunately, there are a few unresolved issues with the overlay-behaviour of the status line in 1.x, see https://github.com/hedgedoc/hedgedoc/issues/862 for more details.
We concluded to not fix this issue in HedgeDoc 1 and to focus on development HD 2 instead.
