### ISSUE TITLE
Heroku - Content Security Policy problem

### ISSUE THREAD

**Issue by adams-family** [hedgedoc/hedgedoc#2293]
### Description

Deployed HedgeDoc to Heroku using the "Deploy on Heroku button" but CSS resources don't load because of Content Security Policy issue

### Steps to reproduce

1. Log in to Heroku
2. Visit this page: https://docs.hedgedoc.org/setup/heroku/
3. Click "Deploy on Heroku" button
4. Leave everything by default and deploy

<img width="1486" alt="image" src="https://user-images.githubusercontent.com/19559733/165493720-aaab6e01-f210-4073-87fa-bd11972f82e8.png">

Editing Config Vars and changing 'localhost' to the actual deployment domain does not seem to make any difference:

<img width="1471" alt="image" src="https://user-images.githubusercontent.com/19559733/165493963-54231726-2441-4f8c-8efa-f79b119be314.png">

### Expected behaviour

HedgeDoc should load correctly including CSS styles.

### Your Setup

Deployed the current version from GitHub on Heroku using the 'Deploy on Heroku' button.

**Comment by ErikMichelson** [comment]
You seem to set `CMD_ALLOW_ORIGIN`, however have you set `CMD_DOMAIN`?
Nevertheless, either the docs or the Heroku default config should be updated.

**Comment by adams-family** [comment]
@ErikMichelson Thanks, you are right, this helped:

<img width="1241" alt="image" src="https://user-images.githubusercontent.com/19559733/166093057-f9abd6ed-932b-4967-b188-504b33ae799f.png">

<img width="1487" alt="image" src="https://user-images.githubusercontent.com/19559733/166093042-d6f9abf7-9b0a-4b4a-af92-486a117d6bd8.png">

I think if this was added to the [Heroku configuration docs](https://docs.hedgedoc.org/setup/heroku/) it would be great.

Thanks for your help, I'm closing this issue.

**Comment by DerMolly** [comment]
I'd think we want to track that we fix the docs or the default heroku config, so I'll reopen this issue.

**Comment by ErikMichelson** [comment]
The environment variable `CMD_DOMAIN` has been made required for the Heroku setup with #2335.
