### ISSUE TITLE
CSP allows wildcard for object-src and frame-src even when configured not to

### ISSUE THREAD

**Issue by kheops2713** [hedgedoc/hedgedoc#2294]
### Description

Even though `csp.addDefaults` is set to `false` and `csp.directives` includes `["'none'"]` for `objectSrc` and `frameSrc`, the actual HTTP CSP header allows `*` for both.

### Steps to reproduce

1. configure `config.json`'s `csp` object like this:

```
       "csp": {
            "enable": true,
            "directives": {
                    "defaultSrc": ["'self'"],
                    "scriptSrc": ["'self'", "'unsafe-inline'"],
                    "styleSrc": ["'self'", "'unsafe-inline'"],
                    "objectSrc": ["'none'"],
                    "frameSrc": ["'none'"]
            },
            "upgradeInsecureRequests": "auto",
            "addDefaults": false,
            "addDisqus": false,
            "addGoogleAnalytics": false
        },
```

2. restart HedgeDoc
3. Make an HTTP request to HedgeDoc, the `Content-Security-Policy` header looks like this:

```
Content-Security-Policy: default-src 'self';script-src 'self' 'unsafe-inline' 'nonce-e397d048-cef5-4e98-8881-74355598ca1a' 'sha256-81acLZNZISnyGYZrSuoYhpzwDTTxi7vC1YM4uNxqWaM=';style-src 'self' 'unsafe-inline';object-src 'none' *;frame-src 'none' *
```

Even though it is explicitely configured otherwise, both `object-src` and `frame-src` have the `*` source appended, which effectively defeats the configuration.

### Expected behaviour

`*` should not be appended to `object-src` and `frame-src` .

In the example's context, the CSP header should be:

```
Content-Security-Policy: default-src 'self';script-src 'self' 'unsafe-inline' 'nonce-e397d048-cef5-4e98-8881-74355598ca1a' 'sha256-81acLZNZISnyGYZrSuoYhpzwDTTxi7vC1YM4uNxqWaM=';style-src 'self' 'unsafe-inline';object-src 'none';frame-src 'none'
```

### Config

```shell
See the reproduce steps.
```

### Your Setup

- Host OS: ArchLinux
- NodeJS version: 17.9.0
- HedgeDoc version: 1.9.3

**Comment by ErikMichelson** [comment]
Thanks for your report. We'll investigate this.

**Comment by davidmehren** [comment]
Can repro on `master`.

**Comment by davidmehren** [comment]
The wildcard comes from the directives that allow to embed PDFs (https://github.com/hedgedoc/hedgedoc/blob/master/lib/csp.js#L48). Add `"allowPDFEmbed": false` to your csp config to disable that.

I'd conclude that this works as intended, wdyt @ErikMichelson?

**Comment by ErikMichelson** [comment]
We concluded this to be working as expected. A further discussion was whether we want to introduce a config option like `onlyUseCustomDirectives` but decided against it as our primary focus is HedgeDoc 2.
