### ISSUE TITLE
CSP errors after enabling HTTPS

### ISSUE THREAD

**Issue by 9j7axvsLuF** [hedgedoc/hedgedoc#2314]
### Description

Hedgedoc not allowing sign in after enabling https

### Steps to reproduce

1. Deploy HedgeDoc with [Caprover](https://caprover.com/) as a one-click app (Docker compose)
2. Enable https
3. Try to log in or register
4. No response, inspecting the page throws an error (see log)

### Expected behaviour

I should be able to register a new user and log in with my existing credentials. It worked before enabling https.

### Logs

```shell
> Refused to set the document's base URI to '[mydomain]' because it violates the following Content Security Policy directive: "base-uri 'self'".
> Refused to load manifest from '[mydomain]/icons/site.webmanifest' because it violates the following Content Security Policy directive: "manifest-src 'self'".
> Refused to send form data to '[mydomain]/login' because it violates the following Content Security Policy directive: "form-action 'self'".
```

### Your Setup

- Host OS: Ubuntu 18.04
- NodeJS version: 8.10.0
- HedgeDoc version: 1.9.3

**Comment by ErikMichelson** [comment]
> It worked before enabling https.

Please ensure that the environment variables `CMD_DOMAIN`, `CMD_PROTOCOL_USESSL` are correctly set.
See [the docs](https://docs.hedgedoc.org/configuration/#hedgedoc-location) for more details.
