### ISSUE TITLE
What should we do with history.md?

### ISSUE THREAD

**Issue by DerMolly** [hedgedoc/hedgedoc#2338]
Currently there is a [history.md](https://github.com/hedgedoc/hedgedoc/blob/master/docs/content/history.md) file in the docs folder on master, which is served under https://docs.hedgedoc.org/history/, but as mkdocs informs us so eloquantly
![2022-05-08_23-37](https://user-images.githubusercontent.com/3978662/167316951-fc1f8629-40d0-4ffd-aa30-98eb761aa54d.jpeg)

It was somewhat replaced by the [history page on the website](https://hedgedoc.org/history/), but as much as I like this page it's fair to say that it's a rather barebones approach to a history of the software.

The questions is what should we do with this file?

I personally see two possibilites:

1. Delete it and forget it ever existed.
2. Move it to the website repo and link it on the history page as a form of long version.

Before anyone suggests keeping it in the docs I want to clarify that I think that this page should be removed from the docs as it no longer is necessary to mix documentation and general information. We now have a website for such things.

What do you think?

**Comment by ErikMichelson** [comment]
My opinion is to follow approach 2 and to move this page to the website (like hedgedoc.org/history/details or something) and then link it from the "diagrammy" history page.

**Comment by davidmehren** [comment]
The history is now included in our website.
