### ISSUE TITLE
Annotations

### ISSUE THREAD

**Issue by KajeArch** [hedgedoc/hedgedoc#2341]
### Is your feature request related to a problem? Please describe.

I really love HedgeDoc and the one feature that prevents me from completely switching away from Google Docs is just the ability for people to leave comments on specific lines of the document. 

### Describe the solution you'd like

So, I thought of if one could implement an inline real-time annotation and conversation layer,

### Describe alternatives you've considered

Or possibly use available third-party libs, such like http://annotatorjs.org/ and build from that.

**Comment by davidmehren** [comment]
I think the other issue covers this use case.
