### ISSUE TITLE
[1.0] `breaks` option is not respected in read-only view

### ISSUE THREAD

**Issue by ErikMichelson** [hedgedoc/hedgedoc#2358]
### Description

The read-only view ("publish", /s/...) does not render notes properly with `breaks: false` set in frontmatter.

### Steps to reproduce

1. Create a new note and set `breaks: false` in the frontmatter
2. See the editor's renderer displaying the note correctly
3. Open the read-only view by clicking the "publish" button
4. See the read-only-view not respecting the breaks false option

### Expected behaviour

The read-only-view should render the note in the same way as the editor's renderer.

### Your Setup

Demo instance at demo.hedgedoc.org

### Additional context

MWE in [editor](https://demo.hedgedoc.org/uJfPRJUkQAqeNw__-CSr1A?view) and [read-only view](https://demo.hedgedoc.org/s/MmvPhDCZv)

**Comment by ErikMichelson** [comment]
Relevant code points:
 - https://github.com/hedgedoc/hedgedoc/blob/master/public/js/extra.js#L222-L227
 - https://github.com/hedgedoc/hedgedoc/blob/master/public/js/pretty.js#L32 is called without `parseMeta` call before

**Comment by DerMolly** [comment]
As this was already fixed with https://github.com/hedgedoc/hedgedoc/pull/2726
