### ISSUE TITLE
api endpoint for changing permission level of note

### ISSUE THREAD

**Issue by kindlychung** [hedgedoc/hedgedoc#2359]
### Which part of the project should be enhanced?

note api

### Is your enhancement request related to a problem? Please describe.

Right now it's done via websocket, which is not scripting-friendly like a rest-api endpoint. 

### Describe the solution you'd like

Something like `POST /<NOTE>/permission?level=private` would be nice

### Describe alternatives you've considered

None atm.

**Comment by mrdrogdrog** [comment]
Hello, thank you for your issue.

This feature is already planned and implemented for HedgeDoc 2 (https://github.com/hedgedoc/hedgedoc/pull/2038). Because HedgeDoc 1 is in maintenance only mode we won't back port it.
