### ISSUE TITLE
Add HedgeDoc to Matt Cone's markdownguide.org

### ISSUE THREAD

**Issue by salim-b** [hedgedoc/hedgedoc#237]
I think it would greatly help to attract people (incl. possible contributors) to CodiMD by having it mentioned on <https://www.markdownguide.org/tools/>, an open-sourced site by Matt Cone (content is licensed under CC-BY-SA).

The site is built using [Jekyll](https://jekyllrb.com/) and its sources are found [here](https://github.com/mattcone/markdown-guide). The README says:

> Contributions are welcome. Feel free to open a pull request with changes.

One simply needs to create a Markdown file `codimd.md` under [`_tools/`](https://github.com/mattcone/markdown-guide/tree/master/_tools) which should adhere to a specific structure (at least I guess so; see e.g. [`hugo.md`](https://github.com/mattcone/markdown-guide/blob/master/_tools/hugo.md) for an example) and add the CodiMD icon to [`assets/images/tool-icons/`](https://github.com/mattcone/markdown-guide/tree/master/assets/images/tool-icons) (does CodiMD have an icon yet?).

**Comment by mattcone** [comment]
This was completed in https://github.com/mattcone/markdown-guide/pull/28 thanks to @jackycute!

**Comment by ErikMichelson** [comment]
Well, that was half of the whole thing. @jackycute added the "hackmd.io-Version" of CodiMD. This is the repo for the "community version". We know that the current situation is bad for everyone, maybe both repos can be linked?

**Comment by davidmehren** [comment]
Let's try to get our version into the guide after releasing 2.0 (hopefully with a new name).

**Comment by T2brozz** [comment]
This is completed since November of last year https://www.markdownguide.org/tools/hedgedoc/. I think it can be closed ^^
