### ISSUE TITLE
Upload file to s3: make public a file on upload and allow to configure destintation folder

### ISSUE THREAD

**Issue by lautaroalvarez** [hedgedoc/hedgedoc#2384]
### Which part of the project should be enhanced?

s3 helper used in POST /uploadimage route

### Is your enhancement request related to a problem? Please describe.

Im trying to configure s3 storage using digitalocean spaces. In digitalocean spaces you cant make a space public, you just can make a file public. So when I configure the s3 digitalocean space in Hedgedoc I can upload the file but I cant see on the document (because the uploaded file is private)

### Describe the solution you'd like

I want to add a configuration field where we can indicate that we want to make public a file. If its true, when Hedgedoc upload the file to the s3 storage it will set as public.

### Describe alternatives you've considered

Add a new configuration field `s3publicFile` (boolean).

In `lib/web/imageRouter/s3.js` verify this configuration. If its true set `ACL: 'public-read'` in the parameters sent to `s3.putObject`.

I want to add another configuration field `s3folder` (string) to change the folder inside the s3 bucket where I want to save the files. The default value should be "uploads" to make it retrocompatible.

**Comment by lautaroalvarez** [comment]
I have forgotten to mention that I was thinking on version 1.x but then we can do it in version 2.x

**Comment by InnayTool** [comment]
PR was merged.
