### ISSUE TITLE
Hedgedo App doesn't deployed properly through Helm and Docker-compose 

### ISSUE THREAD

**Issue by oshi36** [hedgedoc/hedgedoc#2420]
### Description

On deploying Hedgedoc with docker-compose or setting it up through Helm , The app doesn't comes up properly as only HTML structure shows with missing images and other things.

### Steps to reproduce

On deploying Hedgedoc with [docker-compose](https://docs.hedgedoc.org/setup/docker/) or setting it up through [Helm](https://artifacthub.io/packages/helm/nicholaswilde/hedgedoc), The app doesn't come up properly as only HTML structure shows with missing images and other things.

Getting App as 
![image](https://user-images.githubusercontent.com/47573417/172902767-c08927bd-10e8-4bf1-b82c-0b07827f6a3b.png)

### Expected behaviour

It should be like the [demo](https://demo.hedgedoc.org/)

### Your Setup

Ubuntu: 20.04
K8s - 1.23

**Comment by mrdrogdrog** [comment]
It seems like you haven't configured hedgedoc correctly. 
Please check out this FAQ entry: https://docs.hedgedoc.org/faq/#why-does-my-interface-look-weird

**Comment by oshi36** [comment]
Thank you @mrdrogdrog
