### ISSUE TITLE
View every note created by your user, including ones "removed from history"

### ISSUE THREAD

**Issue by DistroByte** [hedgedoc/hedgedoc#2464]
### Is your feature request related to a problem? Please describe.

From time to time, it is desirable to access notes that have been removed from the "history" page. I believe that a note removed in such a way does not delete the document from the database, merely hides it from the easy access of the history page. This means that it can be restored with relative ease.

### Describe the solution you'd like

Some dashboard or user page that allows restoration of removed notes, maybe through the user dropdown menu as seen in Hedgedoc v1?

### Describe alternatives you've considered

Besides digging through your browser history for every note's URL, or using the cli tool, there is no easy way for a regular user to restore a note once removed.

### Additional context

I believe that hiding a note has its purposes, but deleting a note is definitely a more common request. Perhaps replacing the hide feature with a delete feature might be better, or maybe creating a dropdown box on each note to either hide or delete it is the solution.

**Comment by mrdrogdrog** [comment]
Hello,

This is already planned for HedgeDoc 2. See https://github.com/hedgedoc/hedgedoc/issues/994 .

**Comment by DistroByte** [comment]
Aha, perfect. Yes, I was suggesting it for v2, I knew v1 was only getting updates for major security issues. Thanks for linking! I'll close this now
