### ISSUE TITLE
Revision panel unresponsive

### ISSUE THREAD

**Issue by StefanBrand** [hedgedoc/hedgedoc#2483]
### Description

The revisions in the revision UI often don't appear at all or otherwise take very long to appear

### Steps to reproduce

1. Go to Menu > Revision
2. Click on a revision
3. Request is being made (see Network tab in Browser console)
4. Some request respond after several seconds, but most don't respond at all

![image](https://user-images.githubusercontent.com/8948865/177795659-96413d3e-bc0c-42d1-9359-8f2fb3615244.png)

### Expected behaviour

Immediately respond as the content is only 5KB

### Your Setup

https://demo.hedgedoc.org

**Comment by davidmehren** [comment]
This is not a bug, but possibly a performance issue with the database of the demo instance (CC @SISheogorath).

Note that we do not give any performance or availability guarantees for the demo instance: https://hedgedoc.org/demo/

**Comment by StefanBrand** [comment]
So revisions should appear immediately on a self-hosted instance?

**Comment by ErikMichelson** [comment]
I just tested this on two self-hosted instances and can't reproduce the problem. So yes, they should appear near to immediately.
