### ISSUE TITLE
Code in documents of type slide should not get centered

### ISSUE THREAD

**Issue by jmkeil** [hedgedoc/hedgedoc#2502]
### Description

Code in a document with type `slide` is centered in the regular view (not the slide mode), but should be left alignd.

### Steps to reproduce

1. Open the [Slide example](https://demo.hedgedoc.org/slide-example)
2. Go to the slide "Pretty Code"

### Expected behaviour

The code should be left aligned.

### Your Setup

- HedgeDoc version:  1.9.4 2022-07-10
- Tested Browsers: Firefox 102.0.1 (64-bit), Chromium 103.0.5060.53 (64-bit)

**Comment by InnayTool** [comment]
Hi,
yes this is suboptimal but we won't fix this in 1.X. The slides preview has many problems. This will be fixed in 2.0.
