### ISSUE TITLE
Night Theme in mobile view

### ISSUE THREAD

**Issue by carsten-re** [hedgedoc/hedgedoc#2534]
### Which part of the project should be enhanced?

Night Theme on mobile devices is missing

### Describe the solution you'd like

I'd like to use the Night Theme when I'm viewing my HedgeDoc pages on mobile devices.
The "Moon" icon is not available on mobile devices.

### Describe alternatives you've considered

Night Theme is actually only available on desktop devices.

**Comment by pawong** [comment]
I would say this should be classified as a bug. The top image is on my iPad in portrait mode, the bottom image is in landscape mode. On my iPhone, even in landscape mode, the Night Theme button does not show. While I understand not allowing the split screen edit mode for smaller devices, the theme button should always show. 

![hedgedoc](https://user-images.githubusercontent.com/2698757/181386760-b5a0c5cc-c965-4aa6-9ea4-fa098a21f32f.png)

**Comment by DerMolly** [comment]
I guess this is fixed then and I'll close this.
