### ISSUE TITLE
Add guide for reverse-proxy setups

### ISSUE THREAD

**Issue by SISheogorath** [hedgedoc/hedgedoc#256]
We should write a guide that explains how to setup CodiMD behind a reverse proxy with the whole problems to be avoided by setting `domain`, `urlAddPort` and `protocolUseSSL`.

**Comment by AlexKalopsia** [comment]
This would be really appreciated!

**Comment by Amolith** [comment]
If I have time this evening or tomorrow, I'll look into it and draft something.

**Comment by nmaas87** [comment]
That would be helpful :)

**Comment by ErikMichelson** [comment]
I'm currently developing something for that. You might want to test the prototype [here](https://erikmichelson.gitlab.io/codimd-setup-assistant/). If you encounter any bugs or incorrect configurations, please report them as an issue in the corresponding repository.

**Comment by nmaas87** [comment]
That looks quite good - the Docker version should be working - at least what it returns makes sense :)!
