### ISSUE TITLE
Metrics and status exposed by default

### ISSUE THREAD

**Issue by davidc** [hedgedoc/hedgedoc#2574]
### Which part of the project should be enhanced?

metrics/status API

### Is your enhancement request related to a problem? Please describe.

Confidential information is exposed at /metrics and /status by default and this is neither documented nor does there seem to be an easy way to disable it.

### Describe the solution you'd like

1) A configuration option to disable public exposure of metrics (Yes I can block /status and /metrics in the reverse proxy, but those are the only ones I know about, maybe there are more, maybe there will be more in future)

and either:

2) This option set by default so that this information is not exposed
or
3) Very clear and prominent information in all three installation documents warning people that it is enabled by default

### Describe alternatives you've considered

Obviously now I am aware of it I can block these specific URLs in the reverse proxy, however what about the many other people who may not be aware they have been leaking information for months?

**Comment by SISheogorath** [comment]
May I ask which of the information exposed there is considered sensitive and in which context?

**Comment by ErikMichelson** [comment]
> Additionally /metrics is exposing URLs which could include PII.

No, the /metrics route does only include the routes as set up in the source code. For example `/:noteId`  instead of actual note ids. So there is no PII exposed in that way as all the routes are publicly visible in the source code.

**Comment by almereyda** [comment]
I would second the general idea of the original posting, that the `/metrics` and `/status` endpoints provide observability information specific to an instance and primarily used for orchestration and observation purposes.

A possible way to mitigate their exposure by default, would be to have them listen on a separate interface/port, optionally on `localhost`, in order to separate the concerns of the routes cleanly. This would still allow to retrieve them where the process is running, but avoids to have them readily available in the open internet.

**Comment by davidc** [comment]
> > Additionally /metrics is exposing URLs which could include PII.
> 
> No, the /metrics route does only include the routes as set up in the source code. For example `/:noteId` instead of actual note ids. So there is no PII exposed in that way as all the routes are publicly visible in the source code.

This may be the intention but it is not the reality, if you visit /metrics you see thousands of URLs.

**Comment by mrdrogdrog** [comment]
> thousands of URLs

But none of these contain PII

**Comment by ErikMichelson** [comment]
This was implemented with #4165.
