### ISSUE TITLE
Protect notes by password or restrict it to logged in users

### ISSUE THREAD

**Issue by paulmenzel** [hedgedoc/hedgedoc#2688]
### Is your feature request related to a problem? Please describe.

Publishing a note, currently it seems to be protected by a hash in the URL. But if the URL is leaked, for example by pasting it to some search machine, everybody could access it.

### Describe the solution you'd like

When publishing a note, it’d be great, if the access to it could be restricted by an additional password or logged in users only.

### Describe alternatives you've considered

The alternative could be to set up several HedgeDoc instances, where the restricted instance, would be protected on the Web server level. It has the downside, that it’s more complex to the users, and notes could not be protected later or protection removed later.

**Comment by SISheogorath** [comment]
You can already do this by adjusting the note permission to `limited` and you can also adjust the default setting for your instance.

https://demo.hedgedoc.org/features#Permissions

https://docs.hedgedoc.org/configuration/#users-and-privileges

**Comment by paulmenzel** [comment]
Sorry for missing that. *Limited* is what I wanted.

A way to set a password would still be nice though, as sometimes their are collaborators with no account.
