### ISSUE TITLE
Replace deprecated request library

### ISSUE THREAD

**Issue by SISheogorath** [hedgedoc/hedgedoc#269]
Reuqest is deprecated: https://github.com/request/request/issues/3142

We should remove with the next major version. We might find a replacement that doesn't have 20 dependencies. I hope someone will look into it and find all places where it's used an a good way to get rid of this package.

**Comment by ccoenen** [comment]
For perspective: from what I can tell, this is only being used in one place:

https://github.com/codimd/server/blob/d49844d0753581a8d3a1404c2de37e17dc644d03/lib/response.js#L6

once to oauth to github(?) and put something in a gist

https://github.com/codimd/server/blob/d49844d0753581a8d3a1404c2de37e17dc644d03/lib/response.js#L78-L83

https://github.com/codimd/server/blob/d49844d0753581a8d3a1404c2de37e17dc644d03/lib/response.js#L96-L105

and one more time for gitlab

https://github.com/codimd/server/blob/d49844d0753581a8d3a1404c2de37e17dc644d03/lib/response.js#L138

as part of -i guess?- the gitlab login (called from here)

https://github.com/codimd/server/blob/2ddec15af8e77fcad85e62ee8c0b6eccefc52405/lib/web/auth/gitlab/index.js#L34

**Comment by ccoenen** [comment]
So it seems to be a fairly localised change. If anyone wants to take this up, let us know! We'll gladly provide support.

**Comment by theOpetunde** [comment]
Hello @ccoenen 
I am a first time contributor and would like to give this a try if that's OK with the team. Thank you

**Comment by SISheogorath** [comment]
@theOpetunde Sure :) We would really welcome it. Go ahead, when you need any help, don't hesitate to ask in the [community channel](https://matrix.to/#/#codimd:matrix.org).

**Comment by tabuckner** [comment]
@theOpetunde might be worth working on a adapter too to make this sort of change trivial in the future. A single API interface that lives in the codebase that can be adapted for any 3p request dependency. 

Thoughts?

Cc: @SISheogorath

**Comment by ccoenen** [comment]
I don't think these very few lines warrant that complexity yet.

**Comment by SISheogorath** [comment]
I guess the important question would be: How stable would this API be? And here I agree with @ccoenen that it's most likely not really more stable than an upstream API for such fundamental libraries. Request experienced a deprecation after ~10 years, when the current alternative lasts half as long we are off for good.

But if you are interested in developing an own API interface, I have no strong opinions against it, if you are fine with maintaining it :)

**Comment by tabuckner** [comment]
> I don't think these very few lines warrant that complexity yet.

That's my only hangup and a totally valid point. I might just be scarred from working in parallel with a pretty volatile BE. Having that adapter/delegate saved my bacon in more than one instance 😂

**Comment by InnayTool** [comment]
It is possible to simply replace request lib by [http.request](https://nodejs.org/api/http.html#http_http_request_url_options_callback)?

**Comment by DamianKu** [comment]
Is this something that's being worked on? 

I can look into it :)

**Comment by SISheogorath** [comment]
@InnayTool did you put time in here, otherwise this should be something @DamianKu can pick up :)

**Comment by InnayTool** [comment]
I didn't invest much time in that, but I don't think it is worth to do because we plan to rework huge parts of the backend and maybe it's removed anyway. @DerMolly removed the good first issue tag because of that.

**Comment by ErikMichelson** [comment]
Merged in #1025
