### ISSUE TITLE
Delete user button too close to sign out.

### ISSUE THREAD

**Issue by pierreozoux** [hedgedoc/hedgedoc#2693]
### Description

Delete user button too close to sign out.

### Steps to reproduce

![Screenshot 2022-09-27 at 17-25-34 HedgeDoc - Collaborative markdown notes](https://user-images.githubusercontent.com/1863453/192568679-7b7976bc-dd4c-4e42-9e57-6c4e4976b06d.png)

I think the 2 buttons are a bit too close.

We just did a partial restore this afternoon for a user that did that mistake.

### Expected behaviour

The delete action should be a bit more complicated, in a different place?
(Not UX export, sorry :/ )

### Your Setup

n/a

**Comment by davidmehren** [comment]
The new frontend in HedgeDoc 2 has this button [on the profile page](https://hedgedoc.dev/profile)
![image](https://user-images.githubusercontent.com/5023650/193469297-ac1f7c5f-9120-4b26-ae0a-44c7518d6f2f.png)
and an additional popup with a countdown
![image](https://user-images.githubusercontent.com/5023650/193469353-156933b5-2494-4e8d-ae66-78f2221aed2d.png)


This should make accidental deletion impossible ;)
