### ISSUE TITLE
TOC scrollspy's off-by-one-like behavior

### ISSUE THREAD

**Issue by tamo** [hedgedoc/hedgedoc#2697]
### Description

Clicking a toc-label activates a wrong list-item

### Steps to reproduce

1. Go to https://demo.hedgedoc.org/features?both
2. Click the 三 on the right-bottom corner, to pop up the toc
3. Click the third li, "Workspace"
4. See the second li, "Introduction", is activated

Or simply 
1. Go to https://demo.hedgedoc.org/features?both#Workspace
2. Click the 三 on the right-bottom corner
3. See both "Introduction" and "Workspace" are activated

### Expected behaviour

The clicked item, "Workspace", should be activated.
And "Introduction" should NOT.

### Your Setup

- demo.hedgedoc.org

### Additional context

https://github.com/hedgedoc/hedgedoc/blob/98e9616af870dc6f2c79725741091c85f166f065/public/css/extra.css#L400

This -55px allows the previous paragraph to overlap the space above h1,2,3...6.

https://github.com/hedgedoc/hedgedoc/blob/98e9616af870dc6f2c79725741091c85f166f065/public/js/index.js#L1710

headerMap should also consider margin-top of h1-3:before, maybe using

```window.getComputedStyle($(headers[i])[0], '::before').getPropertyValue('margin-top')```

**Comment by mrdrogdrog** [comment]
Hello, Thank you for your issue.
As you can read in the [README](https://github.com/hedgedoc/hedgedoc#state-of-the-project) HedgeDoc 1 is a maintenance-only version and we won't fix any non-critical bug because we're focusing on the development of HedgeDoc 2.

**Comment by tjyuyao** [comment]
For those who want a quick dirty patch, try comment out following lines in `extra.css`: https://github.com/hedgedoc/hedgedoc/blob/98e9616af870dc6f2c79725741091c85f166f065/public/css/extra.css#L388-L403
The `-55px` top margin implies that the page location is still in the tail of the previous section, which causes this issue.

These lines of code were originally designed to prevent content from being hidden underneath navbar, but in my current experience (`v1.9.6`) the navbar somehow by default automatically hide itself so the problem gone. Therefore it seems safe to remove them.
