### ISSUE TITLE
syncscroll gradually gets inaccurate

### ISSUE THREAD

**Issue by tamo** [hedgedoc/hedgedoc#2698]
### Description

Scrolling back and forth will break syncscroll gradually

### Steps to reproduce

1. Go to https://demo.hedgedoc.org/features?both#Typography
2. See the editor and the viewer are (almost) in sync
3. Click the 三 on the right-bottom corner to pop up the toc nav
4. Click the first item, "Features" (OK, synced)
5. Click the last item, "Revisions"
6. See the editor is out of sync (some 30 lines above "Revisions" in my env)

### Expected behaviour

The editor should scroll to "Revisions"

### Your Setup

- Host OS: demo.hedgedoc.org
- NodeJS version: demo.hedgedoc.org
- HedgeDoc version: 1.9.4 + x.x

### Additional context

Maybe we have to set ```editor.setOption('viewportMargin', Infinity)``` more often (at least before scrolling).
codemirror/codemirror5#4108
> The height of lines that aren't in the viewport yet is an estimate, not an accurate value.

> You could set a ```viewportMargin: Infinity``` option, which will disable the optimizations gained by lazy drawing, but give you accurate heights.

syncscroll.js relies on ```editor.heightAtLine()``` and ```editor.getScrollInfo().height``` heavily:
https://github.com/hedgedoc/hedgedoc/blob/98e9616af870dc6f2c79725741091c85f166f065/public/js/lib/syncscroll.js#L180
https://github.com/hedgedoc/hedgedoc/blob/98e9616af870dc6f2c79725741091c85f166f065/public/js/lib/syncscroll.js#L275-L281

Maybe we should make sure viewportMargin=Infinity before calculating the values above.

**Comment by mrdrogdrog** [comment]
Hello, Thank you for your issue.
As you can read in the [README](https://github.com/hedgedoc/hedgedoc#state-of-the-project) HedgeDoc 1 is a maintenance-only version and we won't fix any non-critical bug because we're focusing on the development of HedgeDoc 2, which is a complete rewrite. The problem you describe is already fixed in HedgeDoc 2.
