### ISSUE TITLE
Proper website support?

### ISSUE THREAD

**Issue by SmartBoy84** [hedgedoc/hedgedoc#2740]
### Describe the solution you'd like

~~Is it possible to use hedgedoc to just show the document barring any editing options?
Like [this page](https://demo.hedgedoc.org/features) but without the header? So it actually appears like a normal HTML blog page.~~

Personally, the ideal setup would be one where I am able to have all my markdown files rendered and displayed by hedgedoc on the "main" domain and on a subdomain the same URL would allow the file to be edited? 
So for example, at `domain.com/file.md` I'd be able to just view the file as if it were a normal page then at `edit.domain.com/file.md` I'd be able to sign and edit the file.

Currently, I use Nginx to forward all URLs ending with `.md` to a simple js markdown "processor" that I wrote that renders and displays the file. For now, I edit these files through SSH + nano 😔
Would it possible to forward all `.md` files to hedgedoc to display even if they aren't ones that have been created in hedgedoc?

### Describe alternatives you've considered

Notion

**Comment by mrdrogdrog** [comment]
Hello,

Unfortunately you can't run a HedgeDoc instance on more than one domain. It's not possible to split the editor from the rendering. Also HedgeDoc can't process plain files. It uses a database.
You could
- export the html via the "export" menu in the editor to get a bundled version of the read only page and deploy this HTML file.
- read the note content from the database or use the cli tool to download the note content and process it using another tool. Keep in mind that other tools may not support all features and syntaxes of HedgeDoc. 
- use another tool that fulfills your needs in a better way. HedgeDoc's main purpose is collaborative live editing of documents, not website generation. We recommend https://gohugo.io . We use that for hedgedoc.org

**Comment by DerMolly** [comment]
I think we can close this issue then? If you disagree @SmartBoy84 feel free to reopen…
