### ISSUE TITLE
No way to connect to MySQL database via SSL using environment variables

### ISSUE THREAD

**Issue by markus-k** [hedgedoc/hedgedoc#2808]
### Which part of the project should be enhanced?

Database connection environment variables

### Is your enhancement request related to a problem? Please describe.

I have a MySQL Database that will only connect via SSL (e. g. [PlanetScale](https://planetscale.com)), and a deployment where you can only set environment variables, not files (e. g. Serverless Containers/Knative). 

I'm trying to connect to the database using the `CMD_DB_URL` environment variable, like `CMD_DB_URL=mysql://user:pass@somehost/database?ssl={"rejectUnauthorized":true}` or `CMD_DB_URL=mysql://user:pass@somehost/database`. But the connection to the database will fail (either because you aren't connecting using SSL or because the SSL parameter is parsed wrongly by sequelize (`Unknown SSL profile '{"rejectUnauthorized":true}'`).

There seems to be no environment variable to explicitly set either SSL or additional connection options.

### Describe the solution you'd like

* Either the `CMD_DB_URL` should parsed correctly (not in HedgeDoc's hand, see sequelize issue linked below) or
* Provide an additional environment parameter

Such a parameter could either explicitly enable SSL (like `CMD_DB_SSL={"some": "json"`) or be a generic connection options parameter passed to sequelize.

### Describe alternatives you've considered

Not deploy HedgeDoc in the way I originally wanted to.

### Additional context

The upstream issue in sequelize is https://github.com/sequelize/sequelize/issues/15223

**Comment by davidmehren** [comment]
As this is an upstream issue in sequelize, we can't fix this in HedgeDoc 1.
I created a new issue to expose the database SSL/TLS options in HedgeDoc 2: https://github.com/hedgedoc/hedgedoc/issues/3063
