### ISSUE TITLE
Missing pads after update to v1.9.5

### ISSUE THREAD

**Issue by Mrmaxmeier** [hedgedoc/hedgedoc#2809]
### Description

Pads with associated authors disappeared after updating to v1.9.5. I believe this happens due to a bad interaction between the [convert history to longtext](https://github.com/hedgedoc/hedgedoc/pull/2624) migration,  the `ON DELETE CASCADE` attribute on the `Note.authorId` field, and ~~[surprising typeorm migration APIs](https://github.com/typeorm/typeorm/pull/7922#issuecomment-1151118114)~~ (never mind, the `master` branch is not using typeorm yet. `umzug` simply doesn't seem to be aware of `PRAGMA foreign_keys` !?),.

### Steps to reproduce

Step 0: **create a database backup**
1. (<v1.9.5) Create new pad while logged in or restore from a (<1.9.5) backup
2. Update to v1.9.5
3. Start hedgedoc => automatically runs `20220901102800-convert-history-to-longtext` migration
4. Pads (that had `authorId` set) are gone :/

Note: I'm using the SQLite backend. This might not affect other databases (?)

### Expected behaviour

No missing pads.

### Your Setup

- Host OS: NixOS unstable
- NodeJS version: v18.12.0
- HedgeDoc version: v1.9.5

**Comment by nomaster** [comment]
I have encountered the same issue with our Kubernetes deployment, using sqlite. After upgrading from v1.9.4 to v1.9.5, all rows in the "Notes" table are gone. 😵

**Comment by Mrmaxmeier** [comment]
This patch seems to work as a bandage (applies the migration without deleting pads):
```diff
diff --git a/app.js b/app.js
index 34a107ae..1bf75f61 100644
--- a/app.js
+++ b/app.js
@@ -279,7 +279,13 @@ let currentDBTry = 1
 function syncAndListen () {
   // sync db then start listen
   models.sequelize.authenticate().then(function () {
-    models.runMigrations().then(() => {
+    models.sequelize.query("PRAGMA foreign_keys = OFF;").then(function() {
+      return models.runMigrations()
+    })
+    .then(() => {
+      return models.sequelize.query("PRAGMA foreign_keys = ON;")
+    })
+    .then(() => {
       sessionStore.sync()
       // check if realtime is ready

```
I have not tried this with other database backends though.

**Comment by drupol** [comment]
Using postgresql, no data loss so far.

**Comment by mrdrogdrog** [comment]
I'll take a look.

**Comment by drupol** [comment]
Should we revert https://github.com/NixOS/nixpkgs/pull/198754 to prevent data loss somewhere else?

**Comment by BBBSnowball** [comment]
I got this behaviour with SQLite (on NixOS, without above patch):
```
2022-11-04T04:47:52.723Z info:         == 20220901102800-convert-history-to-longtext: migrating =======
(sequelize) Warning: SQLite does not support TEXT with options. Plain `TEXT` will be used instead.
>> Check: https://www.sqlite.org/datatype3.html
2022-11-04T04:47:52.732Z error:         Validation error
2022-11-04T04:47:52.732Z error:         Database migration failed.
This can be the result of upgrading from quite old versions and requires manual database intervention.
See https://docs.hedgedoc.org/guides/migration-troubleshooting/ for help.
Exiting…
```

I guess, some inconsistency in the post-migration state saved me from disaster. As sequelize seems to think that the column should be just "TEXT" (which it already is), I skipped the migration like this: `insert into SequelizeMeta values ('20220901102800-convert-history-to-longtext.js');`

**Comment by mrdrogdrog** [comment]
Fix is on the way https://github.com/hedgedoc/hedgedoc/pull/2821

**Comment by davidmehren** [comment]
Thanks everyone for reporting!
We released a fix with https://github.com/hedgedoc/hedgedoc/releases/tag/1.9.6

**Comment by drupol** [comment]
Going to prepare the update in NixOS now.

**Comment by drupol** [comment]
Ready for review: https://github.com/NixOS/nixpkgs/pull/199987
