### ISSUE TITLE
Find and replace feature

### ISSUE THREAD

**Issue by domestomas** [hedgedoc/hedgedoc#2827]
### Which part of the project should be enhanced?

Find feature

### Describe the solution you'd like

There could be a possibility of expanding the find row to a second row where you write the replacement, as it is for instance in VSCode.

### Describe alternatives you've considered

Any other version of find and replace would be ok

**Comment by mrdrogdrog** [comment]
If you use Ctrl+H (or CMD+h on Mac) you'll get a replace bar.
It's not exactly the same as VSCode, but it works. HedgeDoc 2 will have a new better search&replace function.

**Comment by eMPee584** [comment]
Mh, CTRL+H clashes with firefox history for me..

> If you use Ctrl+H (or CMD+h on Mac) you'll get a replace bar.

**Comment by ErikMichelson** [comment]
When you click inside the editor (so that the cursor is blinking) and then press CTRL+H it should work and not open the history. Just tested it with Firefox 128.
