### ISSUE TITLE
Does not pass the correct `redirect_uri` while authenticating with Authelia

### ISSUE THREAD

**Issue by stratosgear** [hedgedoc/hedgedoc#2829]
### Description

Hedgedoc does not use the correct redirect_uri while trying to authenticate with Authelia (using http instead of https)

### Steps to reproduce

* Clicking the `Sign in` button opens a mini dialog.
* Inside there there is a button `Sign In with Authelia`
* Clicking that button:
  * Redirects to an empty white page
  * The URL is: `https://sso.example.com/api/oidc/authorize?response_type=code&redirect_uri=http%3A%2F%2Fdocs.example.com%2Fauth%2Foauth2%2Fcallback&scope=openid%20email%20profile&state=secret&client_id=secret`

If you notice, the `redirect_uri` is using `http` instead of `https` 

### Expected behaviour

I would expect it to use `https`

If I Manually substitute `https` in that redirect_uri the link works correctly.

### Config

```shell
environment:
      - CMD_DB_URL=postgres://hedgedoc:password@db:5432/hedgedoc
      - CMD_DOMAIN=docs.example.com
      - CMD_PORT=3000
      - CMD_URL_ADDPORT=False
      - CMD_ALLOW_ORIGIN=localhost,hedgedoc_app,docs.example.com
      - CMD_PROTOCOL_USESSL=True
      - CMD_SESSION_SECRET=secret
      - CMD_CSP_ENABLE=True
      - CMD_HSTS_ENABLE=True
      - CMD_ALLOW_EMAIL_REGISTER=False
      - CMD_EMAIL=False
      - CMD_OAUTH2_PROVIDERNAME=Authelia
      - CMD_OAUTH2_CLIENT_ID=clientid
      - CMD_OAUTH2_CLIENT_SECRET=clientsecret
      - CMD_OAUTH2_SCOPE=openid email profile
      - CMD_OAUTH2_USER_PROFILE_USERNAME_ATTR=sub
      - CMD_OAUTH2_USER_PROFILE_DISPLAY_NAME_ATTR=name
      - CMD_OAUTH2_USER_PROFILE_EMAIL_ATTR=email
      - CMD_OAUTH2_USER_PROFILE_URL=https://sso.example.com/api/oidc/userinfo
      - CMD_OAUTH2_TOKEN_URL=https://sso.example.com/api/oidc/token
      - CMD_OAUTH2_AUTHORIZATION_URL=https://sso.example.com/api/oidc/authorize
```
```


### Your Setup

Docker image:  quay.io/hedgedoc/hedgedoc:1.9.6-alpine

Version (from footer):
https://github.com/hedgedoc/hedgedoc/tree/9ad995d0f66d3cba79b5d645622cb86243389b73

### Additional context

**It is** possible that this is a misconfiguration from my part, but I think I have everything right...?


Thanks!

**Comment by stratosgear** [comment]
Thanks David, that worked!

But I am surprised at that parser!  How did the other settings work? I had a bunch of `False` and `True` settings.  Were they all being interpreted as false?  

This is a new installation so I didn't have an opportunity to fully test-drive everything yet, but I am surprised I came so far with "wrong" settings..

**Comment by DerMolly** [comment]
Maybe your settings were just the defaults?

**Comment by stratosgear** [comment]
No idea! :)

Closing as fixed!
