### ISSUE TITLE
Rework Note History Data Model

### ISSUE THREAD

**Issue by SISheogorath** [hedgedoc/hedgedoc#283]
The data model of of note history is currently basically non-existent. It's a json string that is stored in the User model. It should be change to be an own database table/model that contains data like the userId, the noteId, the last access to this note by the user a boolean for checking if the note is being pinned and maybe more.

We need a migration path for existing history, so we should figure out an import function for this database model as well and keep the old field around (at least for one more minor version).

Code to look at:

https://github.com/codimd/server/blob/004e2fbcb28f75875147a34f3b5863d75bc4f9de/lib/models/user.js#L33-L35

https://github.com/codimd/server/blob/8ce7b285636c02b4215c838640bb748947c8317f/lib/history.js#L1-L200

Might depends on #281. Should help to fix #62.

*Please keep in mind to file your changes against the `release/2.0.x` branch*

**Comment by ccoenen** [comment]
this is related: I am not really sure we should base64 any of this, and certainly not in that order.

**Comment by SISheogorath** [comment]
@ccoenen actually no :thinking: But good that you point it out. I was more thinking of the history data per user of all notes he/she visited. Not the revisions of a note.

**Comment by ccoenen** [comment]
whoops. I mistook history for revisions. We should work on revisions at some point, too, but that was unrelated. You're right.

**Comment by InnayTool** [comment]
This was done in #801.
