### ISSUE TITLE
Incomplete filenames for notes with colon in title in archive.zip

### ISSUE THREAD

**Issue by thmo** [hedgedoc/hedgedoc#2830]
### Description

For a note that has colon in its title, the corresponding file in the exported archive.zip has an incomplete name.

### Steps to reproduce

1. Create a node named 'Foo: bar'
2. Select "Export user data" and download "archive.zip"
3. Inspect contents of archive.zip, find file " bar.md"

### Expected behaviour

The file in the archive.zip should be named "Foo: bar.md".

### Your Setup

Using the official Docker image:
- Host OS: Debian 11 (bullseye)
- NodeJS version: v16.18.0
- HedgeDoc version: 1.9.6

**Comment by davidmehren** [comment]
This has been fixed in https://github.com/hedgedoc/hedgedoc/pull/2831 and will appear in the next 1.x release
