### ISSUE TITLE
Arbitrary HTTP headers

### ISSUE THREAD

**Issue by rekup** [hedgedoc/hedgedoc#2846]
### Which part of the project should be enhanced?

HTTP request handling

### Is your enhancement request related to a problem? Please describe.

Currently, we are able to set the HSTS and CSP headers using the appropriate config directives or env vars. However, as far as I know it is not possible to define additional HTTP headers such as:

- `X-Frame-Options`
- `The X-Content-Type-Options`
- `The X-Permitted-Cross-Domain-Policies`
- `Cross-Origin-Embedder-Policy`
- `Cross-Origin-Resource-Policy`
- `Cross-Origin-Opener-Policy`

### Describe the solution you'd like

It would be nice to be able to define the headers mentioned above in the Hedgedoc config or via env vars. I'm not sure whether it make sense to implement these in the same manner as the existing HSTS/CSP (via a dedicated config directive). It might be better to use a generic header config which enables the configuration of arbitrary headers. This way, the Hedgedoc code does not have to be updated every time a new HTTP security header (or any other HTTP header) emerges.

### Describe alternatives you've considered

To solve this issue, we could add a reverse proxy in front of Hedgedoc. This of course works great but adds additional complexity. In addition, since it's currently already possible to define the HSTS and CSP headers in Hedgedoc it would be more consistent to have the header configuration in one place instead of spreading them across two components.

**Comment by davidmehren** [comment]
To reduce implementation complexity, HedgeDoc will focus on sending headers that are required for safe operation of the app itself.
You are welcome to suggest improvements to our default headers.

If your setup requires more/other headers, you will have to set them via a reverse proxy.
