### ISSUE TITLE
Additional Embedding Suggestions

### ISSUE THREAD

**Issue by mrdrogdrog** [hedgedoc/hedgedoc#2888]
From time to time someone says "Hey! This would be cool as embedding!". Like twitter or giphy. In this Issue we can collect different ideas. If we want to implement them, we can create new issues.

**Ideas**
- <del>Tweet (Twitter doesn't allow emeddings anymore)</del>
- <del>Toot (I have no idea how to detect them)</del>
- Giphy

**Comment by xeruf** [comment]
> We don't want to call every url, that we find in the doc to see what the answer is.

Though that might be handy as an option, like the link banners in Notion or previews in messaging apps.
