### ISSUE TITLE
Cannot visually distinguish between guest user and "vertical bar"

### ISSUE THREAD

**Issue by nidico** [hedgedoc/hedgedoc#2895]
## Problem:

As written in hedgedoc/hedgedoc#2892, authorship information is currently shown as a colored vertical bar in the line number gutter. Content written by the corresponding users is not underlined throughout the (vertically) marked line.

However this clashes with content written by a guest user in lines with colored vertical bars, as those guest edits also marked with "no underline".

Therefore it is currently not possible to distinguish between guest user and "vertical bar user" content.

## Possible solutions:

**Solution 1**: Implement authorship highlighting for anonymous edits (codimd/server#505)

- This would help. Caveat: Once authorship can be cleared (codimd/server#506), "cleared content" could still not be distinguished from to "vertical bar user" content.

**Solution 2**:  Underline all known users' content by adding inline markup (i.e.  `authorship-inline-xxx` classes) (as proposed in hedgedoc/hedgedoc#2892, "simple proposal")

- This would work.

**Solution 3**: Explicitly markup guest content in another color (e.g. with grey underlines and vertical bars).

- As long as solution 1 or solution 2 is not implemented, showing all anonymous content with different markup/color would also work.
- Note that guest users currently do not "own" lines (authenticated users will "take over" the ownership of the line). This should probably be made consistent (i.e. allow for "grey vertical bars").

**Comment by davidmehren** [comment]
We plan to implement full authorship tracking for anonymous users (Solution 1).

Implementation issue: https://github.com/hedgedoc/hedgedoc/issues/5016
