### ISSUE TITLE
Re-add import menu functionality

### ISSUE THREAD

**Issue by DerMolly** [hedgedoc/hedgedoc#2897]
We need to add functionality to the import menu:

- [x] import content from text/markdown file
- [ ] #5600

We won't implement the following functionality again:
- Dropbox (as mentionied in hedgedoc/hedgedoc#2898 we will drop dropbox export, so import doesn't seem to make sense to keep around)
- Gist
- Gitlab snippet
- Clipboard (not really possible and a bit useless, see below)

**Comment by ErikMichelson** [comment]
While working on the sidebar and implementing the gist/snippet exports, I thought that an import from gist/snippet doesn't make really sense. GitHub and GitLab treat gists/snippets more like mini-repositories that can hold multiple files. For a user the import is more complicated when having to enter access tokens etc than just copy&paste the content. Therefore I'd say to drop them.

**Comment by ErikMichelson** [comment]
Since the missing feature is now tracked in #5600, this issue can be closed.
