### ISSUE TITLE
Replace mock avatars with API call

### ISSUE THREAD

**Issue by mrdrogdrog** [hedgedoc/hedgedoc#2911]
**Which part of the project should be enhanced?**
Mock-API

**Is your enhancement request related to a problem? Please describe.**
Right now our avatar are served by the assets url.

**Describe the solution you'd like**
Avatars should be served by an API endpoint.

**Comment by davidmehren** [comment]
Fixed by https://github.com/hedgedoc/hedgedoc/pull/5012
