### ISSUE TITLE
Sort logic for explore page: tags

### ISSUE THREAD

**Issue by kleineLoesungen** [hedgedoc/hedgedoc#2915]
**Which part of the project should be enhanced?**
Personell landing page at filtering section

**Describe the solution you'd like**
Filtering with multi tags has an OR junction. For better results would an AND junction be better. 

**Describe alternatives you've considered**
User can select between OR and AND

**Comment by ErikMichelson** [comment]
This issue has been included in the implementation issue of the new explore page (#3833).
