### ISSUE TITLE
heading level >1 doesn't set the note title

### ISSUE THREAD

**Issue by hferreiro** [hedgedoc/hedgedoc#2925]
### Description

If the note doesn't have a level 1 heading, the title should be set by taking the first heading, whatever the level. Additionally, if a level >1 heading appears before a level 1 heading, the title should probably be taken from the former.

### Steps to reproduce

Use ## test as the note content.

### Expected behaviour

The note should have "test" as its title.

**Comment by DerMolly** [comment]
This was already fixed
