### ISSUE TITLE
Replace Fork-Awesome

### ISSUE THREAD

**Issue by mrdrogdrog** [hedgedoc/hedgedoc#2929]
**Which part of the project should be enhanced?**
Used Icons

**Is your enhancement request related to a problem? Please describe.**
The development of Fork Awesome seems to be dead again. There are many icons that haven't been released yet.
The last release is from Aug. 2021. The latest commit is from Dec. 2021

**Describe the solution you'd like**
I would like to deprecate the usage of Fork Awesome and use another open source icon font for the UI. Something like [Material Icons](https://fonts.google.com/icons) or [Bootstrap Icons](https://icons.getbootstrap.com/). I especially don't wanna use FontAwesome because it's very FOSS-Unfriendly.

To keep compatibility with HD1 notes I wouldn't remove Fork Awesome with 2.0. I would rather suggest to deprecate the usage of Fork Awesome icons in markdown. Users could be informed about that by a new Linter that checks the code for icons like `<i class="fa fa-arrow-right"></i>` and offers a suitable replacement. We could add some kind of lib independent shortcode like `:icon-arrow-right:`.

In a later release we can remove Fork Awesome completly.

**Describe alternatives you've considered**
Keep Fork Awesome.

**Comment by DerMolly** [comment]
We'll go with the following approach:

1. In HD2 we'll ship both Bootstrap Icons and Fork Awesome.
2. Deprecate Fork Awesome for a later 2.x release.
3. Implement a Linter that warn's the user about Fork Awesome and suggests replacing it with Bootstrap Icons.

**Comment by davidmehren** [comment]
It makes no sense to me to ship *two* Icon sets in 2.0, only to deprecate one of them shortly after.
We should use the major release to make the breaking change and be done with it.

**Comment by DerMolly** [comment]
The reason behind that is, that you would need to map one set of icons to the other, which is both time consuming and possible error prone or alternatively just break existing notes content, because `<i class="fa fa-address-book-o" aria-hidden="true"></i>` doesn't do anything anymore.

What we theoretically could do is just leave out the fork awesome and instead just have the linter tell you this is broken now, please change. As this feature is not really too much advertised in HedgeDoc and is mainly a artifact of us using fork awesome for the UI this maybe a decent solution.

**Comment by mrdrogdrog** [comment]
> It makes no sense to me to ship _two_ icon sets in 2.0, only to deprecate one of them shortly after. We should use the major release to make the breaking change and be done with it.

We would deprecate Fork Awesome WITH 2.0. we do that already with other stuff like the yt/Vimeo/pdf shortcodes.

**Comment by DerMolly** [comment]
Oh I just noticed the wrong wording in the post. I meant deprecate with 2.0 and remove in 2.1 or 2.2 or something. Because nobody want's to bring fork awesome along much longer in HedgeDoc 2.

**Comment by mrdrogdrog** [comment]
Okay people, we need a decision now because I wanna close this issue.
Should we keep fork awesome or not?
- We want to get rid of fork awesome because it seems to be unmaintained
- Bootstrap icons support will be merged into the frontend soon
- 2.0 is a good opportunity for that
- We have a linter in the editor that shows that FA is deprecated

Please comment or react now. 
@davidmehren @InnayTool @ErikMichelson @DerMolly

**Comment by ErikMichelson** [comment]
In my opinion we should drop ForkAwesome icon support with version 2.0.

With HedgeDoc 2 we're already doing plenty of changes to the markdown renderer, we even [distinguish between HFM1 and HFM2](https://docs.hedgedoc.org/references/hfm/). Therefore it seems reasonable to not keep every old syntax and library around.
As we've got a linter message that is able to detect the old syntax, we can use it to show a message like "ForkAwesome icons are not supported in 2.0, please switch to bootstrap-icons" on occurrences of the ForkAwesome syntax.
Another point is that people might expect changes to their document more likely when upgrading from HedgeDoc 1 to HedgeDoc 2 than when they upgrade from HedgeDoc 2.0 to HedgeDoc 2.1. This also follows SemVer more closely.
Last, we avoid shipping another dependency that will be dropped in the future anyway.
