### ISSUE TITLE
Possibility to re-open the motd modal

### ISSUE THREAD

**Issue by ErikMichelson** [hedgedoc/hedgedoc#2933]
**Which part of the project should be enhanced?**
Motd modal

**Is your enhancement request related to a problem? Please describe.**
The motd modal can only be dismissed without the possibility to show the information again. As the UI-test uses this to show relevant links to the privacy policy for example, it might be a good idea to allow the user to open the modal at a later point in time again.

**Describe the solution you'd like**
There are two possibilities:
1) The user may choose "Decide later" instead of "Dismiss" on the modal, which re-opens the modal after a full-page reload.
2) There is a button (for example in the footer of the intro page) that opens the motd modal.

**Describe alternatives you've considered**
As listed above

**Additional context**
none

**Comment by DerMolly** [comment]
>     1. The user may choose "Decide later" instead of "Dismiss" on the modal, which re-opens the modal after a full-page reload.
> 
>     2. There is a button (for example in the footer of the intro page) that opens the motd modal.

I think 2. is the way to go, but instead of in the footer I would suggest putting it either in the user menu or the settings perhaps?

**Comment by ErikMichelson** [comment]
What about this menu?

![image](https://user-images.githubusercontent.com/52606896/215500309-f406e887-3f37-4ef6-b105-00bf652df5fe.png)

**Comment by DerMolly** [comment]
You're right it would work in there perfectly
