### ISSUE TITLE
Reconnect of websocket connection

### ISSUE THREAD

**Issue by mrdrogdrog** [hedgedoc/hedgedoc#2939]
**Which part of the project should be enhanced?**
Realtime connection

**Is your enhancement request related to a problem? Please describe.**
If the websocket disconencts it doesn't reconnect

**Describe the solution you'd like**
Add a helper that listens for the correct events of the websocket connection and reconnects after a certain time.

**Additional context**
To avoid flooding we should increase the waiting time with every attempt and reset this on success full connect.

**Comment by DerMolly** [comment]
This was fixed in the mean time…
