### ISSUE TITLE
Notify other clients of metadata updates

### ISSUE THREAD

**Issue by ErikMichelson** [hedgedoc/hedgedoc#2940]
**Is your feature request related to a problem? Please describe.**
When one client changes metadata of a note (for example the permissions or aliases), the other clients won't receive this update as the metadata is usually only fetched once during loading of the note.
In case of permission changes this could lead to serious access violations such as write-after-permission-loss.

**Describe the solution you'd like**
Everytime a client changes non-trivial metadata like permissions, note ownership or aliases a notification message will be distributed to all other clients on the same note via the websocket connection.
A client needs to listen for such notification messages and re-fetch the metadata from the server at that point.

**Describe alternatives you've considered**
- calculate the metadata state locally on each client and solely rely on the server for permission checks
- periodically fetch the metadata from the server

**Additional context**
Messages like this should probably go over our HEDGEDOC message channel of Y.js.

**Comment by mrdrogdrog** [comment]
Already implemented
