### ISSUE TITLE
PlantUML not configured placeholder

### ISSUE THREAD

**Issue by ErikMichelson** [hedgedoc/hedgedoc#2944]
**Which part of the project should be enhanced?**
Markdown extensions -> PlantUML

**Is your enhancement request related to a problem? Please describe.**
The PlantUML API server is an optional config option for the backend. When no server is configured, the frontend does not render anything for PlantUML blocks.

**Describe the solution you'd like**
A blurred image of a PlantUML diagram should be shown which has an overlay containing information that this feature can be enabled by the administrators.

Quick example:
![image](https://user-images.githubusercontent.com/52606896/149675301-31b5c612-1615-4374-8901-c11aa67eeec8.png)

**Describe alternatives you've considered**
- Use a fallback PlantUML server (e.g. hosted by us to reduce load on the official demo)
- Show a code syntax highlighting block for PlantUML altogether with an alert message

**Additional context**
Decided in dev-meeting, 2022-01-16

**Comment by mrdrogdrog** [comment]
Tbh I think just an alert box would fit more into our style.

**Comment by DerMolly** [comment]
We once discussed that it would be beneficial to distinguish between alert boxes the user can create and error messages of the system.

**Comment by ErikMichelson** [comment]
![image](https://github.com/hedgedoc/hedgedoc/assets/52606896/f81bb281-741b-4936-a70d-b9137d346b71)

In #4573 an alert box was introduced that is different from the user-created alert boxes. Therefore this can be closed.
