### ISSUE TITLE
Infinite scroll for explore page

### ISSUE THREAD

**Issue by EV21** [hedgedoc/hedgedoc#2950]
### Which part of the project should be enhanced?

history view

### Is your enhancement request related to a problem? Please describe.

- Currently I can see only 18 documents at one page. 
- As someone who has a lot of documents I am losing the overview on the history view because of the pages. - Pressing 1,2,3... just to look what I have doesn't seem to be modern. 
- As the document order rearranges by every access (even without any change) remembering page numbers makes no sense, so why do we need them at all?

### Describe the solution you'd like

New content should be loaded step by step by scrolling. 

### Describe alternatives you've considered

- Maybe the paging feature can still be available as a configurable option if someone prefers that.
- Selectable page sizes could also be a solution as long as infinite scroll is not implemented.

**Comment by ErikMichelson** [comment]
This issue is included in the implementation issue of the new explore page (#3833).
