### ISSUE TITLE
Enhancement: API Keys

### ISSUE THREAD

**Issue by ykorzikowski** [hedgedoc/hedgedoc#2977]
### Which part of the project should be enhanced?

Add API Key for USers

### Is your enhancement request related to a problem? Please describe.

I did not find a nice way to use api as logged in user when using keycloak oauth.

### Describe the solution you'd like

There should be an option: `+ Add API Key` in the user menu, so users can add api keys to use the API safe

### Describe alternatives you've considered

Or a central API key configured in configuration

Or a admin interface to create seperated API USers

![Bildschirm­foto 2022-12-02 um 10 53 42](https://user-images.githubusercontent.com/20556547/205266068-7a50e9e0-d010-4bb0-8fc1-2eb2366bb460.png)

**Comment by mrdrogdrog** [comment]
Hello,

API keys (and a full REST API) are already planned for HedgeDoc 2.

**Comment by ykorzikowski** [comment]
awesome 👍  is it just planned or is there already a beta to try out?

**Comment by ykorzikowski** [comment]
Another question: Is it possible with the current version to access nots securely with some login mehtod? Or is there only cookie and LDAP method?

https://github.com/hedgedoc/cli#configuration-and-usage

**Comment by ykorzikowski** [comment]
![Bildschirm­foto 2022-12-02 um 11 14 03](https://user-images.githubusercontent.com/20556547/205269637-57f5f1a1-8c11-440a-8b5f-8be0de25888f.png)

Its already there on the mock https://hedgedoc.dev/profile

**Comment by mrdrogdrog** [comment]
>  is it just planned or is there already a beta to try out?

The REST API and the API keys are core features and will definitly come with HD2.
But HedgeDoc 2 is still in development. Right now it's not possible to run it in production.

> Another question: Is it possible with the current version to access nots securely with some login mehtod? Or is there only cookie and LDAP method?

No. The current CLI doesn't support this ootb. But a common workaround is to log into your account in the browser and then use the browser dev tools to copy the session id. You can paste it into the session file of the CLI.(`~/.config/hedgedoc/key.conf` afaik).

> Its already there on the mock https://hedgedoc.dev/profile

That's correct. Like I said: It's planned for HD2.

**Comment by ykorzikowski** [comment]
Thank you for your reply :) I found a solution for me: I enabled email aand self registration, created an account with e-mail and disabled mail-registration again. 

So I have a "api-user" for my purpose

**Comment by davidmehren** [comment]
Closing, as the requested feature is already planned and implemented in HD2.
