### ISSUE TITLE
Book mode equivalent

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [hedgedoc/hedgedoc#300]
It would be great if the current HackMD's "Book Mode" feature being implemented, in order to organize notes/sites from multiple sources and authors.

Thanks in advance!

**Comment by ccoenen** [comment]
In #178 something similar has been suggested, but I do not think that we'll be implementing something exactly like HackMDs Book mode.

**Comment by InnayTool** [comment]
This discussion is continued in #1001
