### ISSUE TITLE
Show permissions settings in editor-only view

### ISSUE THREAD

**Issue by NexAdn** [hedgedoc/hedgedoc#3009]
### Which part of the project should be enhanced?

Web frontend

### Is your enhancement request related to a problem? Please describe.

Currently, when having a document open in the editor-only mode (i.e. Ctrl+Alt+E), the dropdown to select the document's permissions (i.e. who is allowed to view/edit) is not visible. Rather, it can only be seen in the side-by-side mode or the view-only mode.

### Describe the solution you'd like

I'd like to see the dropdown for the permissions to be visible in the editor-only mode,
ideally in a similar position like in the other two modes.

### Describe alternatives you've considered

The current alternative is using the side-by-side mode or switching to it when creating a new document to adjust the permissions.
Both alternatives are viable temporary solutions, but don't solve the UX issue of having to know that these settings are only available in two of three available modes (it took a hint from someone else for me to figure this out, since I almost exclusively have the editor-only mode open and didn't imagine a setting being visible only in the other two modes).

**Comment by mrdrogdrog** [comment]
Hello,

This problem is already known and will be solved in HedgeDoc 2 because we're gonna create a new better ui for the editor.
