### ISSUE TITLE
Editor and Renderer can get out of sync if WebSocket connection fails

### ISSUE THREAD

**Issue by davidmehren** [hedgedoc/hedgedoc#3090]
### Description

When the frontend fails to establish a realtime connection after a note is opened, the editor stays empty

### Steps to reproduce

- Misconfigure your webserver
- Open a note
- Observe the editor staying blank, while the renderer shows content

![image](https://user-images.githubusercontent.com/5023650/209801689-0aaf6202-3242-43b6-9315-517ebfbeda3d.png)

### Expected behaviour

Both views stay blank, or a clear connection error is shown.

### Your Setup

- Host OS: Fedora 37
- NodeJS version: 18.12.1
- HedgeDoc version: c8254ff77923cefb212bbc30539c8b76668f2e98

**Comment by davidmehren** [comment]
Hmm, this seems to also happen when the WebSocket connection *does* work.
At least, I only get *one* WebSocket error and I can see a second WS connection (with a correct noteId query parameter) in the dev tools

**Comment by davidmehren** [comment]
Interesting: When running the frontend in dev-mode, the editor loads correctly.
When I run the frontend in production mode, loading fails.

Both have `HD_EDITOR_BASE_URL` set to the same backend URL.

**Comment by mrdrogdrog** [comment]
Did you follow the dev Setup guide?

**Comment by davidmehren** [comment]
Yep. It works when the frontend runs with the `dev:with-local-backend` task (which has both base URLs patched to `http://172.16.0.41:8080/`), but doesn't work with the `yarn build` and `HD_EDITOR_BASE_URL=http://172.16.0.41:8080/ yarn run`

**Comment by mrdrogdrog** [comment]
Fixed
