### ISSUE TITLE
DELETE /NOTE/ via the API

### ISSUE THREAD

**Issue by ColinMaudry** [hedgedoc/hedgedoc#3093]
### Is your feature request related to a problem? Please describe.

It is currently not possible to delete a note via the API, outside of HedgeDoc.

### Describe the solution you'd like

Add the possibility to issue a HTTP DELETE request to a /<NOTE>/ endpoint to delete the note from user histories and database.

This would only apply to notes with logged in authors, not guest notes.

The HTTP DELETE request should bear some auth information.

### Describe alternatives you've considered

I could connect to the underlying database and delete from there... but that would not be sustainable.

### Additional context

I am developing a Python command line application to manage notes in a more advanced way than what HedgeDoc offers, especially multi tag search (tag1 AND tag2, tag1 OR tag2, etc.)

https://github.com/ColinMaudry/hazelnotes

**Comment by mrdrogdrog** [comment]
Hello,

This is already planned for HedgeDoc 2 which will feature a full token based REST API. This feature won't be added to HedgeDoc 1.

**Comment by ColinMaudry** [comment]
Looking at #474 lets me think `DELETE` has been implemented but [not documented](https://docs.hedgedoc.org/dev/api/).

**Comment by davidmehren** [comment]
The docs at docs.hedgedoc.org talk about the HedgeDoc 1 API. You can see the docs for the HD2 API by running the new backend and accessing http://localhost:3000/apidoc

**Comment by ColinMaudry** [comment]
When is approximately the release of HedgeDoc 2 planned?
