### ISSUE TITLE
Kubernetes installation docs point to hackmdio/codimd

### ISSUE THREAD

**Issue by dvob** [hedgedoc/hedgedoc#313]
The Kubernetes installation documentation (docs/setup/kubernetes.md) points to the Helm chart stable/hackmd which uses the Docker image hackmdio/hackmd, which in turn is based on hackmdio/codimd.
I think it would be best to remove that documentation until there is a new chart for codimd/server?

**Comment by SISheogorath** [comment]
I would actually love to see a new chart appearing, maybe based on the one linked, but also maybe not in the official helm repository, because I had to notice that upgrades to the official repository are rather slow.

**Comment by dsbrng25b** [comment]
The official helm stable and incubator repository will soon be depracted either way.
The new way is to host your own chart repository (e.g. on github pages / releases). Then you can add your repository to https://github.com/helm/hub that you get listed on https://hub.helm.sh/

**Comment by SISheogorath** [comment]
Would you like to get involved with this? It sounds like you are enough into K8s to develop the chart and I'm sure there would be other members in the community willing to help. I'm explicitly thinking of @unteem :wink:

**Comment by dsbrng25b** [comment]
Yes, I can help with this. I think we need to decided the following things:
* **Git Repository**: In which repository do we want to have the helm chart source
* **Helm Repository**: We need a HTTP server to host the index.yaml and the versioned charts.
  * Option 1: Use Github Pages. This would result in a repository named https://codimd.github.io/<repo> or you could use a CNAME like helm.codimd.org. You can see an example on https://github.com/dsbrng25b/charts. In that case the index.yaml is created in the gh-pages branch and the versioned charts are uploaded as releases.
  * Any other HTTP server, depending on what kind of infrastructure you have

The chart itself will be pretty simple I think. We could either reuse the old one from stable/hackmd or maybe even better recreate it from scratch with `helm create` to have the newest best practices from helm in the chart.

**Comment by SISheogorath** [comment]
@dsbrng25b I created a bare-bones repository which we can make available at helm.codimd.org later.

I invited you to have the right to work in this and if you need anything, feel free to reach out :)

Looking forward to your work!

**Comment by unteem** [comment]
Sorry just catching up on this issue now...

On our side we do not use helm anymore, the chart we used was pretty much the same that the original one in `helm/stable`. For now we just use kustomize. But I'm currently developing kubernetes operators for rocketchat and nextcloud, codimd is the next one on the list ;). I'll let you know when I'm done, should be in the next couple of weeks.

@dsbrng25b if you come up with a chart I can review it (well I don't know anything about helm v3)

**Comment by davidmehren** [comment]
Our docs now link to a community-contributed Helm Chart at https://artifacthub.io/packages/helm/nicholaswilde/hedgedoc.

I think that solves the problem for now?
