### ISSUE TITLE
Color password field red on weak password.

### ISSUE THREAD

**Issue by DerMolly** [hedgedoc/hedgedoc#3163]
### Description

The password input field does not become "green" for weak passwords.

### Steps to reproduce

1. open /register
2. enter a weak password e.g. `1234`

![image](https://user-images.githubusercontent.com/3978662/212494290-751368b0-a770-4b99-b9d1-cd33fcebeade.png)

### Expected behaviour

The password fields should be red.

### Your Setup

Current local dev environment

**Comment by Avi98** [comment]
Can i pick this up

**Comment by DerMolly** [comment]
Yeah of course, @Avi98. I'll assign you.
