### ISSUE TITLE
No functional content due to CSP violation

### ISSUE THREAD

**Issue by leofah** [hedgedoc/hedgedoc#3179]
### Description

After upgrading to hedgedoc 1.9.6 from 1.7.2 documents content did not load. Once the csp was disabled in the config or the 'unsafe-eval' option was manually added the documents loaded correctly

### Steps to reproduce

1. Use the latest version 1.9.6 from hedgedoc
2. Use the recommended csp config:  
```
        "csp": {
            "enable": true,
            "directives": {
            },
            "upgradeInsecureRequests": "auto",
            "addDefaults": true,
            "addDisqus": false,
            "addGoogleAnalytics": false
        },
```
3. When opening a document no content is shown and the javascript console shows following error:
```
[Script Loader] EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src https://gist.github.com/ https://vimeo.com/api/oembed.json https://www.slideshare.net/api/oembed/2 'unsafe-inline' 'nonce-2f9bac5f-7592-4bdf-8e3d-264ba01e6784' 'sha256-81acLZNZISnyGYZrSuoYhpzwDTTxi7vC1YM4uNxqWaM='".

    at eval (<anonymous>)
    at e.exports (index-pack.dcc3858b9bbc1e65a8f3.js:formatted:7088:177)
    at Object.<anonymous> (index-pack.dcc3858b9bbc1e65a8f3.js:formatted:250933:11)
    at n (index-pack.dcc3858b9bbc1e65a8f3.js:formatted:11:21)
    at Object.<anonymous> (index-pack.dcc3858b9bbc1e65a8f3.js:formatted:256619:5)
    at n (index-pack.dcc3858b9bbc1e65a8f3.js:formatted:11:21)
    at index-pack.dcc3858b9bbc1e65a8f3.js:formatted:71:5
    at index-pack.dcc3858b9bbc1e65a8f3.js:formatted:72:2
```

### Expected behaviour

The content of the document should be shown and the page working correctly

### Config

```
        "csp": {
            "enable": true,
            "directives": {
            },
            "upgradeInsecureRequests": "auto",
            "addDefaults": true,
            "addDisqus": false,
            "addGoogleAnalytics": false
        },
```

### Your Setup

- Host OS: Debian Bullseye
- NodeJS version: v16.19.0
- HedgeDoc version: 1.9.6

### Additional context

Pull request #1369 removed the `unsafe-eval` from the default csp config.

But we had to add the following directive to include the unsafe-eval and get hedgedoc running again.
```
"directives": {
        "scriptSrc": ["'unsafe-eval'"]
 },
```

The eval which failed seems to be from the [script-loader](https://github.com/webpack-contrib/script-loader/blob/master/addScript.js#L24). According to #923 `script-loader` was replaced by `raw-loader`, so maybe some dependency pulls it in?

**Comment by DerMolly** [comment]
Hello @leofah,

I have a few questions:
- Did you read the changelogs between 1.7.2 and 1.9.2?
- It seems to be you run HedgeDoc manually and not in Docker (possibly even by just pulling the master branch from GitHub). Did you build the frontend again after the update?

**Comment by leofah** [comment]
Hi @DerMolly ,

I used git as installation and checked the release 1.9.6 out. Now i ran `yarn build` and `yarn install` and it is working without the extra csp setting.

I miss understood step 6 in the upgrade path and were thinking after version 1.7.0 the build can be ignored, regardless of tarball or git installation.

Thanks for the quick reply and detecting the issue immediately.
