### ISSUE TITLE
LDAP auth without bind (anonymous)

### ISSUE THREAD

**Issue by marscher** [hedgedoc/hedgedoc#3218]
### Which part of the project should be enhanced?

auth-ldap

### Is your enhancement request related to a problem? Please describe.

Currently it seems that an admin binding to the LDAP server is a hard requirement, although the underlying ldap library supports anonymous queries.

xrefs: 
- https://github.com/vesse/node-ldapauth-fork/issues/58
- https://github.com/vesse/node-ldapauth-fork/issues/32
- https://github.com/vesse/node-ldapauth-fork/issues/27

### Describe the solution you'd like

Allow anonymous LDAP queries (without binding).

### Describe alternatives you've considered

not using LDAP at all.

### Additional context

Stack trace of authentication request without a binding password
``` 
OperationsError: 000004DC: LdapErr: DSID-0C090A5C, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v4563
    at messageCallback (/hedgedoc/node_modules/ldapjs/lib/client/client.js:1220:45)
    at Parser.onMessage (/hedgedoc/node_modules/ldapjs/lib/client/client.js:888:14)
    at Parser.emit (node:events:513:28)
    at Parser.write (/hedgedoc/node_modules/ldapjs/lib/messages/parser.js:107:8)
    at Socket.onData (/hedgedoc/node_modules/ldapjs/lib/client/client.js:875:22)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by mherrb** [comment]
Hi,

Anonymous LDAP bind works here. We're using environment variables to configure it like that :

```
CMD_LDAP_URL=ldaps://ldap.example.com/
CMD_LDAP_SEARCHBASE=ou=users,dc=example,dc=com
CMD_LDAP_SEARCHFILTER='(&(objectClass=posixAccount)(uid={{username}}))'
CMD_LDAP_SEARCHATTRIBUTES='uid,mail'
CMD_LDAP_USERIDFIELD=uidNumber
CMD_LDAP_USERNAMEFIELD=cn
CMD_LDAP_PROVIDERNAME=example.com
```
(I only replaced our domain with example.com)

**Comment by ErikMichelson** [comment]
Hey @marscher,

does it work when using a configuration similar to the one shared by @mherrb above?
Remember to be sure to have your LDAP server configured properly.

As HedgeDoc supports anonymous binding, I'm closing this issue. In case there is a problem with the LDAP binding that is HedgeDoc's fault, feel free to reopen this issue.

**Comment by marscher** [comment]
Thanks! I will try this.

**Comment by marscher** [comment]
I just tried what @mherrb suggested, adopted to my domain, but still receive "OperationsError: 000004DC: LdapErr: DSID-0C090A5E, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v4563". 

Eventually the used query pattern is not allowed for anonymous on this particular LDAP server.
