### ISSUE TITLE
Invalid tokens should cause 401 instead of 500 error code

### ISSUE THREAD

**Issue by SuperSandro2000** [hedgedoc/hedgedoc#323]
I just logged into https://demo.codimd.org/ via GitHub and created a new account and was presented with a ``Internal Server Error``. The time of trying was arround 16:22 German time.

**Comment by SISheogorath** [comment]
Seems like a problem from GitHub or our dependency:

```
codimd_1    | TokenError: The code passed is incorrect or expired.
codimd_1    |     at Strategy.OAuth2Strategy.parseErrorResponse (/codimd/node_modules/passport-oauth2/lib/strategy.js:358:12)
codimd_1    |     at Strategy.OAuth2Strategy._createOAuthError (/codimd/node_modules/passport-oauth2/lib/strategy.js:405:16)
codimd_1    |     at /codimd/node_modules/passport-oauth2/lib/strategy.js:175:45
codimd_1    |     at /codimd/node_modules/passport-github/lib/strategy.js:77:16
codimd_1    |     at /codimd/node_modules/oauth/lib/oauth2.js:209:7
codimd_1    |     at passBackControl (/codimd/node_modules/oauth/lib/oauth2.js:134:9)
codimd_1    |     at IncomingMessage.<anonymous> (/codimd/node_modules/oauth/lib/oauth2.js:157:7)
codimd_1    |     at IncomingMessage.emit (events.js:323:22)
codimd_1    |     at endReadableNT (_stream_readable.js:1204:12)
codimd_1    |     at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

When the token was not valid 500 was an acceptable response.

**Comment by SISheogorath** [comment]
Let's fix the issue description and reopen:

The server should return a 401 on an invalid token, not a 500 HTTP status code.

**Comment by DerMolly** [comment]
I just had a look at this https://github.com/hedgedoc/hedgedoc/blob/master/lib/web/auth/github/index.js and it seems we currently don't do any error handling ourselves, but rather let the passport strategy handle the error case. But maybe I'm just missing something?
