### ISSUE TITLE
css blocked

### ISSUE THREAD

**Issue by Czile-create** [hedgedoc/hedgedoc#3249]
### Description

I deploy the hedgedoc via latest docker image (linuxserver/hedgedoc:latest) and visit localhost:3000, the page shows only text, no format

### Steps to reproduce

1. Deploy hedgedoc via latest docker image
2. Visit localhost:3000

### Expected behaviour

![image](https://user-images.githubusercontent.com/59221621/215489437-142edc52-00fc-4487-a29f-0a5dad2171c4.png)
The pages show no format and css is blocked.
The network report is as follows:
![image](https://user-images.githubusercontent.com/59221621/215489653-abd8dcc4-ef57-4162-9cd3-5e648d3b02fd.png)

### Logs

```shell
Refused to load the stylesheet '<URL>' because it violates the following Content Security Policy directive: "style-src /build/ /css/ 'unsafe-inline' <URL>". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.

6Refused to load the script '<URL>' because it violates the following Content Security Policy directive: "script-src 'unsafe-eval' /build/ /js/ /config <URL> <URL> <URL> 'unsafe-inline' 'nonce-699a5b67-a2f9-4b4d-b2e4-e67cd2e902ea' 'sha256-81acLZNZISnyGYZrSuoYhpzwDTTxi7vC1YM4uNxqWaM='". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

### Config

```shell
CMD_ALLOW_ANONYMOUS_EDITS=true

CMD_URL_ADDPORT=true
```

### Your Setup

QNAP 5.0

**Comment by Czile-create** [comment]
Thanks for your reply.

I've tried all the config combination in this [page](https://docs.hedgedoc.org/faq/#why-does-my-interface-look-weird), but it didn't work. I used reverse proxy to access hedgedoc, and I enter `http://domain.com:3001` ->(reverse proxy)-> `localhost:3000` to visit hedgedoc, which is a docker with ip config 3000:3000. 

However, I noticed that some css are parsed into domain.com:3001, and some are domain.com:3000. But I don't know its meaning.


Before I deployed this image, I used linuxserver/codimd and it worked with default configuration, but it cannot upload image. I knowed this is because I didn't set `domain`. But hedgedoc seems cannot use most of its functions with default configuration.

All that I've tried is:

|env|val|
|-|-|
CMD_DOMAIN| domain.com
CMD_URL_ADDPORT |true/false
CMD_PROTOCOL_USESSL| false
CMD_PORT |3001/3000

**Comment by penCsharpener** [comment]
I'm having the same issue. I use NPM with hedgedoc.domain.com forwarded to <ip>:7744.
Docker-compose.yml has port mapping 7744:3000. I'm using a wildcard certificate which works for all my other sub domains.
I've set 
```
CMD_DOMAIN=hedgedoc.domain.com
CMD_PROTOCOL_USESSL=true
CMD_URL_ADDPORT=false
NODE_ENV=production
CMD_ALLOW_ANONYMOUS=false
CMD_ALLOW_ANONYMOUS_EDITS=true
CMD_DEFAULT_PERMISSION=private
CMD_ALLOW_EMAIL_REGISTER=false
CMD_ALLOW_GRAVATAR=false
```

DNS is set correctly analoguous to my other services
I can't access https://hedgedoc.domain.com at all but <ip>:7744 works without any css. In the console it says

```
Content-Security-Policy: The page’s settings blocked a style (style-src-elem) at http://<ip>:7744/build/font-pack.6f3ecd0bf31c428a95f7.css from being applied because it violates the following directive: “style-src https://hedgedoc.domain.com/build/ https://hedgedoc.domain.com/css/ 'unsafe-inline' https://github.githubassets.com/”
```

**Comment by penCsharpener** [comment]
Now I got it working but it was weird but I tinkered around with the env vars and even though I had this set before now it started working. These are my settings:

```
    environment:
...
      - CMD_PROTOCOL_USESSL=true
      - CMD_URL_ADDPORT=false
      - CMD_HSTS_ENABLE=true
      - NODE_ENV=production
...
    ports:
      - "7744:3000"
```
