### ISSUE TITLE
Impossible to change username selected automatically with email address?

### ISSUE THREAD

**Issue by Neustradamus** [hedgedoc/hedgedoc#3261]
### Description

Impossible to change username selected automatically with e-mail address?

### Steps to reproduce

1/ Create an account with your e-mail address, example: thisisanexample@example.tld and a password
2/ Log-in
3/ You are now connect, the username is thisisanexample, and there are only possibilities to:
- Features
- Export user data
- Delete user
- Sign Out

Impossible to change the username.

Thanks in advance.

### Expected behaviour

Edit username selected by default "The part of email address before @".

### Your Setup

Open service.

**Comment by DerMolly** [comment]
This is not in HedgeDoc 1. We'll have this functionality in HedgeDoc 2.0, which is not yet release.

See also: https://github.com/hedgedoc/hedgedoc/issues/1216

**Comment by Neustradamus** [comment]
@DerMolly: When 2.0 will be released?

**Comment by Neustradamus** [comment]
@DerMolly: Any news on it?
