### ISSUE TITLE
Parse bool config env value case-insensitive

### ISSUE THREAD

**Issue by 6543** [hedgedoc/hedgedoc#3422]
### Description

`CMD_PROTOCOL_USESSL=True` will be interpreted as false

### Steps to reproduce

just use `True` instead of `true`

some frameworks like ansible can cause such conversions ... :/

### Expected behaviour

parse it as true ... tldr: make it case-insensitive so TrUe = true too

### Config

HedgeDoc **1.9.7**

### Your Setup

not needed

**Comment by mrdrogdrog** [comment]
Fixed in https://github.com/hedgedoc/hedgedoc/pull/3424
