### ISSUE TITLE
a Grafana dashboard to monitor HedgeDoc

### ISSUE THREAD

**Issue by oupala** [hedgedoc/hedgedoc#3423]
### Is your feature request related to a problem? Please describe.

When operating a HedgeDoc instance, I need to understand how is my instance working: how much users, how much notes, how many users online, how many notes currrently edited, how much memory and cpu used, how much latency for the eventloop, how often does the garbage collector is launched...

### Describe the solution you'd like

I propose to use a grafana dashboard in order to get a general overview of the HedgeDoc instance health status.

### Describe alternatives you've considered

Using the `/metrics` and the `/status` endpoints, but these are raw text file and does not offer history of metrics.

**Comment by oupala** [comment]
I do propose a dashboard based on another dashboard that has been shared by [tarlety](https://grafana.com/orgs/tarlety) in May 2020 on [Grafana website](https://grafana.com/grafana/dashboards/12214-codimd-dashboard/).

The subject has been discussed in some CodiMD issues and merge requests, such as hackmdio/codimd#1466 and hackmdio/codimd#1507.

As the dashboard was designed to run on Grafana 6.x.x, we converted it to Grafana 8.x.x.

You can download it here : [hedgedoc-v1.json](https://github.com/hedgedoc/hedgedoc/files/10870126/hedgedoc-v1.json.txt) (rename the text file to json).

I don't know how and where this dashboard should be included in the repository, this is why I am opening and issue rather than a pull request. But feel free to take this dashboard and let it go in the best place.

I don't know if this dashboard will be able to run along an instance of HedgeDoc v2.

**Comment by mrdrogdrog** [comment]
I don't understand what you want to achieve with this issue. This issue tracker is for bugs or feature requests in the software itself. How does a grafana dashboard fit into this?

**Comment by oupala** [comment]
A grafana dashboard exclusively designed for HedgeDoc might be something interesting to embed into HedgeDoc.

I just want to share the work I've done on this dashboard as it is helping me much, and other HedgeDoc admin might be interested in using it.

If it is not the right place to share contributions, how should I have shared it?

**Comment by ErikMichelson** [comment]
When being added to the repository, we need to take care to not break it with some changes either by Grafana or by us.

Maybe a better place to share your Grafana dashboard is the [community forum](https://community.hedgedoc.org).

**Comment by mrdrogdrog** [comment]
You could put it into your own git repository or post it in the discourse (or post the link to the repository in a discourse thread).

You could also create a pull request that extends our docs by a page that point to the dashboard file
