### ISSUE TITLE
Ensure that 2.0 docs are up-to-date and properly structured

### ISSUE THREAD

**Issue by davidmehren** [hedgedoc/hedgedoc#3493]
### Which part of the project should be enhanced?

documentation

### Describe the solution you'd like

We need to check that the docs reflect the current state of 2.0 development and restructure them. `2.0.md` should be split up and removed.

### Describe alternatives you've considered

Have wrong/incomplete/confusing docs

**Comment by DerMolly** [comment]
I think this issue can be closed as the main goal of this was achieved and still missing things are tracked in #4830
