### ISSUE TITLE
NestJS Gateway use redis as backend 

### ISSUE THREAD

**Issue by ahkui** [hedgedoc/hedgedoc#3504]
### Is your feature request related to a problem? Please describe.

Just need HA feature

### Describe the solution you'd like

follow `RedisIoAdapter` from https://docs.nestjs.com/websockets/adapter#extend-socketio

can config `WsAdapter` or `RedisIoAdapter` from env

### Describe alternatives you've considered

N/A

**Comment by davidmehren** [comment]
We do not plan to implement high availability in HedgeDoc 2 at this time.
