### ISSUE TITLE
Allow disabling (soft) line wrap

### ISSUE THREAD

**Issue by n-st** [hedgedoc/hedgedoc#3506]
### Is your feature request related to a problem? Please describe.

Currently, HedgeDoc 1.x and 2.x both default to wrapping long lines in the editor.
This makes working with monospace-aligned text (and Markdown tables) very tedious.

### Describe the solution you'd like

The editor should have a checkbox (for example in the bottom right where the Sublime/Emacs/Vim mode switch is in HedgeDoc 1.x) to enable/disable line wrapping in the editor view.

Optionally (but preferably), the setting's value should be persisted in a browser cookie, and in the user settings if a user is logged in.

### Describe alternatives you've considered

Well, uhm… Buy a wider screen, or get better eyes and decrease the page zoom level?

It's also possible to add a CSS attribute `pre.CodeMirror-line { white-space: pre !important; }` through the browser's developer tools to disable wrapping (overriding the default `white-space: pre-wrap`), but that of course needs to be manually repeated on every page reload.

**Comment by mrdrogdrog** [comment]
Hello,

We can definitely do this for HedgeDoc 2. The editor settings are always saved in the browser's local storage anyway.

Hedgedoc 1 won't receive such an update by us. As you can see in the Readme, we concentrate on the development of HedgeDoc 2 and won't add new features to the HD1 code base.

**Comment by KaKi87** [comment]
Hello,
If not at https://demo.hedgedoc.org/, where is this feature available ?
Thanks

**Comment by ErikMichelson** [comment]
The demo instance at demo.hedgedoc.org runs the latest stable release, which is currently 1.9.9.
This feature was implemented in the 2.0 version, which is not yet released as a stable version.
You can test the latest nightly 2.0 build at https://hedgedoc.dev
