### ISSUE TITLE
New Pads aren't added to Dashboard (2.x)

### ISSUE THREAD

**Issue by xf-** [hedgedoc/hedgedoc#351]
1. Create a new pad
2. Go back to dashboard
3. Look or/and search for new pads name

version
d3aa0406262fffa82f99eec1d17a5b1cbabab292

**Comment by davidmehren** [comment]
Thanks for testing the very in-development 2.0 branch! :smiley: 
I just tried the steps you outlined and the newly created note correctly appears in the history. Could you try again if this still happens and if it does provide some details about your environment (Node version, OS, browser)?

**Comment by xf-** [comment]
I will try it again in next days.
- node 13 or 14 (currently it is 14 on the server)
- Firefox nightly - got no js error in console

**Comment by DerMolly** [comment]
I think this can safely be closed…
