### ISSUE TITLE
easy copy-to-clipboard button for code blocks

### ISSUE THREAD

**Issue by lachnerd** [hedgedoc/hedgedoc#3549]
### Describe the solution you'd like

I'd like the ability to add a button "copy to clipboard" to all code blocks -  so that someone is able to copy complete code blocks to clipboard with the push of a button

### Describe alternatives you've considered

mark code and copy it manually

**Comment by mrdrogdrog** [comment]
Hello,

Such a feature is already present in HedgeDoc 2.
As you can read in our [README](https://github.com/hedgedoc/hedgedoc#state-of-the-project), we're focusing on the development of HedgeDoc 2 and won't fix any non-critical bug in or add new features to HedgeDoc 1.
Therefore we won't fix this issue in HedgeDoc 1.
