### ISSUE TITLE
Basic print support

### ISSUE THREAD

**Issue by mrdrogdrog** [hedgedoc/hedgedoc#3551]
### Is your feature request related to a problem? Please describe.

Right now its not possible to use the browser's print function with HedgeDoc 2 because the browser always wants to print the entire page, include editor. But we only want to print the iframe content.

### Describe the solution you'd like

When the browser wants to create the print version then use only the iframe content.
It would be nice if we can redirect the entire request to the iframe to keep features like page wrapping.

### Describe alternatives you've considered

Dont use the browser print function but create a PDF with another service like https://gotenberg.dev/ and tell the user to print this instead.

**Comment by ErikMichelson** [comment]
For this we could use the [`beforePrint`](https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeprint_event) and [`afterprint`](https://developer.mozilla.org/en-US/docs/Web/API/Window/afterprint_event) events and maybe do some magic to return the print version and restore the original version afterwards.

**Comment by mrdrogdrog** [comment]
Not exactly what I want. I don't want to print the editor page. I would like to redirect the request into the iframe.

**Comment by seredenkodenis** [comment]
Good afternoon! 
Can we help with the development of this feature? We are a group of students and would like to help a little with the development of the project. 

Maybe we can implement the function of export to pdf in the tab on the screenshot. Your idea about pdf generation with Gotenberg seems like an interesting solution and we would like to implement it.

![Screenshot](https://user-images.githubusercontent.com/35814526/231704966-fa5a761e-5ac3-478f-b79c-9263a5e8aa84.jpg)

**Comment by DerMolly** [comment]
Some progress was made in [5857](https://github.com/hedgedoc/hedgedoc/pull/5857)

But these issues are still present:
- [ ] link anchor icon on headings
- [ ] TOC (on the side)
- [ ] "copy code block"-buttons
- [ ] background of code blocks only with print backgrounds 
- [ ] sometimes page breaks look weird in Firefox
- [ ] YouTube / Vimeo remove text "Click to load content from x"
- [ ] All Link replacements should still have the link
- [ ] Diagrams need investigation
- [ ] Horizontal rules only work with print backgrounds
- [ ] Deleted Text is not strike through (Firefox)
- [ ] Marked text works only with print backgrounds

Also we currently can't really handle ctrl+p (or cmd+p) and need to display a warning to use the print button in our dialog, which is fine I guess, but it would be better if we could also handle the normal was of doing things.
