### ISSUE TITLE
Don't delete realtime-notes immediately after the last user left

### ISSUE THREAD

**Issue by mrdrogdrog** [hedgedoc/hedgedoc#3608]
### Which part of the project should be enhanced?

Backend realtime code

### Is your enhancement request related to a problem? Please describe.

If a user just refreshs the page and is the last user on a note then the backend creates a new revision and writes it to the database and immediately loads it again. This is a bit overhead.

### Describe the solution you'd like

Add a timer that waits a few seconds before the realtime note gets deleted.

### Describe alternatives you've considered

Accept the overhead.

### Additional context

Keep in mind that on application shutdown the revision must be created in any case!

**Comment by ErikMichelson** [comment]
Has been implemented thanks to @yamashush

**Comment by yamashush** [comment]
@ErikMichelson I appreciate it too. Thank you for fixing and merging the code.

**Comment by ErikMichelson** [comment]
You're welcome and thanks for your contributions too!
