### ISSUE TITLE
FuzzySearch in CheatSheet

### ISSUE THREAD

**Issue by DerMolly** [hedgedoc/hedgedoc#3656]
### Which part of the project should be enhanced?

CheatSheet

### Is your enhancement request related to a problem? Please describe.

The CheatSheet has many options and the number of features will most likely only increase. This makes it hard for the user to find what they search for.

### Describe the solution you'd like

Implement a fuzzy search for the CheatSheet. It should include the name, description and probably the example code?

A possible implementation we could use is https://github.com/nextapps-de/flexsearch

### Describe alternatives you've considered

Let the user search themselves.

**Comment by GGH-WeyboZetO** [comment]
Where is the cheatsheet codes implemented in the code? And the sub-boxes?
Thank you.

**Comment by mrdrogdrog** [comment]
The component that renders the cheatsheet dialog content can be found in `frontend/src/components/editor-page/app-bar/cheatsheet/cheatsheet-content.tsx`
