### ISSUE TITLE
DocumentInfo is not updated

### ISSUE THREAD

**Issue by DerMolly** [hedgedoc/hedgedoc#3657]
### Description

DocumentInfo is not updated excpet for page load

### Steps to reproduce

1. Go to any HegdeDoc 2 note. (Possibly create one)
2. Wait for a few minutes.
3. Write something in the note.
4. Open the DocumentInfo

### Expected behaviour

The Information should be up to date, when the document info is opened or at the very least be updated on opening the note.

**Comment by ErikMichelson** [comment]
We thought about the following:
- we remove the lastEditedBy field (as there can be multiple authors and this would be nonsense)
	- if we really would want this, this needs to be coupled to the last realtime update
- we repalce the lastEditedAt field with a lastRevisionSavedAt field
	- the backend needs to tell the frontend about revision saves in the websocket

**Comment by mrdrogdrog** [comment]
Partly fixed by https://github.com/hedgedoc/hedgedoc/pull/5055
except for the realtime message.
I suggest that we close this issue with the merge and create a new issue for the websocket part.
