### ISSUE TITLE
Subpaths of non-existing pads in FreeURL-mode should yield a 404

### ISSUE THREAD

**Issue by Gittenburg** [hedgedoc/hedgedoc#370]
version: 1.6.0

* `/doesnotexist/download` redirects to `/doesnotexist`, creating the pad
* `/doesnotexist/pdf` redirects to `/doesnotexist`, creating the pad
* `/doesnotexist/publish` redirects to `/doesnotexist`, creating the pad
* `/doesnotexist/slide` redirects to `/doesnotexist`, creating the pad
* `/doesnotexist/info` redirects to `/doesnotexist`, creating the pad
* `/doesnotexist/revision` redirects to `/doesnotexist`, creating the pad

You would expect a subpath on a non-existent resource to yield a 404. This would also be useful because it allows you to check if a pad exists, without creating it if it doesn't (which would be handy if you want to import content, if it does not yet exist as `POST /new/example` happily overwrites existing pads).

**Comment by ErikMichelson** [comment]
A fix for this was merged with #926
