### ISSUE TITLE
Configurable note revision clean-up

### ISSUE THREAD

**Issue by ErikMichelson** [hedgedoc/hedgedoc#3727]
### Is your feature request related to a problem? Please describe.

Huge instances with many notes and many users tend to create a huge amount of data with note revisions. One can delete them manually via the UI or the API, however this is a tedious task.

### Describe the solution you'd like

A new config option `HD_REVISION_RETENTION_DAYS` that sets the number of days a revision should be kept. A regular nest cronjob will clean all note revisions that are due for deletion.
If the config option is not set or set to `0`, all revisions will be kept forever.

### Describe alternatives you've considered

Include a CLI tool for the admin to clean-up old note revisions/the database.

**Comment by yamashush** [comment]
> Huge instances with many notes and many users tend to create a huge amount of data with note revisions.

I totally get it.
I have been operating hackmd & codimd for over 5 years.
I have experienced that the system's response has become very slow due to huge revision.
