### ISSUE TITLE
Adding a bullet list to a colored citation make a tag icon appear

### ISSUE THREAD

**Issue by yazae** [hedgedoc/hedgedoc#3734]
### Description

Adding a bullet list to a colored citation make a tag icon appear.

### Steps to reproduce

When I try to use a citation who contains a bullet list, and that citation is colored with `[color=anyColor]`, a tag icon appear under the citation, colored with the color of the citation.

Here is the md code :

```md
> Citation with color
> [name=invader][color=purple]

> Citation
> - With bullets without color
> [name=invader]

> Citation
> - With bullets (with a `[color]` added)
> [name=invader][color=purple]
```

And it render as such in HedgeDoc :

![image](https://user-images.githubusercontent.com/88883564/230173206-388296ad-4c45-488c-bf41-3c9efed00012.png)

**Workaround**

As pointed by Tilman on the matrix channel, there is a notation who don’t make the icon tag appear :

```
> Citation
> - With bullets (with a `[color]` added)
> [name=invader]
> 
> [color=purple]
```

### Expected behaviour

The icon tag shouldn’t appear, it doesn’t mean anything, and it doesn’t make sense that it appear only on citation with bullets.

### Your Setup

- Host OS: idk
- NodeJS version: idk
- HedgeDoc version: 1.8.2 (but it is the same at http://demo.hedgedoc.org/ and even in hd2 apparently)

### Additional context

It’s an amazing project, many thanks to it’s mainteners o/

**Comment by ErikMichelson** [comment]
I remember stumbling upon this weird tag icon when I re-implemented this feature for 2.0 (https://github.com/hedgedoc/react-client/pull/249#issuecomment-647626674)

Revisiting this now, I see no real use-case in this and would vote to drop it, therefore making the `[color=...]` syntax only a modifier for a blockquote.

**Comment by DerMolly** [comment]
Hm, the color tags can be used to create legends (red is for $A, blue is for $B) etc. So I think we may want to keep this around.

**Comment by ErikMichelson** [comment]
To avoid more syntax that is incompatible with other markdown parsers, I would rather encourage the use of the specific [unicode "circles" for this](https://stackoverflow.com/a/70616224).

**Comment by yazae** [comment]
> Hm, the color tags can be used to create legends (red is for $A, blue is for $B) etc. So I think we may want to keep this around.

Well, for now it's impossible to know what it's for, and it's inconsistent with the normal blockquote, so it needs work before considering it a feature I think 🤔 
(what would be the usage ? several persons as authors of the same blockquote ? some color for each person and this tag close to each ? Wich color would be used for the entire block then ?)

**Comment by mrdrogdrog** [comment]
Tbh I don't get it as well. I would remove them and encourage users to use the emojis.
