### ISSUE TITLE
[2.0] Selecting via CTRL-A when having no write permissions

### ISSUE THREAD

**Issue by ErikMichelson** [hedgedoc/hedgedoc#3754]
### Description

When visiting a note for which you do not have write permissions, you can select text with your mouse cursor, but cannot press CTRL-A to select all text.

### Steps to reproduce

1. Visit a HedgeDoc 2 note for which you do not have write-permissions (but read permission)
2. Try selecting text in the codemirror with your mouse. This works.
3. Press CTRL-A. Everything will be selected except the codemirror content.

### Expected behaviour

After selecting text in the codemirror with your mouse, the focus should be inside the codemirror. Therefore pressing CTRL-A should select all text in the codemirror.

### Your Setup

- HedgeDoc version: 2.0.0-dev (b615ef49a321266dad5401e1c9d25b37854d34ad)
- Linux, Chrome 111.0

**Comment by Avi98** [comment]
@ErikMichelson  can i pick this up. I think we can achieve the expected behaviour by changing this
```js

editable={updateViewContextExtension !== null && isSynced && mayEdit}

```

this to
```js
readOnly={!(updateViewContextExtension !== null && isSynced && mayEdit)}
```

**Comment by ErikMichelson** [comment]
Sounds like a possible solution. If you want feel free to test around and create a PR.
Please ensure that especially the mayEdit and the isSynced properties are still working as expected.

Thanks!

**Comment by Avi98** [comment]
@mrdrogdrog  @ErikMichelson I think the solution is not perfect. The following issue is resolved,

> Press CTRL-A. Everything will be selected except the codemirror content.

But, the cursor position is not proper. Will try to debug this issue and raise a PR with a proper fix 

https://github.com/hedgedoc/hedgedoc/assets/26133749/f59ab083-e915-4e9c-a1be-b4f6dd31b9f5

**Comment by mrdrogdrog** [comment]
This is intended behaviour. At least according to 

2fc89a7de5d3606cb5dcb2dc8acdf299965a98cc

https://github.com/hedgedoc/hedgedoc/blob/develop/frontend/src/components/editor-page/editor-pane/codemirror-extensions/remote-cursors/send-cursor-view-plugin.ts#L20
