### ISSUE TITLE
Sun icon not showing 

### ISSUE THREAD

**Issue by ericgaspar** [hedgedoc/hedgedoc#378]
Toggled between night and day is working but only the moon icon is showing in both case. (v1.6)

**Comment by ericgaspar** [comment]
I don't know if the patch was pushed for version 1.7.1... but i still only have the moon icon displayed when switching between day and night.

**Comment by davidmehren** [comment]
The fix was merged into the frontend for 2.0. So you unfortunately have to wait a bit to actually see the result :smiley:
