### ISSUE TITLE
[RFC] Remove HTTPS-server in 2.0

### ISSUE THREAD

**Issue by davidmehren** [hedgedoc/hedgedoc#382]
Currently, we directly support serving CodiMD over HTTPS using the `https` module. I am proposing to remove this feature in 2.0 and delegating TLS-termination to a reverse proxy.

This has the following advantages:
- simplifying the configuration
- simplifying our code
- better separation of concerns: we can focus on application stuff, reverse-proxies are probably better at TLS-termination
- security: depending on the NodeJS version, older and potentially less secure ciphers are supported and new ciphers aren't (Node 10 does not support TLS 1.3 but supports the deprecated TLS 1.0/1.1 per default)
- security: to bind to ports 80 or 443 node needs to run as root, which is something we should strongly discourage

Disadvantages I can come up with:
- This would break existing setups that use this feature and users would have to switch to a reverse-proxy. We can alleviate the pain this causes by providing example configs for common reverse proxies like nginx, Apache and Caddy.
- It makes it a bit more complicated to setup CodiMD in a production environment when you don't already have a web server/reverse proxy.

**Comment by davidmehren** [comment]
Another thing that just came to my mind: If you would want to deploy CodiMD with LetsEncrypt currently, you would have to setup a LE-client and come up with some way to restart CodiMD when the certificates changed after a renewal. Recommending Caddy, which does all the certificate-stuff automagically would make that use-case simpler to deploy, wouldn't it?

**Comment by SISheogorath** [comment]
I actually see a use case for this that doesn't need certificates from LE and where this feature is still very useful. Internal networking.

One non-public setups that are still available to the outside world it's not uncommon to have a central reverse proxy. What you do there is having a public facing reverse-proxy that takes care of certificates and use an own CA with own certs to encrypt your internal network traffic. The alternative would be to use a VPN or IPSec which have their own set of problems that especially in backend infrastructure you like to avoid.

Obviously you can instead configure two reverse proxies here, but I think it adds unnecessary complexity to the setup.

And honestly speaking, I don't see what we loose by supporting it. The code for it hasn't need to be touched in a [very long time](https://github.com/codimd/server/blame/master/app.js#L32). It's build into nodejs and just works.

**Comment by davidmehren** [comment]
I would guess these non-public setups are quite a rare use-case. The vast majority of users who don't use a container probably want to use a 'normal', publicly-trusted TLS certificate.

And it's not that we would make an enterprise-setup impossible, as you said one can simply add a reverse-proxy with the desired config. I think someone who is already running an own CA can shoulder that ;)

**Comment by davidmehren** [comment]
I think we can close this now and put on record that we will not support an internal HTTPS server in 2.0.
