### ISSUE TITLE
Release 1.7

### ISSUE THREAD

**Issue by davidmehren** [hedgedoc/hedgedoc#387]
We accumulated a few fixes in `master` which we probably should push out in a patch-release before moving 2.0-development to `master`. To do that we should:

- [x] Bump the version
- [x] Write release notes
- [x] Make sure `yarn.lock` is up to date
- [x] Make sure translations are up to date
- [x] Run the tests described in the release test document (internal)
- [x] anything else?

**Comment by SISheogorath** [comment]
The release test document is not really internal, as there aren't really any internal processes:

https://demo.codimd.org/dGE6iySoScy2qrkHMaBFaQ#

The idea is to have as many people as possible, grabbing a copy of this document, test it against the latest master and once this is done, giving feedback if things were broken.

**Comment by davidmehren** [comment]
Test results for the `cookies_same_site` branch from #389:

- "Creating and working with documents": works! :heavy_check_mark: 
- "Database migrations": I don't have an 1.2 database :cry: 
- Testing `/features` in Firefox 78:
	- UML, MathJax, Codeblocks, TOC and embeddings work :heavy_check_mark: 
	- Still, I got some errors, which seem all to be CORS-stuff with Slideshare:

<details>
<summary>Details</summary>

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://public.slidesharecdn.com/fonts/fontawesome-webfont.woff2?v=4.3.0?cb=1590689192. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

downloadable font: download failed (font-family: "FontAwesome" style:normal weight:400 stretch:100 src index:1): bad URI or cross-site access not allowed source: https://public.slidesharecdn.com/fonts/fontawesome-webfont.woff2?v=4.3.0?cb=1590689192
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at about:blank. (Reason: CORS request not http).

downloadable font: failed to start download (font-family: "MathJax_Blank" style:normal weight:400 stretch:100 src index:0): bad URI or cross-site access not allowed source: about:blank
```

</details>

- YAML Metadata: not tested
- GDPR features: Account deletion works :heavy_check_mark: , but a note that was being edited while the account was deleted still exists :red_circle:

**Comment by oupala** [comment]
I'm not sure if this is the right place to mention a few proposal I mage, but I wanted to improve the documentation about configuration of codimd.

- [my main proposal](https://github.com/codimd/server/issues/364#issuecomment-638936829)
- #348 
- #349 

I had no strong answer on my main proposal, so I don't want to start a merge request that would never be merged. But if you are alright with my proposal, I can start to work on it in the next days.

**Comment by InnayTool** [comment]
Should support for node 14 be added to the release?

**Comment by davidmehren** [comment]
@oupala Actually documentation improvements can be made independently of a release ;)

So if you want to make improvements there, go ahead. :rocket: Maybe you can coordinate with @ErikMichelson for the configuration overview table.

We are not sure yet when 1.6.1 will be released (but hopefully in the next few days). When your improvements are merged to `master` soon enough, they will make it into the release, but if they won't, everyone can still read them here :)

**Comment by davidmehren** [comment]
Regarding the migration test: I just tried that with a 1.6.0 instance and a Postgres DB and can report no issues

**Comment by davidmehren** [comment]
The first release candidate is out!
If nothing bad happens, I plan to release the stable version in about two weeks.
