### ISSUE TITLE
Use default note in freeURL mode

### ISSUE THREAD

**Issue by evanlinde** [hedgedoc/hedgedoc#391]
I noticed in my instance of CodiMD that the default note was not being used to populate new notes created in freeURL mode.

The problem appears to be in the `beforeCreate` hook in [lib/models/note.js](https://github.com/codimd/server/issues/new?permalink=https%3A%2F%2Fgithub.com%2Fcodimd%2Fserver%2Fblob%2F2890022d4d2a8bd04cd6b8895e2e28233dcdd767%2Flib%2Fmodels%2Fnote.js%23L96-L100).

It seems to assume that if a note alias exists, then it should load the content from a file in the docs directory and never have to use the default note. However, new notes created in freeURL mode are initially created with an alias; this is causing them to not be created from the default note.

Here's the current problem code:
```js
            if (!note.alias) {
              filePath = config.defaultNotePath
            } else {
              filePath = path.join(config.docsPath, note.alias + '.md')
            }
```
Here's a suggested change to fix the issue: In cases where the file named with the note's alias doesn't exist in the docs directory, fall back to pulling content from the default note.
```js
            if (note.alias) {
              filePath = path.join(config.docsPath, note.alias + '.md')
            } 
            if (filePath == null || !Note.checkFileExist(filePath)) {
              filePath = config.defaultNotePath
            }
```

**Comment by davidmehren** [comment]
This has been fixed with #798 and will be released with 1.8.
