### ISSUE TITLE
Configure custom CSP rules via ENV

### ISSUE THREAD

**Issue by gianklug** [hedgedoc/hedgedoc#3972]
### Is your feature request related to a problem? Please describe.

We're trying to allow base64 images in our Hedgedoc instance (running in a Docker container on K8s). We'd have to specify something like `csp.directives: [{"img-src": "'self' * data:"}]` to allow the base64 images to render, otherwise CSP triggers and the images aren't displayed. 

I haven't found any ENV variable that can be used to add CSP rules, only the `csp.directives` key in the [config](https://docs.hedgedoc.org/configuration/#web-security-aspects). Am I missing out something?

### Describe the solution you'd like

Have a way of adding custom CSP policies via environment variabkes

### Describe alternatives you've considered

Managing the config file by hand; however this isn't really fun with Docker containers.

**Comment by davidmehren** [comment]
This option is not configurable via environment variables in HedgeDoc 1. I recommend overwriting the header in your reverse proxy.

As per our support policy, we do not accept feature requests for HedgeDoc 1 anymore, so I'm going to close this issue.
