### ISSUE TITLE
When using split editor/viewer ("Both" mode), images aren't properly considered when auto-scroling the viewer pane

### ISSUE THREAD

**Issue by reidprichard** [hedgedoc/hedgedoc#3973]
### Description

When an image is present, clicking/typing in the editor causes the viewer pane to auto-scroll to a position that's too high on the page.

### Steps to reproduce

1. Enter "both" mode (ctrl+alt+B)
2. Type at least a full page of content so that the viewer pane is scrollable.
3. Insert an image.
4. Type more text below the image.

### Expected behaviour

When typing in the editor, the viewer pane should auto-scroll so what you are typing is visible.

### Your Setup

- Host OS: Ubuntu 22.04 (running Hedgedoc in Docker)
- NodeJS version: v16.19.1
- HedgeDoc version: 1.9.7

### Additional context

Here's what it looks like when I paste an image and continue typing.
![image](https://user-images.githubusercontent.com/66481248/236861789-c158aad0-e03d-4e1b-af96-7ac2599124ba.png)

**Comment by ErikMichelson** [comment]
The scrolling system in HedgeDoc 1 has several not ideal effects and this is one of them. Unfortunately, the code base is such a mess that a fix is not trivial. As we're focusing on the development of HedgeDoc 2 currently, we won't fix this problem in HedgeDoc 1.

For HedgeDoc 2, a possible solution would be to make the renderer "follow" your own cursor (see #2881, slightly related #2957).
