### ISSUE TITLE
Browser does not show documents

### ISSUE THREAD

**Issue by chriaack** [hedgedoc/hedgedoc#4060]
### Description

Browser  does not show documents

### Steps to reproduce

1. Open MS Edge Canary 
2. go to your hedgedoc document
3. document gets not loaded (offline mod only) 
    elaborate : the hedgedoc page gets loaded, but the content of the document is empty and not editable

### Expected behavior

Documents is loaded and editable.

### Config

```shell
- name: CMD_DB_URL
  value: <db connection>
- name: CMD_URL_ADDPORT
  value: "false"
- name: CMD_DOMAIN
   value: <my url>
- name: CMD_EMAIL
  value: "false"
- name: CMD_ALLOW_EMAIL_REGISTER
  value: "false"
- name: CMD_GITLAB_SCOPE
  value: api
- name: CMD_GITLAB_BASEURL
  value:  <my url>
- name: CMD_GITLAB_CLIENTID
  value: <my id>
- name: CMD_GITLAB_CLIENTSECRET
  value: <my secret>
- name: CMD_GITLAB_VERSION
  value: v4
- name: CMD_PROTOCOL_USESSL
  value: "true"
- name: CMD_ALLOW_ANONYMOUS
  value: "true"
- name: CMD_ALLOW_ANONYMOUS_EDITS
  value: "true"
- name: CMD_ALLOW_FREEURL
  value: "false"
- name: CMD_SESSION_LIFE
  value: "1209600000"
```

### Your Setup

- Host OS: Debian 11
- NodeJS version:  v16.20.0 (version of the container)
- HedgeDoc version: quay.io/hedgedoc/hedgedoc:1.9.7

### Additional context

Reproduced in following browsers on Windows 10 system:
  Edge InPrivate Window Version 113.0.1774.42 (Official build) (64-bit)
  Chrom Ikognito Window Version 113.0.5672.93 (Official Build) (64-bit)
  Firefox 113.0.1 (64-Bit)

**Comment by mrdrogdrog** [comment]
Can you elaborate "document gets not loaded"?

**Comment by chriaack** [comment]
The page gets loaded, but with no content in it. 

So the hedgedocpage is just white with out content. 
If i swap the browser the content gets loaded an i can adjust the document

**Comment by mrdrogdrog** [comment]
Is the bug reproduceable on demo.hedgedoc.org?
Are the provided configuration option the only you've set?

**Comment by chriaack** [comment]
Found the possible error:

We are using cloudflare as an proxy, it seems like the setup works fine if we do not use the cloudflare as proxy it works fine. 

Thank you for your support much appreciated

**Comment by mrdrogdrog** [comment]
You can use Cloudflare as reverse proxy (the demo does that too). You just have to deactivate the Cloudflare html/js/css minimizer.

https://docs.hedgedoc.org/guides/reverse-proxy/#cloudflare
