### ISSUE TITLE
Unable to paste some "text" into note

### ISSUE THREAD

**Issue by neildeadman** [hedgedoc/hedgedoc#4103]
### Description

I have several notes in an alternative selfhosted note taking app which I am trying to migrate away from because it doens't support folders. I have .md files which I open in Notepad and try and copy the markdown from and into HedgeDoc (selfhosted in docker). When I do this, it pastes the code into the editor, but it does not show in the preview window. It changes me to OFFLINE and doesn't save the change. Refreshing the browser removed the pasted code from editor. I have even tried copying the Features note that came with the installation, but the same happens. On the demo site online, pasting works perfectly. Smaller bits of text are hit and miss.

### Steps to reproduce

1. Browse to http://server-ip:5805
2. Login with email and password
3. Open the Features note editor
4. Select all
5. Create a new note
6. Paste the copied content of the Features note
7. Preview remains empty and I can no longer type in the editor

### Expected behaviour

Expected behaviour is that the Features note appears as a copy of the Features note. I.e. what I paste appears formatted accordingly in the preview.

### Config

```shell
This is my docker-compose:
`version: "3"

services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    hostname: mariadb
    restart: unless-stopped
    volumes:
      - mariadb-config:/config
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=hedgedoc
      - MYSQL_USER=hedgedoc
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
  hedgedoc:
    image: lscr.io/linuxserver/hedgedoc:latest
    container_name: hedgedoc
    hostname: hedgedoc
    depends_on:
      - mariadb
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=hedgedoc
      - DB_PASS=${MYSQL_PASSWORD}
      - DB_NAME=hedgedoc
      - CMD_DOMAIN=${SERVER_IP}
      - CMD_URL_ADDPORT=true #optional
      - CMD_PROTOCOL_USESSL=false #optional
      - CMD_PORT=5805 #optional
    volumes:
      - hedgedoc-config:/config
    ports:
      - 5805:5805
    restart: unless-stopped`
```

### Your Setup

- Host OS: Debian
- NodeJS version: n/a (maybe bundled in docker container)
- HedgeDoc version: 1.97

**Comment by DerMolly** [comment]
By any chance are your notes rather long? Did the same behavior occur with short notes? Because there is a limit how many characters each note can hold (which can be configured) to maintain smooth running of the realtime components of HedgeDoc and I'm not entirely sure how HD1 handles a paste of too many characters…

**Comment by neildeadman** [comment]
I don't think my note would have been too long, but I've seen the same
behaviour for 3 or 4 lines.

If I paste those same lines 1 line at a time it works, but all at the same
time, I see the behaviour I experience.

Since the features note came with the install of expect that to be the
right length, maybe not.

This all works in the online demo perfectly.

**Comment by mrdrogdrog** [comment]
Which browsers did you use?
Did you check the browser's console?
Any errors in the application log (stdout)?
Did you try the official docker image instead of one from linuxserver?

**Comment by neildeadman** [comment]
I'm using Chrome but have tried Firefox and Opera with the same results. All browsers are up-to-date.

The console (this is from Chrome) shows a net::ERR_CONNECTION_RESET and then AUTH failed: Cookie is invalid (which ties in with it showing me as OFFLINE until I refresh the browser) - see attached log.
[1684962587345.log](https://github.com/hedgedoc/hedgedoc/files/11559202/1684962587345.log)

Docker log shows:

`2023-05-24T21:11:48.749Z warn: 	Session secret not set. Using random generated one. Please set `sessionSecret` in your config.json file. All users will be logged out.
2023-05-24T21:11:49.047Z info: 	All migrations performed successfully
2023-05-24T21:11:49.078Z info: 	HTTP Server listening at 0.0.0.0:5805
2023-05-24T21:11:49.268Z info: 	<CLIENT-IP> - - [24/May/2023:21:11:49 +0000] "GET /build/5e95fc008c08d7614b8e57591b7b86e7.woff HTTP/1.1" 200 55504 "http://<SERVER-IP>:5805/build/font-pack.51d576c9ea0a7705d2e0.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"`

I did not try the official docker image. Will do that now.

**Comment by neildeadman** [comment]
OK, worked fine with the official docker image using this [docker-compose.yml](https://github.com/hedgedoc/container/blob/master/docker-compose.yml)

I guess this shouldn't be filled here and should go to LinuxServer, though I am not sure what they can do to resolve.

**Comment by neildeadman** [comment]
Issue is with a 3rd parties docker image
