### ISSUE TITLE
Can't update HD1 dependencies

### ISSUE THREAD

**Issue by davidmehren** [hedgedoc/hedgedoc#4113]
### Description

Yarn 1 seemingly breaks when packages rename their dependencies.

Via `rimraf`, we depend on `@isaacs/cliui`. This package depends on two versions of `string-width` simultaneously, see its `package.json`:
```
    "string-width": "^5.1.2",
    "string-width-cjs": "npm:string-width@^4.2.0",
```

`string-width` 5 is ESM-only, so version 4 is renamed to `string-width-cjs`. Yarn 1 seems to only support this properly when **no** `yarn.lock` is present. On every install attempt after the lockfile is created, Yarn 1 incorrectly hoists the more recent (ESM-only) version to the root of `node_modules`, which breaks imports from Common JS modules.

Yarn also complains about packages wanting to write to the same directory.

Other people experiencing this issue:
- https://github.com/isaacs/jackspeak/issues/5#issuecomment-1534321825
- https://github.com/yargs/cliui/pull/139#issuecomment-1537115098

### Steps to reproduce

- Checkout https://github.com/hedgedoc/hedgedoc/pull/4069
- Remove `node_modules` and `yarn.lock`
- Run `yarn install` and observe success
- Remove `node_modules` again
- Run `yarn install` and observe brokenness

### Expected behavior

Install succeeds.

### Your Setup

- Host OS: Fedora 38
- NodeJS version: v16.20.0, Yarn 1.22.19

**Comment by davidmehren** [comment]
Yarn fixed this in version 2 and up: https://github.com/yarnpkg/yarn/issues/4812#issuecomment-759285407

We can now

- stop updating dependencies that cause the bug
- pin dependency versions using `resolutions`, violating dependency constraints of some packages
- update to Yarn 3


I'd favor option three, but wonder how much this will break people's setup?

**Comment by mrdrogdrog** [comment]
Option 3 still sounds better then having out of date packages.

**Comment by ErikMichelson** [comment]
The switch to yarn berry has been merged and will be released soon.
