### ISSUE TITLE
Permalinks are broken

### ISSUE THREAD

**Issue by svengo** [hedgedoc/hedgedoc#4143]
### Description

If permalinks are copied, the link will no longer work. However, within the page, the links work.

### Steps to reproduce

1. Open https://demo.hedgedoc.org/s/features
2. Hover over a header (here "Permalink")
3. You will see `https://demo.hedgedoc.org/#Permalink` in the status bar
4. Right click on the link icon and copy the link
5. You get `https://demo.hedgedoc.org/#Permalink`
6. https://demo.hedgedoc.org/#Permalink doesn't work.

![screenshot](https://github.com/hedgedoc/hedgedoc/assets/2502366/af19d678-e590-4e4c-8a16-44f019dc5b5e)

### Expected behaviour

The link should point to https://demo.hedgedoc.org/s/features#Permalink.

### Your Setup

- Windows 11 Pro 10.0.22621 Build 22621
- Firefox 113.0.2 (64-Bit)
- [HedgeDoc demo](https://demo.hedgedoc.org/s/release-notes)

### Additional context

Presumably, the behavior is triggered by the `<base href="https://demo.hedgedoc.org/">` statement in the html header.

**Comment by ErikMichelson** [comment]
Duplicate of #2344
