### ISSUE TITLE
files and folder management

### ISSUE THREAD

**Issue by semiopat** [hedgedoc/hedgedoc#4237]
### Is your feature request related to a problem? Please describe.

I use Hedgedoc for years now, what means I have a large amount of files stored within, which becomes dificult to manage, because of two features:
1. the file changes its place when you open it, because the storage is based on the date of modification ;
2. when you get out the "admin" page and get back, you lose the last state of the page.

### Describe the solution you'd like

It could be enhanced in several ways;
1. storage based on creation date instead of last modification date ; or, better, let the user have the choice between both ;
2. implementation of folder storage (also based on creation date, better than last modification date);
3. best, folder with tags automatically added to files within

### Describe alternatives you've considered

I don't know online alternative, but I think about apps like Joplin, fsNotes, mWeb, Zettlr, based on folder or category storage…

**Comment by mrdrogdrog** [comment]
Hello,

While we don't plan to implement "folders" in HedgeDoc 2, we have one point on our agenda that is the [notebook mode](https://github.com/hedgedoc/hedgedoc/issues/1001) which allows you to bundle several notes.

Also with HedgeDoc 2 comes the [explore page](https://github.com/hedgedoc/hedgedoc/issues/3833) which allows a better overview of own and shared notes.
