### ISSUE TITLE
Feature requests: Facilitate building documenation

### ISSUE THREAD

**Issue by ScrumpyJack** [hedgedoc/hedgedoc#429]
I ❤️  CodiMD, and I use it to track things daily, write documentation and present it, but i feel CodiMD could be better at the build and presentation part.

I'd like to be able to sync (pull *and* push) from a public git[lab|hub] repo or a self hosted private git repo (like gitea or gogs) via oath, that would be a perfect entry point for pipelines that automate documentation builds.

A sort of book/multi-page-menu driven output to facilitate building documentation to rival builders like Grav or Sphinx.

**Comment by DerMolly** [comment]
Git integration was discussed at [some point](https://github.com/codimd/server/issues/222) in the past. I think such a feature would most likely be feasible in a 2.1 release at the earliest. Currently most of the development time is spend working on the 2.0 release.

**Comment by InnayTool** [comment]
This discussion is continued in #1001.
