### ISSUE TITLE
Updating documentation for enabling logging in production

### ISSUE THREAD

**Issue by Avi98** [hedgedoc/hedgedoc#4335]
### Which part of the project should be enhanced?

documentation

### Is your enhancement request related to a problem? Please describe.

With this [PR](https://github.com/hedgedoc/hedgedoc/pull/4311) merged, `Logger` can now be enabled in production by setting `debugLogging` in localstorage. 

We need to add this info in docs so that hedgedoc users can check logs.

### Describe the solution you'd like

Update the docs with info on how to enable the debugging logs in production.

```js
window.localStorage.setItem("debugLogging", 'true');
```

### Describe alternatives you've considered

non

**Comment by Avi98** [comment]
Should we update 
`docs/content/dev/setup/frontend.md`

or 

`docs/content/config/index.md`

**Comment by mrdrogdrog** [comment]
I would prefer an entry in the dev docs because the debug log is something you usually don't need in production.

**Comment by JunedKhan101** [comment]
I would like to take this up. Correct me if I'm wrong, as @mrdrogdrog has mentioned this needs to be inserted into the dev docs which is docs/content/dev folder.

My question is where do I add the documentation to enable the debug log, Should it be documentation.md or getting-started.md file?

**Comment by mrdrogdrog** [comment]
`docs/content/dev/setup/frontend.md` because it's frontend specific

**Comment by JunedKhan101** [comment]
I have created a PR please review and let me know if it requires any changes.

**Comment by mrdrogdrog** [comment]
Solved by #4365
