### ISSUE TITLE
Support `pathStyle` config otion for S3 media backend

### ISSUE THREAD

**Issue by SpazzMarticus** [hedgedoc/hedgedoc#4352]
### Which part of the project should be enhanced?

S3 Storage

### Is your enhancement request related to a problem? Please describe.

The S3 provider of my organisation only supports path style which currently cant be configured.

### Describe the solution you'd like

Add `CMD_S3_FORCE_PATH_STYLE` as a configuration parameter.

### Describe alternatives you've considered

Building my own docker-image based on the hedgedoc-image and patching `s3ForcePathStyle` as follows:

```sh
sed -i 's/new AWS.Config(config.s3)/new AWS.Config({...config.s3,...{s3ForcePathStyle:true}})/' lib/web/imageRouter/s3.js
```

**Comment by davidmehren** [comment]
As per our [support policy](https://github.com/hedgedoc/hedgedoc#state-of-the-project), we do not accept feature requests for HedgeDoc 1 anymore. 

Let's track this for HD2 instead.

**Comment by davidmehren** [comment]
`minio` has a `pathStyle` option which we can use, so we would only need a new config option for this.
