### ISSUE TITLE
dependencies are wrong for manual installation

### ISSUE THREAD

**Issue by think-nice-things** [hedgedoc/hedgedoc#4375]
### Description

When trying to install manually according to

https://docs.hedgedoc.org/setup/manual-setup/

I get error messages like

➤  HedgeDoc@workspace:. provides sequelize (p91ea1) with version 5.22.5, which doesn't satisfy what connect-session-sequelize requests
➤ HedgeDoc@workspace:. doesn't provide webpack (p83411), requested by clean-webpack-plugin
➤ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code

I believe that I've met all requirements as given in https://docs.hedgedoc.org/setup/manual-setup/

Any ideas?

### Steps to reproduce

1. Download 1.9.8 from https://hedgedoc.org/releases/1.9.8/ or `git clone -b 1.9.8 https://github.com/hedgedoc/hedgedoc.git`.
2. run `bin/setup`

### Expected behaviour

I rather expected that I'd get no conflicting dependencies during `bin/setup`.

### Your Setup

- Host OS: Ubuntu 22.04.2 LTS
- NodeJS version: v20.3.1
- HedgeDoc version: 1.9.8

**Comment by mrdrogdrog** [comment]
Did you upgrade or was it a fresh install?

**Comment by think-nice-things** [comment]
well, I had a previous 1.9.7 installation with nodejs 16.

I upgraded nodejs from 16 to 20 (v20.3.1).

But I believe the new attempt to install hedgedoc 1.9.8 is completely unrelated to the old one as I'm starting in a fresh directory, either by unpacking the tar.gz from https://hedgedoc.org/releases/1.9.8/ or by  `git clone -b 1.9.8 https://github.com/hedgedoc/hedgedoc.git`. In fact I tried both and get the same error messages with both of them.

**Comment by mrdrogdrog** [comment]
The warnings about the peer dependencies can be ignored. They're not relevant in the production environment.

Just to be sure that the tar bundle is correct,
I've tested the manual install instructions again with the same Ubuntu and NodeJS version you've provided. Nothing unexpected happened. You should be able to run HedgeDoc without problems.

Feel free to open another ticket if you encounter other problems.
