### ISSUE TITLE
Add emmet support to the editor

### ISSUE THREAD

**Issue by befocken** [hedgedoc/hedgedoc#4382]
### Describe the solution you'd like

I think it would be very useful to have an [emmet](https://www.emmet.io/) integration into the markdown editor. It saves time when creating documents that need a little bit more than just Markdown and is in general very helpful as it avoids or at least minimizes repetitive HTML writing.

### Describe alternatives you've considered

I guess one could say that you don't need a tool for writing HTML if it's all about Markdown, but it would help in those case that you do need to write HTML for more complex documents. I'm not aware of any emmet alternatives.

**Comment by davidmehren** [comment]
Sorry, we are a Markdown editor and cannot add everybody's favorite plugin. That would lead to feature-bloat and unmaintainable software.

**Comment by befocken** [comment]
Alright, thank you. Maybe I'll add this in a fork of mine, as I could really use it ^^
