### ISSUE TITLE
Remember document URL after expired authentication

### ISSUE THREAD

**Issue by bjoernmartin** [hedgedoc/hedgedoc#4466]
### Which part of the project should be enhanced?

Missing Auth Redirection Code Base

### Is your enhancement request related to a problem? Please describe.

Whenever the authentication of Hedgedoc (auth via OAuth2 (Keycloak instance)) expires, Hedgedoc redirects to its base URL. When logging in again, the document visited / URL active before redirection is lost and the information about which document was viewed in that tab is lost.

### Describe the solution you'd like

Whenever the authentication of Hedgedoc expires, Hedgedoc redirects to its base URL but remembers the original URL, e.g. via query parameter such as `?lastVisited=n0ZtF0-uR96LDAMpSPHqQg`. When logging in again, the document visited is shown again.

### Describe alternatives you've considered

Logging in and then using the browser's `Back` button to get back to the document that tab had open before. 

Strange enough, sometimes even the browser history does not contain any information on that URL anymore. Possibly because JavaScript is used to rewrite the current URL instead of redirecting, preventing the browser from storing any history on this.

### Additional context

* Possibly specific to the OAuth2 authentication flow / implementation.
* Reported for a self-hosted HedgeDoc 1.9.6 installation
  * According to Release Notes this issue was not fixed in 1.9.7 thru 1.9.9

**Comment by ErikMichelson** [comment]
See https://github.com/hedgedoc/hedgedoc/pull/4483 for the state on this.

**Comment by davidmehren** [comment]
Fixed by https://github.com/hedgedoc/hedgedoc/pull/5760
