### ISSUE TITLE
Supported databases in 2.0

### ISSUE THREAD

**Issue by davidmehren** [hedgedoc/hedgedoc#447]
Part of #443

Currently we seem to support all databases that sequelize supports, but don't test them all.
We should state which databases we regularly test with and only officially support these.

What about only supporting SQLite (for development and maybe small instances) and Postgres and MySQL/MariaDB for production use?

**Comment by Trolldemorted** [comment]
Won't virtually all consumers use a containerized deployment of hedgedoc? I don't think anyone cares about which database is declared in your docker-compose file.

**Comment by DerMolly** [comment]
> Won't virtually all consumers use a containerized deployment of hedgedoc? I don't think anyone cares about which database is declared in your docker-compose file.

Quite a few people use HedgeDoc without docker

**Comment by davidmehren** [comment]
>  I don't think anyone cares about which database is declared in your docker-compose file.

This issue is not about what we put into a compose file, but what databases we are going to officially support and test. How you run HedgeDoc (i.e. in a container or not) is completely orthogonal to that.

**Comment by Trolldemorted** [comment]
>How you run HedgeDoc (i.e. in a container or not) is completely orthogonal to that.

It is not, those who use containers don't about the database choice at all and would prefer you cull the database support to one database only

**Comment by davidmehren** [comment]
> It is not, those who use containers don't about the database choice at all and would prefer you cull the database support to one database only

I'm sorry, I don't follow.

It's true that you probably don't care about the database if you set up a new HedgeDoc instance with our docker-compose file, because that spins up a new db.

But there are many cases where you *do* care about what databases we support: If you already have an existing DB. And again, in that case it is completely irrelevant if your database or HedgeDoc runs in a container or not.

**Comment by Trolldemorted** [comment]
>But there are many cases where you do care about what databases we support: If you already have an existing DB. And again, in that case it is completely irrelevant if your database or HedgeDoc runs in a container or not.

That only applies if you switch frequently and do not provide an easy migration. I'd assume that most users are not disgruntled if a service needs a manually triggered migration when a major version bump like hedgedoc 2.0 is released, it's (hopefully) not like you are going to switch to a different database again within the next few years. 10-15 years ago I was super happy if I could configure many services to use one database on my production machines, but that was when memory was expensive and servers were handcrafted.

This was just a suggestion, if you are positive that there are no bugs are created by subtle differences between the databases and your ORM's ingegration of them then don't mind me :)

**Comment by InnayTool** [comment]
I would close this issue with the databases in the description of the issue, because there are good reasons for them and they are supported by TypeORM.
