### ISSUE TITLE
mermaid gantt chart parse error

### ISSUE THREAD

**Issue by lovesharepc** [hedgedoc/hedgedoc#4479]
### Description

when use gantt with tickInterval 
got error
> Parse error on line 4:
...   tickInterval 1day        section Se
-----------------------^
Expecting 'taskData', got 'NL'

code
```
gantt
    title A Gantt Diagram
    dateFormat  YYYY-MM-DD
    section Section
    A task           :a1, 2014-01-01, 30d
    Another task     :after a1  , 20d
    section Another
    Task in sec      :2014-01-12  , 12d
    another task      : 24d
    tickInterval 1day
```

### Steps to reproduce

code
``` #mermaid
gantt
    title A Gantt Diagram
    dateFormat  YYYY-MM-DD
    section Section
    A task           :a1, 2014-01-01, 30d
    Another task     :after a1  , 20d
    section Another
    Task in sec      :2014-01-12  , 12d
    another task      : 24d
    tickInterval 1day
```

### Expected behaviour

mermaid live editor
[![](https://mermaid.ink/img/pako:eNpdUMtqwzAQ_JVlzzZYbk66BUxLDzmllwZdFmudithSkNeFEPLvkZBNaAehx-wMg-aOfbCMGs_kRYyHBHEyMuzhI1PQOTpHmsrIkvB7iBMJwHdCfTjUXbfZ-sunF46_NIKydCt02WfuxQUPx3IWcg9C8wVe0KQqaBu1qxuVVgVvjV2lPsgPx5dB05CigBRAtti_Mau8kF_Z43werjFbhGqzW7Wrm_6HgIZ2Z7HCidOfnU093bPUYNJNbFCnq-WBllEMGv9IUlokHG--Ry1x4QqXay5tbRH1QOOc2Cv5Uwjb-_EEus50Qg?type=png)](https://mermaid.live/edit#pako:eNpdUMtqwzAQ_JVlzzZYbk66BUxLDzmllwZdFmudithSkNeFEPLvkZBNaAehx-wMg-aOfbCMGs_kRYyHBHEyMuzhI1PQOTpHmsrIkvB7iBMJwHdCfTjUXbfZ-sunF46_NIKydCt02WfuxQUPx3IWcg9C8wVe0KQqaBu1qxuVVgVvjV2lPsgPx5dB05CigBRAtti_Mau8kF_Z43werjFbhGqzW7Wrm_6HgIZ2Z7HCidOfnU093bPUYNJNbFCnq-WBllEMGv9IUlokHG--Ry1x4QqXay5tbRH1QOOc2Cv5Uwjb-_EEus50Qg)

### Your Setup

- Host OS: Ubuntu 22.04
- NodeJS version: docker image (1.9.8)
- HedgeDoc version: 1.9.8

**Comment by mrdrogdrog** [comment]
The feature you're mentioning is supported by mermaid 10, but not mermaid 9. HedgeDoc 1 uses mermaid 9.
