### ISSUE TITLE
How user should work in 2.0

### ISSUE THREAD

**Issue by DerMolly** [hedgedoc/hedgedoc#451]
What we talked about in the dev channel:

- user should be able to use multiple login providers
- user should have an username
- user should have a display name
- user should have a profile picture
- user may have an email address
- the profile picture can be provided by the login provider, uploaded by the user or get via libravatar and the user email
- all properties gotten from a login provider should be non-changeable by the user (optional)

Open Questions:
- what do we do if users activate two login providers and can't change properties?

**Comment by ErikMichelson** [comment]
I thought about something like this:
![image](https://user-images.githubusercontent.com/52606896/87536036-b8718f00-c698-11ea-91d4-df9eca3a8e39.png)

**Comment by SISheogorath** [comment]
Some thoughts on the difference between username and display name:

usernames are used to identify users. In best case they are all lowercase, match `[a-z0-9]{3,15}` and can be used anywhere where one can reference a user.

Display names on the other hand, are a UI element in order to make it easier for people to find each other. They shouldn't have too strict limits on characters or length, but the UI doesn't have to show them entirely if they get too long and they should only be used as additional information to the username. If no Display name is set, the username can be used as fallback.

**Comment by DerMolly** [comment]
If login provider properties are not allowed to be changed by the user, we could simply have the relation between User and UserLogin be 1-1.
That would most likely yield a startup error if there already is an 1-n relation, when the feature get's activated…

**Comment by ErikMichelson** [comment]
Some example scenarios:

Person A registers its account directly on the instance (currently known as email-register). It chooses a username and a password. With that username and password person A may sign-in at the instance. The display name equals to the username, but may changed in the profile-settings. The profile image equals to the first letter of the username with a random background color. In the profile-settings the person may optionally add an email address to its account to set the profile-image to the libravatar-result of that email address.

Person B uses a social-login like GitHub. After authenticating at GitHub, there will be a prompt for choosing a username. This prompt is pre-filled with the username that the person has at GitHub. Depending on the server-configuration the person may change that username or not. The profile image will default to the profile image from GitHub and the display name will default to the display name from GitHub as well. The user may add an email address to overwrite the image from GitHub with the libravatar-image for the email address.

Person C already has registered on the instance as person A has done it. The next day person C uses another login possibility like OAuth2. After authenticating at the OAuth2 provider, there will be a prompt for choosing a username, pre-filled with the username fetched from the OAuth2 provider. Person C changes that username to the username that was used for registration earlier. By confirming the password for that username, the OAuth2-login and the username-password login are now linked to the same account with the same notes etc.

**Comment by DerMolly** [comment]
Re: Person C
I think a cleaner way would be to login with username-based login and in the profile page add an OAuth2 Login to the account instead.

**Comment by DerMolly** [comment]
If the login provider provides an image should that be overideable in the non-override mode? I think it's cleaner if nothing can be changed and it could be used by users to identify users.
On the other hand it would be rather dull if the login provider (LDAP) for example does not provide images, but user can't change their profile picture…

**Comment by ErikMichelson** [comment]
The other idea would be to have a dropdown for profile-picture in the profile-settings:
- generated letter on random color
- libravatar image (only selectable if email address is provided)
- external provider (only selectable if account is linked with an external provider like GitHub)

**Comment by SISheogorath** [comment]
We could actually use `{{username}}@example.com` for all users without an email address and supply it to the Libravatar function. Could safe us all the hassle  with "letter-avatars"

**Comment by davidmehren** [comment]
I think the safe flow for C would be: User C logs in with an existing method, visits the profile-page and presses "add login method", which then goes through the normal flow of selecting a provider, logging in etc. That way, account takeover with an external account that has the same username is not possible.
GitLab handles it that way: https://docs.gitlab.com/ee/integration/omniauth.html#enable-omniauth-for-an-existing-user

**Comment by davidmehren** [comment]
> We could actually use `{{username}}@example.com` for all users without an email address and supply it to the Libravatar function. Could safe us all the hassle with "letter-avatars".

I just checked with https://www.libravatar.org/tools/check/ and all example.org mail addresses look [the same](https://www.libravatar.org/static/img/nobody/80.png) with default settings. They get unique if we use another style like 'retro'.

Nevertheless, to quickly identify someone I would still prefer a letter on a simple color instead of some pixelart.

**Comment by davidmehren** [comment]
I started to write down the concept in #1032. Please have a look.

During writing, I asked myself if we want to allow changing the username. I *think* our database schema would allow this, so this is probably more of a UX question than a technical one.

**Comment by storrgie** [comment]
I didn't want to make a specific comment on the MR, but I'd like to point out a use case for changing username. We use gitlab as an SSO, we want the username to always mimic what gitlab has. We do not want to allow users to change their username arbitrarily (or even display name, as it could be abused). However there are use cases (such as the changing of a last name due to marriage) where an existing, instanced user, would have their name changed upstream (in gitlab) and it should change/reflect downstream in hedgedoc.

**Comment by DerMolly** [comment]
I think this is what was meant by *sync source*. The truth lies within Gitlab (in your example) and it's planed to be possible to disallow users to change anything coming from a sync source. The question is if the user is able to change anything else should they be able to change their username, too? And I'm not to keen on the idea, I guess it could be argued that there are cases, where this could be useful, but those cases may just be something where one needs to talk to their admin.

**Comment by SISheogorath** [comment]
I think it mainly depends what's the key identifier of the user. If it's the username, you can not let the user change their username through a sync-source as you can not associate the new  username with the previous account. However, most SSO protocols have an uid or similar unique identifier throughout the lifetime of an account. If we want to allow username changes, we'll definitely need an own id field, while at the same time, make sure the username is unique as well.

**Comment by DerMolly** [comment]
Currently the username is the publicly observable identifier, but internally everything works with a normal id. So changing a username should be no problem for our own internal login for example. The identity is also linked via this user id and should be no problem.
An interesting problem arises from this scenario:
An instance uses internal login and github as an IP. Somebody registers an user with the username `DerMolly` as an internal account. Then I come along and try to log in with my github account. What should happen?
I think we should only change the newly created account (minimal necessary change). So my "github account" would probably get another username like `DerMolly1`. Of course the sync would also need to deterministically change the username each time it runs. (and it should not just try to find a user with the username and if it does change the username, because with that it would periodically sync the username to be `DerMolly1` and `DerMolly2` or `DerMolly11` depending on how the the new username would be decided.)

**Comment by ErikMichelson** [comment]
What about prefixing "external" usernames with a few letters like `gh_DerMolly` for your GitHub login while preventing local user creation with such a prefix?

**Comment by storrgie** [comment]
> What about prefixing "external" usernames with a few letters like gh_DerMolly for your GitHub login while preventing local user creation with such a prefix?

This gets sticky when you consider rolling multiple providers. Notably I've seen [discussion over in this nextcloud plugin](https://github.com/zorn-v/nextcloud-social-login/issues/224) for how they are handling prefixing of usernames. I think that they were both prefixing the names and also having the names be somewhat random. This makes the systems administrators job a lot harder to track who is what on their system.

Whatever is chosen, it should be from a perspective of flexibility (do you want to support a user having multiple social logins linked to their user instance?) and transparency of management (do you, as an administrator of and instance, want to have to dig deeply into the 1:N relationship between a user and their social login flows?)
