### ISSUE TITLE
Include SystemD example service

### ISSUE THREAD

**Issue by ccoenen** [hedgedoc/hedgedoc#46]
I'm running CodiMD directly on my server via SystemD. I collected two service files, that should be combined and that could go into `/docs/setup/` for reference.

https://demo.codimd.org/svq0JObCToqyt3ZBCZ58og#

**Comment by tcharlss** [comment]
Hi,
In the second example, we found out that the complete PATH of the codimd user is needed in the Environment, otherwise the service can't find npm and throw an error.
So in the terminal, `echo $PATH` and then copy and paste the result:

```
Environment=USER=codimd HOME=/home/codimd PATH=/home/codimd/.nvm/versions/node/v11.14.0/bin:/opt/codimd-cli/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
```
Maybe it should be mentionned that this example works in the case where npm was installed with nvm.

**Comment by SISheogorath** [comment]
I would recommend to add `PrivateTmp=true` in the [Service] section.

We could also consider to add `EnvironmentFile=/etc/default/codimd`, which contains an environment configuration for CodiMD (but I consider it as optional).

And `Documentation=` in the `[Unit]` section could point to our repository.

**Comment by ccoenen** [comment]
I'm not using nvm in my setup, I'm not very familiar with it (other than what it does).

For now I'd rather keep this as simple as possible, here's my proposal (also seen in the pad linked at the top):

```sh
[Unit]
Description=CodiMD collaborative markdown notes
Documentation=https://github.com/codimd/server
After=syslog.target
After=network.target
### uncomment if you're using MySQL/mariaDB
#After=mysql.service
### uncomment if you're using PostgreSQL
After=postgresql.service
 
 
[Service]
Type=exec
RestartSec=2s
User=www-data
Group=www-data
# the location you cloned CodiMD to.
WorkingDirectory=/opt/codimd/
# this path _might_ be different on different systems. Especially if nvm is involved.
# use `which npm` to find the full path if this gives you any trouble.
ExecStart=/usr/bin/npm start --production
Restart=always
PrivateTmp=true
PrivateDevices=true


[Install]
WantedBy=multi-user.target
```

Let's go over it line by line:

```sh
[Unit]
Description=CodiMD collaborative markdown notes
Documentation=https://github.com/codimd/server

# I took those verbatim from the other example, but I personally have
# no syslog.target only network.target exists on my machine.
# I have syslog.socket, though!
After=syslog.target
After=network.target
### uncomment if you're using MySQL/mariaDB
#After=mysql.service
### uncomment if you're using PostgreSQL
After=postgresql.service
 
 
[Service]
# type exec felt more appropriate. Docs: https://www.freedesktop.org/software/systemd/man/systemd.service.html#Type=
Type=exec
# taken from example 2
RestartSec=2s
# I generally keep this under the www user, as that user may also need to serve some assets.
# discussion welcome!
User=www-data
Group=www-data
# the location you cloned CodiMD to.
# personally, this is `/var/www/codimd`, but I took this from the example 2 instead.
WorkingDirectory=/opt/codimd/
# use `which npm` to find the full path if this gives you any trouble.
# this is now in the new(ish) npm start format instead
ExecStart=/usr/bin/npm start --production
Restart=always
# added at the request of @SISheogorath
PrivateTmp=true
PrivateDevices=true


[Install]
# basically every example had this, so I included it.
WantedBy=multi-user.target
```

I removed the `Environment=` things, I do not need them on my system. `$USER` and `$PATH` looked fine to me. I also removed a "d" from `mysql.service` - at least that's the name on my system.

Here's the otput of ` tr '\0' '\n' < /proc/$codimdpid$/environ | grep -v npm_` on my system. Note that you need to fill in `$codimdpid$` with a number:

```sh
USER=www-data
HOME=/var/www
LOGNAME=www-data
PATH=/usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/codimd/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
NODE=/usr/bin/node
LANG=de_DE.UTF-8
SHELL=/usr/sbin/nologin
PWD=(whatever was in my unit file)
NODE_ENV=production
INIT_CWD=(whatever was in my unit file)
NODE_CHANNEL_FD=3
```

**Comment by SISheogorath** [comment]
We don't need to wait for anything like `After=syslog.socket`. CodiMD doesn't send anything to syslog and systemd logs everything to journald, no matter what time at the boot it is.

And i would recommend to change the user for CodiMD from `www-data` to an own user `codimd`. Best practice would be to have a `codimd` group as well and `www-data` part of that group, because CodiMD doesn't need to read or write anything of `www-data` but the other way around. But if this is considered too complicated, then we can keep the group `www-data` even when there is a not to ignore security impact when you host more than just CodiMD on this machine.

**Comment by cmseal** [comment]
+1 for this... helped me setup for production env

**Comment by ccoenen** [comment]
@cmseal out of curiosity: did you need to make any changes to it? If so: what gave you trouble? Would you have needed any other guidance along with an example?

**Comment by cmseal** [comment]
@ccoenen I used your fully commented version above.  I knew I'd be changing the user/group, but otherwise no issues.  This was the easiest method for having it run as a service and maintained the newer style ```npm start --production``` mechanism.  PM2 and forever require running this differently, which caused me issues.

**Comment by InnayTool** [comment]
The systemd example service file was merged to `master`.

**Comment by davidmehren** [comment]
You can find the service file at https://docs.hedgedoc.org/setup/manual-setup/#systemd-unit-example
