### ISSUE TITLE
Implement /notes route

### ISSUE THREAD

**Issue by davidmehren** [hedgedoc/hedgedoc#474]
Tracking issue for everything that relates to the `/notes` route of the public API.  
See also [the API spec](https://github.com/codimd/server/blob/develop/docs/dev/public_api.yml) for details.

1. Add E2E tests:
- [x] POST ​/notes
- [x] GET ​/notes​/{note}
- [x] POST ​/notes​/{note}
- [x] DELETE ​/notes​/{note}
- [x] PUT ​/notes​/{note}
- [x] PUT ​/notes​/{note}​/metadata
- [x] GET ​/notes​/{note}​/metadata
- [x] GET ​/notes​/{note}​/revisions
- [x] GET ​/notes​/{note}​/revisions​/{revision-id}
- [x] GET ​/notes​/{note}​/content

2. Add implementation:
- [x] POST ​/notes
- [x] GET ​/notes​/{note}
- [x] POST ​/notes​/{note}
- [x] DELETE ​/notes​/{note}
- [x] PUT ​/notes​/{note}
- [x] PUT ​/notes​/{note}​/metadata
- [x] GET ​/notes​/{note}​/metadata
- [x] GET ​/notes​/{note}​/revisions
- [x] GET ​/notes​/{note}​/revisions​/{revision-id}
- [x] GET ​/notes​/{note}​/content

**Comment by ent3r** [comment]
First time contributing, please excuse me if I'm missing something important.

> I think the `PUT ​/notes​/{note}​/metadata` route has to be rework because it's not very practical that one has to set that much properties. We have thought about to move the functionality to the real time API because most or all(?) are only used in the note view.

It is possible to use `PATCH /notes/{note}/metadata` instead. That allows having just the updated values.

(Bold added manually) https://en.wikipedia.org/wiki/Patch_verb
> The main difference between the PUT and PATCH method is that the PUT method uses the request URI to supply a modified version of the requested resource which **replaces the original version of the resource**, whereas the PATCH method supplies a **set of instructions to modify the resource**.

**Comment by InnayTool** [comment]
We implemented the routes above. `PATCH` is not needed for functionality and is a lot work, so it should not be tracked in this issue, maybe we can add it as feature request in another issue.
