### ISSUE TITLE
Markdown in HTML blocks

### ISSUE THREAD

**Issue by wilkyrlx** [hedgedoc/hedgedoc#4749]
### Which part of the project should be enhanced?

Implement support for markdown rendering in html blocks

### Is your enhancement request related to a problem? Please describe.

I would like to implement support for the markdown attribute in html blocks. Consider this example, where we need a div to wrap the partially bold paragraph:     **in** this **paragraph** every **other** word **is** bolded

Tedious approach =>  **in** this **paragraph** every **other** word **is** bolded
```
<div class="some-mandatory-class">
    <strong>in</strong> this <strong>paragraph</strong> every <strong>other</strong> word <strong>is</strong> bolded.
</div>
```

Desired approach =>  **in** this **paragraph** every **other** word **is** bolded
```
<div class="some-mandatory-class" markdown=1>
    **in** this **paragraph** every **other** word **is** bolded
</div>
```

However, the desired approach, which uses the markdown attribute, does not render currently in hedgedoc, instead rendering plaintext  `**in** this **paragraph** every **other** word **is** bolded `

### Describe the solution you'd like

Certain markdown renderers/plugins address this issue, as mentioned, with support of the markdown attribute in html blocks. This would allow users to wrap markdown with html blocks, which would allow them to save time unnecessarily reformatting markdown into html. 

### Describe alternatives you've considered

It might be possible to use the [md-in-html plugin](https://python-markdown.github.io/extensions/md_in_html/), which supports the markdown=1 attribute

### Additional context

Note: I will confess that I am unfamiliar with the hedgedoc codebase, and I apologize if this issue has been discussed before - I could not find anything in issues that looked similar, but any guidance/insight into the feasibility of this feature would be appreciated!

**Comment by ErikMichelson** [comment]
The markdown syntax HedgeDoc uses ([HFM](https://docs.hedgedoc.org/references/hfm/)) is based on [GitHub Flavored Markdown (GFM)](https://github.github.com/gfm/). GFM allows markdown in HTML when being padded by blank lines, see [the reference](https://github.github.com/gfm/#example-157).

So for your example, change the code to the following:

```html
<div class="some-mandatory-class">
    
**in** this **paragraph** every **other** word **is** bolded

</div>
```

You can see this in HedgeDoc in action in [this example note](https://demo.hedgedoc.org/aGCm0UfNTzOZO-1X1xZ3gg).

**Comment by wilkyrlx** [comment]
ahh thank you, missed that
