### ISSUE TITLE
Implement /me route

### ISSUE THREAD

**Issue by InnayTool** [hedgedoc/hedgedoc#475]
Tracking issue for everything that relates to the /me route of the public API.
See also [the API spec](https://github.com/codimd/server/blob/develop/docs/dev/public_api.yml) for details.

1. Add E2E tests:
- [x] GET ​/me
- [x] GET /me​/history
- [ ] GET /me​/history​/{note}
- [x] PUT /me​/history​/{note}
- [x] DELETE /me​/history​/{note}
- [x] GET /me​/notes

2. Add implementation:
- [x] GET ​/me
- [x] GET /me​/history
- [ ] GET /me​/history​/{note}
- [x] PUT /me​/history​/{note}
- [x] DELETE /me​/history​/{note}
- [x] GET /me​/notes

**Comment by InnayTool** [comment]
@DerMolly GET /me​/history​/{note} is not implemented because we don't need it?

**Comment by DerMolly** [comment]
If that was the argument we don't need PUT either now, do we? I guess it just wasn't mocked int the file when I worked on it and I didn't came back around to finish that, yet.

**Comment by InnayTool** [comment]
PUT adds or removes the pinned state do it is needed I think. I see no reason to implement it. Should we drop it?

**Comment by davidmehren** [comment]
`GET /me​/history​/{note}` seems still useful to get the pin state of a single note.
