### ISSUE TITLE
Implement /media route

### ISSUE THREAD

**Issue by InnayTool** [hedgedoc/hedgedoc#479]
Tracking issue for everything that relates to the `/media` route of the public API.  
See also [the API spec](https://github.com/codimd/server/blob/develop/docs/dev/public_api.yml) for details.

1. Add E2E tests:
- [x] POST ​/media​
- [x] DELETE /media/{filename}
2. Add implementation:
- [x] POST ​/media​
- [x] DELETE /media/{filename}

**Comment by ErikMichelson** [comment]
What about the suggestion to store the uploads in a separate database model to allow the removal of all uploads that belong to a note when the note is deleted? This would also be handy to allow users to find uploaded files again for which they accidentally removed the URL.

**Comment by davidmehren** [comment]
After much discussion, we came up with the following plan for media upload:
- For every uploaded media, the uploading user and the note it was uploaded to is saved in the database
- We can therefore generate lists like "media you uploaded" and "media uploaded to this note".
- The media is *not* subject to ACLs, as we can't enforce them anyway if external storage (like S3 or Azure) is used
- For compatibility with 1.x we continue to use `/uploads` for uploaded media.

**Comment by SISheogorath** [comment]
If you keep a 1.x compatible `/uploads` endpoint, how are you able to store the note relationship?

Also: Why do we explicitly want to keep `/uploads`? We could break it in 2.0 as far as I know it was never an explicit feature, it's just that people happened to like that it's so easy in 1.x.

**Comment by davidmehren** [comment]
To clarify: The `/uploads` endpoint should only be used to serve local media, so we don't break links in Notes from 1.x.
For uploading new media, we will introduce a new endpoint which requires user and note information.

**Comment by DerMolly** [comment]
I think this is fixed by now and can be closed.
