### ISSUE TITLE
Deleting a private note from history doesn't delete it from the database

### ISSUE THREAD

**Issue by drebs** [hedgedoc/hedgedoc#4791]
### Description

As a user, I expect that when I remove a private note from my history it'll also be deleted from the database, but that's not the case.

### Steps to reproduce

1. Create a note.
2. Set it to "Private".
3. Delete the note from history.

### Expected behaviour

The note should be deleted from the database.

### Your Setup

Using [linuxserver/hedgedoc](https://hub.docker.com/r/linuxserver/hedgedoc) container image:

- Host OS: Alpine 3.18
- NodeJS version: v20.5.0
- HedgeDoc version: 1.9.9

**Comment by mrdrogdrog** [comment]
Hello,

This is not a bug, this is intended. If you wanna delete a note, then you need to open it and check the permission drop-down menu on the top of the right side of the screen.

We are aware that this is a bad UX and HedgeDoc 2 will make it better.
