### ISSUE TITLE
pod stuck with message  debug: dmp worker process started

### ISSUE THREAD

**Issue by christophsing** [hedgedoc/hedgedoc#4807]
### Description

Hedgedoc Image Version 1.9.5 and newer doe not start - and stuck with this message:

hedgedoc-f945666f8-h2988 hedgedoc 2023-09-07T13:39:58.828Z debug: 	dmp worker process started
hedgedoc-f945666f8-h2988 hedgedoc 2023-09-07T13:42:48.970Z info: 	HedgeDoc has been killed by signal, try to exit gracefully...

Version 1.9.4 does run without problems

### Steps to reproduce

use version tag: 'version-1.9.4', and upgrade to tag: 'version-1.9.5',

this causes the docker image from linuxserver/hedgedoc to prevent from booting

### Expected behaviour

startup the pod

### Logs

```shell
version 1.9.5 and newer:
hedgedoc-f945666f8-h2988 hedgedoc 2023-09-07T13:39:58.828Z debug: 	dmp worker process started
hedgedoc-f945666f8-h2988 hedgedoc 2023-09-07T13:42:48.970Z info: 	HedgeDoc has been killed by signal, try to exit 

version 1.9.4:

hedgedoc-6b5f98dc7b-g7x8p hedgedoc 2023-09-07T13:43:18.577Z info: 	Executing (default): PRAGMA INDEX_LIST(`Sessions`)
hedgedoc-6b5f98dc7b-g7x8p hedgedoc 2023-09-07T13:43:18.586Z info: 	HTTP Server listening at 0.0.0.0:3000
hedgedoc-6b5f98dc7b-g7x8p hedgedoc 2023-09-07T13:43:18.587Z info: 	Executing (default): PRAGMA INDEX_INFO(`sqlite_autoindex_Sessions_1`)
```

### Config

```shell
env:{
   NODE_ENV: 'production',
   TZ: 'Europe/Berlin',
   DB: 'dialect=postgres',
   CMD_ALLOW_ANONYMOUS: 'false',
   CMD_ALLOW_ANONYMOUS_EDITS: 'false',
   CMD_EMAIL: 'false',
   CMD_DB_USERNAME: cluster.hedgedoc.postgresql.username,
   CMD_DB_HOST: cluster.hedgedoc.postgresql.host,
   CMD_DB_DATABASE: cluster.hedgedoc.postgresql.dbname,
   CMD_DB_DIALECT: 'postgres',
   CMD_DB_PORT: cluster.hedgedoc.postgresql.port,
   CMD_SESSION_SECRET: cluster.hedgedoc.security.sessionSecret,
   CMD_PROTOCOL_USESSL: 'true',
   CMD_URL_ADDPORT: 'false',
   CMD_DOMAIN: cluster.hedgedoc.domain,
   CMD_HOST: '0.0.0.0',
   CMD_PORT: '3000',
   CMD_SOURCE_URL: 'https://github.com/hedgedoc',
   CMD_OAUTH2_USER_PROFILE_URL: 'https://git.i.xxx.com/api/v3/user',
   CMD_OAUTH2_USER_PROFILE_USERNAME_ATTR: 'login',
   CMD_OAUTH2_USER_PROFILE_DISPLAY_NAME_ATTR: 'name',
   CMD_OAUTH2_USER_PROFILE_EMAIL_ATTR: 'email',
   CMD_OAUTH2_TOKEN_URL: 'https://git.i.xxx.com/login/oauth/access_token',
   CMD_OAUTH2_AUTHORIZATION_URL: 'https://git.i.xxx.com/login/oauth/authorize',
   CMD_OAUTH2_CLIENT_ID: cluster.hedgedoc.github.clientId,
   CMD_OAUTH2_CLIENT_SECRET: cluster.hedgedoc.github.secret,
   CMD_OAUTH2_PROVIDERNAME: 'GitHub Enterprise',
   CMD_IMAGE_UPLOAD_TYPE: 's3',
   CMD_S3_ACCESS_KEY_ID: cluster.hedgedoc.s3Storage.accessKey,
   CMD_S3_SECRET_ACCESS_KEY: cluster.hedgedoc.s3Storage.secretKey,
   CMD_S3_ENDPOINT: cluster.hedgedoc.s3Storage.endpoint,
   CMD_S3_BUCKET: cluster.hedgedoc.s3Storage.bucket,
   DEBUG: 'true',
   CMD_LOGLEVEL: 'debug',
  },
```

### Your Setup

Chart 1.1.0
https://github.com/nicholaswilde/helm-charts/blob/main/charts/hedgedoc/values.yaml

**Comment by mrdrogdrog** [comment]
Hello,

thanks for your issue.

I'm sorry to tell you that this bug tracker is the wrong place for your problem because it is only for issues which are code related. For trouble with deployments that are not code-related, please post your request in the [community board](https://community.hedgedoc.org). 
I would also recommend to use a more recent version (because 1.9.5 and 1.9.4 are heavily outdated).

**Comment by christophsing** [comment]
thank you - i will adress this there. But just for you to know - same happens with the latest version and the image from you:
https://quay.io/repository/hedgedoc/hedgedoc

and the chart from:
https://artifacthub.io/packages/helm/adfinis/hedgedoc
