### ISSUE TITLE
CMD_ALLOW_ANONYMOUS does not work

### ISSUE THREAD

**Issue by martinei** [hedgedoc/hedgedoc#4844]
### Description

I am running HedgeDoc 1.9.9
I have set the Environment Variable CMD_ALLOW_ANONYMOUS to false
Still anonymous users are able to view Notes (with Permission EDITABLE or LOCKED).

I'd expect anonymous user to not be able to see any note.

### Steps to reproduce

start hedgeDoc with CMD_ALLOW_ANONYMOUS set to false.
Create a Note with Editable Permissions.

Open that note in an private Browser Window

### Expected behaviour

The note should not be visible.

### Your Setup

HedgeDoc 1.9.9 in Docker: quay.io/hedgedoc/hedgedoc:1.9.9

**Comment by faerics** [comment]
@martinel Confirmed the issue: set `CMD_ALLOW_ANONYMOUS: false`, and all `locked` notes are visible without auth.
However, this is not a bug: if you want to protect a note for quest viewing, you can use either limited or protected, as stated in the description.

That works.
