### ISSUE TITLE
Preserve vim clipboard / registers between tabs

### ISSUE THREAD

**Issue by nidico** [hedgedoc/hedgedoc#4845]
### Which part of the project should be enhanced?

Frontend

### Is your enhancement request related to a problem? Please describe.

The problem is the incapability of copy-pasting between hedgedoc notes in different browser tabs using the vim clipboard / registers.

### Describe the solution you'd like

I don't really know. Maybe

- some cross browser tab communication method (see e.g. this [blog post](https://blog.bitsrc.io/4-ways-to-communicate-across-browser-tabs-in-realtime-e4f5f6cbedca))
- push to / pull from regular clipboard. However it seems like pulling from the clipboard isn't permitted in some browsers (e.g. Firefox), so this is probably no option. Also it wouldn't allow the use of multiple vim registers.

In the end this probably needs to be in [CodeMirror](https://github.com/codemirror/dev) or [codemirror-vim](https://github.com/replit/codemirror-vim/) upstream.

### Describe alternatives you've considered

Using system copy-paste. However this undermines the hedgedoc vim experience and feels quite awkward.

**Comment by mrdrogdrog** [comment]
Hello,
thanks for your issue. Unfortunately we can't do anything here because, as you have already found out, the vim functionality is provided by a 3rd party plugin. Please open an issue in their repository.
