### ISSUE TITLE
Make revision save frequency configurable

### ISSUE THREAD

**Issue by JVimes** [hedgedoc/hedgedoc#4897]
### Which part of the project should be enhanced?

Revision save frequency

### Is your enhancement request related to a problem? Please describe.

I get a revision every 10 minutes, which often misses changes. For example, with marketing material I'll try several phrasings of a sentence (within 10 minutes) and want to review each in context anytime later.

### Describe the solution you'd like

I'd like my instance's revision save timing configurable in seconds the usual way (config file or env. variable). I'll likely pick 5s or 10s.

### Describe alternatives you've considered

I thought about a "smart" dynamic approach but didn't see benefit over more frequent revision saves.

### Additional context

My users and I write mostly short marketing posts, so disk space and revision count isn't a concern.

**Comment by ErikMichelson** [comment]
Hey @JVimes,

thanks for your feature suggestion. As stated in the [readme file](https://github.com/hedgedoc/hedgedoc?tab=readme-ov-file), we're currently focusing on the development of HedgeDoc 2 and therefore don't add new features to HedgeDoc 1.x.

However, this feature has already been implemented in HedgeDoc 2, and thus I'm going to close this issue.

HedgeDoc 2 will have a config option `HD_PERSIST_INTERVAL` for this.

**Comment by JVimes** [comment]
Awesome! I'm super excited about v2. Thanks for all the hard work.
