### ISSUE TITLE
Add read-only-links that are not related to the editor

### ISSUE THREAD

**Issue by mrdrogdrog** [hedgedoc/hedgedoc#4959]
### Which part of the project should be enhanced?

Link generation

### Is your enhancement request related to a problem? Please describe.

HedgeDoc 1 supports the generation of links to the read only view which are different from the editor url.
These links use other ids and made it possible to conceal the editor access.

### Describe the solution you'd like

I was thinking that we might could use the alias system for this?
We could extend the alias by an attribute which defines how it can be used.

Another approach is to generate a special ID which gets appended to the note and only grants access to the read only view but not the websocket endpoint.

### Describe alternatives you've considered

-

### Additional context

You can use any publish-link and append `/edit` to get to the editor. I don't want to reimplement this feature!
If I want people to get access to the editor, I would give them the editor URL.

**Comment by ErikMichelson** [comment]
Closing in favor of #471, which is a superset of this
