### ISSUE TITLE
Sort according to “last modified”

### ISSUE THREAD

**Issue by think-nice-things** [hedgedoc/hedgedoc#4975]
### Is your feature request related to a problem? Please describe.

currently the cards on the overview page are sorted according to “last visited”.
If I view an old topic it will appear afterwards on top of the cards of topics, even if I didn't change the topic.

### Describe the solution you'd like

I'd rather like to sort according to “last modified”.
This way the sorting of the cards in the overview page wouldn't change if old topics having been viewed.
This could be made a configuration option.

### Describe alternatives you've considered

There are not really alternatives.

**Comment by JunedKhan101** [comment]
I'd like to work on this but need guidance on where is the overview page as I am still a beginner contributing to this repo.

**Comment by ErikMichelson** [comment]
Hey @think-nice-things ,

thanks for your feature suggestion. As stated in the [readme file](https://github.com/hedgedoc/hedgedoc?tab=readme-ov-file), we're currently focusing on the development of HedgeDoc 2 and therefore don't add new features to HedgeDoc 1.x.

As this feature is not relevant anymore for HedgeDoc 2, I'm going to close this issue.
HedgeDoc 2 will instead have an explore page (#3833).

@JunedKhan101 Thanks for your interest in working on this. As stated, we are not going to accept new features for HedgeDoc 1. If you'd like to contribute to the project, feel welcome to ask in our [development chat room](https://chat.hedgedoc.org/dev).

**Comment by DerMolly** [comment]
@think-nice-things  Sorry! I believe I suggested to add this issue in our forum in the first place.
