### ISSUE TITLE
Setup full-functioning HD2 demo on hedgedoc.dev

### ISSUE THREAD

**Issue by JunedKhan101** [hedgedoc/hedgedoc#4977]
### Description

Under HedgeDoc 2 UI Test in Readme when I tried to open the hedgedoc.dev link it resutls in this:

![image](https://github.com/hedgedoc/hedgedoc/assets/47941768/17532963-b932-48e7-80ec-7aacc4cbad60)

### Steps to reproduce

1. Go to Readme and find the HedgeDoc 2 UI Test section
2. Click on the hedgedoc.dev link
3. See error page

### Expected behaviour

It should open a demo of the new UI

### Your Setup

Setup based information is not required for this.

**Comment by mrdrogdrog** [comment]
Hello,

We're already aware of this problem and will fix it soon.

**Comment by ErikMichelson** [comment]
This has been done.
