### ISSUE TITLE
Interface breaks if port in docker isn't 3000

### ISSUE THREAD

**Issue by sastromo** [hedgedoc/hedgedoc#5003]
### Description

If I choose another port other than 3000, the interface breaks.
From what i found, its trying to load from :3000 instead of my port (:3002)
Doesn't matter if `CMD_URL_ADDPORT=true` or `=false`

![image](https://github.com/hedgedoc/hedgedoc/assets/45545544/0ec9e0da-b738-4ae2-b2db-9da2fa5ed5dd)

![image](https://github.com/hedgedoc/hedgedoc/assets/45545544/d4486fa6-f51b-45c7-9b4e-a12aad210690)
![image](https://github.com/hedgedoc/hedgedoc/assets/45545544/052359f9-f71f-4952-995a-9ea13fbbf45a)
![image](https://github.com/hedgedoc/hedgedoc/assets/45545544/15d8844a-7b3a-41dd-8c1a-2d3547db4b37)

### Steps to reproduce

Change port on docker compose

![image](https://github.com/hedgedoc/hedgedoc/assets/45545544/f574e81b-00a0-495e-af31-431df015255e)

### Expected behaviour

![image](https://github.com/hedgedoc/hedgedoc/assets/45545544/666b4631-879e-47d1-bbf8-70b4e4988217)

### Your Setup

- Host OS: Proxmox: LXC -> Docker -> Portainer
- NodeJS version: v12.22.12
- HedgeDoc version: 1.9.9

**Comment by mrdrogdrog** [comment]
Well you've changed the port binding in the docker-compose file but you didn't tell the application anything about the other port. The HedgeDoc process still binds to port 3000 inside of the container, so it assumes that it will be available on port 3000. If you want to change the port in the URL then you need to change the port of the application as well.

**Comment by DerMolly** [comment]
You can set the port HedgeDoc will use via the config file or via `CMD_PORT`. See https://docs.hedgedoc.org/configuration/#hedgedoc-location

**Comment by DerMolly** [comment]
As this issue was solved I'll close it. Feel free to reopen if the problem still exists.

**Comment by ErikMichelson** [comment]
> Im I doing something wrong?

Probably.
You want:

```yaml
environment:
  - CMD_DOMAIN=192.168.1.223
  - CMD_DB_URL=...
  - CMD_URL_ADDPORT=true
  - CMD_PORT=3002
ports:
  - "3002:3002"
