### ISSUE TITLE
Move markdown extraction to decorator

### ISSUE THREAD

**Issue by davidmehren** [hedgedoc/hedgedoc#501]
In https://github.com/codimd/server/blob/routes/notes/services/src/api/public/notes/notes.controller.ts we need to get the raw text from the request multiple times. Currently, every function duplicates the code for that. It should be moved to a decorator, see https://stackoverflow.com/a/61416426

**Comment by DerMolly** [comment]
this was fixed with 258dd1db568da7923baf89f6fd13c5a33360fa89 or  #507
