### ISSUE TITLE
Can't add new lines at the end of the document

### ISSUE THREAD

**Issue by InnayTool** [hedgedoc/hedgedoc#5022]
### Description

If you try to add new lines add the end of a document, hitting return does nothing; especially not adding a new line.

### Steps to reproduce

Go to the last line of a document and hit return in a empty line.

### Expected behaviour

For each key press on return a new line should be added.

### Your Setup

--

### Additional context
Seems to be a problem with trim call.

**Comment by DerMolly** [comment]
This seems to be a problem with `@codemirror/language`, `@codemirror/lang-markdown` or `@codemirror/lang-data`

**Comment by DerMolly** [comment]
Fixed by #5048
