### ISSUE TITLE
App breaks if database is deleted

### ISSUE THREAD

**Issue by InnayTool** [hedgedoc/hedgedoc#5029]
### Description

The application breaks if the database is deleted.

### Steps to reproduce

--

### Expected behaviour

--

### Your Setup

--

**Comment by mrdrogdrog** [comment]
> The application breaks if the database is deleted.

that's correct. go on?

**Comment by InnayTool** [comment]
@davidmehren maybe you have to specify what exactly is the problem

**Comment by DerMolly** [comment]
@ErikMichelson, @mrdrogdrog  and myself just discussed this and if I understand the issue correctly the idea was we should be able to handle that someone deletes the user e.g. if the app still runs. We thought about how this could be detected, but nothing to helpful came to mind. I think this issue can be closed as we can't really handle someone messing with the db while the app runs efficiently…

**Comment by ErikMichelson** [comment]
> I think this issue can be closed
