### ISSUE TITLE
Rework import-history-button

### ISSUE THREAD

**Issue by InnayTool** [hedgedoc/hedgedoc#5042]
### Which part of the project should be enhanced?

history button

### Describe the solution you'd like

Rework file and use readfile util

### Describe alternatives you've considered

--

**Comment by ErikMichelson** [comment]
Probably not relevant when we instead implement the explore page

**Comment by InnayTool** [comment]
Do we have an issue for the explore page?

**Comment by ErikMichelson** [comment]
#3833
