### ISSUE TITLE
Set default issuer in SAML auth to HedgeDoc's own URL

### ISSUE THREAD

**Issue by InnayTool** [hedgedoc/hedgedoc#5043]
### Which part of the project should be enhanced?

AuthConfig

### Describe the solution you'd like

Build the default value for issuer from other config values.

For context: HedgeDoc 1 (default: `config.serverURL`) will be build on-the-fly in the `config/index.js` from domain, `urlAddPort` and `urlPath`.

### Describe alternatives you've considered

--

**Comment by DerMolly** [comment]
For context: This is about the issuer in the SAML Config and what the default should be. In HedgeDoc 1 this was just the serverUrl, but this can't be replicated as easy as this is variables is constructed from different settings in HedgeDoc 2.

**Comment by ErikMichelson** [comment]
We don't intend to add SAML authentication to HedgeDoc anymore. We have OIDC and people can use proxy-software like SATOSA or Keycloak or Authentik instead when they want to use SAML. Therefore this issue becomes unnecessary.
