### ISSUE TITLE
Spinners don't stop

### ISSUE THREAD

**Issue by JVimes** [hedgedoc/hedgedoc#5076]
### Description

These spinners don't stop for me on 2.0.0-alpha.1 (local in docker and on hedgedoc.dev):

![image](https://github.com/hedgedoc/hedgedoc/assets/6148201/d59e19fe-22b9-4c0f-9ba0-c9e34f3fb0bb)

### Steps to reproduce

Open main page

### Expected behaviour

Data loads where spinners are

### Logs

[logs.txt](https://github.com/hedgedoc/hedgedoc/files/12842544/logs.txt)

### Config

```shell
Defaults [from the documentation](https://docs.hedgedoc.dev/tutorials/setup/).
```

### Your Setup

- Host OS: Windows 10
- NodeJS version: n/a
- HedgeDoc version: 2.0.0-alpha.1
- Chrome: Version 117.0.5938.150 (Official Build) (64-bit)

**Comment by mrdrogdrog** [comment]
Seems like we still need that iframe fallback trigger outside of test mode @ErikMichelson @DerMolly

**Comment by JVimes** [comment]
Would that also cause the markdown not to render on the right? Also having that issue.

**Comment by mrdrogdrog** [comment]
Yes, that could be the problem. I can fix this soon. The fix would be included in the next nightly image.
Could you try if the problem also occurs with Firefox?

**Comment by JVimes** [comment]
Yes, works in Firefox

**Comment by JVimes** [comment]
Awesome, fixed in develop. Thanks everyone! Very excited about 2.0.
