### ISSUE TITLE
Template variable in maximum note length is not expanded on HedgeDoc 2

### ISSUE THREAD

**Issue by dasJ** [hedgedoc/hedgedoc#5145]
### Description

Creating a very long note shows a message where a variable is not expanded:
![image](https://github.com/hedgedoc/hedgedoc/assets/4971975/f5e2ba96-9c2e-4be2-b279-e8f90401a6d5)

### Steps to reproduce

1. Open a new note
2. Create a 800x600 table
3. Read the error message

### Expected behaviour

The message shows how long the note may be

### Your Setup

hedgedoc.dev

**Comment by mrdrogdrog** [comment]
Huh. I'm wondering what got jammed here. Probably the translation. Thanks for reporting. :)
