### ISSUE TITLE
Revision viewer showing error during revision loading

### ISSUE THREAD

**Issue by christian-heusel** [hedgedoc/hedgedoc#5167]
### Description

There is an error when you check a notes revision history, although it appears only very briefly.
Also there seems to be some empty field there:
![Screenshots2023-10-20_12:05:18](https://github.com/hedgedoc/hedgedoc/assets/26827864/51e57998-d746-4d39-af53-da02ae2df90c)

### Steps to reproduce

1. Go to any note
2. Make an edit
3. Check the revision history
4. Click on the last revision
5. Observe the above behaviour

### Expected behaviour

No errors for regular user interaction

### Your Setup

The hedgedoc beta setup over at 
https://hedgedoc.dev/

**Comment by ErikMichelson** [comment]
Thanks for reporting.

Two separate things:

1. The empty fields are known. This is caused by #5016 still being open.
2. It seems that during the time of loading the revision from the API, there is no loading spinner but this error is shown. This could indeed be fixed.

**Comment by ErikMichelson** [comment]
More context:
[This error](https://github.com/hedgedoc/hedgedoc/blob/develop/frontend/src/components/editor-page/sidebar/specific-sidebar-entries/revisions-sidebar-entry/revisions-modal/revision-viewer.tsx#L36) is probably fired when the component is initialized for the first time and the props are not evaluated yet. The method is then called again when the props (`noteId`, `selectedRevisionId`) are available, and thus the error vanishes.

We could extend the early component return by checking for `noteId` too and then remove this error by silently ignoring the case that the props are not there yet.
