### ISSUE TITLE
Which forbidden note ids should we keep?

### ISSUE THREAD

**Issue by DerMolly** [hedgedoc/hedgedoc#519]
Which of these via default forbidden note ids should we keep? Which are unnecessary anymore?
I think we want to keep this config option around, since admins will possibly used this to accomplish things.

https://github.com/codimd/server/blob/3461993ee05d09106e276e606b143d472908b166/lib/config/default.js#L36

**Comment by ErikMichelson** [comment]
We have to remember that notes will now reside under `domain.tld/n/alias`. The listed directories and special files therefore probably aren't needed to include anymore.

**Comment by DerMolly** [comment]
So which would you suggest we keep? I think e.g. `robots.txt` is not necessary anymore, but maybe we still want to forbid that by default?

**Comment by DerMolly** [comment]
I just had a look at this and I don't see any of the old default forbidden note ids or aliases that we really want to keep around. For reference the old ones were:

- robots.txt
- favicon.ico
- api
- build
- css
- docs
- fonts
- js
- uploads
- vendor
- views

But as stated in the initial post, I think we should keep this option around so that admins that used it on 1.x, can still do so in 2.0.

**Comment by ErikMichelson** [comment]
The reason for this was to ensure that system relevant paths were not overwritten by accident. As I wrote above, this isn't necessary anymore with 2.0, therefore I'd **drop all of them**. The option to forbid some note ids/aliases should nevertheless be kept around.
