### ISSUE TITLE
Hedgedoc 2 alpha: endless memory leak in the editor reproducible under Firefox

### ISSUE THREAD

**Issue by dmsimard** [hedgedoc/hedgedoc#5200]
### Description

When editing slides with Hedgedoc 2 alpha, I noticed that leaving a tab of the editor opened in Firefox 118.0.2 on Fedora Linux will leak memory endlessly until the tab is closed. This is not a leak on the server side, it is on the client side: the browser itself.

This was observed to leak as much as 4GB in less than 24 hours up to 6GB over a longer period:

![Screenshot from 2023-10-24 10-07-18](https://github.com/hedgedoc/hedgedoc/assets/1291204/795b9126-276e-4bf6-b56f-0185b9d200fa)

Looking at the memory inspector tab in Firefox we see that it's all in the dom:
![Screenshot from 2023-10-23 19-23-13](https://github.com/hedgedoc/hedgedoc/assets/1291204/2e808a24-81c0-4a7a-a96e-de24ba55a318)

![Screenshot from 2023-10-23 19-25-26](https://github.com/hedgedoc/hedgedoc/assets/1291204/c56f29e1-72c9-4b91-bee0-30f5ac52348e)

I've tried to see if the issue reproduced in Chromium 118.0.5993.70 out of curiosity and there are no problems to be found, staying under 200MB of memory:

![Screenshot from 2023-10-24 10-06-44](https://github.com/hedgedoc/hedgedoc/assets/1291204/84fd2278-a818-4a05-b942-f7a202246a7c)

### Steps to reproduce

- Open a hedgedoc 2 alpha editor tab in Firefox
- Leave it opened for several hours
- Witness the memory usage in the Firefox task manager slowly but surely rise over time

### Expected behaviour

The editor does not leak memory in Firefox.

### Logs

```shell
I could be mistaken but I don't believe there are relevant server-side logs for the issue.
```

### Your Setup

It's deployed via a slightly altered docker-compose that removes caddy since I already have an nginx running.

- Host OS: Debian 12
- NodeJS version: v20.8.0
- HedgeDoc version: 2.0.0-alpha.1

### Additional context

Link to discussion on Matrix: https://matrix.to/#/!oaRMJImPLfUnnXzwnN:shivering-isles.com/$kNawtzZv0Vk42zmbK4ObNVYaLcAcLInaJtVNjd0Oxy0?via=matrix.org&via=envs.net&via=mozilla.org

**Comment by ErikMichelson** [comment]
Well I tried to reproduce this by letting a (slide) note and the presentation-view of it open for a few hours. Memory consumption looked normal.

![image](https://github.com/hedgedoc/hedgedoc/assets/52606896/53174d92-67cd-4b95-b352-6632c0598eea)

* Firefox 118.0.2 x64 (via snap)
* no extensions
* Ubuntu 22.04.3

We should definitely evaluate further which combination of things results in this effect.

**Comment by dmsimard** [comment]
Thanks for trying to reproduce the issue!

I will attempt to isolate what might be causing the issue on my end and report back my findings.

**Comment by ErikMichelson** [comment]
Hey, did you find anything on how to reproduce this problem?

If not, I'd like to close this issue in a few days.
