### ISSUE TITLE
Firefox Favicon changes randomly on refresh

### ISSUE THREAD

**Issue by DerMolly** [hedgedoc/hedgedoc#5203]
It seems like there is a problem with Firefox and the HedgeDoc 2 Favicon. It changes randomly when freshing (in the shown case via cmd+shift+r to force a reload and circumvent cache usage).

https://github.com/hedgedoc/hedgedoc/assets/3978662/f0e05773-54cc-4db6-b330-64e82450032b

**Comment by mrdrogdrog** [comment]
We don't do anything special here. The favicon files are served as normal files and the head tags are present in the initial HTML. So it seems like a firefox specific problem that we can't fix :shrug:

**Comment by DerMolly** [comment]
I'm not able to reproduce this anymore.
