### ISSUE TITLE
API shoud use base64-coded note ID instead of database UUID

### ISSUE THREAD

**Issue by davidmehren** [hedgedoc/hedgedoc#522]
See https://github.com/hedgedoc/hedgedoc/blob/929d4af2b5f9564c16074f4425a1ff693300f04e/lib/models/note.js#L165 for the old encode/decode logic

**Comment by SISheogorath** [comment]
I'm not sure this aged well, it points to a `}`. Could you link to the code in a specific commit, so it doesn't get lost? (GitHub provides a permalink function for that)

**Comment by davidmehren** [comment]
I'm pretty sure that was a copypaste-error. Link fixed.

**Comment by InnayTool** [comment]
I think we should decide how ids and aliases should work in 2.0. The discussion is in issue #864.
