### ISSUE TITLE
Azure Activate Directory setup documentation is invalid

### ISSUE THREAD

**Issue by RobertNotRob** [hedgedoc/hedgedoc#5249]
### Description

If you look at the initial issue raised to add the documentation here: https://github.com/hedgedoc/hedgedoc/issues/2656

And the PR that added it here: https://github.com/hedgedoc/hedgedoc/pull/4413/commits/07e3a6b81f4eae011f2f51867c314ec054b5bff6#diff-4dd50d40f0cfecb09e9521bceb63e1e9d411b7e43e44e2b43aa73bc5eb2384ba

You'll notice the environment variables as documented are completely incorrect relative to the initial issue, and do not work.

Specifically:
- CMD_OAUTH2_USER_PROFILE_URL
- CMD_OAUTH2_USER_PROFILE_USERNAME_ATTR
- CMD_OAUTH2_USER_PROFILE_EMAIL_ATTR
- CMD_OAUTH2_SCOPE

The values that worked for us were:
CMD_OAUTH2_USER_PROFILE_URL=https://graph.microsoft.com/v1.0/me
CMD_OAUTH2_USER_PROFILE_USERNAME_ATTR=userPrincipalName
CMD_OAUTH2_USER_PROFILE_EMAIL_ATTR=mail
CMD_OAUTH2_SCOPE=openid offline_access email profile User.Read

### Steps to reproduce

1. Follow AD setup guidance
2. Login will fail

### Expected behaviour

1. Follow AD setup guidance
2. Users can log in with AD

### Your Setup

- Azure deployed HedgeDoc instance

**Comment by DerMolly** [comment]
Hey @RobertNotRob,

Thanks for rasing this issue. I create a pull request (https://github.com/hedgedoc/hedgedoc/pull/5250) to fix the documentation. Can you check if this is working, I currently have no access to a azure active directory to verify myself.

**Comment by RobertNotRob** [comment]
Hi @DerMolly 

I can confirm this matches our setup which should be relatively minimal.

Thanks,
Robert
