### ISSUE TITLE
Image upload in 2.0

### ISSUE THREAD

**Issue by davidmehren** [hedgedoc/hedgedoc#529]
Currently we support 6 different image upload types. Which of them are we going to support in 2.0?

My proposal:

- [x] local filesystem
  - easy, works out of the box
  - **keep**
- [x] S3 (see #536)
  - scalable, supported by many backends
  - `aws-sdk` is used, maybe replace with lighter S3 client?
  - **keep**
- minio
  - S3 compatible
  - currently used with `minio` package, maybe replace with S3 client?
  - **keep**/merge into S3
- lutim
  - discontinued upload service
  - **remove**
- [x] imgur (see #538)
  - free upload service
  - GDPR concerns?
  - **keep**, but warn users that images are uploaded to a 3rd party?
- [x] Azure Blob Storage (see #537)
  - "Massively scalable and secure object storage for cloud-native workloads"
  - *not* S3 compatible
  - needed `azure-storage`, now `@azure/storage-blob`
  - **keep**

**Comment by DerMolly** [comment]
> Azure Blob Storage 

Afaik is this a big alternative to S3 so maybe we should keep it if it's reasonable to do so

**Comment by DerMolly** [comment]
Another Question: Which should be the default?
For a normal installation it currently is local fs. For Docker it's imgur iirc. But I don't see any alternatives working out-of-the-box

**Comment by ccoenen** [comment]
azure was contributed here: https://github.com/hackmdio/codimd/pull/675

**Comment by ccoenen** [comment]
> Another Question: Which should be the default?
> For a normal installation it currently is local fs. For Docker it's imgur iirc. But I don't see any alternatives working out-of-the-box

(personal take, YMMV) If I go to the lengths of self-hosting, I usually have a reason for that. IMO the default should be self-hosting the images, too. I.e. local file storage.

**Comment by davidmehren** [comment]
I have updated the list with `keep` for Azure Blob Storage.

I think using local storage in Docker and requiring a persistent volume for that is the better, privacy-respecting way.

**Comment by SISheogorath** [comment]
Making local volumes a requirement will break Heroku support, just saying.

**Comment by ccoenen** [comment]
can heroku just get its own default, then?

**Comment by DerMolly** [comment]
I think we don't have a separate repo for heroku, do we? We just have a docker image to use. Maybe this would need to change then.

**Comment by SISheogorath** [comment]
Heroku doesn't use the docker image, but it'll run in a container on their platform. They build the application from the server repository.

**Comment by DerMolly** [comment]
But then the heroku user needs to add a config file anyway, don't they?

**Comment by ccoenen** [comment]
But AFAIR, one can give heroku their own default env vars:

https://github.com/codimd/server/blob/82aff80b88dca3922e7a8c2705f6c0e1c39bb726/app.json#L13

**Comment by ErikMichelson** [comment]
What about allowing generic WebDAV backends for uploads?

We would need two config options for that:
 - WebDAV upload prefix: e.g. https://user:password@mywebdavshare.com/dav/hedgedoc/
 - Public accessible path prefix: e.g. https://mywebdavshare.com/public/hedgedoc/

As we know the filename of the file we want to upload, we can easily assemble the matching public URL for downloading.

**Comment by DerMolly** [comment]
For WebDAV https://www.npmjs.com/package/webdav seems a promissing canidate…

**Comment by DerMolly** [comment]
As everything except webdav is finished here, I just created a new issue for WebDAV #1041 and will close this now.

**Comment by oupala** [comment]
Unfortunately, lutim is not a "discontinued upload service".

It is an [opensource piece of software](https://framagit.org/fiat-tux/hat-softwares/lutim) that should really be supporter by HedgeDoc 2.
