### ISSUE TITLE
List of all available documents

### ISSUE THREAD

**Issue by rastapopougros** [hedgedoc/hedgedoc#53]
https://github.com/hackmdio/codimd/issues/975

A page with a list of all documents a particular user can access. Maybe only for users who have an account, so it lets us have "secret documents" not publicly listed for anonymous visitors but still open to anyone we send the link.

When connected, before the tab "History", a new tab "All notes", and inside all the accessible notes for me.

**Comment by ccoenen** [comment]
I'm totally comfortable with "notes created myself", I think those will not spark any debate. In fact, they are already in a work-in-progress pull request for a personal profile page:

https://github.com/codimd/server/pull/34/files#diff-c20808cd50fa2d6520d58aa115e52a07R23

but "any document that can be _accessed_ by me" should probably be we would have to put a lot of thought into.

**Comment by InnayTool** [comment]
There is further discussion in #455
