### ISSUE TITLE
Allowed upload mime types in version 2.0

### ISSUE THREAD

**Issue by InnayTool** [hedgedoc/hedgedoc#533]
Which mime types should be allowed to upload in version 2.0 of the backend?

picture formats:
- PNG
- JPG
- TIFF

**Comment by InnayTool** [comment]
related to #529

**Comment by DerMolly** [comment]
* PDF
* GIF
* SVG (maybe?)

**Comment by SuperSandro2000** [comment]
* JPEG
* BMP
* WEBP

**Comment by InnayTool** [comment]
We also implemented APNG, HEIF, HEIC, heif-sequence, heic-sequence.

**Comment by davidmehren** [comment]
We discovered that supporting PDF upload does not make much sense, as the frontend deprecated PDF rendering.
