### ISSUE TITLE
Redirect error on alpha2 container setup

### ISSUE THREAD

**Issue by poVoq** [hedgedoc/hedgedoc#5332]
### Description

I recreated the recommended alpha2 docker setup with Podman and Nginx as a reverse-proxy (with the recommended nginx example) but I get the following error when navigating to the page:

`You can't open this page using this URL. For this endpoint "https://docs.slrpnk.net/" is expected but got "https://10.88.0.86:41043".`

I suspect this might be just a reverse-proxy issue, but I am not an Nginx expert and the example config looks ok to me.

Any idea what might be the cause of this?

### Steps to reproduce

Set up alpha 2 as recommended in the official docu but with Podman and Nginx.

### Expected behaviour

Should work 😅

### Your Setup

- Host OS: Fedora 38 
- HedgeDoc version: 2.0 alpha2

**Comment by mrdrogdrog** [comment]
There is an error in the docs in the nginx config example. You need to set the proxy header `X-Forwarded-Host` instead of `Host`

**Comment by poVoq** [comment]
Thanks, that seems to have fixed it indeed.
