### ISSUE TITLE
Untitled document

### ISSUE THREAD

**Issue by fh59213** [hedgedoc/hedgedoc#5341]
### Description

When am on the homepage, all my documents are "untitled". I can't find a way to rename them and tried different way of naming my new file when starting it, but still "untitled"

### Steps to reproduce

1. Create a file
2. Give it a title name
3. Go back to homepage
4. You file is "untitled"

### Expected behaviour

Having automatic names of my documents with the Title text of the 1st line
and/or
Have a way to change the title of my document 

### Your Setup

- Host OS: Actually Pop!_OS 22.04 LTS but have the same problem on Windows 11
- NodeJS version: 
- HedgeDoc version: 1.9.9

**Comment by ErikMichelson** [comment]
Hi @fh59213,

HedgeDoc uses the first heading found in the note as a title. Headings are declared in markdown by a line beginning with `# ` followed by your title.

Another way of specifying the title is by using the frontmatter. See [the docs](https://docs.hedgedoc.org/references/yaml-metadata/) for more information on this.
