### ISSUE TITLE
:::spoil markdown extension (existing on CodiMD)

### ISSUE THREAD

**Issue by ppom0** [hedgedoc/hedgedoc#5342]
### Is your feature request related to a problem? Please describe.

We, at Picasoft.net , used CodiMD until recently. We easily switched to Hedgedoc, and appreciate the new features, so thanks a lot!

---

A user of our services discovered their spoil blocks weren't *working* anymore 
```
:::spoil Click only if you entirely read the book
They die in the end!
:::
```
This used to build a <details>/<summary> HTML

### Describe the solution you'd like

Make this markdown extension

```markdown
:::spoil TextA
TextB
:::
```

rendering

```html
<details>
<summary>TextA</summary>
TextB
</details>
```

### Describe alternatives you've considered

One can already write its own details/summary HTML, but 
- I consider it's more complex for non-HTML-friendly users
- It's less drop-in from CodiMD
- It can break nested formatting

**Comment by mrdrogdrog** [comment]
Hello,

The spoiler syntax is already included in HedgeDoc 2 (which is in development rn). You can test it on demo.hedgedoc.dev.

We're not gonna backport this feature to HedgeDoc 1, so until we release HedgeDoc 2  you'll have to use the HTML syntax. Sorry :/

**Comment by ppom0** [comment]
Oh, perfect! Thanks :tada:
