### ISSUE TITLE
Upgrade sequelize to newer version in v1.9.9

### ISSUE THREAD

**Issue by mikaello** [hedgedoc/hedgedoc#5343]
### Which part of the project should be enhanced?

Dependencies in [package.json](https://github.com/hedgedoc/hedgedoc/blob/1.9.9/package.json)

### Is your enhancement request related to a problem? Please describe.

Our CI/CD pipeline blocks HedgeDoc v1.9.9 (currently latest stable release) because of Trivy security scanning finding critical issues with sequelize, which is fixed in later versions of sequelize:

![image](https://github.com/hedgedoc/hedgedoc/assets/2505178/55a4ccab-b771-4671-8fba-5dc0f17dcdc7)

Sequelize v5.22.5 is the version used in v1.9.9 of HedgeDoc:

https://github.com/hedgedoc/hedgedoc/blob/f52475dc4f3e3e27927a073754ff86fe6ff1e01a/package.json#L96

### Describe the solution you'd like

Upgrade sequelize to a version fixing the security issues.

### Describe alternatives you've considered

Not considered alternatives.

**Comment by davidmehren** [comment]
HedgeDoc 1 is maintenance-only and a major upgrade of Sequelize unfortunately exceeds our capacity.
