### ISSUE TITLE
User is signed out by redirection

### ISSUE THREAD

**Issue by haslersn** [hedgedoc/hedgedoc#539]
Suppose I have a CodiMD instance on `dest.example2.com` and I have a 301 permanent redirect from `src.example1.com` to `dest.example2.com`. Now, if a signed-in user accesses `src.example1.com`, they will get redirected to `dest.example2.com` (as intended), but now they're signed out.

**This problem does not appear if both subdomains are under the same second-level domain** (such as `src.example.com` and `dest.example.com`)

## Additional information

Branch: `master`

I used oauth2 login when experiencing this issue.

Cookies when signed in (before accessing `src.example1.com`):

```yml
connect.sid: <redacted>
loginstate: true
userid: <redacted>
```

Cookies after accessing `src.example1.com` and being redirected to `dest.example2.com`:

```yml
connect.sid: <redacted> # The connect.sid changed. It now has a completely different value.
loginstate: false
```

**Comment by haslersn** [comment]
More insight: This only happens with `"cookiePolicy": "strict"`. Is it intended behaviour?

**Comment by davidmehren** [comment]
Setting `cookiePolicy` to `strict` seems to cause login issues (see https://github.com/codimd/server/commit/3d1fab0512a828927f277796a0e23e8133230be5). We therefore changed the default to `lax` (in https://github.com/codimd/server/commit/387e6682757d32b9d9e9b7e3d443143a39ce2184), but somehow skipped updating the example config. I just did that in https://github.com/codimd/server/commit/46647170f323f38857fccf9cd1d3c5dd99259818.

So currently, you have to use `"cookiePolicy": "strict"`.

**Comment by InnayTool** [comment]
I think this issue is solved. If not let us know.
