### ISSUE TITLE
Permit multiple owners of a note (or group)

### ISSUE THREAD

**Issue by rastapopougros** [hedgedoc/hedgedoc#55]
https://github.com/hackmdio/codimd/issues/1174

Let us have multiple admins on a note. In the config panel of a note, a selector should let us add other owners.

Or implement a new concept of groups, and if a note is assigned to a group, anyone in the group can change the config? Not the same way at all, but maybe can solve the problem too.

**Comment by davidmehren** [comment]
To centralize the discussion about this topic, I created https://github.com/hedgedoc/hedgedoc/issues/998
Please take a look and comment if you feel I missed an important aspect.  
Thanks!
