### ISSUE TITLE
Server stuck at migration

### ISSUE THREAD

**Issue by marcelcosta** [hedgedoc/hedgedoc#552]
I am trying to freshly install manually codimd in my server. In fact I managed to build it (2Gb RAM + 2Gb swapfile), but when I try to run it, it gets stacked at a line (after peacking 100% CPU usage): 
`== 20200321153000-fix-account-deletion: migrating =======` 

While the service is running, I don't think it really is. I am installing on a VPS running ubuntu 18.04 and I am using SQlite as db (I am testing for personal use).

**Comment by marcelcosta** [comment]
I managed to install it and run it using the docker image.

In case is useful, the CPU information I found from Hetzner (where I host my VPS):
CPX: Optimized for CPU performance based on AMD EPYC 2nd Gen processors.

I have 1 VCPU.

**Comment by davidmehren** [comment]
There might be some kind of bug in `bin/cleanup`, which gets run by the migration you mentioned. Did you see a line like `Cleaning up notes that should already have been removed. Sorry.`?

Did you follow [this document](https://github.com/codimd/server/blob/master/docs/setup/manual-setup.md) when setting up CodiMD? Did you use a release or the `master` branch? What is the output of `node -v`?

**Comment by marcelcosta** [comment]
Hi,

I did follow that document. I used the master branch (was that correct?) and the output of `node -v` is `v10.19.0`.

>There might be some kind of bug in bin/cleanup, which gets run by the migration you mentioned. Did you see a line like Cleaning up notes that should already have been removed. Sorry.?

Yes:
`2020-11-04T19:15:54.344Z info: 	Cleaning up notes that should already have been removed. Sorry.`

**Comment by davidmehren** [comment]
I just tried to reproduce this error on Hetzner Cloud.
You probably used Ubuntu 20.04 instead of 18.04, as 18.04 has node 8 and 20.04 has node 10 ;)

Unfortunately, the initial migration (using sqlite) worked for me. Do you still have your `config.json` and `.sequelizerc` and could share them?

**Comment by marcelcosta** [comment]
Yes, you are right! I have Ubuntu 20.04 installed in my server.

I show the files you ask for:
config.json (I don't show all the connection part, which I have empty):
```{json}
{
    "test": {
        "db": {
            "dialect": "sqlite",
            "storage": ":memory:"
        },
        "linkifyHeaderStyle": "gfm"
    },
    "development": {
        "loglevel": "debug",
        "hsts": {
            "enable": false
        },
        "db": {
            "dialect": "sqlite",
            "storage": "./db.codimd.sqlite"
        },
        "linkifyHeaderStyle": "gfm",
		"port":1936
    },
    "production": {
        "domain": "codi.ratg.cat",
		"port":3000,
		"protocolUSeSSL":true,
		"useSSL":true,
		"allowOrigin": ["codi.ratg.cat"],
        "loglevel": "info",
        "hsts": {
            "enable": true,
            "maxAgeSeconds": 31536000,
            "includeSubdomains": true,
            "preload": true
        },
        "csp": {
            "enable": true,
            "directives": {
            },
            "upgradeInsecureRequests": "auto",
            "addDefaults": true,
            "addDisqus": true,
            "addGoogleAnalytics": true
        },
        "cookiePolicy": "strict",
        "db": {
            "dialect": "sqlite",
            "storage": "./db.codimd.sqlite"
        },
        "linkifyHeaderStyle": "gfm"
    }
}
```

.sequelizerc:
```{json}
var path = require('path');

module.exports = {
    'config':          path.resolve('config.json'),
    'migrations-path': path.resolve('lib', 'migrations'),
    'models-path':     path.resolve('lib', 'models'),
    'url':             'sqlite://:memory:'
}
```

**Comment by davidmehren** [comment]
You configured two different database locations: in the `production` section of your `config.json` you used the file `./db.codimd.sqlite`, but in `.sequelizerc` you used `memory`. That would lead to things not working, as Sequelize sets up a different database than the application itself tries to use.

**But:** It seems our migrations (specifically the `bin/cleanup` script) have a bug and get stuck when run with a `memory` sqlite db. Maybe @SISheogorath has an idea why?

**Comment by davidmehren** [comment]
Alright, I also think we can leave this be. `memory` is just no a very sensible database location ^^
