### ISSUE TITLE
Multi instance/Load balancing 

### ISSUE THREAD

**Issue by archef2000** [hedgedoc/hedgedoc#5524]
### Is your feature request related to a problem? Please describe.

I have setup two HedgeDoc instances on two nodes that are accessing the same database and uploads folder. And the editing is not shared.

### Describe the solution you'd like

Set an optional redis instance/cluster to make the HedgeDoc instance stateless.

### Describe alternatives you've considered

I could not find an alternative way to use two instances at the same time.

**Comment by davidmehren** [comment]
Running multiple instances of HedgeDoc 1 with the same database [is not supported](https://docs.hedgedoc.org/faq/#can-i-run-multiple-instances-on-the-same-database).

We also currently do not plan to add support for multi-instancing in HedgeDoc 2.0.
