### ISSUE TITLE
Implement support to serve media from private buckets

### ISSUE THREAD

**Issue by syphernl** [hedgedoc/hedgedoc#5542]
### Which part of the project should be enhanced?

Media Uploads

### Describe the solution you'd like

Media uploaded to buckets, e.g. S3, require the buckets (and their objects) to be available publicly. It would be preferable to keep a bucket set to private.

### Describe alternatives you've considered

A few ideas to implement this:

* Use signed urls (but they expire so they cannot be stored as-is). 
* Create a "media proxy" endpoint that retrieves the image from the bucket. It could return either the signed URL (or redirect to it) or the actual object it obtained.

**Comment by ErikMichelson** [comment]
An endpoint for media access is tracked in #2310 and currently being implemented in #5535. The endpoint will redirect to the URL that the configured storage backend returns.

Making the S3 storage backend return signed-URLs is a feature I'd like to see as well. Issue #2104 has some similarities, although not being the same thing.
