### ISSUE TITLE
Can't paste image

### ISSUE THREAD

**Issue by Beulu** [hedgedoc/hedgedoc#5543]
### Description

I copy any image from the web in clipboard or importing one from a file and it not appearing in my note

### Steps to reproduce

import picture
or copy/paste

### Expected behaviour

Seeing pictures in my notes of course x)

### Your Setup

Docker and latest Hedgedoc

**Comment by ErikMichelson** [comment]
Can you please elobarate a bit on the details?

Which browser are you using? Which operating system? Does the upload fail (take a look at the logs) or isn't there no upload action on pasting? From where did you copy the image, especially in which format is it? Does it work on demo.hedgedoc.org?

Please understand, that we can't help without any more context or reproducability.

**Comment by Beulu** [comment]
It works perfectly ! Thanks ^^
