### ISSUE TITLE
Offer automatic "system" light/dark theme switching using `prefers-color-scheme`

### ISSUE THREAD

**Issue by nekohayo** [hedgedoc/hedgedoc#5547]
### Which part of the project should be enhanced?

Stylesheet for UI and text editor and previewer rendering

### Is your enhancement request related to a problem? Please describe.

Dark themes don't work in all situations, especially in a sunlit room during the day.

The current UI provides a manual switch, but it should follow the operating system instead.

### Describe the solution you'd like

I'd like Hedgedoc's theme to automatically switch between light/dark based on my browser's reported system theme mode. GNOME (and other DEs/OSes) does the switch for me everyday at the correct times with [this extension](https://extensions.gnome.org/extension/2236/night-theme-switcher/) (and eventually the native setting once it gets implemented in GNOME Settings), and my web browser follows suit, telling webpages' CSS mediaqueries that dark is now "preferred" or not. This works on all OSes and modern browsers nowadays.

You can detect this condition using CSS like this, for example:

```
@media (prefers-color-scheme: dark) { blah blah }
```

See https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme for more details.

### Describe alternatives you've considered

You could still keep a manual switch button to toggle between System vs always light vs always dark, but that's just complicating things IMHO.

**Comment by ErikMichelson** [comment]
The upcoming HedgeDoc 2.0 already includes this feature. There you can choose between setting the mode manually or let the system decide.

![image](https://github.com/hedgedoc/hedgedoc/assets/52606896/b6e8509e-9f01-4da5-b02c-11929c9cff41)


You can test it out on https://hedgedoc.dev - it's in the settings dialog, that can be opened from the top right.
