### ISSUE TITLE
Feature Request: Wakatime integration

### ISSUE THREAD

**Issue by muety** [hedgedoc/hedgedoc#555]
I know that this is a pretty specialized feature request, so feel free to close this issue, if you consider it irrelevant. However, it would be cool to integrate CodiMD with [Wakatime](https://wakatime.com/) to keep track of the time you spend in the editor, broke down by individual notes, etc. What do you think?

**Comment by DerMolly** [comment]
We had a look at this and it seems rather complicated to include as the only way to talk to Wakatime seems to be their python-cli.

**Comment by muety** [comment]
I think you can also send raw heartbeat requests to their API, but then you would have to come up with a custom implementation for crafting them.

**Comment by davidmehren** [comment]
As this seems to be completely blocked by a lack of an useable implementation in JS, I'm going to close this for now.
