### ISSUE TITLE
Documentation for project setup

### ISSUE THREAD

**Issue by JunedKhan101** [hedgedoc/hedgedoc#5551]
### Which part of the project should be enhanced?

Documentation

### Is your enhancement request related to a problem? Please describe.

I would love a documentation for project setup and to run the project locally, almost all the open-source projects have this and it would be great to have in this project.

### Describe the solution you'd like

NA

### Describe alternatives you've considered

NA

**Comment by ErikMichelson** [comment]
You mean one of the following docs entries?
- https://docs.hedgedoc.org/setup/manual-setup/ (1.x manual production setup)
- https://docs.hedgedoc.org/dev/getting-started/ (1.x dev setup)
- https://docs.hedgedoc.dev/how-to/develop/setup/ (2.0 dev setup; might still need improvements)

**Comment by JunedKhan101** [comment]
Sorry! Didn't see those links, maybe you could consider adding these to the README? othewise it's fine.

**Comment by JunedKhan101** [comment]
@ErikMichelson I'm getting this error when I run `yarn start:dev`
Can you help me out?

![image](https://github.com/hedgedoc/hedgedoc/assets/47941768/6b3ad7da-fcc0-4f0e-9dc1-29578a8547fc)

**Comment by JunedKhan101** [comment]
Oh nevermind I need to download candy to setup proxies.

**Comment by ErikMichelson** [comment]
> maybe you could consider adding these to the README

For HedgeDoc 1.x there are the links in the README file. For HedgeDoc 2.0 there's a link to the HD2 docs in general, but from there you'd also find that page. I doubt that there's anything more required at this point of time.
