### ISSUE TITLE
support rendering csv codeblocks as tables

### ISSUE THREAD

**Issue by tionis** [hedgedoc/hedgedoc#5565]
### Describe the solution you'd like

Codeblocks that have the language set to `csv` could render the content as a table.
There seems to have been some implementation for this in the old react client, but it doesn't seems like it was implemented in the migration.

### Describe alternatives you've considered

I considered writing a small userscript that does this, but that's not really a good solution and I think many other people would appreciate such a feature.

**Comment by ErikMichelson** [comment]
Hey @tionis,

thanks for your feature suggestion. As stated in the [readme file](https://github.com/hedgedoc/hedgedoc?tab=readme-ov-file), we're currently focusing on the development of HedgeDoc 2 and therefore don't add new features to HedgeDoc 1.x.

However, this feature has already been implemented in the upcoming version HedgeDoc 2.0, which can be tested out at <https://hedgedoc.dev>.
