### ISSUE TITLE
Feature Request: Allow transferring note ownership to different user

### ISSUE THREAD

**Issue by n-st** [hedgedoc/hedgedoc#557]

**Comment by davidmehren** [comment]
To centralize the discussion about this topic, I created https://github.com/hedgedoc/hedgedoc/issues/998
Please take a look and comment if you feel I missed an important aspect.  
Thanks!

**Comment by yurenchen000** [comment]
Don’t know when new features will be launched
I'll use it like this for now:

- Change Notes owner:
  Edit `Notes.ownerId` (column in database) manualy to change the owner of Notes

- Check Notes owner:
psql> `select id,"ownerId",title from "Notes";`
