### ISSUE TITLE
Share URL randomly crashes

### ISSUE THREAD

**Issue by boehs** [hedgedoc/hedgedoc#5573]
### Description

When I visit https://doc.boehs.org/s/socials in chrome, sometimes randomly it is blank. I see this in the console:

```
Uncaught SyntaxError: Invalid or unexpected token (at vendors~cover~cover-pack~index~index-pack~pretty~pretty-pack~slide~slide-pack.d107ac6ccdc2f7684946.js:10:32081)
```

When I click the link, I see this:

<img width="345" alt="image" src="https://github.com/hedgedoc/hedgedoc/assets/51836263/eb0264e5-85db-4f4b-976e-1e5d7d2dd479">

The strongest lead is https://github.com/feross/buffer/issues/330

### Steps to reproduce

1. Open chrome
2. https://doc.boehs.org/s/socials 
3. Pray to the bug gods
4. <img width="921" alt="image" src="https://github.com/hedgedoc/hedgedoc/assets/51836263/137fc61f-569b-4333-adfd-f035081872fc">

### Expected behaviour

The page correctly shows the page

### Your Setup

- Host OS: Alpine
- NodeJS version: Docker
- HedgeDoc version: 1.9.9 (latest)

**Comment by boehs** [comment]
Its clear there is some dependency in here that is being fucky. I'm not quite sure what it is, but 

"Number.toFixed: incorrect invocation!" is a good lead, leads to

- https://github.com/recharts/recharts/issues/1702
  - todo: what did they change in this version?

**Comment by boehs** [comment]
Probably has to do with cloudflare: https://community.cloudflare.com/t/cache-minify-breaking-script/386650/11

**Comment by boehs** [comment]
This is a bug introduced by cloudflare's bad minification scripts, which will be removed in 3 months.

![image](https://github.com/hedgedoc/hedgedoc/assets/51836263/505f932e-822b-45ef-a649-388e36178302)

**Comment by ErikMichelson** [comment]
Yes this is known and there's also a warning in the docs. 

https://docs.hedgedoc.org/guides/reverse-proxy/
