### ISSUE TITLE
Feature Request: Publicly accessible page that lists all notes with a given tag

### ISSUE THREAD

**Issue by n-st** [hedgedoc/hedgedoc#558]
Listing notes by tag is currently implemented within a user's history.
It would be useful to also have a public feature that lists all notes with a given tag. This could be used to "group" all notes concerning a certain topic or project, and allowing anyone to easily find them later.

**Comment by davidmehren** [comment]
To centralize the discussion about this topic, I created https://github.com/hedgedoc/hedgedoc/issues/994.  
Please take a look and comment if you feel I missed an important aspect.  
Thanks!
