### ISSUE TITLE
Demo instance down?

### ISSUE THREAD

**Issue by Saptaparna** [hedgedoc/hedgedoc#5587]
### Description

Hi, is the demo instance down and can it be restored so I can backup my notes? I know other people who rely on the demo instance too and once you restore the demo instance, I will request everyone I know to backup and not use the demo instance. Thanks!

### Steps to reproduce

Click on the demo instance: https://demo.hedgedoc.org/

### Expected behaviour

I get a 404 page not found error.

### Your Setup

Hedgedoc demo version.

**Comment by ErikMichelson** [comment]
Hi, yes the instance was down for a while.

We're currently facing a lot of spam and bot requests, and somehow the instance died and didn't recover.

Please remember that the demo instance is just for trying out HedgeDoc, but we encourage everyone to host their own instance or use another public one. https://hedgedoc.org/demo/

In addition, we have to add some counter-measures regarding the spam and bots. An official announcement will follow soon.

Thanks for your understandings

**Comment by lakonis** [comment]
I believe that the new counter-measures prevent my Flask application to `/download` properly demo.hedgedoc.org markdown source. Is there a way to fix this on my side ? Do I need to set up a token for CloudFlare ? 
Thanks !

**Comment by mrdrogdrog** [comment]
Sorry but no. As long as we have trouble with bots we can't lower the security checks.

**Comment by lakonis** [comment]
I understand. Would you say this is temporary ? Will you consider opening controlled access for application ?
Many thanks !

**Comment by yurenchen000** [comment]
I can't login use email and export my data  : (

**Comment by mrdrogdrog** [comment]
Everything is explained in this community post. https://community.hedgedoc.org/t/status-of-the-demo-instance/1634/14?u=mrdrogdrog

**Comment by mrdrogdrog** [comment]
For more support questions please the community board.
