### ISSUE TITLE
Accessible name of headings is redundant

### ISSUE THREAD

**Issue by xi** [hedgedoc/hedgedoc#5589]
### Description

Screen readers allow users to navigate a page by heading. It is therefore crucial that accessible names of headings are meaningful.

### Steps to reproduce

Create a heading in a pad. Then find the accessible name of the rendered heading (e.g. in Firefox: right click > Inspect Accessibility Properties)

For a heading called "My Heading", the accessible name should be "My Heading", but it is "My-Heading My Heading"

### Your Setup

- HedgeDoc version: 1.9.9

**Comment by ErikMichelson** [comment]
Hi @xi,

thanks for reporting. This has been fixed and will be included in the next 1.x maintenance release.

**Comment by davidmehren** [comment]
Fix released with 1.10.0
