### ISSUE TITLE
[html-to-react] Inline CSS custom properties (e.g. `--variable`) are incorrectly transformed

### ISSUE THREAD

**Issue by sxxov** [hedgedoc/hedgedoc#5596]
### Description

thanks for all your hard work on the project, it's super useful!

react handles css custom properties that are written as inline styles by eliding them & passing them to the DOM as is. however, this project's css property conversion fails to account for custom properties (starting with `--`) & incorrectly transforms them into mangled versions of them (e.g. `--foo-bar` -> `-fooBar`).

### Steps to reproduce

```js
import { convertNodeToReactElement } from '@hedgedoc/html-to-react';
import * as cheerio from 'cheerio';

// 1. load the element with `--foo-bar`
const el = cheerio.load('<div style="--foo-bar: hello" />', {}, false).root().get(0).childNodes[0];

// 2. pass it to html-to-react
const reactEl = convertNodeToReactElement(el);

// 3. get the styles
console.log(reactEl.props.style);

// in the console you will see:
// { "-fooBar": "hello" }
```

### Expected behaviour

``` js
// in the console you should see:
// { "--foo-bar": "hello" }
```

### Your Setup

- Host OS: Windows 11
- NodeJS version: v22.1.0
- HedgeDoc version: 2.1.1

**Comment by ErikMichelson** [comment]
Hey @sxxov,

thanks for reporting this issue and the steps to reproduce it, the problem is reproducible on our side too.
We'll look into it and report back when we've got any news.
