### ISSUE TITLE
Delete Note revisions

### ISSUE THREAD

**Issue by davidmehren** [hedgedoc/hedgedoc#560]
Should the owner of a note be able to
- delete specific revisions
- only delete all revisions
- delete no revisions at all?

In the last case it would still be possible to delete the note and recreate it with the last content, which is the same effect as "delete all revisions".

Note that in all cases, only the owner of a note would be able to delete something. Users with write permissions have the ability to "reset" a note to a previous revision, but that only appends a new revision with the content of that previous revision, so no content gets lost.

**Comment by DerMolly** [comment]
I think as you pointed out we can add an easier way to delete all revisions. Deleting some specific revision seem to be nice too, but it's a bit more involved. I think this can be done later, if we want to add it.
