### ISSUE TITLE
Preview of markdown numbered lists breaks when numbers are not continuous

### ISSUE THREAD

**Issue by iTrooz** [hedgedoc/hedgedoc#5605]
### Description

See image:
![image](https://github.com/user-attachments/assets/5f81f58e-a2dc-403a-ba6f-47bad7d806db)

Note that the last line is `6)` but preview as `5.`

### Steps to reproduce

- Go on https://hedgedoc.dev
- Create a new guest note
- Write the following:
```
1) aa
2) ee
4) zazazaz
5) 
6)
```

Notice the numbers in the preview are wrong

### Expected behaviour

The preview should mirror the numbers I've written

### Your Setup

https://hedgedoc.dev

**Comment by ErikMichelson** [comment]
This is intended behavior. According to the CommonMark specification (1), for ordered lists only the first number is relevant. 

> The start number of an ordered list is determined by the list number of its initial list item. The numbers of subsequent list items are disregarded.

This might seem unusual in the first place but quickly becomes handy when you need to add list items in between without having to re-number everything subsequent. Some people therefore actually use "1" for every item in their list.

(1): https://spec.commonmark.org/0.31.2/#lists
