### ISSUE TITLE
Admin Interface/CLI

### ISSUE THREAD

**Issue by davidmehren** [hedgedoc/hedgedoc#561]
We currently don't have an admin interface, so people who do administrative tasks (such as complying with GDPR-deletion-requests) need to access the database directly.
We should find a way to make admin-tasks easier, e.g. by creating an admin CLI.

**Comment by andynd** [comment]
We had the exact same problem and wrote one: https://git.cccv.de/infra/ansible/roles/hedgedoc/-/blob/master/files/hedgedoc-util.py
It's a pitty we had to access the db directly since there is no admin API.

**Comment by InnayTool** [comment]
New Issue for this #1003.
