### ISSUE TITLE
Extensibility of client templates and functions

### ISSUE THREAD

**Issue by GrazingScientist** [hedgedoc/hedgedoc#569]
I am currently crawling through the code and looking in how far I can just plug-in custom templates and functions both on client and server side.
Unfortunately, there is no documentation on this topic (at least, I could find none). Would it be possible to get some insights on this topic.

**Comment by davidmehren** [comment]
I'm not sure what you are looking for 😅, could you give an example what you want to achieve?

Generally, we currently don't have any kind of official API to extend CodiMD. This is something we could possibly fix in a 2.x release, after we gathered some feedback about common use-cases.

**Comment by GrazingScientist** [comment]
A probably simple example would be just to add a button + front-end functionality. For example, a button to search in the text with regex, to make it very simple. A button that adds markdown syntax to a marked text element.

**Comment by davidmehren** [comment]
While we generally are happy to add a plugin system to HedgeDoc, realistically this won't happen quickly. So please be patient :smiley:

**Comment by GrazingScientist** [comment]
I feared so! If you want to leave this issue open for later development that's fine. Otherwise, close!

**Comment by davidmehren** [comment]
I created https://github.com/hedgedoc/react-client/issues/1096 to discuss this further.
