### ISSUE TITLE
CodiMD in Cover screenshot

### ISSUE THREAD

**Issue by SISheogorath** [hedgedoc/hedgedoc#573]
**Description**
On the cover page the screenshot contains a CodiMD logo as part of the features page while stating being HedgeDoc.

**To Reproduce**
Look at https://demo.hedgedoc.org

**Expected behaviour**
The logo is not there, or replaced by a HedgeDoc logo.

**Your Setup:**
 - HedgeDoc version: https://github.com/hedgedoc/hedgedoc/tree/4c0efe1237bc33b52d06eaf86a28adad9a041ec2

**Comment by ritesh-pandey** [comment]
I can see HedgeDoc logo present in [screenshot image](https://demo.hedgedoc.org/screenshot.png).

**Comment by SISheogorath** [comment]
Yes, the editor has the right logo but inside the content we see an old one, as the screenshot was taken before  https://github.com/hedgedoc/hedgedoc/commit/a9026e0ec05abb72cad607a22f388aa22beca652
