### ISSUE TITLE
Same UserID when authenticating with multiple auth-providers

### ISSUE THREAD

**Issue by thenicejake** [hedgedoc/hedgedoc#5796]
### Which part of the project should be enhanced?

Same UserID when authenticating with multiple auth-providers

### Is your enhancement request related to a problem? Please describe.

I'm using Hedgedoc in a Docker Container with LDAP Authentication. I implemented Oauth2 (Keycloak as Provider) as additional authentication method.
When you log in with LDAP, the User gets a prefix in its database entry:
`profileid    | LDAP-username`

When you log in with Oauth2, the User *does not* get a prefix:
`profileid    | username`

The problem is, that there are two different users without any permissions to its documents.

### Describe the solution you'd like

Suggestion 1:
No prefix. Just use the same User object for every authentication method. It's the same User so there is no need for a prefix at all.

Suggestion 2:
Create a method to link both users when the system finds another User with the same profileid.

### Describe alternatives you've considered

The current solution is to deactivate the LDAP method - Oauth2 should be the primary auth method - and change the profileid database (PostgreSQL) entry to non-prefix:
`delete from public."Users" where profileid like 'username%' ;` (deletes the new created oauth2-user without any documents)
`update public."Users" set profileid = substring(profileid from 6) where profileid like '%username%' ;` (get rid of the first 5 characters (`LDAP-`) of the profileid column of the LDAP user and make it accessible with oauth2.

**Comment by ErikMichelson** [comment]
Hey @thenicejake,

thanks for your enhancement suggestion. As stated in the [readme file](https://github.com/hedgedoc/hedgedoc?tab=readme-ov-file), we're currently focusing on the development of HedgeDoc 2 and therefore don't add new features to HedgeDoc 1.x.

However, this feature has already been implemented in HedgeDoc 2, and thus I'm going to close this issue.

With the merge of #4827, new users in HedgeDoc 2 will be prompted to choose a username (no matter if LDAP or OIDC as auth source). This username is unique and not prefixed with any auth identifier. Afterwards, they can link other auth providers to that username.
