### ISSUE TITLE
更改完数据库密码，无法访问

### ISSUE THREAD

**Issue by zzqsmile** [hedgedoc/hedgedoc#5797]
### Description

更改完数据库密码，无法访问

### Steps to reproduce

更改完数据库密码，无法访问

### Expected behaviour

更改完数据库密码，无法访问

### Your Setup

- Host OS: [e.g. Ubuntu 20.04]
- NodeJS version: [run `node --version`]
- HedgeDoc version: (Click "Releases" in the footer)

**Comment by davidmehren** [comment]
Sorry, please use English to create issues in this project.
