### ISSUE TITLE
Avoid the authentication method dialog if only one is enabled

### ISSUE THREAD

**Issue by jmallach** [hedgedoc/hedgedoc#5802]
### Which part of the project should be enhanced?

authentication

### Is your enhancement request related to a problem? Please describe.

In my setup, only a OIDC provider is allowed for authentication. When trying to log in, I get presented with a dropdown menu to select an authentication method.

### Describe the solution you'd like

For setups with one authentication method, clicking on the Log in button should take you to your authentication provider directly, without needing to do an extra click on the "Login via <whatever>" button.

### Describe alternatives you've considered

None.

### Additional context

My setup is based on HedgeDoc 1.10.0 and Keycloak as an OIDC provider.

**Comment by ErikMichelson** [comment]
Hey @jmallach,

thanks for your feature suggestion. As stated in the [readme file](https://github.com/hedgedoc/hedgedoc?tab=readme-ov-file), we're currently focusing on the development of HedgeDoc 2 and therefore don't add new features to HedgeDoc 1.x.

This feature has already been implemented in HedgeDoc 2. 
When only a single OIDC provider is configured, the login button in the top bar links directly to that OIDC provider.

Therefore I'm going to close this issue.
