### ISSUE TITLE
Save the draft

### ISSUE THREAD

**Issue by TengshunYang** [hedgedoc/hedgedoc#5806]
### Is your feature request related to a problem? Please describe.

I cannot find the draft I have already written evenif I have logined in and I use the same link.
When I use the same link, it report 404 not found.

### Describe the solution you'd like

provide the feature of save for the users who loginin.

### Describe alternatives you've considered

preseve the link

**Comment by mrdrogdrog** [comment]
Drafts are always saved automatically. You don't need to save them manually. Every few minutes and when certain events happen, HedgeDoc writes the document into the database.

Can you provide some more information? Like where did that problem happen? Was it your own instance or a shared one? Do you know the version? Have you been able to reproduce the problem on demo.hedgedoc.org?

**Comment by ErikMichelson** [comment]
You're using the demo instance at demo.hedgedoc.org. As prominently pointed out when accessing the demo instance, notes are only kept for max 24 hours.

To keep your notes, setup your own instance or use another (publicly) available instance.

**Comment by TengshunYang** [comment]
How can I setup my own instance? Could you introduce some other (publicly) available instance?


---- Replied Message ----
| From | Erik ***@***.***> |
| Date | 10/2/2024 18:47 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [hedgedoc/hedgedoc] Save the draft (Issue #5806) |

You're using the demo instance at demo.hedgedoc.org. As prominently pointed out when accessing the demo instance, notes are only kept for max 24 hours.

To keep your notes, setup your own instance or use another (publicly) available instance.

**Comment by DerMolly** [comment]
> How can I setup my own instance?

There are multiple installtion guides listed on our docs page here https://docs.hedgedoc.org/setup/getting-started/.

> Could you introduce some other (publicly) available instance?

There is this thread in our community forum. https://community.hedgedoc.org/t/public-instances/282
