### ISSUE TITLE
Can't insert a forward slash "/" with a Brazilian input source

### ISSUE THREAD

**Issue by danielpetri1** [hedgedoc/hedgedoc#5842]
### Description

I use the Brazilian ABNT2 keyboard, where the forward slash is inserted with ⌥ + Q on a Mac. This works fine with all other applications, web-based or otherwise.

### Steps to reproduce

1. Press Option + Q when writing a note

### Expected behaviour

See the symbol /

### Your Setup

- Firefox 131.0.2 (aarch64)
- Host OS: MacOS 15.0.1 (24A348)
- HedgeDoc version: 1.10.0

The physical keyboard layout is Portuguese (Portugal), only the input source is Brazilian.

### Additional context

I also run into this problem on a Hedgedoc 1.9.9 instance.

**Comment by ErikMichelson** [comment]
Hi @danielpetri1,

thanks for reporting this issue.
Could you test whether this issue also occurs on the new 2.0-preview deployment at https://hedgedoc.dev? It sounds as if the problem resides in the used editor library which has been updated to a new major version for the upcoming version 2.0.

**Comment by danielpetri1** [comment]
Hi @ErikMichelson, thanks for the reply. It works as intended on the 2.0 preview deployment.

**Comment by DerMolly** [comment]
Then I'll close this issue.
