### ISSUE TITLE
type a short title of your bug report here

### ISSUE THREAD

**Issue by huiyuchen708** [hedgedoc/hedgedoc#5853]
### Description

Why am I getting this kind of page after deploying with Docker?
![image](https://github.com/user-attachments/assets/da04c4f3-5946-40f4-858f-ab129dfcb49d)

### Steps to reproduce

access http://localhost:3000

### Expected behaviour

Page Error

### Your Setup

- Host OS: [e.g. Ubuntu 20.04]
- NodeJS version: [run `node --version`]
- HedgeDoc version: (Click "Releases" in the footer)

**Comment by ErikMichelson** [comment]
Please fill out the issue template and title correctly. 
Without additional information nobody is able to help you. 

Also see this FAQ entry: https://docs.hedgedoc.org/faq/#why-does-my-interface-look-weird
