### ISSUE TITLE
CSS Injection: This is a vulnerability and I might have a way forward for you

### ISSUE THREAD

**Issue by koraa** [hedgedoc/hedgedoc#587]
Hi,

in #136 the ability to inject CSS was reported as a bug. The report was closed as "this is a feature".

I agree it is a cool feature, but I am pretty sure it is also a security vulnerability. I am sure there are worse payloads than "blank the page", if it is really necessary for me to find such payloads I can start a search, but it would save us time if that wasn't necessary.

I suggest the minimum step forward should be sand boxing the rendered markdown; put it in an iframe so any CSS cannot affect the rest of the page.

I would also suggest that this issue be left open for now to track the implications of this and develop new sandboxing ideas.

**Comment by koraa** [comment]
https://github.com/hedgedoc/hedgedoc/issues/587

**Comment by mrdrogdrog** [comment]
Hi,

Thanks for your issue. We discussed this bug in our public matrix room, and unfortunately it seems like it isn't so easy to fix. The current code base of hedgedoc is very messed up and wrapping an iframe around the renderer would potentially break a lot of stuff and create new bugs. Therefore we're probably not gonna fix it in 1.x.
However: Right now we're developing HedgeDoc 2.0, which is a complete rewrite. I created an issue in the frontend repo for that.

https://github.com/hedgedoc/react-client/issues/762

**Comment by mrdrogdrog** [comment]
(I'm not closing this issue, because right now we're discussing, if we add a hotfix)

**Comment by hugopeixoto** [comment]
If you're using 1.6.0, I've created a patch that lets you enable/disable CSS rendering via an environment variable: https://github.com/hedgedoc/hedgedoc/commit/9932f1cac2dcdc0793e3e2cae349f107d5bd450a / https://github.com/hugopeixoto/hedgedoc/tree/development/1.6.1

It's not ideal but it works as a stopgap measure if you want this fixed before 2.0. I'll try to do the same for 1.7 when it is released.

**Comment by mrdrogdrog** [comment]
We discussed it and the conclusion is, that we won't fix this for 1.7. The effort is too big and want to focus on 2.0.
