### ISSUE TITLE
`breaks: false` as a global setup option

### ISSUE THREAD

**Issue by offray** [hedgedoc/hedgedoc#59]
Hi,

I have been using CodiMD with great success in book sprints, workshops and document-athons. But in all of them I have observed that starting all documents in CodiMD with `breaks: false` in the YAML metadata block seems contra-intuitive for most of the people who already know Markdown, as they expect no hard breaks with single new line feeds and paragraphs be started with two line feeds, as in most Markdown processors.

Following the principle of least surprise, could the `breaks: false` YAML directive be setup as a global preference for all pads created in a particular CodiMD instance? (making `breaks: true` the directive you want to enable at the beginning of documents, if you want single line feed hard breaks)

Thanks,

**Comment by SISheogorath** [comment]
You can prepare a default template into the public/default.md and put it there:

```
---
breaks: false
---
```

There is just minor issue, we start in view mode right now, which we should change so it always results in `?both`. But that's something I'll prepare as a PR soon :)

**Comment by hoijui** [comment]
I would second the original proposal. The default should be Markdown standard conform. How likely is it, that anyone who will edit a document, or who sets up a CodiMD instance will know about this feature? Also if you do know, it still means extra work when you copy a document to or from CodiMD (adding/removing these lines).

**Comment by SISheogorath** [comment]
I think we should start with moving the document options into a separate dataset in the datebase. This will allow changes to the defaults in future without breaking existing documents. And also make it easier to set such defaults.

**Comment by ccoenen** [comment]
Would this extend to all the YAML metadata? I would like to avoid having two places to store stuff.

**Comment by SISheogorath** [comment]
Yes, it would break the current YAML-metadata out of the document. Make the editor more focused on editing the document and remove CodiMD specific settings from it by moving them into a separate field, settings page, or similar.

**Comment by InnayTool** [comment]
This is in Discussion in https://community.hedgedoc.org/t/should-we-change-the-hedgedoc-default-for-breaks-from-true-to-false/298/12.

**Comment by davidmehren** [comment]
The poll in our forum was quite split between changing the global default and keeping it as-is. Luckily, a new idea for handling this problem emerged:

We could introduce a new setting for each user, where the preferred break-behavior can be configured. When the user then creates a new note, the frontend would automatically generate YAML front matter with the setting. That way the breaks will behave the same way for everyone in the document, but at least new notes will follow the preference of the respective user.

Additionally, we could also introduce a global option to set the default for all users.

**Comment by ccoenen** [comment]
In that case, the easier way would be to allow a custom "default new document" per user, where that user could just also add front matter. But not only for the break behaviour, but for everything including tags or often used diagrams or things like that.

**Comment by DerMolly** [comment]
If we want to go the default template route (and I'm not sure we really want this) this [issue](https://github.com/hedgedoc/react-client/issues/90) should be relevant…

**Comment by SISheogorath** [comment]
I like the idea @ccoenen suggested, because in the database this results in just one new column in the user table, while adding defaults as settings into the database in a way that allows to generate the front-matter will require to dublicate all front-matter settings into the database unless we want to use some sort of JSON or text field and just shove it in there, hoping it never breaks.

**Comment by offray** [comment]
Anything that allows the line breaking default behavior from most common formats and editors for Markdown (variants)
will be fine for me. 

I think that the issue will be solved once new users don't need to add anything extra manually in their YAML metadata and get the expected behavior that the one in Pandoc, Zettlr, and will support [semantic line breaks](https://sembr.org/) inside the same paragraph. Meanwhile this issue/feature request should remain open. 

Thanks for reviving the discussion.

**Comment by mrdrogdrog** [comment]
IMHO this discussion is over. Therefore this issue should be closed. As far as I know all core devs are fine with the idea of custom templates (even if this is more of a "after 2.0" feature).

So I propose that we close this discussion issue and create actionable tickets for implementing custom templates.

@DerMolly @davidmehren @InnayTool @ErikMichelson do you agree?

**Comment by offray** [comment]
I'm fine with closing it. And will be waiting for the news on the actionable tickets that allow semantic breaks and compatibility with wide spread Markdown variants. No rush, I always put `breaks: false` by hand with the current behavior of HedgeDoc in the YAML metadata and teach others to do it, for compatibility with external tools.
