### ISSUE TITLE
demo.hedgedoc.org seems to be down

### ISSUE THREAD

**Issue by rogerluan** [hedgedoc/hedgedoc#604]
**Description**
demo.hedgedoc.org seems to be down for the past ~30 minutes-ish:

<img width="987" alt="image" src="https://user-images.githubusercontent.com/8419048/100484638-046b2080-30dc-11eb-8011-0a9148a66afb.png">

**To Reproduce**

Visit https://demo.hedgedoc.org 

**Expected behavior**
The website should work.

**Additional context**

I was using the website to update a document, and it suddenly stopped working (nothing was editable anymore). When I tried refreshing, I'm facing the issue shown in the screenshot above.

I couldn't find any status page, twitter account or such 🤷 So I'm posting here 😅 

JW when it's going to be back up 🙏

**Comment by mrdrogdrog** [comment]
Sorry for the inconvenience. We're on the it!

We recommend to not use the demo instance for important documents, but rather suggest to setup your instance for production use.
If you want to know more about the topic "How stable is the demo?" please read
https://community.codimd.org/t/how-stable-is-the-demo/88/2

**Comment by mrdrogdrog** [comment]
It should be back now.

**Comment by rogerluan** [comment]
I had no idea it wasn't supposed to be used in production 😮 I'll keep that in mind.
Thanks!
