### ISSUE TITLE
Feature Request: Add the ability to follow someone's cursor

### ISSUE THREAD

**Issue by ZZYSonny** [hedgedoc/hedgedoc#606]
**Is your feature request related to a problem? Please describe.**

Currently if someone is writing at the end of document. Other users have to constantly scroll down to read latest text. 

**Describe the solution you'd like**

Add an option to follow someone's cursor. 

**Describe alternatives you've considered**

Or could go the other side. Someone requests everyone to follow its cursor. 

**Additional context**

**Comment by DerMolly** [comment]
I think this is already covered by https://github.com/hedgedoc/react-client/issues/281 and can be closed…

**Comment by davidmehren** [comment]
Yep, looks like we already track that feature in the new frontend.

Duplicate of https://github.com/hedgedoc/react-client/issues/281
