### ISSUE TITLE
SSL and reverse proxy breaks authentication

### ISSUE THREAD

**Issue by titulebolide** [hedgedoc/hedgedoc#616]
**Description**
I you uses hedgedoc behind a reverse-proxy with SSL, the auth don't work

**To Reproduce**
- Run hedgedoc on localhost:3000, set protocolUseSSL to true and domain to example.com
- setup a reverse-proxy with ssl between https://example.com and localhost:3000
- Ho no! Authentication on hedgedoc don't work

**Additional context**
Some experiments to conduct:

From the "to reproduce":
- Stop the server
- Disable ssl in config.js and in your reverse proxy conf
- Wow authentication works back!
- Stop the server
- Re enable the ssl in config.json and in your reverse proxy
- Wow authentication works again!

Now try:
- open another browser, and try again, authentication don't work
- but copy the cookie  `connect.sid` from the working browser to this new one : authentication works back! you can disconnect, and connect back!

Try also on the working browser:
- Disconnect on the working browser, you can still connnect back
- Delete the `connect.sid` cookie. Authentication is broken.

**Conclusion**
`connect.sid` and SSL are sus

**Config**
Reverse-proxy with Apache2:

```apache
<VirtualHost *:80>
        Redirect permanent / https://example.com/
        ServerName example.com
</VirtualHost>

<VirtualHost *:443>
    ServerName example.com
    ProxyPass / http://127.0.0.1:3000/
    ProxyPassReverse / http://127.0.0.1:3000/

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined

    SSLCertificateFile /etc/letsencrypt/live/example.com/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/example.com/privkey.pem
    Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
```

Thanks for hedgedock! :hedgehog:

**Comment by Luxumbra27** [comment]
I have the exact same issue, the same setup (Apache https reverse proxy) used to work on CodiMD 1.6.0. The project is amazing (thanks !) so I wanted to try out the 1.7.0, but I can't use it without the any log in functionality.
No error anywhere, so I don't know where to look for the problem...
My browser does not have the `connect.sid `cookie it used to. So as @titulebolide says, the issue comes from this.

**Comment by titulebolide** [comment]
Glad I'm not the only one to experience that. Weirdly enough the demo version is using ssl, but not with the same scheme as us.
i think I will give a try to make it run under nginx but I don't think it will solve amything...

**Comment by davidmehren** [comment]
Please make sure that `protocolUseSSL` is set to `true` and `useSSL` is set to `false`, so that HedgeDoc will [trust your reverse proxy](https://github.com/hedgedoc/hedgedoc/blob/e9973a28d41ef4af0af60ccfd725d9e39df32faf/app.js#L58). 

Sadly, I don't use Apache and can't tell if something is wrong with the config you use. :/

**Comment by titulebolide** [comment]
> Please make sure that protocolUseSSL is set to true and useSSL is set to false
It does!
Is it tested against nginx?

**Comment by titulebolide** [comment]
there is a special line in the docs for socket.io, is it mandatory?

**Comment by titulebolide** [comment]
As someone mentionned it on matrix, it shown the same symptoms on nginx before using the suggested headers. Maybe it would be worth it to translate cautiously the nginx conf to apache2

**Comment by davidmehren** [comment]
I set up a fresh Ubuntu 20.04 VM with Apache2 to debug the issue. I noticed that HedgeDoc does not even try to send a `Cookie` header when behind Apache.
It seems Apache does not send `X-Forwarded-Proto` headers by default, so we don't send any cookies as we think the connection is not secure. Adding `RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}` solved the issue.

My full Apache config looks like this:
```
<VirtualHost *:443>
        ServerName hedgedoc.example.org

        RewriteEngine on
        RewriteCond %{REQUEST_URI} ^/socket.io             [NC]
        RewriteCond %{HTTP:Upgrade} =websocket [NC]
        RewriteRule /(.*)  ws://127.0.0.1:3000/$1          [P,L]

        ProxyPass / http://127.0.0.1:3000/
        ProxyPassReverse / http://127.0.0.1:3000/

        RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
## stuff for logs & certificates removed
</VirtualHost>
```

**Comment by davidmehren** [comment]
As mentioned in the PR, we now set the `secure` flag of our session library when TLS is enabled in the config. This means that if the app is not sure if the connection is secure, it will not send any cookies. This is by design, so I removed the 'bug' label. I also plan to mention this in our release notes, so everyone can make sure their reverse proxy sets the `X-Forwarded-Proto` header.

**Comment by Luxumbra27** [comment]
Thank you very much @davidmehren ! This solved the issue !

**Comment by titulebolide** [comment]
It worked perfect! I close this issue :)

**Comment by leandroembu** [comment]
This never worked for me since 2023, I'm using [this nginx reverse proxy](https://docs.hedgedoc.org/guides/reverse-proxy/#nginx) and Nextcloud's oAuth. After authentication I get the logged out home page.

**Comment by titulebolide** [comment]
@leandroembu  for reference, here is my current configuration:
```
<VirtualHost *:80>                                                   Redirect permanent / https://(redacted)/
        ServerName (redacted)
</VirtualHost>

<VirtualHost *:443>
    ServerName (redacted)

    RewriteEngine on
    RewriteCond %{REQUEST_URI} ^/socket.io             [NC]
    RewriteCond %{HTTP:Upgrade} =websocket [NC]
    RewriteRule /(.*)  ws://127.0.0.1:xxxxx/$1          [P,L]

    ProxyPass / http://127.0.0.1:xxxxx/
    ProxyPassReverse / http://127.0.0.1:xxxxx/

    RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
SSLCertificateFile /etc/letsencrypt/live/(redacted)/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/(redacted)/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
```

**Comment by leandroembu** [comment]
@titulebolide thank you.

I'm using a nginx reverse proxy following HedgeDoc's documentation, useSSL=false and CMD_PROTOCOL_USESSL=true. Nextcloud's oAuth returns to my logged out home page. It only works if I set CMD_PROTOCOL_USESSL=false, but I got "mixed content" in the browser (assets served without SSL), and things like reveal.js don't work.
