### ISSUE TITLE
Enhancement request: add new time format

### ISSUE THREAD

**Issue by misaka00251** [hedgedoc/hedgedoc#617]
**Which part of the project should be enhanced?**

`[time]` in hedgedoc

**Is your enhancement request related to a problem? Please describe.**

**Describe the solution you'd like**

Currently, you can only write in format like this: `[time=Dec 04, 2020]`

**Describe alternatives you've considered**

Add another format like `[time=2020/12/04]` or `[time=2020-12-04]` will be awesome!

**Additional context**

**Comment by DerMolly** [comment]
This is already fixed in the new [client for version 2.0](https://github.com/hedgedoc/react-client). Feel free to play around with it on the [ui-test](https://ui-test.hedgedoc.net). But as far as I could test everything you wanted works there. It even does outside of block quotes.
