### ISSUE TITLE
Feature request: Allow view / edit permissions to individual users

### ISSUE THREAD

**Issue by milanlakhani** [hedgedoc/hedgedoc#620]
**Is your feature request related to a problem? Please describe.**
I would like to be able to select specific users, most likely via e-mail address, to be able to view and edit documents (rather than just assigning permissions to 'Signed-in people' or 'Anyone').

**Describe the solution you'd like**
I am happy to contribute this change myself. Next to the Limited/Freely/Editable/Locked etc dropdown, I can implement a 'Share'/'Invite' button that opens a window where the Note owner can enter the e-mail addresses (possibly with the option of usernames instead) of people to give permissions to and select whether these people have view or edit access. The popup window could also include a list of current note contributors and options to change their permissions.

**Describe alternatives you've considered**
#471 on adding share links is related to this. This should be a smaller change, the API would not need to understand an additional authtype URL as mentioned in that issue.
This feature would keep the document permission type list (Limited, Freely, Editable etc) as is, with a separate button to add additional users.
The provider of the authentication could affect whether it's possible to list and search e-mail addresses / usernames with autocomplete. If SAML is used this may not be possible.

**Comment by ErikMichelson** [comment]
You mean an interface like this? If so, keep expecting version 2.0.

![image](https://user-images.githubusercontent.com/52606896/101405096-deadfa80-38d7-11eb-97ad-2167735a6e5a.png)

**Comment by milanlakhani** [comment]
Looks good :) Do you know approximately when release 2.0 will come out?

**Comment by mrdrogdrog** [comment]
Sometime in 2021 😅
There is still a lot to do.

**Comment by milanlakhani** [comment]
Good to know mrdrogdrog :)

**Comment by InnayTool** [comment]
The feature is merged into the `develop` branch and will be part of 2.0.
