### ISSUE TITLE
Support multiple gitlab providers

### ISSUE THREAD

**Issue by lu-zero** [hedgedoc/hedgedoc#621]
I'd like to allow authentication using both `gitlab.com` and other gitlab instances. As [discussed on matrix](https://matrix.to/#/!ybaSlrrMNLeuoQuUuR:matrix.org/$16077153553pWsiY:kif.rocks?via=matrix.org&via=shivering-isles.com&via=kif.rocks) there are plans to support multiple openauth and saml, this issue is opened as reminder.

**Comment by DerMolly** [comment]
I think this is fixed since #733 was merged
