### ISSUE TITLE
Add an option to modify key bindings in vim mode.

### ISSUE THREAD

**Issue by varamsky** [hedgedoc/hedgedoc#630]
**Which part of the project should be enhanced?**

The vim mode should have options to modify the default key bindings.

**Is your enhancement request related to a problem? Please describe.**

I see that you have vim mode in HedgeDoc similar to any other platform supporting vim mode for editing, but I think all of these platforms, including this one, lack a very important feature. One should be able to modify vim bindings to their liking. For example, in my `.vimrc file` I have modified it to use `j k l ;` for navigation instead of the default `h j k l`, similarly I use `jk` to go to normal mode instead of moving all the way to `ESC`. I'm new to this software and I'm liking it but the vim mode that you currently provide is practically useless for me, or anyone who is used to a vim binding different than the defaults.

**Describe the solution you'd like**

You definitely realize that people love to configure vim and such software completely to their likings so you should definitely consider enhancing your vim mode feature to support a separate vimrc configuration as specified by the user.

Ideally, if I am logged in to my account then, in my profile I should be able to add a .vimrc file or maybe have a TextField where I can add my vimrc configurations and save them. Now when I do editing in vim mode, these personalized vim configs should be used instead of the default key bindings.

I think that such a feature is a must in all platforms that provide vim mode to the user, so please do work on this issue.

**Comment by DerMolly** [comment]
As I can understand this request fully. I must point you in the direction of codemirror, from which this vim mode of the Editor originates. We just make it possible for our users to activate this mode in HedgeDoc.

**Comment by davidmehren** [comment]
As mentioned at https://codemirror.net/demo/vim.html, the CodeMirror vim keymap is currently unmaintained and seems to have [multiple issues](https://github.com/codemirror/codemirror/issues?page=2&q=is%3Aissue+is%3Aopen+label%3Avim).

I'd actually think about dropping these keybindings altogether in 2.0 instead of shipping something broken.

Regarding configuring the keymap in some kind of settings dialog: That seems generally possible, but is a lot of work. I'm not sure this is something we will build, but contributions are of course welcome.

**Comment by varamsky** [comment]
> As mentioned at https://codemirror.net/demo/vim.html, the CodeMirror vim keymap is currently unmaintained and seems to have [multiple issues](https://github.com/codemirror/codemirror/issues?page=2&q=is%3Aissue+is%3Aopen+label%3Avim).
> 
> I'd actually think about dropping these keybindings altogether in 2.0 instead of shipping something broken.
> 
> Regarding configuring the keymap in some kind of settings dialog: That seems generally possible, but is a lot of work. I'm not sure this is something we will build, but contributions are of course welcome.

I didn't know that HedgeDoc used CodeMirror service for editor support.

I think that this feature should be available in every online code editor but sadly, is present in none(as per my limited knowledge).

Therefore, I would again **emphasize the usefulness** of this so that the community can come together to build something to **solve this issue** :pray: :smile:

**Comment by DerMolly** [comment]
Let's get to what we would exactly need to build here:

Modifiable:
- the movement keys
- back to normal mode key
- visual / insert / insert and new line key

Anything else?

**Comment by varamsky** [comment]
> Let's get to what we would exactly need to build here:
> 
> Modifiable:
> 
> * the movement keys
> * back to normal mode key
> * visual / insert / insert and new line key
> 
> Anything else?

These mentioned here are complete for me and my use case. But a popular application like yours should cater to the needs of a larger audience, for which a vimrc implementation will be required.

But again, if you ask me then I'm okay with these modification options.

**Comment by davidmehren** [comment]
As this is unresolvable by us without upstream support, I'm going to close this for now.

**Comment by xeruf** [comment]
Looks like there is some upstream support, but it is not entirely clear to me: https://github.com/codemirror/CodeMirror/issues/2841
