### ISSUE TITLE
Firefox preventing inclusion of PDFs

### ISSUE THREAD

**Issue by famfop** [hedgedoc/hedgedoc#631]
**Description, How to reproduce, Log**

Open the official feature-Pad using firefox and go to the pdf-subsection: https://demo.hedgedoc.org/features#PDF . Instead of showing the actual pdf it does show nothing. The Webconsole reports (among various other issues): 'The loading of “https://papers.nips.cc/paper/2014/file/a14ac55a4f27472c5d894ec1c3c743d2-Paper.pdf” in a frame is denied by “X-Frame-Options“ directive set to “DENY“.' 

**Expected behavior**

Show the pdf.

**Logs**

**Config**

**Your Setup (please complete the following information):**
 - Host OS: Manjaro 
 - NodeJS version [run `node --version`] v15.3.0
 - HedgeDoc version (Click "Version info" in the footer)
     - server [e.g. 2.0]
     - client [e.g. 2.0]

**Additional context**

**Comment by davidmehren** [comment]
It seems the server our demo-PDF is loaded from now sets this header.
Did you try including other PDFs?

**Comment by famfop** [comment]
It did work with a paper from arxiv.org! How could I solve the problem with the header? Also, is it possible to include local PDFs? I was not able to do it using a file:///path/to/file.pdf which does make sense. But at the same time you may want to include local PDFs...

**Comment by davidmehren** [comment]
The server that hosts the PDF must either not set the `X-Frame-Options` header or include `allow-from <your_hedgedoc_instance>`. 
It is good security practice to set `X-Frame-Options: SAMEORIGIN`, which disallows embedding from other origins.
This has the unfortunate side effect that simply using the URL of random PDFs does not work when the server hosting that PDF is properly configured.

We really can't do much about that. If you want to include a PDF in a HedgeDoc note, you need to make sure that it is hosted on a server that allows embedding.

As for using a `file://` URI: I don't think it is possible to use these URIs on pages that are not loaded from a file. Allowing this would allow any website to access arbitrary files on you computer, which your probably don't want.
