### ISSUE TITLE
Error migrating from CodiMD 1.5.0

### ISSUE THREAD

**Issue by moepman** [hedgedoc/hedgedoc#641]
**Description**
An error occurs when migrating from CodiMD 1.5.0.

**To Reproduce**
1. Install CodiMD Server 1.5.0
2. Upgrade to HedgeDoc 1.7.1. according to the documentation

**Expected behavior**
No error when running `NODE_ENV=production yarn start`

**Logs**
```
/opt/hedgedoc-1.7.1$ NODE_ENV=production yarn start
yarn run v1.22.5
$ sequelize db:migrate && node app.js

Sequelize CLI [Node: 10.21.0, CLI: 5.5.1, ORM: 5.22.3]

Parsed url postgres://hackmd:*****@localhost:5432/hackmd
== 20200321153000-fix-account-deletion: migrating =======

ERROR: constraint "Notes_owner_fkey" for relation "Notes" already exists

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Config**

**Your Setup (please complete the following information):**
 - Host OS: Debian 10
 - NodeJS version: 10.21.0
 - HedgeDoc version: 1.7.1

**Additional context**

**Comment by davidmehren** [comment]
This looks like another bug with the migrations. For some reason, Sequelize sometimes runs the migration, but does not save that it did that. It then tries to run the migration again and produces an error.
The simplest fix is adding the migration to the `SequelizeMeta` table. In your case, you should be able to fix the problem by adding the line `20200321153000-fix-account-deletion.js` in that table.

**Comment by moepman** [comment]
In the meantime I removed the offending fkey constraint that was already there from `20200321153000-fix-account-deletion.js` which also made it run through the whole migration.

**Comment by davidmehren** [comment]
Great to hear!
