### ISSUE TITLE
/me route does not respect the url path configuration

### ISSUE THREAD

**Issue by lnhrdt** [hedgedoc/hedgedoc#642]
**Description**

The `/me` route doesn't respect the url path configuration.

**To Reproduce**

1. Deploy hedgedoc with a `CMD_URL_PATH` environment variable (e.g. `/docs`)
2. Load the web page
3. Use browser tools to observe that a request is made to `/me` instead of `/docs/me`

**My Setup:**

docker: `quay.io/hedgedoc/hedgedoc@sha256:96411fa3ad535b638c1a7dcb2136623df06510de0cde53ad778f18f9e43e8bd9`

**Additional context**

Perhaps related to #475

**Comment by lnhrdt** [comment]
I believe this was a configuration error on my end, not a bug in the software. Closing.

**Comment by lnhrdt** [comment]
The issues is back intermittently. I don't believe it is a cache related issue on my end. Now I can reproduce the error (intermittently) by refreshing the page.

**Comment by DerMolly** [comment]
Me and @ErikMichelson tried to replicate this problem and it weren't able to replicate this.

But we noticed that in the Networktab (at least in Firefox) the request is shown in the table as if it only calls `/me` but it does in fact, when you click on it call `/subdir/me`.

![image](https://user-images.githubusercontent.com/3978662/111027283-94b14500-83ef-11eb-89fc-c23df8aa284b.png)

Could this be what you noticed, @lnhrdt?

**Comment by DerMolly** [comment]
Current theory is that there was no bug, so I'll close the issue. If there still is, feel free to reopen.
