### ISSUE TITLE
CLI based configuration management

### ISSUE THREAD

**Issue by EV21** [hedgedoc/hedgedoc#643]
It would be nice if you provide a CLI for configuration management so there is no need to manually edit config files, like .env, json etc.

I don't like to edit config files. A config management system could prevent users from setting invalid settings or breaking the syntax.

Suggestion: Management commands could be context sensitive like this:
`config:database:set:dialect mysql`
`config:database:set:name hedgedoc`
`config:database:set:password "magic!1234"`
`config:database help` -> list all options for database like `set`, `get`, etc.
`config help` list all options for config 

(this is inspired from the very nice Nextcloud CLI)

Maybe the setup script could also catch some basic parameters for initialisation like: 
`--db='mysql' --db-user=hedgedoc --db-password="magic!1234" --db-name=hedgedoc`

This idea could also apply to user and content/permission management. #561

**Comment by davidmehren** [comment]
HedgeDoc 2 will have a new config system using environment variables or a `.env` file. This file will be easily editable by common tools.
The config will be automatically validated on application startup.

We also have https://github.com/hedgedoc/hedgedoc/issues/1003, which tracks implementation of an admin CLI.
