### ISSUE TITLE
Remove the IE (Internet Explorer) from the Browser support in README.md

### ISSUE THREAD

**Issue by mirguest** [hedgedoc/hedgedoc#645]
Dear developers,

I found the hedgedoc did not work in IE. Should we remove IE from the list?
* Link: https://github.com/hedgedoc/hedgedoc#browser-support

Thank you!

Tao

**Comment by SuperSandro2000** [comment]
> did not work in IE

What did not work?

**Comment by mirguest** [comment]
> > did not work in IE
> 
> What did not work?

When I use IE to create a new note in demo.hedgedoc.org, it is blank.

![image](https://user-images.githubusercontent.com/831611/103432854-bccb3d80-4c21-11eb-90b0-ab459029e813.png)

My Windows version is Windows 10 20H2.

Thanks.

**Comment by InnayTool** [comment]
The problem is that IE 11 does not support default arguments in function definitions and that is required by the webpack output. Maybe it is possible to edit the webpack configuration to support IE 11 again, but we don't think it's worth it. So we going to remove it from the list.
