### ISSUE TITLE
OAuth2 log in is not working

### ISSUE THREAD

**Issue by jimmy09140456** [hedgedoc/hedgedoc#647]
**Description**
After upgraded to HedgeDoc version 1.7.1, OAuth2 is not working. And the previous 1.6.0 is working fine.
I've tried both RocketChat and NextCloud OAuth provider and both are not working.

**To Reproduce**
1. Go to the home page
2. Click on Sign in button
3. Click OAuth2 sign in and it will redirect to RocketChat 
4. Authorize successfully and it will go back to HedgeDoc
5. Nothing happen, not log in and no error log

**Expected behavior**

Supposed I should see my previous notes.

**Logs**
```
Jan 03 22:27:29 my-host-name yarn[16263]: 2021-01-03T14:27:29.808Z info:         my:ip:v6:address - - [03/Jan/2021:14:27:29 +0000] "GET /auth/oauth2 HTTP/1.1" 302 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"
Jan 03 22:27:32 my-host-name yarn[16263]: 2021-01-03T14:27:32.637Z info:         my:ip:v6:address - - [03/Jan/2021:14:27:32 +0000] "GET /auth/oauth2/callback?code=xxxxxxxxxxxx&state=xxxxxxxxxxxx HTTP/1.1" 302 126 "https://rocketchat.host.name/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"
Jan 03 22:27:33 my-host-name yarn[16263]: 2021-01-03T14:27:33.141Z info:         my:ip:v6:address - - [03/Jan/2021:14:27:33 +0000] "GET / HTTP/1.1" 304 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"
Jan 03 22:27:33 my-host-name yarn[16263]: 2021-01-03T14:27:33.352Z info:         my:ip:v6:address - - [03/Jan/2021:14:27:33 +0000] "GET /config HTTP/1.1" 304 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"
Jan 03 22:27:34 my-host-name yarn[16263]: 2021-01-03T14:27:34.640Z info:         my:ip:v6:address - - [03/Jan/2021:14:27:34 +0000] "GET /me HTTP/1.1" 304 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"
```

**Config**
```
        "oauth2": {
                "clientID": "secret",
                "clientSecret": "secret",
                "authorizationURL": "https://rocketchat.host.name/oauth/authorize",
                "tokenURL": "https://rocketchat.host.name/oauth/token",
                "userProfileURL": "https://rocketchat.host.name/api/v1/me",
                "userProfileUsernameAttr": "username",
                "userProfileDisplayNameAttr": "username",
                "userProfileEmailAttr": "emails.address"
        },
```

**Your Setup (please complete the following information):**
 - Host OS: Gentoo
 - NodeJS version v12.18.4
 - HedgeDoc version 1.7.1

**Additional context**

I can provide more information if needed.

**Comment by jimmy09140456** [comment]
I've enabled the url path configuration. Not sure does it matter?

```
        "urlPath": "hackmd",
```

**Comment by jimmy09140456** [comment]
I found the solution from here: https://community.hedgedoc.org/t/using-nginx-as-a-reverse-proxy/244

I need to add the following configuration to my nginx server:

```
proxy_set_header Host $host; 
proxy_set_header X-Real-IP $remote_addr; 
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
proxy_set_header X-Forwarded-Proto $scheme;
```

Anyway I will close this bug.

**Comment by leandroembu** [comment]
> I found the solution from here: https://community.hedgedoc.org/t/using-nginx-as-a-reverse-proxy/244
> 
> I need to add the following configuration to my nginx server:
> 
> ```
> proxy_set_header Host $host; 
> proxy_set_header X-Real-IP $remote_addr; 
> proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
> proxy_set_header X-Forwarded-Proto $scheme;
> ```
> 
> Anyway I will close this bug.

OAuth2 (Nextcloud) is not working here, even though my reverse proxy has the mentioned settings.

Version: 1.9.9
