### ISSUE TITLE
CI & code coverage

### ISSUE THREAD

**Issue by davidmehren** [hedgedoc/hedgedoc#654]
**Which part of the project should be enhanced?**
Continous integration

**Describe the solution you'd like**
The CI should
- [x] check for linting errors
- [x] make sure `tsc` is happy
- [x] check if the code is correctly formatted
- [x] run integration tests
- [x] run e2e tests
- [x] collect coverage information
- [ ] maybe run tests on all supported databases (this might be complicated/slow)

**Describe alternatives you've considered**
No CI or running the tests only locally

**Comment by InnayTool** [comment]
I think we should create a test script for all supported databases but don't add them to the CI.

**Comment by davidmehren** [comment]
Superseded by https://github.com/hedgedoc/hedgedoc/issues/2119
