### ISSUE TITLE
Internationalisation of features

### ISSUE THREAD

**Issue by webafrancois** [hedgedoc/hedgedoc#700]
Like the homepage is international, like here in french : https://md.roflcopter.fr/ , the features homepage isn't : 
https://md.roflcopter.fr/features#

Previously in Codimd, the features page was in /public/docs/features.md and we could translate it.
Where can we find this page in hedgedoc to translate and would it be useful to make a PR ?

**Comment by DerMolly** [comment]
Hello @webafrancois,

> Previously in Codimd, the features page was in /public/docs/features.md
Please note that current default branch of this project is the [WIP](https://en.wikipedia.org/wiki/Work_in_process) Version 2.0. Therefore the `feature.md` page currently is not part of this repo.

> Where can we find this page in hedgedoc
The version from 1.7.1 can be found in the [master branch of this repository](https://github.com/hedgedoc/hedgedoc/blob/master/public/docs/features.md).

> [...] to translate and would it be useful to make a PR ?
Yes and no. We've talked about translating this page [before](https://github.com/hedgedoc/react-client/issues/328), but the first thing that would be needed is, to get a nice new `feature.md` page (reorganized and completed) for the version 2.0. Then you (and hopefully others) could work on translating this page.

If you're interested in helping reorganizing the `feature.md`, we would be very thankful.

Anyway, once we have a new `feature.md` and have the translation process figured out, I'll mention it in this issue and translation work could start.

**Comment by InnayTool** [comment]
Further discussion should be in #328.
