### ISSUE TITLE
PUT /notes/{id} does not return any content

### ISSUE THREAD

**Issue by salbeira** [hedgedoc/hedgedoc#702]
**Description**
Sending a PUT request to a /notes/{id} URL that gets accepted with a status code 200 does not contain any data inside the response even though the API documentation says it should return the updated note metadata.

**To Reproduce**
Send new content to a note via the PUT on URL /notes/{id} with a valid Note-ID.

**Expected behavior**
I get a response with content documented in the API-doc.

**Alternatives to consider**
Update the documentation to say that a PUT does not return any content. This would conflict with how any other "change" to the system returns content though and would just be inconsistent behaviour.

**Your Setup (please complete the following information):**
 - Host OS: Win10
 - NodeJS version: v14.15.0
 - HedgeDoc version: current dev branch (no frontend, so I did not look up any version number)

**Comment by salbeira** [comment]
Looking through the public API it seems that the implementation of PUT might be simply incomplete:

https://github.com/hedgedoc/hedgedoc/blob/136c43258797731fcb4ed4df37c94d61ebeb537b/src/api/public/notes/notes.controller.ts#L62-69

https://github.com/hedgedoc/hedgedoc/blob/136c43258797731fcb4ed4df37c94d61ebeb537b/src/notes/notes.service.ts#L188-195

**Comment by ErikMichelson** [comment]
Please note that the current 2.0 state is still heavy in development and therefore not everything is implemented yet.
