### ISSUE TITLE
Please ahttps://github.com/codimd/server/blob/master/docs/configuration-env-vars.mddd `CMD_DOMAIN` and if you run behind a reverse proxy `CMD_PROTOCOL_USESSL` AND `CMD_URL_ADDPORT`.

### ISSUE THREAD

**Issue by qianzai** [hedgedoc/hedgedoc#719]
Please add `CMD_DOMAIN` and if you run behind a reverse proxy `CMD_PROTOCOL_USESSL` AND `CMD_URL_ADDPORT`.

This should fix your problems :) for details check our docs: https://github.com/codimd/server/blob/master/docs/configuration-env-vars.md

_Originally posted by @SISheogorath in https://github.com/hedgedoc/hedgedoc/issues/67#issuecomment-492123028_

**Comment by DerMolly** [comment]
This seems to just be the comment from @SISheogorath from the linked issue. I guess this was just a mistake and I'll close the issue. Feel free to reopen and explain what you wanted.
