### ISSUE TITLE
Picgo/Picgo-core for image/attachment storage

### ISSUE THREAD

**Issue by Konano** [hedgedoc/hedgedoc#742]
**Which part of the project should be enhanced?**
image/attachment storage

**Is your enhancement request related to a problem? Please describe.**
I use Aliyun OSS to store my pic, but I can't use this in my Hedgedoc.

**Describe the solution you'd like**
Maybe we can add Picgo/Picgo-core, so that we can add OSS to store pic, like Typora.
https://support.typora.io/Upload-Image/

**Comment by davidmehren** [comment]
Alibaba Cloud OSS seems to be (somewhat) compatible with S3, see https://www.alibabacloud.com/help/doc-detail/64919.htm#title-cds-fai-yxp
You might already be able to use Alibaba OSS with the existing MinIO and S3 integration.

**Comment by Konano** [comment]
That does work, but I'm thinking that Picgo could support more kind of OSS storage. It is also quite troublesome to use MinIO.

**Comment by davidmehren** [comment]
Unfortunately, most PicGo documentation seems to be only available in Chinese. As far as I know, nobody on our dev team can read that. :/ 

For the 2.0 release we will not add any more storage providers than the ones mentioned in #529.

For a later release, we *might* accept a PR adding more. But again: The PicGo library and the cloud provider it uploads to being only available in Chinese makes testing and support very difficult.

> It is also quite troublesome to use MinIO.

Could you elaborate what problems you encountered?

**Comment by Konano** [comment]
> Could you elaborate what problems you encountered?

I don't need help because I've already configured it, but it's just that there were a lot of problems in the process, but they were solved one by one. Thanks -v-

I just learned that most PicGo documentation is written in Chinese. About the language problem, I would like to be able to help, but I don't have the free time right now. Maybe I'll submit a PR to support PicGo library and maintain it when I have time later?

**Comment by DerMolly** [comment]
> > Could you elaborate what problems you encountered?
> 
> I don't need help because I've already configured it, but it's just that there were a lot of problems in the process, but they were solved one by one. Thanks -v-

@davidmehren was interested in what those problems were, because maybe they could be avoided if we changed something. So if you want, we're more than happy to hear what your problems were.

**Comment by davidmehren** [comment]
I'll close this for now. As I said, we won't be adding more upload providers in 2.0. If somebody is interested in implementing and maintaining a Picgo provider in later releases, please comment below.
