### ISSUE TITLE
Features for 2.0

### ISSUE THREAD

**Issue by InnayTool** [hedgedoc/hedgedoc#746]
Which features do we want to add and which do we want remove for version 2.0?

This Issue should track that in the following lists:

- Permissions and Note Organization #1000 
- Import and Export Features #1011

#### Features to be removed
- 

#### Features to be added
- [ ] Permissions on user level
- [ ] stable public API

**Comment by DerMolly** [comment]
Many feature additions, changes and removes are in this file of the frontend https://github.com/hedgedoc/react-client/blob/main/CHANGELOG.md

**Comment by DerMolly** [comment]
But maybe this issue would be better suited as a `CHANGELOG.md` in the repo?

**Comment by InnayTool** [comment]
I think we should track in this Issue what we want to add and what we want to drop.

**Comment by davidmehren** [comment]
Replaced by the [project board](https://github.com/orgs/hedgedoc/projects/1)
