### ISSUE TITLE
Keys in dark mode are still black

### ISSUE THREAD

**Issue by caro314** [hedgedoc/hedgedoc#773]
**Which part of the project should be enhanced?**
Dark mode View

**Is your enhancement request related to a problem? Please describe.**
When using hedgedoc for noting keys (e.g. guitar cords) and switching to dark mode, written text is converted to white while written keys are still black (see images below).

**Describe the solution you'd like**
Enable keys to be visible in dark mode

**current state displayed in images below**
![blackkeys_hedgedoc](https://user-images.githubusercontent.com/54809072/105841718-5eea0580-5fd5-11eb-83f9-359c5aaf6b7a.png)
![whitekeys_hedgedoc](https://user-images.githubusercontent.com/54809072/105841720-601b3280-5fd5-11eb-8f81-eade22e9d2bc.png)

**Comment by davidmehren** [comment]
This has been fixed and will be released with 1.8.
