### ISSUE TITLE
Please add support for custom document URL naming

### ISSUE THREAD

**Issue by ArsalaBangash** [hedgedoc/hedgedoc#774]
**Is your feature request related to a problem? Please describe.**

When I create a document, I would like to name its URL according to its context, for example, "Org Leadership" would be docs.mydomain.com/org-leadership

Right now, I have to manage and copy links

**Describe the solution you'd like**

It would be nice to have an editable text field on the navbar where I could set the preferred URL.  

**Describe alternatives you've considered**

We could also have a button to set the URL which would pop open a modal. 

**Additional context**

**Comment by cfstras** [comment]
Note that when you enable `allowFreeURL`, you can manually choose the name for a new pad when creating a new one, simply by typing in "https://your-hedgedoc.com/org-leadership". This will create an empty pad under that URL.
See: https://docs.hedgedoc.org/configuration/#users-and-privileges

**Comment by ArsalaBangash** [comment]
Thank you so much :)
