### ISSUE TITLE
Difference in preview and publish verisons

### ISSUE THREAD

**Issue by DistroByte** [hedgedoc/hedgedoc#782]
**Description**
When editing a document with long paragraphs of text, in the preview of the edit screen, it shows paragraph breaks. When published, those disappear. More information in screenshots

**To Reproduce**
1. Create a new note
2. Paste some long paragraphs of text with any number of newlines between paragraphs
3. Look at preview: there are paragraph breaks
4. Publish and notice there are no paragraph breaks.

**Expected behaviour**
The published version should be the same as the previewed version, or at least keep certain styling

**Your Setup (please complete the following information):**
 - Host OS: Ubuntu 20.04
 - NodeJS version: v14.15.4
 - HedgeDoc version (Click "Version info" in the footer)
     - Latest, (set up on the 16th of January)

**Additional context**
![screenshot of styling and newlines in editor](https://user-images.githubusercontent.com/58866873/106281763-90faa200-6237-11eb-89cf-60f0356637be.png)
![screenshot of lack of newlines in publish](https://user-images.githubusercontent.com/58866873/106281799-9e179100-6237-11eb-8362-2623a903f174.png)

**Comment by DerMolly** [comment]
Hey @DistroByte,

I just tried to recreate your issue on our demo instance [here](https://demo.hedgedoc.org/sOdMCzAFR9uHCja7ExKI4A#) and [here](https://demo.hedgedoc.org/s/lR6B2vECf#), but I'm not able to get this to work. I'm not to sure why that is…

Some things I'd want to clarify moving forward:

1. Are you using any [frontmatter configuration](https://demo.hedgedoc.org/yaml-metadata#) in this note?
2. Does the same problem happen with the content of my test note on your instance?

**Comment by DistroByte** [comment]
Hey @DerMolly !
Thanks for getting back to me!

On the note I have screenshotted, I have the following YAML config
`
---
title: CA115 DIME Blog
description: Digital Innovation Management & Enterprise (DIME) blogs
tags: dcu, ca1, sem2, ca115, blog
robots: noindex, nofollow
---
`

For the test note, I can see you have the correct spacing, but when I copy and paste your test note content (from the editor) to my own site, it comes out like [this](https://md.james-hackett.ie/s/QsqhSrImL)

**Comment by DistroByte** [comment]
I am using the hedgedoc docker container however, and that could be the cause of the issue

**Comment by DerMolly** [comment]
I hope not that this is the difference.

**Comment by SISheogorath** [comment]
@DistroByte do you use a reverse proxy in front that tries to optimize things (e.g. mod-pagespeed), like collabsing HTML?

**Comment by DistroByte** [comment]
@SISheogorath Yes, I am using NGINX as a reverse proxy. Could that be the issue?

**Comment by mrdrogdrog** [comment]
No, but cloudflare that runs in front of your nginx. Can you check if you enabled any html optimizing features in cloudflare?

**Comment by mrdrogdrog** [comment]
The HTML of your note is missing some important white spaces in publish mode. It could be possible, that cloudflare optimizes this away. The demo instance is also running with cloudflare, but there isn't this issue. Therefore we assume, that you enabled a optimizing feature.

**Comment by mrdrogdrog** [comment]
Or do you use any html optimization plugins for nginx?

**Comment by DistroByte** [comment]
Ah okay! Yes, it is running through cloudflare. I shall check sittings there

> Or do you use any html optimization plugins for nginx?

I have only the most basic settings on NGINX, as far as I am aware that's not the issue

**Comment by DistroByte** [comment]
![image](https://user-images.githubusercontent.com/58866873/106324429-06cf2f80-6271-11eb-84cd-14e32e07245f.png)
This seems to be the issue, it has fixed [this note](https://md.james-hackett.ie/s/QsqhSrImL) now.

I really appreciate all of your help guys!
