### ISSUE TITLE
Export all notes / Backup

### ISSUE THREAD

**Issue by thangisme** [hedgedoc/hedgedoc#804]
I decided to use Hedgedoc to store my notes, my knowledge base,...
I know there is an option to export a particular note at a time. This's helpful. But if I want to export them all for offline backup, I've to export one by one? I don't want to deal with databse backup.

Hence, It'd be great if I can export all data (to a zip file, maybe) at a same time.

**Comment by SISheogorath** [comment]
There is the possibility to do that in the use menu on the cover/front-page :) when you click on the dropdown menu.

**Comment by DerMolly** [comment]
Additionally I'd like to point out, that not having a database backup and only having the markdown files, will negatively impact the time you need to restore a HedgeDoc instance in the case of catastrophic failure, as you won't have any user data, history or revisions etc.
