### ISSUE TITLE
Empty constructors for tests in 2.0

### ISSUE THREAD

**Issue by InnayTool** [hedgedoc/hedgedoc#835]
Should we add an empty constructor (or delete the existing private) to every entity class, making it possible to create objects where only needed values are set. @DerMolly used this in PR #801.

Example:
For class:
```ts
class User {
  id: string;
  userName: string;
  displayName: string;
  createdAt: Date;
  updatedAt: Date;
  photo?: string;
  email?: string;
  ownedNotes: Note[];
  authTokens: AuthToken[];
  identities: Identity[];
  groups: Group[];
}
``` 
only set `id`, `username`:
```ts
const user = new User();
user.id = 5;
user.username = "test";
```

**Comment by DerMolly** [comment]
I played around a bit with this and it seem we can use this in the tests

```
const user = User.constructor();
```

even if the constructor is `private`.

**Comment by DerMolly** [comment]
I just had a look at this again. The problem with the User entity instead of most (maybe all) others is that we have this weird type here in the `.create` function:
https://github.com/hedgedoc/hedgedoc/blob/c02ff36d3246a24fc23b1e37c9ea67e5cd21bd75/src/users/user.entity.ts#L61-L64 

If we would remove that we should be able to just use the `.create` function as the constructor.

Any reason why this was done anyway, @davidmehren @InnayTool?

**Comment by davidmehren** [comment]
The reason for the "weird" type is to ensure type correctness.
An object created with `new User()` does not have the properties specified in the `User` class until it is saved to the database, at which point TypeORM magically adds the properties.

This is also the reason why we have `.create` methods in the first place: If we would allow the use of the normal constructors, TypeScript would think that all properties exist, and we might get runtime errors. The `create` methods have a type signature that contains only the attributes that actually exist at runtime after calling them.

That said, I don't yet understand what your concrete problem is. The `create` methods should already contain the smallest number of attributes that is needed to create an instance that makes sense.

**Comment by DerMolly** [comment]
Well it creates type errors as `Pick<User, $someproperties>` is at most times not the same as `User`.

**Comment by davidmehren** [comment]
That works as intended. If something wants a `User`, it wants a complete instance, with a primary key and all. `.create` doesn't return that.
If the consumer also works with something "less", we should probably adjust it's type signature.

**Comment by DerMolly** [comment]
So use `.create` and then add what extra you need and change the type signatures around?

**Comment by DerMolly** [comment]
As I was just starting to implement this I noticed this clashes hard with the mocking of all TypeORM functions. 
![image](https://user-images.githubusercontent.com/3978662/107990216-3e114080-6fd4-11eb-9b54-40a1cb92dc23.png)

**Comment by davidmehren** [comment]
If you return incomplete objects during testing and are *sure* that this is okay, you can always do an explicit cast.

**Comment by DerMolly** [comment]
I'll try to summarize:

1. The `.create` functions of the entity objects should have the correct return type. This means they should be of the type `Pick<Class, attribute1 | attribute2>` and specify everything they set. If `.create` return a fully initialized object this is of course not necessary.
2. Any tests that need to receive a full object and not a 'Pick-SubType' should be cast via `as Class`

**Comment by davidmehren** [comment]
That sounds about right. Of course, care must be taken when casting, as missing attributes might cause runtime errors.

**Comment by InnayTool** [comment]
By now we implement the last solution presented.
