### ISSUE TITLE
Image upload optimization

### ISSUE THREAD

**Issue by boschkundendienst** [hedgedoc/hedgedoc#86]
Hi,

I would suggest the following concerning image uploads:

- make it possible to browse already uploaded images
- prefer usage of relative paths if possible
- include images in exported user data

Description:

I use the Docker version of CodiMD and have my images folder exposed and accessible within CodiMD as /uploads. When uploading an image CodiMD inserts it like `![](http://server.fqdn/uploads/upload_bd6ff6cfc1624f0dca604f8e390216d1.png)` and it shows up.

Server URls can change so using `![](/uploads/upload_bd6ff6cfc1624f0dca604f8e390216d1.png)` also works and would make it easier to move documents to other systems without the need of modifying the source of the Markdown files. (correctly it should be `![](uploads/upload_bd6ff6cfc1624f0dca604f8e390216d1.png)`) without the `/` in front.

When relative addressing of images is in place, images that are on the server should be included within the exported user data.

When an image has been uploaded but the image has been removed from a Markdown document you have no clue what the original image name was eg. `upload_bd6ff6cfc1624f0dca604f8e390216d1.png`. If possible, a **browse** button for images located on the server should be implemented somehow.

Please don't see that as criticism, I absolutely love CodiMD and your great work, I only wanted to share some ideas.

Regards

Peter

**Comment by ccoenen** [comment]
Right now, we don't store anything but the image itself. We don't have a table for attachments.

I especially like exporting the images along with the documents.

One tiny thing I disagree about: the leading slash should stay in place. Sometimes we deliver pages from sub paths (`/p/...` for presentations comes to mind). In those cases, `uploads/upload_09023845029348` would now point to the wrong path.

While we're at it, I would furthermore like to add: some part of the original file name should be kept in place. If I uploaded `kitty.gif` it should at least somewhat resemble this original file name.

**Comment by SISheogorath** [comment]
@ccoenen while I agree that the filename might should stay around in order to find the file in a table or similar, I would like to **not** have them around in the filesystem. Unique object ID are only avoiding conflicts and prevent content from becoming discoverable, it's also a security feature as it removes all nasty trickery an attack could do with filenames in order to do [path traversing](https://www.owasp.org/index.php/Path_Traversal).

**Comment by davidmehren** [comment]
Exporting a note with uploads is now tracked in https://github.com/hedgedoc/hedgedoc/issues/1005  
Browsing already uploaded files is now tracked in https://github.com/hedgedoc/react-client/issues/1094 and https://github.com/hedgedoc/react-client/issues/1095
