### ISSUE TITLE
Problems with Google Translator

### ISSUE THREAD

**Issue by cod3monk** [hedgedoc/hedgedoc#881]
**Description**

When using hedgedoc with Chrome and Google Translator (GT) set to always translate English to another language, things break horribly. Viewing documents and editing documents is not possible anymore as only garbage comes out and is shown, especially if the document is not actually written in English.

**Expected behavior**

Since the page and document was already in German, nothing should have been translated. There are two separate problems from what I can tell:
1. `<html lang="en">` seems to be hardcoded, even if a translated version is served. This forces GT to translate anything it finds, even it is not English. Not really your problem, but `lang="en"` is just not correct if serving translations.
2. [`class="notranslate"`](https://stackoverflow.com/questions/12238396/how-to-disable-google-translate-from-html-in-chrome) should be added to pad content to disable Google Translator at least when in an editing mode as it interferes with the input.

**Comment by ErikMichelson** [comment]
I thought that this should be fixed already with #437 as you could define your content-language in the [frontmatter](https://demo.hedgedoc.org/yaml-metadata#lang).

**Comment by DerMolly** [comment]
I think the PR you mention just touched the read-only (publish) view. At least in https://github.com/hedgedoc/hedgedoc/blob/master/public/views/index.ejs it's still hard coded to `en`.

**Comment by ErikMichelson** [comment]
Hm, you're right. But if we should add "notranslate" to the pad-content itself, the html-language would only affect the interface (whose language can be changed).

So the language attribute should be set to the configured interface language, or?

**Comment by DerMolly** [comment]
Good point

**Comment by cod3monk** [comment]
Having GT translate read-only views would be okay, but not in the rendered half in the `?both`-view. That would be very confusing, because input and rendered documents differ in content.
