### ISSUE TITLE
special groups in 2.0

### ISSUE THREAD

**Issue by InnayTool** [hedgedoc/hedgedoc#908]
We worked out that we want to use special groups for implementing permission levels for guest and logged in users. 

How should we call them?

For example:
- everyone
- loggedIn

**Comment by DerMolly** [comment]
As these are special groups we probably want to translate them in the frontend anyway. So we only need to come up with internal names for these groups, which would be seen by devs or power users.
With that in mind maybe we want to call the 2nd group `loggedInUsers` instead?

**Comment by ErikMichelson** [comment]
In addition to the names, what about using different ids for user-groups and system-groups?
When using integer ids, my suggestion would be to use negative ids for "special" system-groups and positive ones for user-created groups.

**Comment by InnayTool** [comment]
we thought about that but decided to use a field named special for that purpose.

**Comment by InnayTool** [comment]
I don't really see a benefit in adding `Users` because I think it gives no more information. What do the others think?

**Comment by DerMolly** [comment]
As nobody has any other opinions and I'm not married to `Users` let's go with your initial suggestion and close this issue, shall we @InnayTool?

**Comment by davidmehren** [comment]
Please document these decisions somewhere (API spec, `docs/dev/2.0.md`)

**Comment by davidmehren** [comment]
#967 is merged
