### ISSUE TITLE
Imgur not supporting ipv6 only server

### ISSUE THREAD

**Issue by TilCreator** [hedgedoc/hedgedoc#927]
**Description**
I'm trying to upload an image to Imgur, but I get a 500 and the log shows that the server tries to access Imgur with an ipv4 address which can't work since the server is ipv6 only. There is no problem accessing Imgur from the server as long as one is using ipv6. So it seams like Hedgedoc isn't using the dns resolution of the system.

**To Reproduce**
1. Go to an ipv6 only hedgedoc instance (I woun't link mine since all you get is an 500 on image upload)
2. Click on 'upload image' and select an image
4. See error --> 500 from `/uploadimage`, log: `Error: connect ENETUNREACH 151.101.84.193:443 - Local (0.0.0.0:0)`
  (151.101.84.193 is an ipv4 address of imgur.com)

**Expected behavior**
The server should resolve `imgur.com` to and ipv6 address and upload the image to imgur.

**Logs**
`Error: connect ENETUNREACH 151.101.84.193:443 - Local (0.0.0.0:0)`

**Config**
```bash
NODE_ENV=production
DEBUG=true
CMD_HOST=::
CMD_DOMAIN=CENSORED
CMD_HOST=::1
CMD_PORT=3000
CMD_USECDN=false
CMD_DB_URL="postgres://codimd@localhost:5432/codimd"
CMD_ALLOW_ANONYMOUS_EDITS=true
CMD_DEFAULT_PERMISSION=freely
CMD_SESSION_SECRET=CENSORED
CMD_ALLOW_GRAVATAR=true
CMD_ALLOW_FREEURL=true
CMD_ALLOW_PDF_EXPORT=true
CMD_LINKIFY_HEADER_STYLE=keep-case
CMD_PLANTUML_SERVER="https://www.plantuml.com/plantuml"
CMD_IMAGE_UPLOAD_TYPE=imgur
CMD_IMGUR_CLIENTID=CENSORED
CMD_EMAIL=true
CMD_ALLOW_EMAIL_REGISTER=true
CMD_PROTOCOL_USESSL=true
CMD_HSTS_ENABLE=true
CMD_CSP_ENABLE=true
```

**Your Setup (please complete the following information):**
 - Host OS: Arch container on a Proxmox Host
 - NodeJS version: v15.8.0
 - HedgeDoc version ([package](https://archlinux.org/packages/community/any/hedgedoc/), [PKGBUILD](https://github.com/archlinux/svntogit-community/blob/5eace0b65815ddee0862861eba332aa1601f487b/trunk/PKGBUILD))
     - server 1.7.2
     - client 1.7.2

**Additional context**
The server is ipv6 only, so any attempt to use ipv4 will fail.

**Comment by davidmehren** [comment]
It does not look like `api.imgur.com` (the endpoint we use) has an IPv6 address:
```
$ host api.imgur.com
api.imgur.com is an alias for ipv4.imgur.map.fastly.net.
ipv4.imgur.map.fastly.net has address 151.101.12.193
```

**Comment by DerMolly** [comment]
> There is no problem accessing Imgur from the server as long as one is using ipv6

How did you test this? It seems impossible…

**Comment by mrdrogdrog** [comment]
Well @DerMolly  such  a behaviour is possible if the server has an ipv4 gateway (or tunnel) but not the container

**Comment by TilCreator** [comment]
Example with a public DNS64 server: https://www.trex.fi/2011/dns64.html

```
[root@hedgedoc ~]# curl https://api.imgur.com/3/image -v
*   Trying 2001:67c:2b0:db32:0:1:9765:54c1:443...
* Connected to api.imgur.com (2001:67c:2b0:db32:0:1:9765:54c1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Imgur, Inc.; CN=*.imgur.com
*  start date: Jan 15 00:00:00 2020 GMT
*  expire date: Mar 16 12:00:00 2022 GMT
*  subjectAltName: host "api.imgur.com" matched cert's "*.imgur.com"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x560aa339c740)
> GET /3/image HTTP/2
> Host: api.imgur.com
> user-agent: curl/7.75.0
> accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 401 
< content-type: application/json
< access-control-expose-headers: X-RateLimit-ClientLimit, X-RateLimit-ClientRemaining, X-RateLimit-UserLimit, X-RateLimit-UserRemaining, X-RateLimit-UserReset, Geo-City, Geo-Region, Geo-Metro-Code, Geo-Country-Code
< etag: "3d650768f5c0ff90c9a062ebd3c986593bd13247"
< cache-control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< accept-ranges: bytes
< date: Thu, 18 Feb 2021 14:43:29 GMT
< x-served-by: cache-bwi5179-BWI, cache-bma1621-BMA
< x-cache: MISS, MISS
< x-cache-hits: 0, 0
< x-timer: S1613659409.074090,VS0,VE97
< access-control-allow-methods: GET, PUT, POST, PATCH, DELETE, OPTIONS
< server: cat factory 1.0
< access-control-allow-origin: *
< access-control-allow-credentials: true
< x-frame-options: DENY
< access-control-allow-headers: Authorization, Content-Type, Accept, X-Mashape-Authorization, IMGURPLATFORM, IMGURUIDJAFO, sessionCount, IMGURMWBETA, IMGURMWBETAOPTIN, X-expSNKPK127, X-Imgur-Defender-Bypass
< 
* Connection #0 to host api.imgur.com left intact
{"data":{"error":"Authentication required","request":"\/3\/image","method":"GET"},"success":false,"status":401}
```

**Comment by TilCreator** [comment]
I have worked around that issue with just using my local fs for image upload, so no rush from my side.

It would be nice to see if that bug still exists in 2.0: Since I sadly have not enough time to set up a 2.0 dev env, I will just give a short explanation to get a ipv6 only host (that is also easy reversable) for anyone who already has a dev env:
(You will need an ipv6 capable internet connection)
1. Disable the ipv4 address on your uplink interface (with NetworkManager just set ipv4.methode to disabled and restart the connection)
2. Set your DNS nameserver to one listed [here](https://www.trex.fi/2011/dns64.html)
3. :tada:

You probably don't want to keep that setup for long since Github **still** has no ipv6 address, so it will be slow.
To reverse that just reset or unset your DNS nameserver entry and reenable the ipv4 address on your uplink interface.

**Comment by TilCreator** [comment]
Thx for that insight, let's hope it will help someone!
