### ISSUE TITLE
Define semantics of 'patch' in a revision

### ISSUE THREAD

**Issue by davidmehren** [hedgedoc/hedgedoc#935]
Each revision has a `patch` attribute, which, according to the documentation, contains "The patch from the previous revision to this one.".

We have not yet defined how this patch will look like. Should it follow the format of POSIX `diff` ([implementation available](https://github.com/kpdecker/jsdiff))? Do we want to invent something different?

@ErikMichelson You already built the diff-feature for the new frontend, do you have any preference?

**Comment by ErikMichelson** [comment]
The [component for the diff-view](https://github.com/praneshr/react-diff-viewer) in the frontend calculates the diff on the fly based on two given revisions.

From frontend code side there's no need for a diff field generated by the server, but maybe for API tools or the CLI that would be interesting. I'm thinking of getting earlier revisions from the CLI as patch files.

**Comment by davidmehren** [comment]
> calculates the diff on the fly

:fearful: But...performance!

> I'm thinking of getting earlier revisions from the CLI as patch files.

That sounds like [jsdiff](https://github.com/kpdecker/jsdiff) is the way to go.

**Comment by SISheogorath** [comment]
@ErikMichelson can we performance test this frontend implementation with a sample data set, that resides around 1000 rows, 5000 words, and 200 meaningful revisions?

**Comment by DerMolly** [comment]
I'll link this old issue https://github.com/hedgedoc/hedgedoc/issues/521

**Comment by ErikMichelson** [comment]
@SISheogorath Automated? That's probably not gonna work with the performance of the GitHub action runners. But I can look into making some kind of testing (maybe with the Web-Performance API).

**Comment by SISheogorath** [comment]
@ErikMichelson not necessarily automated, no, but I would think it's important to check if the implementation is quick enough for a typical use-case and also how the bandwidth usage looks like

**Comment by ErikMichelson** [comment]
The bandwidth usage isn't any different to currently (1.x). The 1.x version already sent the whole content in the single revision responses.
See https://demo.hedgedoc.org/features/revision/1606684158802 for example.

**Comment by DerMolly** [comment]
So what would be test best idea here? And please keep in mind we should also expect api users and not only the new frontend.

**Comment by davidmehren** [comment]
Could we move the frontend performance testing to the other repo?

This issue is about the patch format. Anyone *against* using jsdiff for that?

**Comment by DerMolly** [comment]
> Anyone against using jsdiff for that?

I think this can be answered with: No.

**Comment by davidmehren** [comment]
It turns out that just deciding on "jsdiff" is not enough, as the serialization of the data jsdiff returns is also important.

I see two options:
- JSON-string of the object returned by `Diff.structuredPatch`
- [unidiff](https://www.gnu.org/software/diffutils/manual/html_node/Unified-Format.html) text

The second option has the upside of being familiar, easily displayable ([supported by codemirror](https://codemirror.net/mode/diff/index.html)) and being compatible with GNU `patch`.

**Comment by mrdrogdrog** [comment]
Jsdiff supports unidiff ootb. See `Diff.createPatch`

**Comment by DerMolly** [comment]
Sounds like a good idea then. Let's use unidiff and close this issue once the patch logic is implemented…

**Comment by mrdrogdrog** [comment]
The frontend also uses jsdiff so I'm okay with every format that can be parsed by the lib.

**Comment by DerMolly** [comment]
This discussion is finished the relevant information were ported into an implementation issue #2857
