### ISSUE TITLE
Testing new CSS rules - how to (use/not use) webpack from running instance?

### ISSUE THREAD

**Issue by zeigerpuppy** [hedgedoc/hedgedoc#951]
I am interested in testing some changes to the CSS styles for `slide-preview.css` (see #79)

However, I notice that the CSS styles are pulled from the packed CSS files in `public/build/` rather that the style files in `public/css/`.
Is it possible to have the unpacked CSS files used on a running Hedgedoc instance (I am running with docker).

Or else, and my apologies for what is probably a basic question, which command would I use to update the packed CSS files on a running container?

**Comment by DerMolly** [comment]
The frontend is built with ˋyarn buildˋ, but be warned the process is rather RAM intensive, so I'm not to sure if that would work inside the docker container…

Maybe you want to make changes on a non-docker instance…

**Comment by zeigerpuppy** [comment]
Thanks, running within a VM sounds like a good idea

**Comment by SISheogorath** [comment]
@DerMolly our docker images are build this way, it works, no worries :)

@zeigerpuppy the easiest way would be to fork hedgedoc, do your minor changes, then build the container with a custom repostiroy build-arg:

https://github.com/hedgedoc/container/blob/3500b7705e82e80157925156ba1b1353f378f12b/debian/Dockerfile#L18

**Comment by DerMolly** [comment]
I think this can be closed now…

**Comment by zeigerpuppy** [comment]
agreed
