### ISSUE TITLE
Remove `getFileUrl` from MediaBackend Interface

### ISSUE THREAD

**Issue by DerMolly** [hedgedoc/hedgedoc#957]
### What?

I suggest removing the function `getFileURL(fileName: string, backendData: BackendData): Promise<string>;` as we already return the url in this function `saveFile(buffer: Buffer, fileName: string): Promise<[string, BackendData]>;`. We could save that into the DB and recall that from there.

### Why? 

While building the imgur upload, I found out that we only get the url for the image at the point of uploading the image and never after that.

Another thing to consider is that we can't really change the file url after the upload, because it's part of the note after that point in time (at least most times).

**Comment by InnayTool** [comment]
Do we want to save the URL of other backend types than imgur?

**Comment by davidmehren** [comment]
I think you misunderstood the concept.

The idea is that *only* the `BackendData` is persisted and that each backend saves everything it needs in there to reconstruct the URL or to delete the file. So `getFileURL` gets the `BackendData` and generates a URL from that.

**Comment by DerMolly** [comment]
Well that's just needlessly complicated and would need either change of the `BackendData` or saving stringified JSON in the DB (and I don't think we want the later)
