### ISSUE TITLE
Provide prebuilt installation

### ISSUE THREAD

**Issue by AndiLeni** [hedgedoc/hedgedoc#96]
Is it possible to provide a prebuilt installation. Maybe even with a gui to install? 
I'm using a shared hosting service and the possibilities to built codimd on the server are very limited.

**Comment by SISheogorath** [comment]
We currently support fully automated installations on Heroku or Cloudron as well as providing a container image that can run on any hosting platform that supports container images using `docker` or `podman`.

https://github.com/codimd/server#installation--upgrading

I don't think we have the resources to provide more installation methods. But we are welcoming people to join us and taking care of them :)

**Comment by ccoenen** [comment]
I started a step by step guide, but I never really got around to finishing it:

https://demo.codimd.org/svq0JObCToqyt3ZBCZ58og#

Our current setup instructions only concern CodiMD itself. That document there would include database, a user and system service with SystemD.

Not automated, but maybe a step in that direction.

**Comment by SISheogorath** [comment]
https://docs.travis-ci.com/user/deployment/releases/ <-- this should already help with this issue.

We also need to pack the repository without `.git` and we can ask ourselves if we want to upload `node_modules` or not (iirc we compile some things as part of the npm dependencies, so probably it's better not to go for it). And we should also only get the production dependencies.

**Comment by ccoenen** [comment]
as soon as there's compiled stuff in `node_modules`, packaging them it is probably not a good idea. Also this might clash with their respective licenses if we pre-package them.

**Comment by ErikMichelson** [comment]
Maybe it's worth to have a look at this GitHub action: https://github.com/actions/upload-release-asset#example-workflow---upload-a-release-asset

The advantage is that it integrates directly with GitHub and does not need a 'machine user account' on GitHub. ([1])

[1]: https://docs.travis-ci.com/user/deployment/releases/#authenticating-with-an-oauth-token

**Comment by SuperSandro2000** [comment]
> does not need a 'machine user account' on GitHub like travis does.

Not one we need to provide. It technically stills uses one.

**Comment by DerMolly** [comment]
This is fixed by now, isn't it. Then I'll close this issue
