### ISSUE TITLE
Handling deleted users

### ISSUE THREAD

**Issue by DerMolly** [hedgedoc/hedgedoc#988]
**Which part of the project should be enhanced?**
private API: user deletion

When the user wants to delete their account, there are a few thing that we definitely need to also delete:
- identity
- auth_token
- session
- note_user_permission
- group_members_user
- history_entry

Others may be kept:
- note (user is owner)
- media_upload

Should we make the user chose if they want to delete those in the frontend? And if so would we want to make each of those separately removable?

**Comment by DerMolly** [comment]
I think it may be desirable to not delete one's notes when deleting the user account. For example when one created a lot of notes for the team. I'd also think that when one doesn't delete all notes, the same should be true for media_uploads.

It may be argued that we don't need this feature as long as it's possible to reassign the owner of a note / media_upload as most users won't want to keep all their notes / media_uploads around, but only a specific few. Which could be done by reassigning those to other users that still need / want them and then deleting everything else…

**Comment by davidmehren** [comment]
> It may be argued that we don't need this feature as long as it's possible to reassign the owner of a note

That sounds like the way to go. #998 is the issue to follow.  
If transfer of ownership is possible, the frontend should show "these notes owned by you will be deleted along with all media files uploaded by you" along with a list of affected notes, when a user wants to delete themselves.

**Comment by DerMolly** [comment]
> the frontend should show "these notes owned by you will be deleted along with all media files uploaded by you" along with a list of affected notes, when a user wants to delete themselves.

open an issue for that in the frontend

**Comment by DerMolly** [comment]
If the solution of delete everything (because things that shouldn't be deleted, can be given to other people) is agreeable, I think we can close this issue…
