### ISSUE TITLE
Hedgedoc Instance Administration

### ISSUE THREAD

**Issue by InnayTool** [hedgedoc/hedgedoc#995]
**Idea:**
To administrate a HedgeDoc instance it would be useful to have a support for that in the software.

**Possible Solutions:**
- Admin users https://github.com/hedgedoc/hedgedoc/issues/177
    - Can access all notes
    - Can set permissions & owner
    - Can add other admins
- Admin shell on the server
	- Can add users
	- Can delete notes
	- etc. (basically everything)

**Details already discussed:**
- A shell is much easier to implement with many features.
- Only server administrators can access the admin shell

**Comment by DerMolly** [comment]
I think for now the shell is the way to go.

**Comment by InnayTool** [comment]
Yes I think that, too. Are there obstacles to implement the other version later in the software?

**Comment by DerMolly** [comment]
Depends greatly on what you want and how you want it to work.

**Comment by InnayTool** [comment]
I think in range are admin users which have every permission and also can add and remove users.

**Comment by DerMolly** [comment]
I'd suggest having a separate admin page, that only users with an admin flag can use. Maybe we would need to have a some extra API routes. And of course the whole affair has the typical problem of regular users being admins.

All in all this should be fairly easy to add later.

**Comment by aschrijver** [comment]
Would love to have this functionality. Especially as admin not able to see all notes or delete them makes me very nervous. Who knows what people are adding in terms of nasty content to notes I lost track of.

**Comment by InnayTool** [comment]
We decided to implement an admin shell  https://github.com/hedgedoc/hedgedoc/issues/1003 in 2.0.
An admin GUI https://github.com/hedgedoc/hedgedoc/issues/2761 should be something for a later release.
