### ISSUE TITLE
Note Ownership

### ISSUE THREAD

**Issue by davidmehren** [hedgedoc/hedgedoc#998]
**Idea:**
Allow the current owner of a note to change the ownership of a note to other users or a group.

**Use-cases:**
- Permit multiple owners of a note https://github.com/hedgedoc/hedgedoc/issues/55
- Allow transferring note ownership to different user https://github.com/hedgedoc/hedgedoc/issues/557

**Details already discussed:**
- [SpecialgGroups](https://github.com/hedgedoc/hedgedoc/issues/908) can not be set as owner.

**Open questions:**
- Having user-groups *and* permitting multiple owners at the same time seems needlessly complicated. A note should probably have only one owner at a time, which might be a group.
- We need to examine if transferring the note-ownership breaks assumptions that we already make in the API or that a user might have

**Existing solutions:**
- GitLab solves this problem using [Groups](https://docs.gitlab.com/ee/user/group/). A group can have multiple users with permission-level "owner", which automatically get that permission in all projects that the group contains ("owns"). Using groups is also the only way to get multiple users to have "owner" permission-level.

**Comment by DerMolly** [comment]
The owner of a note should probably not be the special group "anonymous". Not sure if "logged-in" is desirable as a the owner of a note…
Maybe the easiest solution would be to just reject any special group to be the owner of a note.

**Comment by ValentinKolb** [comment]
Hello,
Is this feature part of the 2.0 release? We use HedgeDoc and we would love to have it. 
Is it already clear when 2.0 will be released?

**Comment by davidmehren** [comment]
@ValentinKolb This feature is part of the 2.0 milestone, so planned for that release.
We have no ETA for that, HedgeDoc is built in the free time [of our contributors,](https://hedgedoc.org/team/) which unfortunately got quite sparse in the last weeks.

**Comment by ValentinKolb** [comment]
@davidmehren Thanks for your answer! We'll just be patient a bit :)

**Comment by InnayTool** [comment]
Status: It is possible to change the owner. The application and the database structure by now doesn't support to have an owning group.

**Comment by InnayTool** [comment]
We don't plan to add user defined groups in 2.0, so it would make no sense to implement groups as owners in 2.0.
The feature request is moved to #2762.
